### ISSUE TITLE
January 2022 Contributions - {rafaccc#5473}

### ISSUE THREAD

**Issue by rafaccc** [Phala-Network/growth-program#103]
Telegram : [rafaccc](https://t.me/rafaccc)
Discord : rafaccc#5473
Dirección PHA: 42LYD29z2f6hYQeuamH5puXTGa1KHhWd6YxYSHXzRjih4xJd

**Telegram and Discord Spanish:** I have actively participated in the moderation of Telegram and Discord channels in English and Spanish. I've also shared twitter posts from Phala, my own twitter threads and old "Marvin Tong" posts that are worth keeping posting.

![image](https://user-images.githubusercontent.com/97988345/216508641-c96d8c6b-b76a-475f-bd64-3b87ddd858c7.png)

**Twitter:** In January I managed to double all statistical values ​​compared to the previous month (December). Go from 6,300 impressions (December) to 15,000 impressions (January). You can see in the Twitter spreadsheet.

More than 20 posts have been published about Phala, in addition to the Rt Twitter, translation posts. etc Here is just a sample
![image](https://user-images.githubusercontent.com/97988345/217066594-dc960827-3e06-4cc7-96c8-d8a69f8a53cc.png)
![image](https://user-images.githubusercontent.com/97988345/217066641-eee65e2d-265f-48e3-ae9a-d00bc9d46f08.png)
![image](https://user-images.githubusercontent.com/97988345/217066695-7dd4eb65-953c-4ceb-91d1-4a9f98ea44bc.png)

**Analytic**

![image](https://user-images.githubusercontent.com/97988345/216509760-db34a2b2-fb6b-4b04-97a4-9b800ab462bb.png)

![image](https://user-images.githubusercontent.com/97988345/216509917-ab57f3aa-a817-4762-97eb-f2415e7a04d2.png)

**CC: Article translation:** I have translated all the Medium articles (7)

1-https://medium.com/@rafacabilla/muestre-su-shell-de-pw-privadex-ingresa-a-open-beta-phala-weekly-vol-118-941f41ad45d6
2-https://medium.com/@rafacabilla/polkadot-meet-up-en-nueva-york-con-la-presencia-de-phala-nuevo-caso-de-uso-de-phat-gan%C3%B3-584b0aa63251
3-https://medium.com/@rafacabilla/phala-se-asoci%C3%B3-con-saas3-phalaworld-lanz%C3%B3-una-hoja-de-ruta-a-corto-plazo-phala-weekly-vol-116-ba97cfe61bb0
4-https://medium.com/@rafacabilla/phala-network-introduce-phat-contract-en-saas3-para-crear-un-oracle-altamente-escalable-d0468aafc385?postPublishedType=initial
5-https://medium.com/@rafacabilla/se-abren-las-solicitudes-para-el-programa-de-embajadores-de-phala-bcb9586fdacf
6-https://medium.com/@rafacabilla/phala-lanz%C3%B3-el-resumen-anual-del-2022-la-incubaci%C3%B3n-del-shell-de-phalaworld-sera-la-pr%C3%B3xima-semana-35bf76b093f3?postPublishedType=initial
7-https://medium.com/phala-espa%C3%B1ol/phala-network-se-asocia-con-subsquid-para-proporcionar-un-servicio-de-indexaci%C3%B3n-de-alta-calidad-e4d178e7039f

**ART** :Some images created by me, but I also use dozens of Phala's own images to advertise and make easy writing for users to understand how the project works

![image](https://user-images.githubusercontent.com/97988345/216511634-cc5eba0f-ee23-43a9-bf51-52879833698f.png)
![image](https://user-images.githubusercontent.com/97988345/216511997-60ec5cef-60b0-45fb-bdd0-98d6098a6c2b.png)
![image](https://user-images.githubusercontent.com/97988345/216512388-6a297c34-0069-4d44-9c0e-c50be1c0a20f.png)

**Here suggested A $Pha Price bot**
![image](https://user-images.githubusercontent.com/97988345/216513425-aa17ea32-e883-40fc-a865-9d7b1e4d09fd.png)

**Gif/Movie** :gifs and short videos take hours to edit, but are worth making.
https://twitter.com/RafaelCabilla/status/1615116766606233600
![image](https://user-images.githubusercontent.com/97988345/216512216-c084ec42-3e88-4b83-8ef5-74d0ae670d1a.png)

https://twitter.com/RafaelCabilla/status/1620208573723848705?t=_bytMIxJJ26h2RTP06TNFg&s=19
![image](https://user-images.githubusercontent.com/97988345/216514079-184f30e1-3fea-4378-9e3a-9af8ed7cf8d9.png)

------------------------
**Regarding the score of the previous month, I have managed to double the activities carried out, and I will continue to improve myself month after month.**
CM 37/40
MK 37/40
Supplementary tasks 20/20 (CC 10;Art 10)

Overall : 94

**Comment by willphala** [comment]
Great progress. I am happy to see you more involved in the departments. It would be great to see you engaging more too though.
