### ISSUE TITLE
January 2023 Contributions - {Scarlet#2215}

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#107]
Telegram Username: @Scarlet_Thr
Discord Username: @TheScarletThread#2215
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

### BASIC/MANDATORY CONTRIBUTIONS
**CONTENT CREATION**
_STANDARD TASKS_
•Made two threads, one about Phalaworld and the other about Phat Contracts. 
Created two simple graphic compositions  as visual aids for these threads.
https://twitter.com/TheScarletThr/status/1614981278893309954?t=2-22ZHupTh61AEaSj_wJQg&s=19
![Screenshot_20230203-125114_Twitter-01](https://user-images.githubusercontent.com/99918790/216588853-73b24af2-8c82-457d-a620-b05dead4954d.jpeg)
https://twitter.com/TheScarletThr/status/1618241265283530753?t=vARJ1g9dBYERH2aAxjZxgA&s=19
![Screenshot_20230203-125108_Twitter-01](https://user-images.githubusercontent.com/99918790/216588870-0b0a4341-d1cb-4270-8d93-8dcf04a461ba.jpeg)

•Compiled images from wiki and phalaworld discord 
server into visuals for presentation at Phala Africa Community Call.
![Screenshot_20230203-125337_Canva-01](https://user-images.githubusercontent.com/99918790/216589295-ffa3d4e3-b487-46de-9df9-3e914a4496d5.jpeg)

•Gave a presentation about a basic understanding of PhalaWorld at Phala Africa's first community call.

• Created Google form to collect questions from community before the community call and a Google doc to track ideas for the future local community calls.

_DEPARTMENT TASKS_
• Contributed to the ambassador onboarding document and the Phala Beginner guide. 

**COMMUNITY MANAGEMENT**
_STANDARD TASKS_
 • Monitor Phalaworld server and Phala Africa Telegram group. Greet new members, engage in discussions with members, answer community questions, refer community to useful resources when it is applicable. Removed spam and inappropriate content from channels when they came up and banned bots/spammers. Resolved concerns from community members when I could.

• Answer questions during Phala Africa Community Call

_DEPARTMENT TASKS_
• Added questions from community to the Community Digest. 

### SUPPLEMENTARY TASKS
**PM**
•Promoted Phala Network on Twitter and Telegram. Liked and retweeted posts from Phala and PhalaWorld official accounts. Engaged with fellow ambassador posts. Posted tweets. Engaged with posts about Phala Network.
![Screenshot_20230203-125936_Chrome-01](https://user-images.githubusercontent.com/99918790/216601799-c1a26236-1ab0-45fb-8e7e-65bd7875c433.jpeg)
![Screenshot_20230203-124600_Chrome-01](https://user-images.githubusercontent.com/99918790/216591758-aa2c740f-5f9b-46e8-807a-6250e19830f8.jpeg)
![Screenshot_20230203-124608_Chrome-01](https://user-images.githubusercontent.com/99918790/216594992-6931daf3-9873-4ae0-8a6d-3930c98358fe.jpeg)

### AREAS TO IMPROVE FOR FEBRUARY
•Produce better quality content and aim for more pieces  than this month
•Improve quality of Phala Africa community call and collaboration in preparation for this. 
• Contribute more to department tasks and the CC/CM discord channels and the Phala Network Official Telegram.

### SCORES
CC 30/40
CM 35/40
PM 5/10
TOTAL 70

**Comment by willphala** [comment]
Great work. I've increased your score due to all of your work with our African community. Really happy that you're now part of our team!
