### ISSUE TITLE
January 2023 Contributions - {Janema#7205}

### ISSUE THREAD

**Issue by Janemake** [Phala-Network/growth-program#108]
Telegram Username: @Janemake
Discord Username: @Janema#7205
Twitter Username: https://twitter.com/JanemakeCrypto
PHA Wallet Address: 41owbtwKf7dfZxEfdfhRfey4uGLkg8V9iLG74ZhTQnMnsAwA

**Departments** : #CC & #CM
**Department Score Weight** : 50% & 50%

### **DEPARTMENTS**

**#CM**
During this month, I have contributed in the french and international community on telegram and discord!

- In the french discord, we have been availabe with other french community members to promote the products of Phala : mining activities, PhalaWorld and the use of the app V2.
- In the international community, I have been present on daily basis on both Discord & Telegram to help community, provide some hints on the use of Phala products, manage some users from posting FUD on Phala.

![image](https://user-images.githubusercontent.com/58589481/216638213-7129505e-e483-4899-b1c6-c06565378492.png)

**#CC**
My contributions in this department were:
I've translated  the subtitles of 3 "Weekly report PhalaNetwork FR" youtube video made by Gator
Weekly report PhalaNetwork FR - 1 : https://www.youtube.com/watch?v=FbFNHyBA3YA
Weekly report PhalaNetwork FR - 2 : https://www.youtube.com/watch?v=K7FKaqbYhj0
Weekly report PhalaNetwork FR - 3 : https://www.youtube.com/watch?v=mnEJZUos3A0

I made some memes & images related to the Phala & PhalaWorld activities:
- Backgroung image of the "Weekly report PhalaNetwork FR - 3"  https://www.youtube.com/watch?v=mnEJZUos3A0
![image](https://user-images.githubusercontent.com/58589481/216607768-213ec240-c21f-4a50-a2f5-d325aada84a9.png)

- PhalaWorld Hatching events
![image](https://user-images.githubusercontent.com/58589481/216657713-b9ec86d9-dc42-490f-b619-9b43ea4df483.png)

https://twitter.com/JanemakeCrypto/status/1614957631587631108
https://twitter.com/JanemakeCrypto/status/1612171516606545921

- PhalaWorld: show your Shell around your city
![image](https://user-images.githubusercontent.com/58589481/216633091-1765fe39-ebda-405d-812a-ace3f814c322.png)

### **SUPPLEMENTARY TASKS**

**#HD**
I've been present in both french & international community to assist our commity by answering their questions related to Phala & PhalaWorld, providing them some hints in the mining deployment. 

I made some recommendations on the candidate onboarding: 
- The creation of a dedicated profile for candidates on the Phala Telegram group as the candidate did not have a profile and were facing a countdown between 2 messages.
- I made a recommendation to simplify the process of selection of the department especially the self-assignment process.

#PM
I have shared most of the Phala related subjects on Twitter to Promote events and products related to Phala & PhalaWorld.
![image](https://user-images.githubusercontent.com/58589481/216648986-022ba52a-dd4a-45c4-8280-96b51b593b60.png)

![image](https://user-images.githubusercontent.com/58589481/216641502-1b644aa0-5cc9-4335-9c68-370610dade10.png)
![image](https://user-images.githubusercontent.com/58589481/216646330-008fe289-b076-4fbb-b8e0-492a507f4d47.png)

### SUGGESTED SCORES
#CC : 25/40
#CM : 30/40

#HD : 8
#PM : 7

**Overall : 70**

**Comment by willphala** [comment]
Brilliant work. It's great that you're a part of the team!!
