### ISSUE TITLE
January 2023 Contribution - {ChrisBck#1751}

### ISSUE THREAD

**Issue by chrisbck** [Phala-Network/growth-program#109]
Telegram Username: @ChrisBck
Discord Username: @ChrisBck#1751
Twitter Username: https://twitter.com/BckChris
PHA Wallet Address: 45bL3R8XnNZ15hnRNu5Ww3vbQYCUjystcKXT2r8JWXPBiYfk

### Community Management
* Engage mostly with PW members and provide assistance and troubleshooting around shell hatching issues, was able to close off a few tickets.
   * Created step by step video to try workaround an issue
      * https://discord.com/channels/920642630835138601/920642633011953697/1066726655328006206.
* Provided links to livestream answers on PW future and game plans. Gathered together meme contest entries and collected votes to determine winners.
* Contributed community questions to the community digest

### Content Creation
* Created two memes for the PW meme contest.
   *https://twitter.com/BckChris/status/1612362077267714048
   *https://twitter.com/BckChris/status/1612457924449931264
![FmBCfuSaMAAVmrY](https://user-images.githubusercontent.com/32775411/216756714-e3b41f55-9098-4b82-a468-66a597ca4808.jpg)

![image](https://user-images.githubusercontent.com/32775411/216756909-8f7e9f0f-84f2-4a65-b960-2e0d9309a951.png)

 * Created a wasteland themed scene for ‘show your shell’ activity
   * https://twitter.com/BckChris/status/1617394787489058817
![FnIj7Y4aMAMlXhq](https://user-images.githubusercontent.com/32775411/216756960-d41bb39d-dc79-4eea-b7c0-14891c3ef323.jpg)
* To complement the above I created a 2nd version but recorded and edited the process as a timelapse: 
   * https://twitter.com/BckChris/status/1617942798619250689
![image](https://user-images.githubusercontent.com/32775411/216757057-a17cdb78-9ddc-403b-be62-e531c4317d3c.png)

* Made a thread covering some of the features of Phat Contract. Created an original 3D rendered animation to go with this.
   * https://twitter.com/BckChris/status/1617407515427471360
   * ![image](https://user-images.githubusercontent.com/32775411/216757102-2cc99861-69e0-4e49-8ddf-b27ce38832a9.png)

* Wrote an article to encourage PW nft holders to start mining. I also created an original 3D rendered animation and infographic to accompany this article.
   * https://medium.com/@ChrisBck/increase-your-intelligence-become-a-miner-6f5c1a657ac3
![image](https://user-images.githubusercontent.com/32775411/216757279-163a0743-74cd-45a9-8c71-dfa9495562e0.png)

* Added ambassador directory to the guidebook.

### PM
I engage, share and promote most PhalaWorld and Phala Network announcements and recommend joining livestreams and calls whenever possible. Twitter impressions are growing healthily.

![image](https://user-images.githubusercontent.com/32775411/216755536-e65bf41d-8acf-421d-a019-50cdd1123335.png)

![screencapture-analytics-twitter-user-BckChris-tweets-2023-02-04-14_53_21](https://user-images.githubusercontent.com/32775411/216755559-b25f0013-ae6e-4e33-a40a-b7b0ab6bcf36.png)

## How to improve
PW server has been quiet towards of the end of the month, there’s been a lull in activity since the buzz of the hatching. Need to perk up PW community with more activities and engage with them more about positive news to come this month. I have started to engage more in the Phala Network community but need to work more on this along with the telegram chat.

## Scores
Weight (CC/CM): 60%/40%
CM: 25/32
CC: 40/48
PM: 7/10
ART: 10/10

Total: 82

**Comment by willphala** [comment]
Great work. I'm really happy that you joined our team Chris!
