### ISSUE TITLE
January 2023 Contributions - {Rom1.io#5329}

### ISSUE THREAD

**Issue by Rom1io** [Phala-Network/growth-program#111]
Amb Rank : Candidate
Telegram Username: https://t.me/Imo_999
Discord Username: Rom1.io#5329
Twitter Username: https://twitter.com/RCajina
PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q

### Contributions: 
Hello, an excellent month of January was made by the Team FR and it is a happiness to work in team in this sense
You will find below my contribution for the month :

Departments : #CC & #CM

**Twitter analytics:** [Here](https://analytics.twitter.com/user/RCajina/home)

<img width="935" alt="image" src="https://user-images.githubusercontent.com/63704652/216824434-ba5881a5-6fb2-45ad-90c5-5f1affa8bea4.png">

**Best Tweets:** 
- Tweet 1: [Here](https://twitter.com/RCajina/status/1615669369261985792)
- Tweet 2: [Here](https://twitter.com/RCajina/status/1617829898110013440)
- Tweet 3: [Here](https://twitter.com/RCajina/status/1611782807717613574)
- Tweet 4: [Here](https://twitter.com/RCajina/status/1615354834076540928)

![image](https://user-images.githubusercontent.com/63704652/216824627-9168b1f0-417e-4abc-8946-ce8199f6c0a3.png)

<img width="845" alt="image" src="https://user-images.githubusercontent.com/63704652/216827308-dd6a24be-5517-4e09-9c0e-c65a763aca3b.png">

Here is also the creation statement for the medium and Youtube of the work provided by the FR team for January 2023: 
- Medium: [Here](https://docs.google.com/spreadsheets/d/18dbIeVvzdYRBvry5t1ntRfLKxtzOJsAo2pneJII8oY4/edit?usp=sharing)
- Youtube: [Here](https://docs.google.com/spreadsheets/d/1nhBF0_rHDbXMJqYsVXhi6ppIaIXKINjrXt9Mh5ihL9o/edit?usp=sharing)

I helped Gathor on the translation of the infographics and tweet of PHALA101: [Here](https://docs.google.com/document/d/1rD65D0NehmymjIxXUoW_YxQu0QiAktak9LqcGIx4AoA/edit?usp=sharing)

<img width="911" alt="image" src="https://user-images.githubusercontent.com/63704652/216825556-1615a38c-0b66-41fe-815c-d64108843967.png">

You can find the translation of the Growth program I made on our GitHub PhalaFR :
- GitHub Phala FR: [Here](https://github.com/PhalaTeamFR)
- Growth-program-FR: [Here](https://github.com/PhalaTeamFR/growth-program-FR)

<img width="902" alt="image" src="https://user-images.githubusercontent.com/63704652/216826279-f15ec8f2-3ee3-4be7-a5b6-88f3cc97ee77.png">

I am currently working on the implementation of the translation of the WIKI phala because it is very important that our community has access to it in our language that will allow a better understanding and interest for our ecosystem. You will find the status of the advancement below: 
- GitHub WikiFR: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/tree/Dev_Translation)
- WIKI Status: [Here](https://docs.google.com/spreadsheets/d/1Smia8YClIXawT53rFA20FewoBNi3Xpg2C8NxfbugXDA/edit?usp=sharing)
- Translation WIKI page 1: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/general/phala-network/products.md)
- Translation WIKI page 2: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/general/khala-network/tokenomics.md)
- Translation WIKI page 3: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/general/khala-network/intro.md)
- Translation WIKI page 4: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/general/khala-network/governance.md)

**February goal with the FR team:** Focus Translation PhatContract section and setup architecture for Netlify configuration

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/63704652/216826802-118cbf48-86b0-4563-ad94-6003de350408.png">

**Contribution to Lore Phala Francophonie :** Yes - Helping Images/Translations 
I introduced the birth of my character (French): [Here](https://docs.google.com/document/d/1OgWLM7kxFGps8s7GNMrqNHiTI4KUNg_SgTjTZVXNqNM/edit?usp=sharing)

### Slide in progress: 

**- Service Vault Presentation Slide:** 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/63704652/216827414-0fd3e503-0add-4764-8593-eb7adabdf05d.png">

***As soon as they are finished and validated by the FR team, I will share with you a file to make the translations according to the regions*** 

**Next Slides:** 
- PhatContract Service
- Onboarding Ambassador

### SUGGESTED SCORES
#CC: 30/40
#CM: 30/40

Overall : 60

**Comment by willphala** [comment]
Awesome work. It's fantastic that you're a part of the team!
