### ISSUE TITLE
January 2023 Contributions - GatorKorps | Phala#7997

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#112]
Title: january 2023 Contribution - GatorKorps | Phala#7997
Telegram Username: (https://t.me/Gatorkorps)
Discord Username: GatorKorps | Phala#7997
Twitter Username: @gk18_dog https://twitter.com/gk18_dog
PHA Wallet Address: 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV

My Mandatory (Basic) Contributions of January:
Ambassador

Phala Francophone Channel link: https://t.me/phala_french
Have I participated in Discord Channel Moderation (choose)? Yes
Have I participated in Telegram Channel Moderation (choose)? Yes

Departments : #CC & #MK
Department Score Weight : 100% & 100%

Hello :-)   January has been a very busy month for the teamFR. I think I have fulfilled the contracts at the level of the CC and the MK. Indeed, several concepts have been introduced:

- The Sunday video each week (except the week end of my daughter's birth) allows to summarize the Weekly report of Phala in French. These videos work well and are also subtitled in English and Italian. (more info in the youtube branch) 
https://www.youtube.com/watch?v=FbFNHyBA3YA&list=PLcA3wRzTFvV3URgvvuZbH0-6FsEALOuYK 

- The French PhalaWorld Lore concept, the lady of the canteen. The video was a team effort and we are proud of the result. This video inaugurates our Lore competition where users have to tell the story of their character while being faithful to the general PhalaWorld Lore. This contest will take place throughout the month of February and allows users to take ownership of the Lore and also to help us build our French Lore.
- https://twitter.com/phala_fr/status/1618564721116073986

- The translation and modification of the Phala101 slides into French will allow us to quickly spread the key information of Phala to our French targets.
- https://twitter.com/phala_fr/status/1610030106755448835

- The application of our targeting strategy at the French level is working and little by little we are growing our target audience.
- no link sorry

- The creation of a channel discord so that each French ambassador amplifies each important tweet on Phala
- 
![image](https://user-images.githubusercontent.com/82824139/216811446-d2b5a943-c79c-4251-8ff5-aa5ee07e02e5.png)

- The use of the # PhalaTeamFR in order to make it emerge (application still to be pushed).

- Use and training of ambassadors on the creation of IA Midjourney image with the creation of a dedicated discord to facilitate the exchange and creation. I think that our thumbnails and graphics have climbed enormously in quality since this introduction. We share some account and I can do request for others
![image](https://user-images.githubusercontent.com/82824139/216811501-7ba3d868-674e-458c-85ef-fa0d6df81f9a.png)

- Increased quality for our AMA. The AMA studio allows to give an interesting production, I will continue in this direction in order to professionalize our AMA to adjust notably the PB of certain sounds and help them to have a clear microphone. In general the studio structure of our AMA and satisfactory it remains for us to progress on our animation.
- https://twitter.com/gk18_dog/status/1618898889066840066

Community Management
Telegram :  _(copied report from tioneb)_
The telegram activity is stable.  _(copied report from tioneb)_
The 2 peaks that we observe at the beginning of the month crush the rest of the curve. it represent the New Year's greetings for the first one and a big animated discussion for the second one concerning the update of the V2 stacking and its new interface.
[image](https://user-images.githubusercontent.com/16654460/216784977-bd703e71-5a29-46b0-9287-9b5991a7a712.png)

https://user-images.githubusercontent.com/16654460/216785013-49b2ff53-aa21-40cf-a103-0deb27c5fa13.png

Discord :  _(copied report from tioneb)_
The activity of the discord continues to grow. New subscribers are joining and if you are a subscriber you should see that we are regularly present in voice channels.
image.
Our presence in these vocal chans invites members of our community to come and meet us and allows us to take the time to explain our passion for PhalaNetwork in person.
It's very much appreciated by our community.
[image](https://user-images.githubusercontent.com/16654460/216785118-5ffd4498-6fcd-4e58-b7d7-c2ade742ee87.png)

Youtube :
The introduction of weekly videos allows to flatter the youtube algorithm, so our videos will appear more and more in the spropositions and searches. The construction of the channel continues with playlists for each topic:

- weekly report

- Lore PhalaWorld

- Phala short educational

- AMA

- tutorials

We observe an increase in the number of views with the application of this strategy which will continue to develop, the increase of subscribers is also to be noted and will go crescendo.

![image](https://user-images.githubusercontent.com/82824139/216811749-7f153ed9-eebc-430a-8c33-0557286bb4ba.png)

![image](https://user-images.githubusercontent.com/82824139/216811763-b64691c2-9db4-4b5c-b7b3-370f41c7a4f9.png)

twitter
![image](https://user-images.githubusercontent.com/82824139/216811794-efd2face-cb03-479d-80ba-4ee2b616c635.png)
![image](https://user-images.githubusercontent.com/82824139/216811817-c27c6a2c-d130-45b4-8e3a-ce314082671d.png)

The strategy of targeting French tweeter accounts to respond and spread the good word of Phala works, we notice an increase in impressions and followers, I will continue to refine this strategy by focusing mainly on tweets in French. 

Conclusion :
The month of January was rich. I am really satisfied with the introduction of the new concepts. We have a great dynamic in the FR Team and we are all involved and complementary.  We all help eachothers. A very nice teamwork.

For the month of February I will focus on weekly reports, completely redo the Twitch PhalaFR to offer new lives outside our AMA (live discussion ambassador, PhatContract and various tuto staking v2) I think we can attract many new users with Twitch.

I participate in monthly Bitcoin Crypto meetups in my area and it works well because the discussions about the need for decentralization of the network allow me to present Phala's ideas every time. I'm thinking of trying to organize a Phala party in the coming months.

Our February thread will be the Phatcontract development with our Thursday / Wednesday night discussions and trying to put them live on Twitch

The PhalaWorld FR lore with the lady of the canteen, the contest and the broadcasting of the complete video. Our goal is to keep our community busy and to surf on the potential of PhalaWorld.

Thanks for your patience in reading this big report, I didn't describe everything I can provide more info or proof if you want. 

I will try to be as active in February but with the arrival of my daughter my activity will necessarily be reduced.

Thank you and have a nice day cheers

For Will:
Pm = OK 10
HD = OK 10
RC = NO 0
CC= OK 10
TT: almost video tuto.... 10/10
EM = OK 10
BD= 0
DEV No 0
50 points without marketing and content creation part. So I would Say 91 ^^

**Comment by willphala** [comment]
Excellent work! Proud of you Pham.
