### ISSUE TITLE
January 2022 Contributions – {Arηo#8446}

### ISSUE THREAD

**Issue by arnobase** [Phala-Network/growth-program#113]
Telegram Username: @arnobaze
Discord Username: Arηo#8446
Twitter Username: https://twitter.com/test_ut
PHA Wallet Address: 44siNV2pbrTSwiL3KdT4VVC1yqcSvfGzxcd7rHMD1cgQnjcn

mandatory tasks : CM & CC
ratio : 70%CM (56/80) - 30%CC (24/80)

# Contributions:
### 1) Good points:
presence on a daily basis on every channels of international and french community, high first reply rate

![Capture d’écran 2023-02-05 à 11 13 56](https://user-images.githubusercontent.com/8094810/216815877-a7876059-1d5f-4c8e-b042-63a872585d08.png)
![Capture d’écran 2023-02-05 à 11 25 04](https://user-images.githubusercontent.com/8094810/216815885-5c38557b-5eef-4ffd-884b-0ef9c9df682e.png)

Reading all messages on international channels, and French channels
Providing assistance on any question types: general, mining, bridging, staking
Reaching out to amb channels to ask for assistance when necessary
Redirecting chats to adequately channel 
Value added on every conversation: don't reply when not necessary (already answered and no useful complement)
Extensive usage of pha words branding
Reactive to official announcements, post links on channels
Securing channels by removing spam and banning inadequate users

Added some of the most asked questions to the dedicated document
Participated to the rewriting of the TG welcome message, added suggestions for new amb guide
Proposed tool for local datetime display in Discord: https://r.3v.fi/discord-timestamps/

### 2) bad points:
less active this month on Phala World (less activity there than previous month though)

### 3) how to improve :
increase presence on phalaworld discord and engage conversation there

### 1) Good points: 
Proofreading & editing of articles published in medium FR
https://medium.com/phala-fran%C3%A7ais/analyse-technique-des-raisons-pour-lesquelles-phala-ne-sera-pas-affect%C3%A9-par-les-vuln%C3%A9rabilit%C3%A9s-des-7ec4999a475f
https://medium.com/phala-fran%C3%A7ais/phala-sera-au-polkadot-meet-up-%C3%A0-new-york-le-nouveau-cas-dutilisation-du-phat-contract-remporte-8162a91d8ba2
https://medium.com/phala-fran%C3%A7ais/phala-a-conclu-un-partenariat-avec-saas3-le-phalaworld-publie-sa-roadmap-court-terme-hebdo-phala-cf3245b5d8a2
https://medium.com/phala-fran%C3%A7ais/phala-ouvre-les-candidatures-pour-le-programme-ambassadeur-rejoignez-le-meme-contest-phalaworld-cdc87bdf5fdd
https://medium.com/phala-fran%C3%A7ais/phala-a-publi%C3%A9-le-recap-de-2022-le-hatch-des-shell-phalaworld-se-fera-la-semaine-prochaine-2a8c7ca4b1be
https://medium.com/phala-fran%C3%A7ais/lapp-phala-v2-0-361161b25f89
https://medium.com/phala-fran%C3%A7ais/les-fonctions-on-chain-de-stakepool-v2-sont-en-mise-%C3%A0-jour-lhabillage-du-phalaworld-est-lanc%C3%A9-6ed3d9feba97
https://medium.com/phala-fran%C3%A7ais/le-beta-test-de-la-v2-de-lapp-phala-app-est-ouvert-cc0ca69622eb
https://medium.com/phala-fran%C3%A7ais/app-phala-2-0-2eed8f2b641b
https://medium.com/phala-fran%C3%A7ais/vaults-simplifier-optimiser-vos-d%C3%A9l%C3%A9gations-phala-28853fc8aa6e
https://medium.com/phala-fran%C3%A7ais/share-ou-part-tracer-la-propri%C3%A9t%C3%A9-de-la-pool-d93ba7a893e2

contribution to the phala wiki (PR to edit broken link)
proofreading of Shares article on medium international (update for errated numbers given in example)

contribution to the new ambassador guide (rules of conduct)

some twitter original posts and visuals
![Capture d’écran 2023-02-05 à 11 55 19](https://user-images.githubusercontent.com/8094810/216815928-6f40cb79-13b5-4822-b696-dd7e95b32b8a.png)
![FnT_GvkWQAAzZ5e](https://user-images.githubusercontent.com/8094810/216815967-6e38aac2-3296-43e7-a8d4-d272ed1f84d7.jpg)

### 2) Bad points:
mainly text contributions, and not much visual content created

### 3) How to improve:
create more original and visual content

### MK: 
co-organized an recurrent event for PhalaTeamFR : workshop for Phat contract, starting on jan. 25th, running on every wednesday until the closed beta ends
first event was wed. 25th feb (2h live)

Participation to the organization of the event LDDLC with PhalaTeamFR

Took contact with the node provider "RadiumBlock" and agreed for a permanent support of "archives" node to ensure a faster setup for new Phala miners

27 tweets or retweets about Phala: https://analytics.twitter.com/user/test_ut/tweets

### HD:
proposing dm or vocal when users need specific assistance, to improve efficacity, even if time consuming - ~5 this month

SUGGESTED SCORES

#CC : 51/56
#CM : 19/24 
#HD : 10
#PM : 10

Overall : 90

For my first month I brought added value by helping to develop Phala’s community, monitoring, engaging, supporting and spreading the Phala's culture, could help to improve the Phala ecosystem understanding by increasing the quality of assets produced and providing helpful attendance when necessary as a help desk.
With these objectives reached, it seems that the score of 90 is well representative of my engagement in Phala's ambassador missions.

For the next month, I want to improve the content creation part, by creating more visual and original content, and be more active on the PhalaWorld Discord

**Comment by willphala** [comment]
Excellent work. I'm really happy that you're a part of our team!
