### ISSUE TITLE
January 2023 Contributions - (johnrhodel#8162)

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#115]
Telegram Username: https://t.me/johnrmb
Discord Username: johnrhodel#8162
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

Scores: 

MK 40/40
CC: 25/40
Suplementary CM : 10/10
Suplementary ART : 10/10

Departments : #CC & #MK

![phala january twt john](https://user-images.githubusercontent.com/77474076/216847127-190e198d-5c9d-442e-8a76-2b36e55ba794.png)
![phala january twt portuguese](https://user-images.githubusercontent.com/77474076/216847696-527a8e3c-5b1c-461c-9a02-c936d28c34c5.png)

MK: 40/40 Score : Worked pretty actively on tweets and spreading the word on both phala portugues and parachain boy

RT + Like + Quoted Created Tweet ( PARACHAIN BOY and PHALA PORTUGUESE)

PHALA PORTUGUESE:
https://twitter.com/PhalaNetwork/status/1609545987206574080
https://twitter.com/PhalaNetwork/status/1610987516924162050
https://twitter.com/subsquid/status/1610985859058106370
https://twitter.com/PhalaNetwork/status/1612119316278960128
https://twitter.com/PhalaNetwork/status/1612657405309104130
https://twitter.com/PhalaNetwork/status/1613143448152084482
https://twitter.com/PhalaNetwork/status/1613521449867780096
https://twitter.com/PhalaNetwork/status/1614635598823960577
https://twitter.com/PhalaNetwork/status/1615569267277336578
https://twitter.com/PhalaNetwork/status/1616077411044700160
https://twitter.com/PhalaNetwork/status/1616415187988545537
https://twitter.com/phalaportugues/status/1617861112627884032
https://twitter.com/phalaportugues/status/1620400702353997826
https://twitter.com/phalaportugues/status/1620604114173583360
https://twitter.com/PhalaNetwork/status/1620066335190568960
https://twitter.com/PhalaNetwork/status/1616641583474180097
https://twitter.com/PhalaWorld/status/1617113299874877440
https://twitter.com/zoemcfox/status/1618015808281776129
https://twitter.com/PhalaNetwork/status/1618538036509442048
https://twitter.com/WillCottrell_io/status/1618623262053011457
https://twitter.com/PhalaNetwork/status/1619225027626545152
https://twitter.com/phalaportugues/status/1619855883353362432
https://twitter.com/phalaportugues/status/1618251127518294023

PARACHAIN BOY:

https://twitter.com/parachainboy/status/1620601690520195072
https://twitter.com/parachainboy/status/1619495873288998914
https://twitter.com/parachainboy/status/1619341281150525440
https://twitter.com/PhalaWorld/status/1615592488097689600
https://twitter.com/PhalaWorld/status/1617113299874877440
https://twitter.com/parachainboy/status/1618651890853761024
https://twitter.com/parachainboy/status/1618296168450265090
https://twitter.com/parachainboy/status/1618250947117092868
https://twitter.com/PhalaNetwork/status/1618015047334100992
https://twitter.com/PhalaNetwork/status/1617886638432227328
https://twitter.com/PhalaWorld/status/1615349523223805956
https://twitter.com/PhalaNetwork/status/1615569267277336578
https://twitter.com/PhalaNetwork/status/1616077411044700160
https://twitter.com/parachainboy/status/1617308433794965505
https://twitter.com/PhalaNetwork/status/1617120798984278016
https://twitter.com/PhalaNetwork/status/1617250757396283398
https://twitter.com/parachainboy/status/1616596827452895232
https://twitter.com/parachainboy/status/1616486504448000023
https://twitter.com/parachainboy/status/1616123943290650629
https://twitter.com/parachainboy/status/1616122832697671683
https://twitter.com/parachainboy/status/1615346717297344518
https://twitter.com/PhalaWorld/status/1614953661964357636
https://twitter.com/parachainboy/status/1614962459638435840
https://twitter.com/parachainboy/status/1613997412518924293
https://twitter.com/parachainboy/status/1613997198416482318
https://twitter.com/PhalaNetwork/status/1610290002872926210

CC: 25/40

Create Linktree from Phala Portuguese :

https://linktr.ee/phalaportugues

I still need to work on the phala content for beginners, I'm going to help Gabriel on the advocates' document so for the next month I'm improving my score, I've translated articles, I managed to have an interview answered by marvin and I will post this week in medium, subsocial and translate to portuguese and filipino

https://docs.google.com/document/d/1CvjytQ5T7QkqE0To25FQ4JqR92WP65j-/edit

Medium:
https://medium.com/@phalaptbr/phala-lan%C3%A7ou-o-ano-2022-em-revis%C3%A3o-phalaworld-shell-eclodir%C3%A1-na-pr%C3%B3xima-semana-7df34b73d839
https://medium.com/@phalaptbr/phala-2022-revis%C3%A3o-do-ano-99319aa51fe8
https://medium.com/@phalaptbr/phala-estar%C3%A1-no-polkadot-meet-up-em-nova-york-novo-caso-de-uso-phat-venceu-hackathon-phala-875f74d9c4c1
https://medium.com/@phalaptbr/phala-network-introduz-contrato-phat-em-saas3-para-construir-um-oracle-altamente-escal%C3%A1vel-21b58554f90a

Whats phala in telegram :
https://t.me/phalaportugues/2586

Phala and IA in telegram:
https://t.me/phalaportugues/2588

Phala pt 1 twitter:
https://twitter.com/phalaportugues/status/1620400702353997826

Phala pt 2 twitter:
https://twitter.com/phalaportugues/status/1620604114173583360

Suplementary task
CM 10/10 - Suplementary task - I was active in phala portugues taking doubts and helping people with basic questions about the ecosystem
Have I participated in Discord Channel Moderation (choose)? Yes
Have I participated in Telegram Channel Moderation (choose)? Yes

![Combot January - Phala Portuguese](https://user-images.githubusercontent.com/77474076/216846070-4db08d4f-063d-41b1-8bb9-4c3d5919cb34.png)

I moderated Phala's discord in Portuguese, we had a great deal of movement and an increase in the number of members that formerly had 90 and today we have 102 members, an increase of 13% in the number of members

ART : 10/10 - I made two arts explaining the phala in Portuguese 1 and 2 the parts

![phala parte 1](https://user-images.githubusercontent.com/77474076/216846924-26461f7c-a6ed-47df-bd08-d023e88177b8.jpg)
![phala parte 2](https://user-images.githubusercontent.com/77474076/216846926-3055fcbc-9e13-4d0b-bcdf-1bedd8686b77.jpg)

**Comment by willphala** [comment]
Good work. Please participate more in our department channels to earn higher scores.
