### ISSUE TITLE
February 2023 Contributions - {BlackStone | Phala Amb#0238} #98

### ISSUE THREAD

**Issue by BlackStoneSheperd** [Phala-Network/growth-program#117]
PERSONAL INFO
Amb Rank : Senior Ambassador
Telegram : [BlackStone](https://t.me/BlackStoneSD)
https://twitter.com/BsSheperd
PHA Address : 42fBg7rmA9fp1dyA9LhVVKm5rAzNLLSxdiqkq46sBJGjEEHU

Departments : #CC & #MK
Department Score Weight : 25% & 75%

DEPARTMENTS
#CC
I've translated weekly, articles etc, published it on our french Medium and our Discord/Telegram.
https://medium.com/@blackstonesheperd
https://medium.com/phala-fran%C3%A7ais
Arno gave me help and reviewed the translations.
I continue making a weekly support for gator's weekly videos.
I've made a vignette for all the Shells of the TeamPhalaFR for an upcoming event.
here : https://drive.google.com/drive/folders/1UsuRNftnsaU6uAxt8ugYKmhLXnQLz0Yi?usp=share_link
I'm still planning to do so for all the ambs.

The lore contest launched by gator for the french community is stil ongoing.

----- AMA for 2022 Review -----

#MK (Twitter)
official local : https://twitter.com/phala_fr
![image](https://user-images.githubusercontent.com/107954611/221891502-b0d19fec-6b9a-4926-849a-f81113958fe2.png)
![image](https://user-images.githubusercontent.com/107954611/221891654-c74d13df-4f55-49a2-9bae-5c55e88206c0.png)

ambassador : https://twitter.com/BsSheperd
![image](https://user-images.githubusercontent.com/107954611/221891064-220aaa5a-5ecc-4631-8706-9ac560ee37df.png)
![image](https://user-images.githubusercontent.com/107954611/221891242-5f772688-78dc-45ef-b6fc-a5c84a24f41b.png)

All the French team participated to our rebranded Monthly AMA, now called #CommunityCallFR
here : https://www.youtube.com/watch?v=ds3CndAeE1Q

SUPPLEMENTARY TASKS
#CM
I've started a collaboration with Angie to make a support for her presentation
here : https://www.canva.com/design/DAFbyT4rrzc/PuKqH1VNEMEiPMd53k-ZxA/edit?utm_content=DAFbyT4rrzc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

SUGGESTED SCORES
#CC : 40/40
#MK : 40/40

#CM : 10

Overall : 90

**Comment by willphala** [comment]
Great work. I'm especially happy to see you collaborating with and supporting our other ambs in our departments. Keep it up!
