### ISSUE TITLE
February 2023 contributions DKSM#0396

### ISSUE THREAD

**Issue by darknight7** [Phala-Network/growth-program#118]
Telegram: randomusernameidontneed
Discord: DKSM#0396
PHA Address: 427s7coF6yveYnXPNvCc1BtKgkHABxwgZpcwbFXbpJE9X1iP

MK: I do not contribute to this department.

CM
Have I participated in Discord Channel Moderation (choose)? Yes, telegram too.

Phala Italian Channel link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a
Comments: nothing special to comment, it was a quiet month from my POV.

How many people increased or decreased? Why?
The Italian Phala chats are traditionally very low traffic, following the PhalaWorld mint things are back to normal.
What was good?
There was some sort of interest about developing phat contracts.
What was bad?
Activity is minimal as usual, not a bad thing per se, especially in these market conditions.
How can I improve this next month?
I've been able to improve my presence on discord, I hope the trend will continue.
CM end.

CC
Submitted my proposal for website and wiki revamp as centralized repository for quality documents replacing publishing platforms used by ambassadors.
I've started to investigate how to work on the wiki for translation purposes at first.

Translated [weekly #121](https://medium.com/@aypm/phala-parteciper%C3%A0-ad-ethdenver-farm-pha-attiva-su-moonbeam-riassunto-settimanale-n-121-7335a6343c8d)

Collab with Pigro85 and others for a complete PRB mining guide, the draft already circulated and got feedback. Pigro85 being the mind behind it will likely offer a more detailed report.

Helped Scarlet and Kamala edit their new content.

Trying to push the discussion for a single set of assets for videos, currently each amb creating a video recycles stuff his own way. A kit with intro, outro, interlude and background music would make it all look far more professional. Also, other projects have a youtube channel where all ambs contribute, again, to me it's more professional, the content is probably vetted and so on. "Automatic" work on captions and avoiding duplicates should be a priority. eg: the Frenchmen are doing a series on the weekly, no need for internal competition on that one
This needs a lot of love before it can become a good habit. I can help with static pictures, particularly photographs, but I'm not in the position to step in and work on video.
CC end.

PM
![immagine](https://user-images.githubusercontent.com/4477195/222096180-d58ad576-8217-41c0-915b-acc3b667a8fe.png)
PM end.

HD
Phala Mining Channel link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a
Comments: February was an easier month for me and my presence has been steadier.
HD end.

My self evaluation:
MK: -
CM: 25
CC: 40
PM: 2/10
HD: 4/10

**Comment by willphala** [comment]
Good work. I'm especially happy with all of your great suggestions, they're very much appreciated and valued!
