### ISSUE TITLE
February 2023 Contributions - {Rom1.io#5329} 

### ISSUE THREAD

**Issue by Rom1io** [Phala-Network/growth-program#119]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/63704652/216827308-dd6a24be-5517-4e09-9c0e-c65a763aca3b.png">

Amb Rank : Candidate
Telegram Username: https://t.me/Imo_999
Discord Username: Rom1.io#5329
Twitter Username: https://twitter.com/RCajina
PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q

Departments : #CC & #MK

**Contributions:**

Hello, an excellent month of february was made by the Team FR and it is a happiness to work in team in this sense
You will find below my contribution for the month :

Here is also the creation statement for the medium and Youtube of the work provided by the FR team for february 2023: 
- Medium: [Here](https://docs.google.com/spreadsheets/d/18dbIeVvzdYRBvry5t1ntRfLKxtzOJsAo2pneJII8oY4/edit?usp=sharing)
- Youtube: [Here](https://docs.google.com/spreadsheets/d/1nhBF0_rHDbXMJqYsVXhi6ppIaIXKINjrXt9Mh5ihL9o/edit?usp=sharing)

![image](https://user-images.githubusercontent.com/63704652/222117520-bf30a95b-18be-44e8-9e0f-aad3e09f879c.png)

Twitter analytics: [Here](https://analytics.twitter.com/user/RCajina/home)

<img width="850" alt="Capture d’écran 2023-03-01 à 11 14 28" src="https://user-images.githubusercontent.com/63704652/222114901-25717742-5817-4ea5-8a10-c484d21e7eb1.png">

**Best Tweets:** 
- Tweet 1: [Here](https://twitter.com/RCajina/status/1625063855100510209)
- Tweet 2: [Here](https://twitter.com/RCajina/status/1625376800166608903)
- Tweet 3: [Here](https://twitter.com/RCajina/status/1625776077825093634)
- Tweet 4: [Here](https://twitter.com/RCajina/status/1626898706153832450)
- Tweet 5: [Here](https://twitter.com/RCajina/status/1627925458296643584)
- Tweet 6: [Here](https://twitter.com/RCajina/status/1628115599741034499)
- Tweet 7: [Here](https://twitter.com/RCajina/status/1628422136938332161)
- Tweet 8: [Here](https://twitter.com/RCajina/status/1629145094753320961)

![image](https://user-images.githubusercontent.com/63704652/222119319-3963d2ad-cf39-4cd8-a72f-fb0fa8527493.png)

![image](https://user-images.githubusercontent.com/63704652/222127175-63457716-d724-49b1-bfca-1522aae94750.png)

**Medium:** 
- Translation: [Here](https://medium.com/@rom1.io/le-programme-builders-de-phala-network-ouvre-les-candidatures-d%C3%A8s-maintenant-ecb1e2327b24)
   -  Word : 776

**WIKI:** 

I am currently working on the implementation of the translation of the WIKI phala because it is very important that our community has access to it in our language that will allow a better understanding and interest for our ecosystem. You will find the status of the advancement below: 
- GitHub WikiFR: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/tree/Dev_Translation)
- WIKI Status: [Here](https://docs.google.com/spreadsheets/d/1Smia8YClIXawT53rFA20FewoBNi3Xpg2C8NxfbugXDA/edit?usp=sharing)

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/63704652/222136579-c18ccd0f-5af4-4678-9952-d7be49333e52.png">

- Translation WIKI page 1: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/general/phala-network/intro.md)
   -  Word : 427
- Translation WIKI page 2: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/general/phala-network/tokenomics.md)
   -  Word : 1314
- Translation WIKI page 3: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/general/phala-network/phat-contract-fee.md)
   -  Word : 2397
- Translation WIKI page 4: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/build/general/builders-program.md)
   -  Word : 1127
- Translation WIKI page 5: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/build/general/intro.md)
   -  Word : 409
- Translation WIKI page 6: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/build/general/features.md)
   -  Word : 527
- Translation WIKI page 7: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/build/general/usecases.md)
   -  Word : 209
- Translation WIKI page 8: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/build/general/closed-beta.md)
   -  Word : 585
- Translation WIKI page 9: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/build/getting-started/prep.md)
   -  Word : 135
- Translation WIKI page 10: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/build/getting-started/account-prep.md)
   -  Word : 166
- Translation WIKI page 11: [Here](https://github.com/PhalaTeamFR/phala-wiki-next-FR/blob/Dev_Translation/content/en-us/build/getting-started/next-step.md)
   -  Word : 121

![image](https://user-images.githubusercontent.com/63704652/222129779-71fbe690-0699-4255-9d0f-68bbf45a9ce8.png)

![image](https://user-images.githubusercontent.com/63704652/222132508-0d6e193e-00e0-4897-82c7-a936376a0ca5.png)

- Slide: Service Vault Presentation: [Here](https://docs.google.com/presentation/d/1ZTDpjkxrErGDWlsCdtkrFcL-TP3zlLA2VCrikeuw4rc/edit?usp=sharing)
- Slide: Programme Builders: [Here](https://docs.google.com/presentation/d/1LCXEgWqQxhZvFSW86eqVT5QsVKd5_U8aatMJuz8oKOg/edit?usp=sharing)
- Slide: Transferring PHAs between Khala and Moonbeam On-chain: [Here](https://docs.google.com/presentation/d/1STTSRmxwfptDCi4ulz7OZoF4UAcGAyb9cb6t48MqkCQ/edit?usp=sharing)
- Slide: Withdraw Fees CEX - $PHA: [Here](https://docs.google.com/presentation/d/1V68_MezajoAcw4ZlKpKhWOXFFjNFkZuLKI_yumREBpc/edit?usp=sharing)

![image](https://user-images.githubusercontent.com/63704652/222132673-f4bf53f3-fa03-42d8-b151-1c775e8231f0.png)

Participation in AMAs and LIVE on Discord see below: 

- Wednesday, February 1st: Phat Contract Workshop
- Wednesday, February 8th: Phat Contract Workshop
- Wednesday, February 15th: Phat Contract Workshop
- Saturday, February 18: Live for the community non-stop from 2pm to midnight 
- Wednesday, February 22nd: Phat Contract Workshop
- Tuesday, February 28: Monthly AMA Phala FR

![image](https://user-images.githubusercontent.com/63704652/222134127-67fe6ec1-f49c-43d7-a391-f681d8d5a87e.png)

I helped Gathor on the integration of the subtitles for the video "Transferring PHAs between blockchains and CEX and using StellaSwap pools": [Here](https://drive.google.com/drive/folders/1AWQ8wTR837p6fIgeRXHwi54excGOSczt?usp=sharing)

![image](https://user-images.githubusercontent.com/63704652/222134855-7eff0b13-3d74-4aad-a848-63d581a00c44.png)

It is a real pleasure to work with the French team, ***"Alone we go faster, Together we go further"***. 

***March's goal with the FR team:*** Focus the Translation and Infographics section on the PhatContract and set up the architecture for the Netlify configuration.

## SUGGESTED SCORES
#CC: 40/40
#MK: 40/40
#Other: 20/20

Overall : 100

**Comment by willphala** [comment]
Great work. Its lovely to hear that you're enjoying the ambassador programme and that working alongside the rest of the French team is going well! 

Next time please specify which supplementary tasks you participated in please. E.g. EM would be one as you co-hosted an online event. E.g. it would also be great to know how much community related tasks you have performed too. If you provide more information it's easier for me to give you a higher score.
