### ISSUE TITLE
February 2023 Contributions - {infaceAi#5149} 

### ISSUE THREAD

**Issue by infaceAi** [Phala-Network/growth-program#120]
PERSONAL INFO
Amb Rank : Ambassador
Telegram:[ @infaceAi](https://t.me/infaceAi)
Twitter: https://twitter.com/infaceAi
PHA Address : 45vo82ABupacJoafLRW8oVWiYyErk9UqZLpfBn8wtE1zcB4M

Departments : #CC & #MK
Department Score Weight : 25% & 75%

Contributions:
MK & CC - I promoted Phala on Twitter and both Phala general and local telegram chats. My stats below.
**Twitter** analytics Feb 2023 stats:
<img width="892" alt="Tw 1" src="https://user-images.githubusercontent.com/112633185/222540310-70dfc656-85b4-4d31-816a-566221398020.png">
<img width="961" alt="Tw2" src="https://user-images.githubusercontent.com/112633185/222540316-6899653d-5deb-42ed-9783-f2da93a0fee9.png">
<img width="1329" alt="Tw3" src="https://user-images.githubusercontent.com/112633185/222540322-f22834b7-853c-4338-9c1e-ef5ccc0013d4.png">

<img width="616" alt="Feb 2023 Tw" src="https://user-images.githubusercontent.com/112633185/222540781-a4aa3580-8f2d-4ba8-8621-849a5456e33f.png">

**Telegram Phala**
Combot Link: https://combot.org/c/1421178003?start=2023-02-01&end=2023-02-28
<img width="771" alt="Tg general" src="https://user-images.githubusercontent.com/112633185/222540946-86f80252-39cd-456e-815e-b7b96f4bdd55.png">

**Phala Ru (local)** - Channel link: @phalaworld_ru
Combot Link: https://combot.org/c/1649002165?start=2023-02-01&end=2023-02-28
<img width="901" alt="Tg local" src="https://user-images.githubusercontent.com/112633185/222541041-08cd9e3c-2cc0-47db-af1e-c2ee2e33d69d.png">

**SUPPLEMENTARY TASKS**

#HD (actually it #CM)
I did much HD, the screen with the stats above is the best evidence of it. 
#CC  - 4 articles
https://medium.com/@infaceAI/78cb780dfada
https://medium.com/@infaceAI/b3ed8e5387df
https://medium.com/@infaceAI/eb7cd9cd7570
https://medium.com/@infaceAI/fb4a4f685aef

#ART
https://twitter.com/infaceAi/status/1627572763119562754
https://twitter.com/infaceAi/status/1629402066698264578

#RC (do not count it in self score)
I have done a bit different thing by started private group “Phala pre-advocate чат”
where I help pre-advocates to move to a candidate role.
The Feb result is here https://docs.google.com/spreadsheets/d/1HC_Y3ld1FCy9uzPXebFZNK3F-kiNHedgx1rkleTLJCU/edit#gid=0
Feb Twitter stats of these pre-advocates can be found in list “Feb stats Twitter”

SUGGESTED SCORES
#CC : 30/30
#MK : 40/40
#HD : 10
#CC:  10
#ART 3
Overall : 93

**p.s:** I want to continue my experiments with pre-advocates. I see some rooms for improvements as well as some areas with lack of people in it (for example, promotion in local languages). I think it can be patched in the next 2 months.
Also, I think it is a good idea to give at least some little rewards to pre-advocates/advocates. Let’s say ShellNFT, or some few PHA, of course if a person does activities for it. This can inspire people to make more effort on their way to a candidate role.

**Comment by willphala** [comment]
Fantastic work. I've been really impressed with your leadership/organisational skills with the pre-advocates. Keep it up!
