### ISSUE TITLE
February 2023 Contributions - {102j#2259}

### ISSUE THREAD

**Issue by ZunkCii** [Phala-Network/growth-program#122]
Telegram : @j102j
Discord : @102j#2259
PHA Address : 3zkfLRrjyCy33f9xTNHDwAEjdjJknx4W6ZQ6GVTk5ffJcpck

1. CM (Community Management)

Have I participated in Telegram Channel Moderation (choose)? Yes
Phala Korean Channel link: https://t.me/phalakorean
Combot Link : https://combot.org/c/1340032853/a?start=2023-02-01&end=2023-02-28

![image](https://user-images.githubusercontent.com/96286632/222597591-c078e79b-4845-4d51-8466-0a43952ad349.png)
![image](https://user-images.githubusercontent.com/96286632/222598355-ff7cc322-2631-4f5d-93df-64b940554244.png)
![image](https://user-images.githubusercontent.com/96286632/222597651-da05ba73-d8fa-4500-85b8-d12d3a6a6636.png)

2. VSM (Twitter Virals)

Twitter as Official Ambassador : https://twitter.com/ZunkCii
Analytic : https://analytics.twitter.com/user/ZunkCii/tweets

![image](https://user-images.githubusercontent.com/96286632/222597957-17bcb3a6-e1c0-4d46-a7e8-6cee97ca9531.png)
![image](https://user-images.githubusercontent.com/96286632/222597983-fb787a80-09c1-4b4b-8f63-d266be4bce4c.png)

3. CC (The Contents Creation)

https://blog.naver.com/102j102j/223016845685
![image](https://user-images.githubusercontent.com/96286632/222598098-7ee4bba6-cf02-4829-b272-7d5005c18e86.png)

MK: 40/40
CM: 40/40
CC: 10

**Comment by willphala** [comment]
Good work. You need to participate within our departments to achieve 30+/40 scores. Please message me if you require any support/information.
