### ISSUE TITLE
February 2023 Contributions

### ISSUE THREAD

**Issue by KAMALAIMMACULATE** [Phala-Network/growth-program#123]
Name: Kamala Immaculate
Email: (kamalaimmaculate@gmail.com)
Telegram: Kamala Immaculate
Discord: Kamala Immaculate#5476
Twitter: @Immei256
PHA Address: 46KQkYs3uxsS8zxVGKK9BpdcaVt2vUaspA2Rn45mkmCehEjr
Contribution of February: Ambassador

Departments: CC & MK
Department Score Weight: 40% & 35%

1st Contribution
Community Management
I have been sharing updates about Phala Network in the African Telegram channel, greet and welcome new members and also participating in ways how we could grow our Local community in Africa e.g Hosting monthly  Calls.
**Telegram Activity**
![snip3](https://user-images.githubusercontent.com/61009431/222726848-b6de25cd-4bb1-4989-8401-5dfcbd96e45b.png)
![Snip2](https://user-images.githubusercontent.com/61009431/222726899-d487a598-c787-46f8-b073-c42856b93c7b.png)
![snip1](https://user-images.githubusercontent.com/61009431/222726922-783fe215-27b0-4b42-bc89-5274e54c7150.png)

I gave a presentation about Understanding Phala's Spirit NFT during our Monthly Community Call
https://www.google.com/url?q=https://docs.google.com/presentation/d/1YBubsgpooIhEyWnMT9n5DFLB3LeROQReFOMG5bJBfoU/edit?disco%3DAAAArxb9sUE%26usp%3Dcomment_email_discussion%26ts%3D63f82030&source=gmail&ust=1677336997833000&usg=AOvVaw3Z_4DnaEoi8GNd3OSbHcs1

Twitter:
I created some content about Phala Network and Phalaworld
And I am also trying to grow the main account for Phala Africa by posting some content about Phala and I am hoping for some improvement in this month of March.
Phala Africa Community twitter Activity
![Snip6](https://user-images.githubusercontent.com/61009431/222731651-9209add9-62b5-4d6e-9ed7-b7ee08f14177.png)
![snip5](https://user-images.githubusercontent.com/61009431/222731675-11276a70-3b4b-4ec0-a875-d2afbc4bd33f.png)

LinkedIn
My focus has been on growing all local channels including LinkedIn, I made three post and posted.
I received some impression, I will move forward to growing the account.
LinkedIn Activity
![snip9](https://user-images.githubusercontent.com/61009431/222734817-cae47341-a4f7-4416-8182-cd7989802178.png)
![snip8](https://user-images.githubusercontent.com/61009431/222734869-e579a0fc-0914-4c68-9821-b31b4622a042.png)
![snip7](https://user-images.githubusercontent.com/61009431/222734897-ddb90909-4709-41ca-8a4b-100ed7393812.png)

I also promoted Phala Network on my Twitter account by creating content and sharing on Twitter.
Liked and retweeted posts from Phala and PhalaWorld official accounts. Engaged with fellow ambassador posts. Posted tweets. Engaged with posts about Phala Network.
Twitter Activity
![snip10](https://user-images.githubusercontent.com/61009431/222737251-d8fecad4-7f71-4ef7-99dd-d132cdc852d3.png)
![ss](https://user-images.githubusercontent.com/61009431/222737295-05ae1616-70ee-4343-bde5-3e5ee1d0e646.png)
![snip12](https://user-images.githubusercontent.com/61009431/222737414-f0286296-c3c6-456c-b3a1-2bfe78f97092.png)

Tweet Links
https://twitter.com/Immei256/status/1626990739115716610?s=20
https://twitter.com/Immei256/status/1627638477239078912?s=20
https://twitter.com/Immei256/status/1626292583013011456?s=20
https://twitter.com/Immei256/status/1625229795234615296?s=20
https://twitter.com/Immei256/status/1624816682521841668?s=20
https://twitter.com/Immei256/status/1624071914787418114?s=20
https://twitter.com/Immei256/status/1624066178745348096?s=20
https://twitter.com/Immei256/status/1622593022226583553?s=20
https://twitter.com/Immei256/status/1627638867930058758?s=20
https://twitter.com/Immei256/status/1627639150592593920?s=20
https://twitter.com/Immei256/status/1628402039234478081?s=20
https://twitter.com/Immei256/status/1630135635930431490?s=20

Things I have to improve on during my contributions of March
• Contribute more to department tasks and the CC/CM discord channels 
• Being more active in discord department channels and Phala Africa Telegram group.

SCORE
CC 40
MK35
PM 8
TOTAL 83

**Comment by willphala** [comment]
Good work Kamala. I feel that you've made significant progress this month, which is awesome! In terms of feedback, I would like to see you continue to increase your participation in our department chats/tasks and being more proactive and less 'reactive'. E.g. starting discussions and sharing ideas rather than just providing feedback etc.
