### ISSUE TITLE
February 2023 Contributions - {Jeretucu | Tucuman.Phala#4603}

### ISSUE THREAD

**Issue by Jeretucu** [Phala-Network/growth-program#124]
Telegram : [jeretucu](https://t.me/jeretucu)
Discord : Jeretucu | Tucuman.Phala#4603
PHA Address : 41D9LFABTeEMZMgaskRaob15k6c7RAsriJeLNSnvWVApZnv3

Contributions : CC50% & CM50%

Make all the translations of the weeklies in the official channel of Phala in Spanish
https://medium.com/phala-espa%C3%B1ol/phala-asistir%C3%A1-a-ethdenver-la-granja-de-pha-est%C3%A1-en-online-en-moonbeam-semanario-de-phala-vol-a58be551054b
https://medium.com/phala-espa%C3%B1ol/el-programa-phala-builders-ahora-est%C3%A1-aceptando-solicitudes-f43c1c6f4c1e
https://medium.com/phala-espa%C3%B1ol/lanzamiento-del-programa-phala-desarrolladores-ca6ecb7f4466
https://medium.com/phala-espa%C3%B1ol/phala-comparti%C3%B3-la-hoja-de-ruta-2023-en-una-llamada-comunitaria-el-marketplace-de-pw-en-desarrollo-9f35ea0b656b

Twitter as Official Ambassador : https://twitter.com/jeretucu

![image](https://user-images.githubusercontent.com/107716407/222757603-9348ef76-756e-4c06-a922-f8cbc638bf4c.png)
![image](https://user-images.githubusercontent.com/107716407/222757893-f1f97775-695f-4979-b767-ef7fc7ce914d.png)

Telegram

![image](https://user-images.githubusercontent.com/107716407/222758425-208b5375-2b53-4344-b27e-947ef4af698b.png)

![image](https://user-images.githubusercontent.com/107716407/222758596-c4b41e47-9b3a-42a8-ba15-38f82f10954f.png)

AMA with CESS
https://twitter.com/jeretucu/status/1628149214818492423
![image](https://user-images.githubusercontent.com/107716407/222758773-fce8745e-483d-470a-924e-7053e08407a2.png)

BH
![image](https://user-images.githubusercontent.com/107716407/222759455-9b41cf07-b0e6-4182-a58e-bd124071567d.png)

![image](https://user-images.githubusercontent.com/107716407/222759639-717e1f88-51c9-405a-b75b-38744645244b.png)

[BUG Vault.docx](https://github.com/Phala-Network/growth-program/files/10883463/BUG.Vault.docx)

SUGGESTED SCORES
Community 35/40
Contect 35/40
Supplementary tasks, 20/20

**Comment by willphala** [comment]
Great work. Especially with being more active in the department channels!
