### ISSUE TITLE
February 2023 Contributions {favour_cy#5138}

### ISSUE THREAD

**Issue by BBoss01** [Phala-Network/growth-program#125]
Telegram: @solomon_bb
Discord: favour_cy#5138
Twitter: https://twitter.com/official_bles1?t=v-D8pvqj0jPHS2TpvqSdlw&s=09
PHA Address:  41dNB3qCWz1m4b874815wYnthsbSUvmKUws6624wRrjX4tnL
Rank : Ambassador 

Department : MK & CC
Department score weight: 60/40

Have I moderated the discord channel? Choose Yes
Have I moderated the telegram channel? Choose Yes 

DEPARTMENTAL TASKS 

MK

I promoted Phala on Twitter, on Reddit ( on PN page and outside to increase engagement and community growth) and Instagram. I retweeted all posts from Phala Network and PhalaWorld Twitter page plus some local pages and from other Phala ambassadors.

![IMG_20230303_121521_839.jpg](https://user-images.githubusercontent.com/116058765/222761876-06bd4901-6ed9-49b6-ae74-605d5ffdf3e4.jpg)![IMG_20230303_121517_866.jpg](https://user-images.githubusercontent.com/116058765/222761907-810d92bb-5ba9-485d-8e18-381cb8a966c2.jpg)

Twitter stat: https://docs.google.com/spreadsheets/d/1jw-Rr95gozF6K0ibWub5JlJvKNgmTYsEIV-lyyy9i6M/edit?usp=drivesdk

Twitter Link: https://twitter.com/official_bles1?t=OOx3R_ljSgSgEVebPOohDw&s=09
Alt Twitter: https://twitter.com/Official_Cygirl?t=IfGgEIYtNFVSlnS6zd1W1A&s=09

Reddit Link: https://www.reddit.com/u/favour_cy?utm_medium=android_app&utm_source=share
Reddit stat: https://drive.google.com/drive/folders/1C_ScjMuFWpIWOL8z6UQZrlfMxLp0ZMiY

IG Links : https://www.instagram.com/p/CosADLao2mb/?igshid=YmMyMTA2M2Y=
https://www.instagram.com/p/CpFLHkKoQ2r/?igshid=YmMyMTA2M2Y=
https://www.instagram.com/p/CoXVFQOol2v/?igshid=YmMyMTA2M2Y=

 

CC
 I created and shared some educative content on Reddit and IG, I supported Angie with little information for her presentation and I transcribed the community call, https://medium.com/@phalaafricacommunity/phala-african-community-talk-session-afe10169261f
https://medium.com/@phalaafricacommunity/scarlet-phat-contract-e994cddb18a6
it was uploaded to Phala African medium account by Kamala.

SUPPLEMENTARY TASKS 

ART
I created and shared infographics, banner and video

https://twitter.com/official_bles1/status/1630910638418546688?t=5lXLIaQrjre34rqtiJkRVg&s=19

https://twitter.com/official_bles1/status/1629434272963543043?t=a1IMff07S9TSGi0rsi_zeA&s=19

https://twitter.com/official_bles1/status/1628715764676022277?t=rzXX12v8Ve3LayyY-sSr-Q&s=19

https://twitter.com/official_bles1/status/1626939303069728774?t=d-MARyALq3kytlW2QR0qyw&s=19

https://twitter.com/official_bles1/status/1625893230016446464?t=dVU8931QRRvbF_CMKgSo8w&s=19

https://twitter.com/Official_Cygirl/status/1628121006354169857?t=Lhr-asGHgwEV-iCSE0PFqQ&s=09

https://www.reddit.com/r/PhalaNetwork/comments/11g0pvs/phat_contract/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

CC
I wrote two articles about PhalaWorld and SubBridge

 https://link.medium.com/h7B3Fn13Pxb
 https://link.medium.com/Nb7GC523Pxb

CM ( HD)
1. I had daily engagement on PN discord server, There's been growth in the African telegram community in terms of engagement and population. I had little engagement on Phala World discord server this month, I answered some questions and shared some helpful resources on discord, local telegram and reddit.
2. Phala African TG community engagement reduced in the middle of the month (second week to third week) but the community call brought back the vibe.
3. I'll keep being active in the  African telegram community and also pay more attention to Phala World discord server.

Suggested Scores

MK : 40
CC  : 30
ART : 10
CC  : 10
HD : 10
Total : 90

I increased my community engagement this month alongside the quality of contents, worked closely with other African ambassadors and I had engagement in Marketing and Content discord channels.

**Comment by willphala** [comment]
Good work Favour. To achieve a score within the region of 90 I need you to be substantially more active within our departments. Ping me if you need any support with this!
