### ISSUE TITLE
February 2023 Contributions -{ The Scarlet Thread#2215}

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#126]
Telegram Username: @Scarlet_Thr
Discord Username: @TheScarletThread#2215
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

### BASIC/MANDATORY CONTRIBUTIONS
**CONTENT CREATION**
_STANDARD TASKS_
● Meme
Made a fan art for PhalaWorld. This was in the theme of a Dooms Kitchen Pub. I used many layers of graphic elements and some animated elements like rain and steam. Incorporated PW characters and background as the view from the window. This was intended to be a little funny and to help survivors imagine more scenarios in PhalaWorld. 
https://twitter.com/TheScarletThr/status/1626098461199282176?t=26YDCQEXsvqOQFAlz3IKag&s=19 

● Explainer video
Made an explainer style video for talking about Phala Builders program. This video was one minute. I noticed from the tweet analytics for this particular piece of content that 15-30 second videos do better in terms of people staying to watch till the end.
https://twitter.com/TheScarletThr/status/1630326763204100096?t=8I05WaRWVuN7kr-RiEIfPg&s=19 

● Phat Contract presentation for Phala Africa Community Call and accompanying video.
Researched and compiled a presentation to help our local community members understand Phat Contract better.  Thereafter, I made a 7 minute video of the presentation slides and did a voiceover so that the presentation can be viewed again with clearer sound. The resources I used as content for the presentation can be found in the Google docs here.
 1. Presentation Script
https://docs.google.com/document/d/1HmDekz_tPsoBZ5TYJOgUVpBFqYE2b00xvR3IkEROumM/edit?usp=drivesdk

2. Video
https://drive.google.com/file/d/1kgSSW-INjyIwhCbCetX_zZCjgcm1LLso/view?usp=drivesdk 

● Collaborated with Phala Africa Ambassdors on creating content for Phala Africa February Community Call.
Collaborated with fellow ambassador Kamala in offering input for her spirit nft presentation. I tracked community questions that needed to be answered in the event from the Google Form that I created. Tracked questions during the community call. I prepared some PhalaWorld related FAQ to be read in the community call and hosted the call on Google Meet.  Added my ideas and suggestions to improve our community call to a google doc form I created so we can brainstorm ways to create better content for our local community. 

_Department task_
● Contribute to pinned tasks
Contributed to the Phala for beginners guide by adding a piece of content about Phat contracts that was adapted from my presentation research. 

● Participation in discord channel
Participated in discussions in the content creation discord  channel with other ambassadors about topics such as content creation tools, offering input on presentations etc.

**COMMUNITY MANAGEMENT** 
_STANDARD TASKS_
● Monitored Phalaworld discord server, Phala Africa telegram and the Africa discord channel.
I maintained a constant presence in these chats. Greeted and welcomed new members. Engaged in discussions with members. Answered community questions. Referred community to useful resources when it is applicable.Removed spam and inappropriate content from channels when they came up and banned bots/spammers. Resolved concerns from community members when I could. 
Our engagement is slowing down from the first two months after group was created. So we should plan how to improve this and how to shift discussions to our discord channel. I can improve on my Phala Network discord stats.
1. PhalaWorld 
![Screenshot_20230303-171106_Discord-01](https://user-images.githubusercontent.com/99918790/222760826-3c7207eb-e9ae-430c-b5d2-7d09b6d0fd9d.jpeg)
2. Phala Africa Combot
![Screenshot_20230303-165729_Chrome-01](https://user-images.githubusercontent.com/99918790/222761093-c614a5b9-36b5-4714-b0b3-38f6b7c9ae24.jpeg)
 
● Coordinated with Phala Africa Ambassadors to organise Februrary community call and attended rehearsal for the community call. 
Helped to organise the Community Call with the other Phala Africa Ambassadors. I played my role this month in identifying tasks that needed to be done and setting appropriate deadlines, checked in with members to see if anyone needed assistance from my side. Worked on improving points from the last call such as the Q & A session. We need to improve our quality for the next call.

_DEPARTMENT TASKS_
● Contributed to the community digest by adding questioms from the community to the digest 

●Participated in the community management discord channel. I could improve in participating in the community management departments discord channel.

### SUPPLEMENTARY TASKS
**PM**
![Screenshot_20230303-174931_Samsung Internet-01](https://user-images.githubusercontent.com/99918790/222765278-c3f12298-db08-4608-88aa-47302f3f4303.jpeg)

![Screenshot_20230228-110657_Samsung Internet-01](https://user-images.githubusercontent.com/99918790/222765291-33633723-c883-4e5b-8c15-bb31efb18369.jpeg)

I tweeted about Phala Network 5 times which can be improved a lot, I engaged more in the form of commenting, liking and retweeting content from: Phala Network ambassadors, Phala and PhalaWorld Official twitter, Phala related content from EthDenver. I promoted Phala Network and PhalaWorld on other servers and even met some users in other Polkadot NFT related servers that had their PW NFTs as profile pictures.

### AREAS TO IMPROVE FOR MARCH
● This month I feel like I improved on the quality of my content but I want to increase the quantity this month. I will work on finding more ways to make  better content as well.
● I want to improve my stats on the Phala Network Discord server. Also, I would like to work on encouraging our local community to chat more on the Africa discord channel.
●Improve my technical skills for Community Call. I think making a video of my presentation was a good idea - in the event that I could not attend for unforeseen reasons, the presentation can still be played. 

### SCORES
CC 40/40
CM 40/40
PM 10/10
TOTAL 90

**Comment by willphala** [comment]
Excellent work. You've really stepped your game up this month. Proud of you! 👏
