### ISSUE TITLE
February 2023 Contributions - {Janema#7205}

### ISSUE THREAD

**Issue by Janemake** [Phala-Network/growth-program#128]
Telegram Username: @Janemake
Discord Username: @janema#7205
Twitter Username: https://twitter.com/JanemakeCrypto
PHA Wallet Address: 41owbtwKf7dfZxEfdfhRfey4uGLkg8V9iLG74ZhTQnMnsAwA

**Departments** : #CC & #CM 
**Department Score Weight** : 25% & 75% 

### ==========================     1. MANDATORY TASKS ==============================
**====== 1.1 CM ======** 
My contributions in this department during this month, I have contributed in the french and global community on both telegram and discord. This month i was more present on Discord for the french community and on telegram for global community.

The main activities have been:

In the french community:
- **Mining activities:** Help the Phamily members facing issues with their mining infrastrures / Help others to install their workers
- **Phat Contract:**  In the French communities, we have a dedicated working group for the Phat Contract implementation & promotion, every Wednesday , with all the ambassadors we organise a call at 9 PM CET and the community members interested to learn the Phat Contract. A reminder tweet on the last one from the phala_fr twitter account [here](https://twitter.com/phala_fr/status/1628482391395237898?s=20)
- **Use of Phala products:** help on the issues on staking activities, etc.

In the global community, 
- I was available to help and guide community members, on both Discord & Telegram with more presence on telegram. Stats available below. link [here](https://combot.org/c/1421178003?start=2023-02-01&end=2023-02-28)

![image](https://user-images.githubusercontent.com/58589481/222718595-203c3594-2ada-425c-8f0d-38b372f7dc05.png)

- I contributed by removing scam contents from the telegram group. 
- I also made a proposal to strengthen the telegram bot as we are facing a bot strike with scammy content. I believe improving this security measure could be useful for the community and the moderators. 

**====== 1.2 CC ======**
During this month, I was more focused on DEV contents related to Phat Contrat coding and tools required to extract data (mainly building squid from Subsquid related to Phala governances) that could be used in the Phat Contract.

In the Phala_FR, as part of the Closed Beta activities, we are also exploring the possibility to build a community bot  related to Phala products with Phat Contract.

IMO, DEV contents and time related should be considered somewhere in the different departments as it's more time consuming. As an example, the squid developed was approximatively **more than _3 000 lines of codes_** to be implemented and tested which are really time consuming. Link to source code of the squid [here](https://github.com/PhalaTeamFR/phalaTeamFR-squid)

In addition to DEV content, I have also published a lore of the Phala Word approximatively 1000 words as part of the contest organised by PhalaTeamFR. Link to the [medium](https://medium.com/@janemake/la-renaissance-de-cyb-jan-c44b648e37bb) .

The link was also shared on [twitter](https://twitter.com/JanemakeCrypto/status/1626350188808880130?s=20)
![image](https://user-images.githubusercontent.com/58589481/222739493-ee56ba6e-5474-4793-be62-4c94f11077ad.png)

I have also tested the PRB setup provided by Pigro85 and provided some amendements to the documents.

### ==========================    2. SUPPLEMENTARY TASKS  ==========================   
**====== 2.1 HD ======**
I've been more present in both french & global community to assist our commity by answering their questions related to Phala & PhalaWorld, providing them some hints in the mining deployment.

**====== 2.2 PM ======**
I have shared most of the Phala related subjects on Twitter to Promote events and products related to Phala & PhalaWorld.
extract of my twitter analytics of february. Most of my articles are related to Phala.
![Twitter analytics](https://user-images.githubusercontent.com/58589481/222758619-86650865-a632-4dc8-a18f-3ac39e0698b7.png)

![image](https://user-images.githubusercontent.com/58589481/222757912-7e2fe16e-94a3-4bd2-9346-69f919dd3241.png)

I took part actively in the different community events organized by Phala_FR (Community FR Monthly AMA, Weekly Closed Beta)

### ==========================   3. CONCLUSION  ============================== 
This month was exciting on DEV parts, as I started working deeply with Phat Contract products. It has been interesting to work on the different possibilities of the Phat Contract. As an ambassador, understanding the Phat Contract and its different possibilities, will give more confort in helping other to better understand the Phat Contrat and infrastructure requirements.

In addition of DEV contents, I have been able to contribute:
1. To promote Phala, 
2. To assist the community members on both french and global network
3. To participate to differents events.

For next month, my target is to increase the non-dev contents creation and continue my Phat Contrat development skills.  

### ==========================    4. SUGGESTED SCORES ============================== 
#CM : 38/40 with 75% CM => 57/60
#CC : 30/40 with 25% CC => 15/20 
with the split 75% CM /25% CC and the suggested score above, the **MD tasks suggested score is 72/80**

#HD : 10
#PM : 10

**Overall : 92**

**Comment by willphala** [comment]
Excellent work. I would love to hear some suggestions from yourself as to how to incorporate DEV related work into our programme, as per your comment.
