### ISSUE TITLE
February 2023 contributions [pigro85#6032]

### ISSUE THREAD

**Issue by pigro85** [Phala-Network/growth-program#129]
Telegram: @pigro85
Discord: pigro85#6032
Twitter: https://twitter.com/pigro85
PHA Wallet Address: 44Rc9bxvmfyVJx1qmKThhUXUCuyhU6tqULvM5QKxtxks19uH

[CM]
Phala Italian Channel link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a
<img width="1023" alt="Screenshot 2023-03-03 alle 21 58 25" src="https://user-images.githubusercontent.com/92217448/222828140-23bcf1d3-dc80-471b-8cb1-7cdeb91f2671.png">

Phala Mining Channel link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a
<img width="1039" alt="Screenshot 2023-03-03 alle 21 59 07" src="https://user-images.githubusercontent.com/92217448/222828241-bf2dc881-d3eb-461b-8c41-91990d3de6ec.png">

![immagine](https://user-images.githubusercontent.com/92217448/222830423-3f2fe527-26ce-4326-a851-716d37fa3a4d.png)

Have I participated in Discord Channel Moderation? Yes
Have I participated in Telegram Channel Moderation? Yes
Removed all deleted account from the italian telegram group.

[CC]
This month no translation from my side, finalized the draft of the PRB guide with the team in order to publish it next week, write down my experience with phala in a short way.
https://pigro85.medium.com/phala-pool-912-a-decentrilized-experiment-7de138081059

Collaborated more in general with others ambassadors providing feedback and personal POV on content shared on discord.

[MK]
Standard activity on Twitter.
<img width="929" alt="Screenshot 2023-03-03 alle 22 04 08" src="https://user-images.githubusercontent.com/92217448/222829757-49b9240d-1eb7-4baa-b126-83785e0eab34.png">

<img width="929" alt="Screenshot 2023-03-03 alle 22 04 39" src="https://user-images.githubusercontent.com/92217448/222829780-4bef4b8c-d9a7-4771-b374-7357a642fd19.png">

<img width="929" alt="Screenshot 2023-03-03 alle 22 05 28" src="https://user-images.githubusercontent.com/92217448/222829808-38e5dd26-0393-4577-961a-282c03e4d51a.png">

CM: 40/40
CC: 20/40
MK: 10

**Comment by willphala** [comment]
Great work. Your PRB was very well received by the core-team, keep it up Pham! 👏
