### ISSUE TITLE
July 2022 Contributions - {Cappex#7765}

### ISSUE THREAD

**Issue by cappehub** [Phala-Network/growth-program#13]
Telegram : [cryptocappex](https://t.me/cryptocappex)
Discord : Cappex#7765
PHA Address : 46FGLnh69wQ2EQU6gotqhmZjq9foVCF4vYSYaaLmxKViPGTr

My Mandatory (Basic) Contributions of July:
Senior-ambassador

Phala Italian Channel link: https://t.me/phalaitalia
Have I participated in Discord Channel Moderation (choose)? **Yes**
Have I participated in Telegram Channel Moderation (choose)? **Yes**
Combot Link : https://combot.org/c/-1001169537547/a

![PHA community JULY](https://user-images.githubusercontent.com/57374748/182237584-11b6f65e-c5de-4b9b-b75d-070cde92432d.jpg)
![PHA community JULY2](https://user-images.githubusercontent.com/57374748/182237659-cf77fbb0-42f8-44a3-8490-71f4cd7a0bc4.jpg)

Comments :

- How many people increased or decreased? Why?
The number of users increased from the previous month
- What was good?
Appreciation of and interest in Phala World and the latest published content such as Shells of Origin of Species.
- What was bad?
Introducing people to mining is still difficult, but there have been some users who have purchased and delegated the PHA token for the first time. 
- How can I improve this next month?
The general change of positive sentiment in the crypto market may help in user growth and also attract new miners.

VSM(Twitter Virals)
Twitter as Official Ambassador : https://twitter.com/cryptocappex
Twitter as Official Local Phala Account : https://twitter.com/PhalaItalia
Analytic : https://analytics.twitter.com/user/cryptocappex/tweets
Analytic : https://analytics.twitter.com/user/PhalaItalia/tweets

Comments :
Like the last month, with my personal account I tried to maximize the visibility of some of the tweets from the general account, I liked and retweeted every message from Phala Network and Phala Italy.
https://twitter.com/search?q=PhalaNetwork%20(from%3Acryptocappex)%20until%3A2022-07-31%20since%3A2022-07-01&src=typed_query
https://twitter.com/search?q=%24PHA%20(from%3Acryptocappex)%20until%3A2022-07-31%20since%3A2022-07-01&src=typed_query&f=top
![cappex JULY](https://user-images.githubusercontent.com/57374748/182241176-eea57273-eb16-4d65-8494-7eba2dbe4914.jpg)

The Phala Italia account retweeted in Italian all the tweets sent by the official Phala Network account and shared them in the telegram group; the Phala Italia account achieved 3,400 views in July and an interaction rate of 9 percent, up from the previous month.
![phala JULY](https://user-images.githubusercontent.com/57374748/182241970-12b24937-c846-4f61-99b4-5a1519090b6b.jpg)

==========

My Supplementary(Advanced) Contributions of July:

CC(Contents Creation)
Translation of articles on Medium from Phala World and Weekly Reports from Phala Network.
https://medium.com/phala-italia/latest

TT(Tutorial)
Introductory thread on how to delegate PHA on twitter:
https://twitter.com/PhalaItalia/status/1550224775825555459
![phala JULY tutorial](https://user-images.githubusercontent.com/57374748/182242873-ed6f3177-a90d-40e0-a931-5fd2f82bfb68.jpg)

**Comment by RHEEUNION** [comment]
Hi, Cappex. Really like your last tutorial thread on Twitter!
However, the thread is still counted as part of VSM, but please keep up the high-quality thread all the time =]
Thank you very much, and your point exceeds 90% already even without the TT supplementary points, so you will definitely get extra bonus again in this month.
