### ISSUE TITLE
February 2023 Contributions - Arηo#8446

### ISSUE THREAD

**Issue by arnobase** [Phala-Network/growth-program#133]
February 2023 Contributions - Arηo#8446

Telegram Username: @arnobaze
Discord Username: Arηo#8446
Twitter Username: https://twitter.com/test_ut
PHA Wallet Address: 44siNV2pbrTSwiL3KdT4VVC1yqcSvfGzxcd7rHMD1cgQnjcn

mandatory tasks : CM & CC
ratio : 70%CM (56/80) - 30%CC (24/80)

# Contributions:

### 1) Good points:
presence on a daily basis on every channels of international and french community
![Capture d’écran 2023-03-04 à 23 14 54](https://user-images.githubusercontent.com/8094810/222931018-9e6f8db7-9787-41e1-aa42-8b4dcbf3031c.png)

Reading all messages on international channels, and French channels
Providing assistance on any question types: general, mining, bridging, staking
Reaching out to amb channels to ask for assistance when necessary
Redirecting chats to adequately channel 
Value added on every conversation: don't reply when not necessary (already answered and no useful complement)
Extensive usage of pha words branding
Reactive to official announcements, post links on channels

- Securing channels by removing spam and banning inadequate users
![Capture d’écran 2023-02-25 à 22 20 11](https://user-images.githubusercontent.com/8094810/222931053-4f807516-6f85-487c-9733-0991c86125f8.png)

- Added some of the month most asked questions to the dedicated document

- Proposed a full Rewriting of the TG messages bot
https://docs.google.com/document/d/1VPR28XMVqoKPnpMJLNfwIgi7Qad7g086w1Kid8_zQFk/edit?usp=sharing

- TG spam groups monitoring, found 5 fake groups, warn the community about it along the month

### 2) bad points:
Good collaboration with teamFR but not enough with other international teams

### 3) how to improve :
collaborate with other team to increase synergy

### Good points

a lot of work on content this month, with a lot of teamwork (TeamFR and Italian team)
- Overview of the networks and withdraw fee for PHA on CEX into a dedicated document
  https://docs.google.com/document/d/1o4GEq7B2y7JoCvnBfN0q3yVnoObgShjEOLs8-JFWjGw/edit
- translation of Phala builders thread
  https://twitter.com/test_ut/status/1623763090897600512
- Medium article proofreading and editing
	- https://medium.com/phala-fran%C3%A7ais/la-seconde-transaction-de-r%C3%A9compense-de-calcul-aura-lieu-%C3%A0-2h00-utc-le-21-f%C3%A9vrier-1ee84ec20b00
	- https://medium.com/phala-fran%C3%A7ais/phala-arrive-au-ethdenver-34cada3cc6e5
	- https://medium.com/phala-fran%C3%A7ais/lancement-du-builders-program-de-phala-83fffb8748b5
	- https://medium.com/phala-fran%C3%A7ais/phala-a-partag%C3%A9-sa-roadmap-2023-lors-du-community-call-la-marketplace-du-phalaworld-est-en-ce6116de13ce
- proposed PhalaTeamFR video intro to CC for reuse in international contents
- collaboration with the Italian team, tested and commentated proposed procedure to install a PRB
  https://docs.google.com/document/d/1Rm8_lMdO_y0TsDArmcJnk99cZUJk3vAeePIfZmox93Q/edit
- Creation of an original content for the participation to the lore of "dame de la cantine" in Phala world
  https://docs.google.com/document/d/1WpvpsKCFqLW3FQve99yRqiD799CsIVHPnRYj-WIaRPk/edit?usp=sharing
- Translation in EN of subtitles for GatorKorp's video "Tutorial - Transfert PHA between blockchains and CEX and how to go on StellaSwap Pools" used for generating the voice in the EN video
  FR: https://www.youtube.com/watch?v=AJ_ypjD3OXY
  EN: https://www.youtube.com/watch?v=iKKGhQAoTHo
- proposed Vectr tool and made a template for content creation with Phala guidelines
  https://vectr.com/design/editor/62abbb05-ad75-4083-9138-b7057b6fa2ac

### 2) Bad points:
low regularity, more active in the end of the month

### 3) How to improve:
Be more constant to produce more content

#### EM: 
organisation with Tioneb and Janema of 4 workshop for Phat contract in PhalaTeamFR Discord (1/02, 8/02, 15/03, 22/02)

#### DEV
PhatContract development container setup and sharing on github
https://github.com/arnobase/phat-devcontainer
Deployed on Docker Hub
https://hub.docker.com/repository/docker/arnobaze/phat-devcontainer/tags?page=1&ordering=last_updated

#### HD
assist for users in DM or vocals to provide specific assistance

## SUGGESTED SCORES
- CM: 54/56
- CC : 20/24 
- HD : 10
- EM : 10

Overall : 94

This month I was very active in the community channels and in ambassadors channels. We worked as a team with other ambassadors of PhalaTeamFR to bring new ideas and help each others to provide good contents to the community, I brought added value by helping to develop Phala’s community, monitoring, engaging, supporting and spreading the Phala's culture, could help to improve the Phala ecosystem understanding by increasing the quality of assets produced and providing helpful attendance when necessary as a help desk.

For the next month, I want to improve the collaboration with other international teams, to get an even better synergy.

**Comment by willphala** [comment]
Great work. I've given you 10/10 for DEV rather than HD because CM/HD are essentially the same tasks.
