### ISSUE TITLE
February 2023 Contributions - {nikkilikeonlynikki#0803} 

### ISSUE THREAD

**Issue by NikkifromDotSama** [Phala-Network/growth-program#134]
Telegram: @jungesbluthatmut
Discord: nikkilikeonlynikki#0803
Twitter username: https://twitter.com/dabeibleibn
PHA Address: 43UYPSJwcuoQWGihJajJqEcZChbbfjFhDEkE5wwjd28z2PjZ

Contributions:
MK and CC:
My goals in February were following:
 - promotion of the Phala/Khala through a personal twitter account, interaction with other DotSama communities (especially german).
 -creation of content for German-speaking users
- building of German community around Phala/Khala
- creation of Polkaverse(Subsocial) for Phala Germany 
- articles/translations into German
- discord activity +managing of Phala german section in Discord
- creation of new social-media activity "GM Phala" in Twitter

 Here are some analytics + best tweets:
<img width="977" alt="Знімок екрана 2023-03-05 о 21 31 27" src="https://user-images.githubusercontent.com/125280467/222981985-c04e160b-9767-4554-8023-76df147d6378.png">
<img width="383" alt="Знімок екрана 2023-03-05 о 21 32 00" src="https://user-images.githubusercontent.com/125280467/222981990-d1082d8e-1981-4268-8178-e16904331621.png">
<img width="852" alt="Знімок екрана 2023-03-05 о 21 32 47" src="https://user-images.githubusercontent.com/125280467/222981993-9e8f21ec-936c-48fe-adf1-08289ec2be8b.png">
<img width="856" alt="Знімок екрана 2023-03-05 о 21 32 58" src="https://user-images.githubusercontent.com/125280467/222981994-193edf22-5025-44b5-8d58-bebd6b3752cb.png">
<img width="835" alt="Знімок екрана 2023-03-05 о 21 33 13" src="https://user-images.githubusercontent.com/125280467/222981995-96bd141e-9d8c-47e4-9cb2-bf0a62bd2cda.png">
<img width="850" alt="Знімок екрана 2023-03-05 о 21 33 21" src="https://user-images.githubusercontent.com/125280467/222981996-c3bdc90b-7664-4d47-9503-26963f8cf50a.png">
<img width="846" alt="Знімок екрана 2023-03-05 о 21 34 07" src="https://user-images.githubusercontent.com/125280467/222981997-26fcf6fd-cee5-40a2-9bf8-33403937c802.png">
<img width="826" alt="Знімок екрана 2023-03-05 о 21 55 21" src="https://user-images.githubusercontent.com/125280467/222982688-334709c2-4ee0-4101-96f1-fbb0cc1d49ec.png">

Twitter-threads of high quality and high educational level(21):
https://twitter.com/dabeibleibn/status/1622634322606927872?s=20&t=N17gJXkCeD9pige051djuQ
https://twitter.com/dabeibleibn/status/1623710198413115392?s=20&t=IV6YrEERFyS0YOpXjTM0vQ
https://twitter.com/dabeibleibn/status/1623759837266935810?s=20&t=dRbr2GMReKX0vPZP_L135g
https://twitter.com/dabeibleibn/status/1624046659763154948?s=20&t=ZB7my2RlNQD5UqVZ0Lc7kQ
https://twitter.com/dabeibleibn/status/1624427211787755520?s=20&t=vuS8_ThQgyZTinMpX6-vWA
https://twitter.com/dabeibleibn/status/1625029800413786114?s=20&t=oK1JA738tt-mlTIN4AYe7Q
https://twitter.com/dabeibleibn/status/1625159091789209600?s=20&t=vlDujM_qNqporkq8DmIr1Q
https://twitter.com/dabeibleibn/status/1625400884543778816?s=20&t=1kCE5zr1Gv3jSstBxreHgA
https://twitter.com/dabeibleibn/status/1625821658152898562?s=20&t=i1peCHYEkovyCxM_lg7GUg
https://twitter.com/dabeibleibn/status/1626460814965108736?s=20
https://twitter.com/dabeibleibn/status/1626868156940619776?s=20
https://twitter.com/dabeibleibn/status/1627569279792021504?s=20
https://twitter.com/dabeibleibn/status/1627924256163041281?s=20
https://twitter.com/dabeibleibn/status/1628053714031321088?s=20
https://twitter.com/dabeibleibn/status/1628300303798882304?s=20
https://twitter.com/dabeibleibn/status/1629072843697754116?s=20
https://twitter.com/dabeibleibn/status/1629392085202751492?s=20
https://twitter.com/dabeibleibn/status/1629711998228340737?s=20
https://twitter.com/dabeibleibn/status/1630212574766661633?s=20
https://twitter.com/dabeibleibn/status/1630840949944250369?s=20
https://twitter.com/dabeibleibn/status/1630887337516314625?s=20

Articles + translations (8):
<img width="782" alt="Знімок екрана 2023-03-05 о 21 56 31" src="https://user-images.githubusercontent.com/125280467/222982719-50daeecc-215d-4cd9-bda5-b0a4fd07052b.png">

1.Phat Contract. Hallo.
https://polkaverse.com/10988/phat-contract-hallo-37432
2.Phala Network baute zusammen mit SubQuery die ERC20-ChainBridge
https://polkaverse.com/10988/phala-network-baute-zusammen-mit-sub-query-die-37437
3.Phala: Transparente und private globale Computer-Cloud
https://polkaverse.com/10988/phala-transparente-und-private-globale-computer-cloud-37473
4.Phala kommt nach EthDenver!
https://polkaverse.com/10988/phala-kommt-nach-eth-denver-entdecken-sie-die-zukunft-des-37497
5.Die zweite Compute-Reward-Transaktion findet gegen 2:00 Uhr statt. UTC am 21. Februar
https://polkaverse.com/10988/die-zweite-compute-reward-transaktion-findet-gegen-2-00-uhr-37569
6.Wie man an einen StakePool delegiert?
https://polkaverse.com/10988/wie-man-an-einen-stake-pool-delegiert-37656
7.Wie kann man PHA-Token holen und transfer?
https://polkaverse.com/10988/holen-sie-sich-pha-und-transfer-37676
8.Builders-Programm
https://polkaverse.com/10988/builders-programm-37678

Suggested score:
#CC : 30/30
#MK : 40/40
#HD : 5
#CC: 5
#ART 0
Overall : 80

**Comment by willphala** [comment]
Great work Nikki. It's great to have you in our amb Phamily!
