### ISSUE TITLE
July 2022 Contributions - {102j#2259}

### ISSUE THREAD

**Issue by ZunkCii** [Phala-Network/growth-program#14]
Telegram : [치포](https://t.me/J102J)
Discord : 102j#2259
PHA Address : 3zkfLRrjyCy33f9xTNHDwAEjdjJknx4W6ZQ6GVTk5ffJcpck

My Mandatory (Basic) Contributions of July:
ambassador

CM(Community Management)
Phala Korean Channel link: https://t.me/phalakorean
Have I participated in Telegram Channel Moderation (choose)? Yes

Combot Link : https://combot.org/c/1340032853/a?start=2022-07-01&end=2022-07-31
![스크린샷 2022-08-02 오후 3 22 50](https://user-images.githubusercontent.com/96286632/182305969-138074d6-c27a-4952-9c40-a4d53d378a0f.png)
![스크린샷 2022-08-02 오후 3 23 03](https://user-images.githubusercontent.com/96286632/182305979-f574c159-3651-42fd-9821-25b577098a54.png)
![스크린샷 2022-08-02 오후 3 21 42](https://user-images.githubusercontent.com/96286632/182305984-8bddb691-d62a-4f2e-a90b-907fbb8f79b6.png)

EM(Event Manager):
- Community Call : https://t.me/phalakorean
7월 19일 PM 9:00 ~ 10:00 KST
- Casual Meeting (offline): Seoul Korea
7월 27일 PM 6:00 ~ 9:30 KST

Comments :
- How many people increased or decreased? Why?
The number of users did not increase from last month.
- What was good?
It has been confirmed that many miners' mining machines are becoming more stable.
- What was bad?
There are still difficulties in promoting and introducing mining to the Korean market. The reason seems to be that one of the characteristics of Koreans is that they want a big income right away.
- How can I improve this next month?
Because it was difficult to access due to the difficulty of using Linux and most of the English documents, it would be good to further subdivide the Korean guide. I plan to utilize Notion, not the Naver Blog I am currently using.

VSM(Twitter Virals)
Twitter as Official Ambassador : https://twitter.com/ZunkCii
Analytic :
![스크린샷 2022-08-02 오후 3 51 04](https://user-images.githubusercontent.com/96286632/182310563-b57143b0-c290-41e4-92ee-63b38c5780b3.png)
![스크린샷 2022-08-02 오후 3 51 16](https://user-images.githubusercontent.com/96286632/182310572-d1fa6944-0bbd-470d-9816-643b7f6f7708.png)

Comments :
We still need to learn how to use Twitter, but we will do our best to promote the ecosystem related to Pala, including Pala Network Pala World Polka Dot.

CC(Contents Creation) TT(Tutorial):

video of 'docker-compose.yml.template' modification
https://t.me/phalakorean/33904

5 posts in July
https://blog.naver.com/102j102j

Comments :
In July, due to the increase in Kusama data, there were many errors in the mining machine.
I have posted the basic parts to solve these errors. I posted the basic directory structure of Linux, monitoring method using rs232 cable, Linux reinstallation and node reinstallation methods.

![image](https://user-images.githubusercontent.com/96286632/182311791-08df2601-6e57-42c8-b07b-b3623d8f7761.png)

https://blog.naver.com/PostView.naver?blogId=102j102j&logNo=222796825564&categoryNo=6&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=&from=
https://blog.naver.com/PostView.naver?blogId=102j102j&logNo=222813608234&categoryNo=6&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=&from=
https://blog.naver.com/PostView.naver?blogId=102j102j&logNo=222833034539&categoryNo=6&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=&from=
https://blog.naver.com/PostView.naver?blogId=102j102j&logNo=222833065149&categoryNo=6&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=&from=
https://blog.naver.com/PostView.naver?blogId=102j102j&logNo=222834863764&categoryNo=6&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=&from=

**Comment by RHEEUNION** [comment]
Well-done, bro!
