### ISSUE TITLE
March 2023 Contributions - {BlackStone | Phala Amb#0238} (busy AF)

### ISSUE THREAD

**Issue by BlackStoneSheperd** [Phala-Network/growth-program#140]
PERSONAL INFO
Amb Rank : Senior Ambassador
Telegram : [BlackStone](https://t.me/BlackStoneSD)
https://twitter.com/BsSheperd
PHA Address : 42fBg7rmA9fp1dyA9LhVVKm5rAzNLLSxdiqkq46sBJGjEEHU

Departments : #CC & #MK
Department Score Weight : 25% & 75%

DEPARTMENTS
#CC
I've translated monthly articles & thread.
https://medium.com/@blackstonesheperd
https://medium.com/phala-fran%C3%A7ais
Arno gave me help and reviewed the translations as usual. 

The lore contest launched by gator for the french community is stil ongoing.

I've created a teasing with little video made with my shell (like my french mates did too)
here : https://twitter.com/BsSheperd/status/1635018466817343488?s=20

----- Monthly Community Call held with Astar FR -----
https://www.youtube.com/watch?v=YuZX9xvPB-c

#MK (Twitter)
Official Phala French
![image](https://user-images.githubusercontent.com/107954611/229927570-7b97cc32-9196-45c9-8233-f9744df478b6.png)
![image](https://user-images.githubusercontent.com/107954611/229927641-a2a334cc-106b-491a-acdb-ff1af3df653f.png)
Personal
![image](https://user-images.githubusercontent.com/107954611/229927830-d9314209-6415-4401-b8c6-2f9b9a2a0977.png)
![image](https://user-images.githubusercontent.com/107954611/229927874-af58b1c1-a849-416e-bd28-dbde762cf6a5.png)

#Supplementary
I helped Angie reviewing articles, with my italian mate Cappex 

#Other 
I'm officially a Computing Provider. My machines are running smoothly. I have PRB setup thanks to Tioneb who gave me helps during months !

SUGGESTED SCORES
#CC : 30/40
#MK : 30/40
#Supplémentary : 10
Overall : 70

It's been the worst month of my life talking about work and availability, this little month doesn't mean I'm not involved !

**Comment by willphala** [comment]
Don't worry, I know you're involved, we all have busy months so its all good. Thanks for your honesty and I hope that work gets less busy/stressful soon mate!
