### ISSUE TITLE
March 2023 Contribution - {Angie_ada#0973}

### ISSUE THREAD

**Issue by Angie-ada** [Phala-Network/growth-program#149]
Telegram Username: @angie_ada
Discord Username: Angie_ada#0973
Twitter Username: https://twitter.com/_encrypted_____
PHA Wallet Address:
42qf1tXPH8HfxBqUpTv79VHiTghEatoBnM1QULFgRRXeiUiL

Contributions:
DEPARTMENTAL
CC 30/40- I have participated actively in the department by publishing promotional content on Twitter, giving feedback on various contents provided and also served in providing quality content in form of  comprehensive slide presentations including pictorial content which served educational purposes during the last 2 Phala Africa monthly community calls (Feb & March).
I also participated in the review task for the content migration project on Notion.
I believe the goal of this department which is to facilitate deeper conversations and connections within and outside of our community was met.
Twitter posts
https://twitter.com/_encrypted_____/status/1641405492453863424?s=46&t=qpxJeJhHDn1u-4-9LSNFug
https://twitter.com/_encrypted_____/status/1638791352908500993?s=46&t=qpxJeJhHDn1u-4-9LSNFug https://twitter.com/_encrypted_____/status/1630684172317519872?s=46&t=qpxJeJhHDn1u-4-9LSNFug https://twitter.com/_encrypted_____/status/1630547730882867201?s=46&t=qpxJeJhHDn1u-4-9LSNFug

Presentation materials 
https://drive.google.com/file/d/13v2OvoyOyLXv4CpMfhC01ZiOrgpxeKGo/view?usp=drivesdk
https://docs.google.com/document/d/10AGGZOyWCwsiDMVC2HcaCC-xy9BzbJ1mVNl75C5ZslA/edit
https://drive.google.com/file/d/1gGqkld4nvzgHpD-LdgatzufoyfnPwPZt/view?usp=drivesdk https://docs.google.com/document/d/10AGGZOyWCwsiDMVC2HcaCC-xy9BzbJ1mVNl75C5ZslA/edit
![FE15F3F8-7B0A-44F9-AC9D-98F22CC07A16](https://user-images.githubusercontent.com/87555884/229937344-5daef6a4-6d93-47d8-83d2-dbbbbca00207.png)
![10D38F34-1C32-4063-B762-3EDD19794D0D](https://user-images.githubusercontent.com/87555884/229937351-734b7422-59ae-4306-a138-4ad24d28c354.png)

CM 30/40: 
I continued my participation in community moderation by nurturing, providing support to new and inexperienced users of the updated Phala App V2 in both Local and global Phala communities.
Myself along with the other African ambassadors and the advocate (Charles) have successfully maintained the African regional community on discord as well as Telegram; planned and executed community calls in Feb. and march, welcomed new members, provided support and security to the growing community as well as encouraging ambassador-applicants. 
I also created a sample Phala Africa logo in February and I suggested we make the flag picking a community event by making a poll from the available samples. (We’re yet to follow up on this due to the branding guidelines check). 
![013D5ACD-E5C7-461F-B152-5A966CBA65A8](https://user-images.githubusercontent.com/87555884/229944124-88821525-03a0-4d58-831a-208c3ad195fb.jpeg)
![EE0C556F-9EF1-4225-B65F-670BC1BADB28](https://user-images.githubusercontent.com/87555884/229944140-37165404-09fa-4211-adac-7cd012cf9d74.png)
![DF92969B-0613-4F8A-B4E2-C2E000D18B4D](https://user-images.githubusercontent.com/87555884/229944143-7d448389-37b3-43d1-8d09-e61780b8f93e.png)
![6A69D1F7-87F8-4C01-968A-46D4710A5E69](https://user-images.githubusercontent.com/87555884/229944146-511a2efe-37ef-4357-9e49-5bd4a8ff71e6.png)
 Stat for the main TG can’t be accessed 
![26EA3772-718A-47EA-9CDC-D92975EB167F](https://user-images.githubusercontent.com/87555884/229945089-0e27d4b2-c31c-4cb4-a29e-834e455a91e9.png)
![057058C5-22A1-42AC-8A85-A4C2F6CD8CAE](https://user-images.githubusercontent.com/87555884/229948058-edab7b1c-a75a-4bbf-8949-f3074d177de4.png)

supplementary Tasks
EM 9/10- Collective planning and execution of the Phala Africa monthly call in February and March. Corrections gotten earlier on based on branding and presentation style were executed and the call (though having a modest number of listeners) was generally successful. https://drive.google.com/drive/folders/1PGdUYHCN6Ilac9Z6_jQr-Bu05k5MDBx2
Plans are in place to make April’s call even more interactive.

ART 8/10- I created a sample Phala Africa flag in February, and custom canva design slides in both February and March (following the branding guidelines).
![8CA6F62E-1E4F-4E6C-B8A7-50448C2FE526](https://user-images.githubusercontent.com/87555884/229947189-02a28a79-f11d-44cb-8e6a-49e49c44a618.png)
![70DE6E1B-69DA-4C91-9412-CB88C408E481](https://user-images.githubusercontent.com/87555884/229947204-8ce48eae-f091-49c5-bbfb-d621514cf238.png)

**Comment by willphala** [comment]
Hey Angie. Please note that ambs can't:
- List contributions from previous months.
- Be rewarded twice for the same contribution e.g. listing creation of slides as CC and also EM.
