### ISSUE TITLE
March 2023 Contributions - {Rom1.io#5329}

### ISSUE THREAD

**Issue by Rom1io** [Phala-Network/growth-program#153]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/63704652/216827308-dd6a24be-5517-4e09-9c0e-c65a763aca3b.png">

Amb Rank : Candidate
Telegram Username: https://t.me/Imo_999
Discord Username: Rom1.io#5329
Twitter Username: https://twitter.com/RCajina
PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q

Departments : #CC & #MK

**Contributions:**

Hello! I'm thrilled to present my contributions for the past month as part of the FR team, which had a great month of March. Working as a team has been a real pleasure and I look forward to continuing to work together to produce even more quality content for our audience.

Twitter analytics: [Here](https://analytics.twitter.com/user/RCajina/home)

![image](https://user-images.githubusercontent.com/63704652/230175934-527ff031-80ef-466e-882b-89ebad8ec195.png)
![image](https://user-images.githubusercontent.com/63704652/230175856-163130f8-0f0b-481c-8400-13db1ef44b79.png)

**Best Tweets:** 
- Tweet 1: [Here](https://twitter.com/RCajina/status/1632004181178327042)
- Tweet 2: [Here](https://twitter.com/RCajina/status/1636753540063404034)
- Tweet 3: [Here](https://twitter.com/RCajina/status/1641023084273573889)

![image](https://user-images.githubusercontent.com/63704652/222129779-71fbe690-0699-4255-9d0f-68bbf45a9ce8.png)

![image](https://user-images.githubusercontent.com/63704652/230178300-cc3a2f42-dcfc-48cc-bd0b-c6b6cc17eb31.png)
![image](https://user-images.githubusercontent.com/63704652/230178512-7b95a2b6-a465-46af-8196-ed7c0a2256fa.png)
![image](https://user-images.githubusercontent.com/63704652/230178564-76a2d2ae-f0fa-4b1d-beb5-0cf8b8eafeba.png)
![image](https://user-images.githubusercontent.com/63704652/230178600-d252c3a8-7a23-4690-b9cd-e5629b554108.png)
![image](https://user-images.githubusercontent.com/63704652/230178987-4660895e-01cc-47c9-bde8-3517c0b55aa7.png)

![image](https://user-images.githubusercontent.com/63704652/222132673-f4bf53f3-fa03-42d8-b151-1c775e8231f0.png)

Organization & Participation in AMAs & Workshop on Discord with FR team see below: 

- Wednesday, March 1st: Phat Contract Workshop
- Wednesday, March 8th: Phat Contract Workshop
- Wednesday, March 15th: Phat Contract Workshop
- Wednesday, March 29: Phat Contract Workshop
- Tuesday, March 28: Monthly AMA Phala FR with Astar Network FR

![image](https://user-images.githubusercontent.com/63704652/222134127-67fe6ec1-f49c-43d7-a391-f681d8d5a87e.png)

I'm thrilled to have worked with Gator to design exceptional images for St. Patrick's Day, and it has inspired us to create animations and infographics for each upcoming calendar event, strengthening our online presence and engaging our audience in creative ways.

I'm proud to have worked with Gator to develop the strategy for the "La dame de la cantine" contest and to have set up a social media content delivery process for ambassadors. The creation of my character video for "La dame de la cantine" ([Here](https://twitter.com/RCajina/status/1632004181178327042)) was a true success thanks to the tools provided by Gator, which strengthens our ability to create engaging, high-quality content for our audience.

**Tools :**
- Create video : https://studio.d-id.com/editor
- Voice changer : https://voicechanger.io/

I want to thank Cappex for inspiring me to create quality content by offering "Analysis of real-world TEE-based blockchains" ([Here](https://twitter.com/RCajina/status/1636753540063404034)), an idea that has garnered great interest from our audience.

![image](https://user-images.githubusercontent.com/63704652/222134855-7eff0b13-3d74-4aad-a848-63d581a00c44.png)

I am confident that next month we will create amazing and informative infographics that will capture the attention of our audience and further strengthen our online presence.

## SUGGESTED SCORES
#CC: 30/40
#MK: 30/40
#ART: 10/10
#EM: 10/10

Overall : 80

***Quote*** : "Together, we are stronger and more creative than on our own, because we have a diversity of ideas and skills that can merge to produce amazing results."

**Comment by willphala** [comment]
I love the quote! 🙌
