### ISSUE TITLE
April 2023 Contributions - Arηo#8446

### ISSUE THREAD

**Issue by arnobase** [Phala-Network/growth-program#159]
Telegram Username: @arnobaze
Discord Username: Arηo#8446
Twitter Username: https://twitter.com/test_ut
PHA Wallet Address: 44siNV2pbrTSwiL3KdT4VVC1yqcSvfGzxcd7rHMD1cgQnjcn

mandatory tasks : CM & CP
ratio : 40%CM (32/80) - 60%CP (48/80)

### 1) Good points:
Daily presence and activity on international channels and FR channels, 

read all messages, follow up with community members and provide assistance on any question types: general, mining, bridging, staking
Antispam work, delete individual and raid spam, add spam words to blocklist bot
spotted Discord hacked account and urgently reported to Will
Added some of the month most asked questions to the dedicated document

Participate with FR ambassadors to the monthly community AMA on FR discord (Live twitch 27/04)
replay: https://www.youtube.com/watch?v=emzBCPXJndU

### 2) bad points:
focused on new CP dpt and less activity on TG

### 3) how to improve :
send again daily GM to phamily

### Good Points
Lot of work on the CP dpt

#### Phat contract testing
participate to the closed beta with FR team
https://github.com/Phala-Network/closed-beta-submission/issues/9
https://github.com/Phala-Network/closed-beta-submission/issues/1

#### Work with Radiumblock to add Khala archive to their available blockchain snapshots 
https://khala-archive.radiumblock.com/providers-khala-archive.php?name=khala_rocksdb_archive
tested 2 different snapshots to replace the Khala blockchain on 2 of my local nodes (1 on solo and 1 on PRB)

#### Improvements on Guide for PRB setup
added Khala snapshot archive download and setup (step 1.2)
- https://docs.google.com/document/d/1kgTOH6nh_wDp-vnntJ4ZgnhrABTzqZcOrVwcJ67mpCo

#### investigate on the PRB data-provider disk usage
compared different community members disk usage and reported into compute channel

#### help desk
provided help desk as a daily basis, reported to team when necessary

#### Phala mining test
started a new setup to test the new Phala mining
Deployed phala node (WIP)
Initiate a setup guide (WIP)

### 2) bad points:
some work is dedicated to current PRB setup which will soon be replaced by v3

### 3) how to improve :
 discuss more about the work in progress with the team in the compute channel

### maintain Doc PHA from CEX's (check networks, update fees)
- https://docs.google.com/document/d/1o4GEq7B2y7JoCvnBfN0q3yVnoObgShjEOLs8-JFWjGw

### organisation with FR team of 3 workshop for Phat contract in PhalaTeamFR Discord 
- 05/04 21h-23h
- 12/04 21h-23h
- 19/04 21h-23h

## DEV
dev UI for beta SDK (query and tx) on dApp client side
https://capable-muffin-6e7ae9.netlify.app/
https://github.com/arnobase/vite-mui-dapp/blob/master/src/components/ContractCall.js 

SUGGESTED SCORES
#CM : 28/32 
#CP: 45/48
#EM : 10
#DEV : 10

Overall : 93

This month I was in line with other month in terms of implication into the ambassadors tasks, 
I focused on the new CP department and improved my understanding of the Phat Contract SDK 
Main objectives are filled with added value in every tasks and being always helpfull to community and other ambassadors when necessary.

**Comment by willphala** [comment]
Excellent work. Especially spotting the hack so quickly!
