### ISSUE TITLE
July 2022 Contributions - {JimiFlowers#6721}

### ISSUE THREAD

**Issue by jimiflowers** [Phala-Network/growth-program#16]
Telegram : [JimiFlowers](https://t.me/JimiFlowers)
Discord : JimiFlowers#6721
PHA Address : 43Xvmd6hoLe4ibnPxaPxSYdq6smdHb5L8wAm7rKYpTB7sRTG

Phala Spanish Channel link: https://t.me/phalaspanish
Have I participated in Discord Channel Moderation (choose)? Yes
Combot Link : https://combot.org/c/-1001463390461/a?start=2022-07-01&end=2022-07-31
![imagen](https://user-images.githubusercontent.com/82945790/182451579-6a901232-16c1-4421-ad8a-57183f668d00.png)

Comments :

How many people increased or decreased? Why?
Increased in 23 people
What was good?
There is a growing interest in PhalaWorld metaverse
What was bad?
The general economy state and cryptowinter are not attracting investors to the web3
How can I improve this next month?
I'm preparing 2 AMAs in popular cripto channels, one to talk about Phala World and another to talk abour Phala Network  

VSM(Twitter Virals)
Twitter as Official Ambassador : https://twitter.com/PhalaEspanol
Analytic : https://analytics.twitter.com/user/PhalaEspanol/tweets

Comments :
Visits increased in 32% compared with June
I have retweeted in Spanish the tweets sent by the official Phala Network & Phala World twitter accounts, and created own content about them

![imagen](https://user-images.githubusercontent.com/82945790/182456240-e2482550-4c41-46e7-a659-d72cb9e543a9.png)

My Supplementary(Advanced) Contributions of July:
CC(Contents Creation):

Translation of articles on Medium from Phala World and Weekly Reports from Phala Network.
https://medium.com/phala-espa%C3%B1ol/latest

DEV(The Developer):

I have developed a tool to execute autopayouts for Phala/Khala rewards on Secure Worker Mining. It can be used by Pool owners or delegators. 

https://github.com/jimiflowers/phala-miner-autopayout

NOTE: I know this is not a development contribution to Phala code repositories, but I don't know what category to put in

**Comment by lubi-hub** [comment]
Keep up the good work Jimi and thank you for your continued support.

**Comment by jimiflowers** [comment]
> Keep up the good work Jimi and thank you for your continued support.

Thanks!
