### ISSUE TITLE
 inFaceAi April 2023 contributions report {infaceAi#5149}

### ISSUE THREAD

**Issue by infaceAi** [Phala-Network/growth-program#161]
PERSONAL INFO
Amb Rank : Senior Ambassador
Telegram:[ @infaceAi](https://t.me/infaceAi)
Twitter: https://twitter.com/infaceAi
PHA Address : 45vo82ABupacJoafLRW8oVWiYyErk9UqZLpfBn8wtE1zcB4M

**Departments** : #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

Contributions:
MK & CC -  I promoted Phala on Twitter, Discord and both Phala general and local telegram chats. 

**Twitter analytics** April 2023 stats:
<img width="604" alt="stat tw" src="https://user-images.githubusercontent.com/112633185/235721120-47086f72-a667-47fb-8556-b2e9fdd6771d.png">
<img width="825" alt="Tw 1" src="https://user-images.githubusercontent.com/112633185/235722577-ee49a61d-07d7-4995-9d6d-e1890b516ec8.png">

<img width="857" alt="Tw2" src="https://user-images.githubusercontent.com/112633185/235721260-0c6be1e5-b248-453e-bab6-a9c4f0f1f70e.png">
<img width="1041" alt="Tw3" src="https://user-images.githubusercontent.com/112633185/235723395-2d95cd6d-2e86-411a-8803-348a90bf49d3.png">

**Phala Ru (local)** - Channel link: @phalaworld_ru
https://combot.org/c/1649002165

<img width="770" alt="Tg local" src="https://user-images.githubusercontent.com/112633185/235721353-1b34687c-bb86-4f5b-abf4-3f243aa7bcd3.png">

**SUPPLEMENTARY TASKS**
**#HD (or #CM)**
I try to do as much HD as I did previous months(both general and local tg, as well as at different Discord’s chats).
**#CC**  - 3 articles
https://medium.com/@infaceAI/7e7f668825c7
https://medium.com/@infaceAI/fbd9e87429d6
https://medium.com/@infaceAI/fbd9e87429d6 This is How to stake (delegated) translation with adjusting https://medium.com/@infaceAI/fbd9e87429d6

**#ART**

https://twitter.com/infaceAi/status/1649713324680986624
https://twitter.com/infaceAi/status/1647666991363244035
https://twitter.com/infaceAi/status/1642818310793318403
https://twitter.com/infaceAi/status/1644013316614791178

**#RC**
This is the person, who have been doing job for Phala for 3 months,
Twitter @Dima35109517  Discord  Ivakhnenko_Dmitriy | Sui Apes#8257
His stats for April 2023
https://docs.google.com/document/d/1_w5Mn6MLeAErb1n55MWC6nINUOxZsnlnqO2lnF9jQRc/edit?usp=sharing

SUGGESTED SCORES
#CC : 35/40
#MK: 37/40
#HD: 10
#CC: 10
#ART: 9
**Overall**: 92 - according to the point system(up to 2 suppl. tasks are taken into account).

My performance is about the same as last month.
_Good moments_:
Daily presence and activity on Twitter and various chats on Discord and telegram, as well as some activity on PW Discord.
I try to both provide helpful responses to community queries and just keep the conversation going so that the chats feel more natural.
I translated 2 highly demanded topics - staking (wiki), and mining (PRB), thanks to Arηo for his work!
I also continued to work with pre-advocates. In fact, there are Dmitry and one more person who did not leave the race. Dmitry has shown good results for about 3 months so far.
Tori spent her 1st month as a candidate, showing consistently good results (I hope she will develop and her results will grow).

_Bad points:_
Rather not bad, but those where I would like to see more action, from both the Russian and especially Ukrainian community.

_How to improve_:
It will be good if we can see some activities from PW side (it attracted people in the past). And I am going to work with Tori in order to fill her video with more material about the phat contract in the next few months.

**Comment by willphala** [comment]
Excellent work as always. I look forward to hearing updates on your involvement with Tori's vids!
