### ISSUE TITLE
April 2023 Contributions - {Cappex#7765}

### ISSUE THREAD

**Issue by cappehub** [Phala-Network/growth-program#162]
Telegram Username: @cryptocappex
Discord Username: @Cappex#7765
Twitter Username: https://twitter.com/CryptoCappex
PHA Wallet Address: 46FGLnh69wQ2EQU6gotqhmZjq9foVCF4vYSYaaLmxKViPGTr

Contributions:
MK & PM - I promoted Phala on Twitter and on Polkadot and Kusama's official discord servers!
All the april details of my social (twitter) activity have been shared here: https://docs.google.com/spreadsheets/d/1jw-Rr95gozF6K0ibWub5JlJvKNgmTYsEIV-lyyy9i6M/edit#gid=0
https://twitter.com/search?q=%40phalanetwork%20(from%3Acryptocappex)%20until%3A2023-04-30%20since%3A2023-04-01&src=typed_query&f=top
https://twitter.com/search?q=%23phalanetwork%20(from%3Acryptocappex)%20until%3A2023-04-30%20since%3A2023-04-01&src=typed_query&f=top
https://twitter.com/search?q=%24PHA%20(from%3Acryptocappex)%20until%3A2023-04-30%20since%3A2023-04-01&src=typed_query&f=top
![cappex APR](https://user-images.githubusercontent.com/57374748/235766140-42f280a6-ebf8-47ee-a8a5-47b7e8d58daa.jpg)

CM
- Compilation of Community digest
- The local Italian community continues to have low participation, ambassador chat presence is constant as is the sharing of all important news!
![PHA community apr23](https://user-images.githubusercontent.com/57374748/235766806-f06f6e93-28ba-4a6c-8b3b-b6f2db1f5a2a.jpg)
![PHA community apr23_1](https://user-images.githubusercontent.com/57374748/235766975-467ba929-b97f-47c2-bf8c-7e8ba7cd48dc.jpg)
![PHA community apr23_2](https://user-images.githubusercontent.com/57374748/235767336-b23196b4-6af7-471d-a077-568eeff44d4e.jpg)

All april details of social activity related to Phala Italy's twitter account were shared here: https://docs.google.com/spreadsheets/d/1jw-Rr95gozF6K0ibWub5JlJvKNgmTYsEIV-lyyy9i6M/edit#gid=0
![PHA community apr23_3](https://user-images.githubusercontent.com/57374748/235767501-7f239071-85f5-4e25-bed8-ef59edf3b005.jpg)

HD 
- Constant presence in chat (discord and telegram), moderation, answering users' questions, removing spam and banning users who don't follow the rules!
![PHA community apr23_4](https://user-images.githubusercontent.com/57374748/235767886-b8269ac4-6ffb-443f-842f-592731641708.jpg)
![cappex discord apr23](https://user-images.githubusercontent.com/57374748/235768035-74fdba58-0463-4fa9-959f-80f9ee2f9e31.jpg)

CC Content Creator
- Review of articles on notion as a "Gatekeeper"!
- Translation of articles on Medium from Phala World and Weekly Reports from Phala Network.
https://medium.com/phala-italia/latest
I expect a result in line with other months 90%:
MK: 40/40
CM: 40/40
CC: 10

**Comment by willphala** [comment]
Excellent. You deserve a trophy for your community member detective work too haha.
