### ISSUE TITLE
Tori April 2023 contributions report {tori#2692}

### ISSUE THREAD

**Issue by toriribolla** [Phala-Network/growth-program#163]
PERSONAL INFO
Amb Rank : Candidate Ambassador
Telegram: @ToriRibolla
Twitter: @ToriRibolla
PHA Address : 435b1mp9FuSY4X6NNMTN6mALfyeChiQU1htPViw7hnD26sEM

Departments: #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

Contributions:
MK & CC -  I promoted Phala on Twitter and on YouTube, as well as translated some articles on the Medium. 

Twitter analytics April 2023 stats:

Twitter analytics and https://analytics.twitter.com/user/ToriRibolla/home
![Screenshot_108](https://user-images.githubusercontent.com/132458076/235914250-f20d2ced-fdf3-486e-a76e-e84d46b09451.png)

![Screenshot_109](https://user-images.githubusercontent.com/132458076/235911906-4515d31e-0e7d-4741-a0e8-fe7998c79554.png)
![Screenshot_110](https://user-images.githubusercontent.com/132458076/235913443-2b927c2b-a61a-47fa-b718-f06dde8517b8.png)
![Screenshot_111](https://user-images.githubusercontent.com/132458076/235913767-3fd4bebc-bbc4-41f8-886f-c707e1d31754.png)
![Screenshot_112](https://user-images.githubusercontent.com/132458076/235913785-adb1565b-f99e-4c09-a308-de9d7dac11a9.png)

![Screenshot_113](https://user-images.githubusercontent.com/132458076/235913986-8d22739f-26ea-45a7-9f95-343cde55fa41.png)

![Screenshot_114](https://user-images.githubusercontent.com/132458076/235913994-bcf8278e-8b69-402c-a0fc-6388e8489c69.png)
![Screenshot_115](https://user-images.githubusercontent.com/132458076/235914048-fadd8180-130d-4390-a1b0-6215488d3908.png)
![Screenshot_116](https://user-images.githubusercontent.com/132458076/235914078-7590aab4-58c0-4e70-a631-ff84dc5cf0b0.png)
![Screenshot_117](https://user-images.githubusercontent.com/132458076/235914098-5b086799-bdee-4e49-bcc5-7647d3e89edd.png)
![Screenshot_118](https://user-images.githubusercontent.com/132458076/235914116-dd6e825f-42fe-4c9b-8fcb-93482f28c013.png)

I can’t say anything special neither about good nor bad moments, because it is my first month as a candidate, but I feel I can bring more to Phala, and I am going to do it!

SUPPLEMENTARY TASKS
#CC  - 4: 4 articles and 2 videos
https://medium.com/@ribollavvv/edac5b505eff
https://medium.com/@ribollavvv/8bd418488bad
https://medium.com/@ribollavvv/47e57e971e25
https://medium.com/@ribollavvv/7963a5f70d8
https://youtu.be/WF_k5z-sHR4
https://youtu.be/btQ887l0vGU

#ART
https://twitter.com/ToriRibolla/status/1645479367940915200?s=20
https://twitter.com/ToriRibolla/status/1644686565648498689?s=20
https://twitter.com/ToriRibolla/status/1646861207884767233?s=20

SUGGESTED SCORES
#CC : 35
#MK : 25
#CC : 10
#ART : 10
Overall : 80

This was my first month as an official Phala Network candidate Ambassador.
Also, I had done some work as an advocate for ~2 months before April.
I am very happy to be part of the team of ambassadors and help promote the project. 
So, I am going to do a lot of creative stuff to promote Phala Network on Twitter, medium and on YouTube in the near future!

**Comment by willphala** [comment]
Solid work, especially for your first month. I look forward to seeing you and Inface collab on future videos too. 

Some feedback, which I hope helps:

- It could be great to see you being more active within our amb Discord channels. I want to see you building relationships with the rest of our team. We're a Phamily and support each other, so I'm sure the others would love to get to know you better.
- Check out our scoring system. You can't earn points for supplementary tasks that are linked to your chosen departments. E.g. CC and ART have major overlap, so you can't earn rewards for both. If you want to earn additional points avoid supplementary tasks that are linked to your departments. E.g. you're not in CM so HD would be a good supplementary task.

Let me know if you need any additional support 😃
