### ISSUE TITLE
APRIL 2023 Contributions - {The Scarlet Thread#2215}

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#165]
Amb Rank: Ambassador 
Telegram Username: @Scarlet_Thr
Discord Username: @TheScarletThread#2215
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

### CONTENT CREATION
• Created threads in twitter and made accompanying colourful graphics to increase the impact of the tweets. 
https://twitter.com/TheScarletThr/status/1648602251005501441?t=BoHjmyn3YFZi6tc0BvJ4kA&s=19
https://twitter.com/TheScarletThr/status/1651974736711233537?t=a7vhPjvHCsrbfkgMZtMqTw&s=19

• Created video  showing a walk through for PhalaWorld's new marketplace and explaining the basic features.
https://youtu.be/zdYIqReyeO0

•Quiz event
Hosted the quiz event for the Phala Africa community using the Quiz Bot we have on PhalaWorld discord. I prepared the content in the bot last month, so this month the quiz was executed by the Phala Africa Ambassadors. We collaborated on this event. It was a fun little activity and a nice way to help the community engage and learn. 

•AMA 
Phala Africa had the fourth community call. We collaborated on this event and also implemented Angie's suggestion of offering an incentive. Therefore we had a better turnout and many stayed till the end. We also had community members engage more and ask questions as compared to last month.

I did a presentation on the PhalaWorld marketplace.
Additionally, I played my role this month with the AMA by:
Helping with organisation of the call, maintained constant presence throughout the month when other Phala Africa ambassadors wanted assistance; tracked  progress with planning this call; created a banner artwork;  initiating discussions about aspects of the event. I created a follow-up document for us to contribute to about how we can  improve our community calls and make the presentations more enjoyable and informative to listen to.
![png_20230417_114154_0000](https://user-images.githubusercontent.com/99918790/236159133-fd652697-3369-4242-bd49-a41bc8a73e4a.png)
https://docs.google.com/document/d/1Sj5KRJjGAouY567o_BDncJMbcdSKy5Hh5K3RoFegIzg/edit?usp=drivesdk

• Added some questions to the document for Ambassadors interviews

• Assisted with article migration by doing first checks.

**GOOD POINTS**
Tried creating a video which was fun. It is a good method of delivering information. Also learnt a little more about how the Twitter algorithm works so hoping to use that to increase the reach of my tweets. For thr local community, new events were implemented which brought some fun into the community.

**BAD POINTS**
I posted episode 2 of my comic but while being fun, this wasn't an effective method of delivering information. 
For the quiz, we had a rather low turnout. We should look at hosting these kind of events on weekdays when people are more available and also find good ways to market the event. 

**HOW TO IMPROVE** 
Try more effective ways of delivering information. Take careful consideration of which audience I am trying to address to make content more impactful.

### COMMUNITY MANAGEMENT 
• Monitor PhalaWorld, Phala Africa Telegram and Phala Network server to remove spam and other malicious content.
![Screenshot_20230504-113936_Discord-01](https://user-images.githubusercontent.com/99918790/236168783-6e5d3b25-7a9d-4431-b1dd-fcc7f0632fbb.jpeg)
![Screenshot_20230504-113414_Discord-01](https://user-images.githubusercontent.com/99918790/236167824-273d579b-36d1-4fc8-9657-41982765ba97.jpeg)
![Screenshot_20230502-103653_Chrome-01](https://user-images.githubusercontent.com/99918790/236167836-c75da0ba-a781-45d8-b0ca-c84c105c5108.jpeg)

• Provide feedback to pre-advocates

• Welcome new people, answer questions from community and chat generation. Also shared helpful resources to the community members.

•Contributed to community digest by sharing questions from community. 

**GOOD POINTS**
This month we had a lot of scammers try to cause chaos in the servers. But the team and ambassadors reacted quickly. Although we cannot completely remove all attempts, by continuing to be as vigilant and proactive then we can minimize these scammers or  potential scam attempts. Also I answered some community concerns and received positive feedback. 

**BAD POINTS** 
Our local community is still quiet, although we still  share resources and updates. The engagement has improved a little this month as compared to last month.  The improvement seems to have come from our attempts to include more engaging events and communication methods. 

**HOW TO IMPROVE** 
Engage more with community in more meaningful ways. 

### SUPPLEMENTARY 
**PM**
![Screenshot_20230430-214134_Samsung Internet-01](https://user-images.githubusercontent.com/99918790/236161706-bcd169f8-f05d-4be9-895b-aab25ff045f8.jpeg)
![Screenshot_20230430-214153_Samsung Internet-01](https://user-images.githubusercontent.com/99918790/236162152-8d6552ee-9486-46f9-99a7-94ee52bafc9c.jpeg)
![Screenshot_20230430-214159_Samsung Internet-01](https://user-images.githubusercontent.com/99918790/236162186-061d76d2-e26c-42a6-997f-b601d23848c6.jpeg)

I managed to maintain the number of of tweets I did compared to last month (around the 70- 80 range). I also improved the quality of these tweets a little more. I engaged in the form of commenting, liking and retweeting content from: Phala Network ambassadors, Partners, Phala and PhalaWorld Official twitter. I promoted Phala Network and PhalaWorld on other servers. I will be working on improving my reach this month. Additionally, try to aim to maintain around 70-100 tweets about Phala Network in May.

**QC** 
Helped to clarify some information 
https://docs.google.com/document/d/1QP__bWnmEg7w0RwmhIFijTd-jc0WKKTOv2GQhAC3USA/edit?usp=drivesdk

SCORES
CC         36/40
CM        37/40
PM        10 /10
QC         2/10
TOTAL   85/100

**CLOSING COMMENTS**
I think I did less than last month but I have improved the quality of my work. I want to make a better improvement in quality and quantity so I will continue to work on this goal this month. 
Thank you !

**Comment by willphala** [comment]
Great work. Keep it up!
