### ISSUE TITLE
April 2023 Contributions { favour_cy#5138}

### ISSUE THREAD

**Issue by BBoss01** [Phala-Network/growth-program#166]
Amb Rank : Ambassador
Telegram username : @solomon_bb
Twitter Link  :https://twitter.com/official_bles1?t=OJWYQVRtPTlH8YIe23Ctlw&s=09
PHA Address : 41dNB3qCWz1m4b874815wYnthsbSUvmKUws6624wRrjX4tnL
Department : MK /50  CC /50

MK
• I promoted Phala on Twitter and Reddit in order to increase engagement and Awareness.
•  I ensured to create better contents in terms of quality( following the branding guildlines).
• I engaged In the MK channel.
• I also engaged in links shared by other members of the marketing department.

Stat
Reddit insight : https://drive.google.com/drive/folders/1fbQUxvHU-XiQnHhchwH6Cu8HCxIaCh2k

Phala Network Reddit: https://www.reddit.com/r/PhalaNetwork?utm_medium=android_app&utm_source=share

Reddit account : https://www.reddit.com/u/favour_cy?utm_medium=android_app&utm_source=share

Twitter stat: https://docs.google.com/spreadsheets/d/1jw-Rr95gozF6K0ibWub5JlJvKNgmTYsEIV-lyyy9i6M/edit?usp=drivesdk

![IMG_20230504_114011_653.jpg](https://user-images.githubusercontent.com/116058765/236183201-ef883944-fac2-46f4-bb0b-1a141869af87.jpg)![IMG_20230504_114008_575.jpg](https://user-images.githubusercontent.com/116058765/236183219-b0545047-398d-4182-8680-c78b72a9c21c.jpg)

Good point
More up votes on Reddit and increased insight.

Bad point
Reduced impression on Twitter ( although I created more posts than the previous month)

How to improve
I'll keep creating quality contents on Twitter and Reddit and I'll keep engaging in the marketing channel.

CC
• I participated in reviewing notion articles ( first round review) 
• I Participated in the African community call, 
Slide : https://docs.google.com/presentation/d/1lTwuYSyMJsnYWIbglJ_eoMUe3VVBvIwcFyzstBjX6Wc/edit?usp=drivesdk
• I recorded and transcribed the call, then Kamala uploaded it on medium and Twitter 
https://twitter.com/PhalaAfrica/status/1651896509238067201?s=20
Video link : https://drive.google.com/drive/folders/1dB6Bl3BibLsvXUyJNAfUwY_KExLo8zrZ
• Participated in hosting Phala African Quiz
• Worked closely with other African ambassadors by sharing ideas and creating awareness for events.
• Had More engagement in the CC channel than the previous month.
• All African ambassadors contributed to the incentives for Quiz and the community call winners.

Good point
• We had a More productive community call ( thanks to Angie's idea about the incentive program).
• We also successfully hosted the Quiz in PhalaWorld channel.
• Got permission to host Quiz in Phala African discord channel.
• More community members on telegram and More engagement.
• More engagement on discord.

Bad point
• It was hard getting the recorded video across to Angie.
• We had a low turn up for the Quiz ( we're going to plan a better strategy).

How to improve
I'll keep working closely with other ambassadors, engaging in content channel and improve my community call presentation.

SUPPLEMENTARY TASKS

HD
I had More engagement on Discord and little engagement on telegram sharing important information to keep the community updated and attended to some questions.
![Screenshot_20230504_115414~2.jpg](https://user-images.githubusercontent.com/116058765/236184592-8a300724-3774-42e3-bb02-a52db0cee52b.jpg)![Screenshot_20230504_115306~2.jpg](https://user-images.githubusercontent.com/116058765/236184623-ce05a3a7-bf4a-4218-94c7-bfe101164e9b.jpg)

TT
I wrote an article and also created a video guide on how to delegate and withdraw $PHA on Phala app.
 https://link.medium.com/8cYYxApowzb

ART
I created infographics, short videos , meme and banner

https://twitter.com/official_bles1/status/1647334896845701121?t=-UgSJCNhuCE2_gHp1E9M_g&s=19

https://twitter.com/official_bles1/status/1648361744631300103?t=ytLEETTnvYexfGxrF3Gh4w&s=19

https://twitter.com/official_bles1/status/1649012782908555264?t=s37LfqOl-SBEMiUkXkjykw&s=19

https://twitter.com/official_bles1/status/1649115198576263169?t=v75juU7lN8cjfLdwTlsk7w&s=19

https://twitter.com/official_bles1/status/1650908977524359182?t=3mdUnX-8btkvAR3eWS6PtQ&s=19

https://twitter.com/official_bles1/status/1653039517010411520?t=K_GhN3q5IJ4IfvIIh_aLaQ&s=19

https://www.reddit.com/r/PhalaNetwork/comments/12ng1vg/phat_contract_is_an_innovative_programming_model/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

![png_20230427_140047_0000.png](https://user-images.githubusercontent.com/116058765/236183728-b00a748e-94f2-41ab-9438-79bde2dce56e.png)

Suggested Scores
MK : 38/40
CC : 40/40
HD : 10
TT : 10
ART : 8
Total Suggested : 91

Closing Comment
It was great working with other ambassadors on various platforms. My performance had improved than the previous month, I was more active in departmental channels, I focused more on quality of contents and passing the right message across to the target audience.

**Comment by willphala** [comment]
Good work. Please re-review our score system doc though, as if you're in CC you can't earn points for TT and ART as there is major overlap and it all revolves around producing content. Please lmk if you need any help :)
