### ISSUE TITLE
April 2023 Contributions {nikkilikeonlynikki#0803}

### ISSUE THREAD

**Issue by NikkifromDotSama** [Phala-Network/growth-program#169]
Amb Rank: Candidate
Telegram Username: @jungesbluthatmut
Discord Username: nikkilikeonlynikki#0803
Twitter Username: @dabeibleibn
PHA Wallet Address: 466yGPYZJqCjzLXACYXEH59ZD1ayB5GbRTPeb57JmwWrsQt4

Contribution:
https://twitter.com/dabeibleibn/status/1643567400103686144?s=20
https://twitter.com/dabeibleibn/status/1645341484936318976?s=20
https://twitter.com/dabeibleibn/status/1646455172103544832?s=20
https://twitter.com/dabeibleibn/status/1646862461423722496?s=20
https://twitter.com/dabeibleibn/status/1647892237164871683?s=20
https://twitter.com/dabeibleibn/status/1648335585021394947?s=20
https://twitter.com/dabeibleibn/status/1649068664308604929?s=20
https://twitter.com/dabeibleibn/status/1650384763176321025?s=20
https://twitter.com/dabeibleibn/status/1651495411713036293?s=20
https://discord.com/channels/697726436211163147/1098219986692079727/1098554150347866152

Translations:
https://polkaverse.com/10988/verwendung-von-w-pha-oder-delegations-nft-fuer-38048
https://polkaverse.com/10988/steigern-sie-das-tempo-tester-die-closed-beta-von-phat-38197

<img width="980" alt="Знімок екрана 2023-05-04 о 20 26 25" src="https://user-images.githubusercontent.com/125280467/236282332-39787bac-8bc7-4677-a016-11b5bfb23154.png">
<img width="333" alt="Знімок екрана 2023-05-04 о 20 26 57" src="https://user-images.githubusercontent.com/125280467/236282354-7ebd86d9-768a-4eb8-b4a0-b35e93e0bdc6.png">
<img width="846" alt="Знімок екрана 2023-05-04 о 20 27 18" src="https://user-images.githubusercontent.com/125280467/236282363-50658987-a57c-459e-b639-a1fc4f0e244e.png">
<img width="892" alt="Знімок екрана 2023-05-04 о 20 27 34" src="https://user-images.githubusercontent.com/125280467/236282370-d62bb45a-e352-4502-a7ae-ce6b7af3a48c.png">
<img width="699" alt="Знімок екрана 2023-05-04 о 20 29 02" src="https://user-images.githubusercontent.com/125280467/236282673-1ac57559-cdab-417f-95bd-280022f9a942.png">
<img width="791" alt="Знімок екрана 2023-05-04 о 20 29 19" src="https://user-images.githubusercontent.com/125280467/236282703-09c6c659-0ba6-4b6f-8e40-0b55741e64f3.png">

SUGGESTED SCORES
#CC : 40/40
#MK: 40/40

Total:80 points

Because i'm the only one german ambassador in Phala, it takes too much time to create smth interesting and useful. Couple ambassadors could cooperate and create together easier and faster. The main goal for me,that I represent Phala also in another DotSama communitites, ofc it hard to track,but I represent Phala on solid level. This month was a bit crazy and hard for all of us,because of Discord hack, but I think it showed us what we can improve. I've tried in this month to create as much content as I can,help with questions in Discord and create good mood in different discord sections, hope to contribute even more in the following month.

**Comment by willphala** [comment]
Hey Pham. Please re-review the structure for reports, it's available on our Github page for the amb programme. I also appreciate that it's difficult to be solely leading the German local community by yourself, so please don't worry. I'm sure we will have some new guys to support you soon! 

It's awesome to hear you're representing Phala in different communities too. This is very important and great to hear, please attach some screenshots and links when possible in your next report too.

Good work!
