### ISSUE TITLE
July 2022 Contributions - {pigro85}

### ISSUE THREAD

**Issue by pigro85** [Phala-Network/growth-program#17]
Title: August 2022 Contribution
Telegram Username: @pigro85
Discord Username: @pigro85#6032
PHA Wallet Address: 44Rc9bxvmfyVJx1qmKThhUXUCuyhU6tqULvM5QKxtxks19uH

Contributions:
<img width="1272" alt="Schermata 2022-08-02 alle 23 09 36" src="https://user-images.githubusercontent.com/92217448/182474637-467a9ee3-8697-409e-bc1d-82b00563e21e.png">

VSM
Twitted Phala World lore video and reteewt of Phala World post on Phala Network Italy account.
[https://twitter.com/pigro85]
[Screenshot of your Twitter account stats https://analytics.twitter.com/]
<img width="1272" alt="Schermata 2022-08-02 alle 23 03 30" src="https://user-images.githubusercontent.com/92217448/182474674-435ab2e3-f382-4507-befd-5d41b0f22130.png">

PS. Back on duty on 15/07
<img width="628" alt="Schermata 2022-08-02 alle 23 17 16" src="https://user-images.githubusercontent.com/92217448/182475030-515a1ead-08e7-4121-b554-18afbf8a9258.png">

**Comment by lubi-hub** [comment]
Thanks for returning Pigro85. Since July is only 15 days active for the whole month, it is not high in terms of points. You can keep working hard next month and can get higher rewards through Supplementary Task.
