### ISSUE TITLE
April 2023 Contributions - {Janema#7205}

### ISSUE THREAD

**Issue by Janemake** [Phala-Network/growth-program#172]
Telegram Username: @Janemake
Discord Username: @janema#7205
Twitter Username: https://twitter.com/JanemakeCrypto
PHA Wallet Address: 41owbtwKf7dfZxEfdfhRfey4uGLkg8V9iLG74ZhTQnMnsAwA

**Departments** : #CP & #CM
**Department Score Weight** : 25% & 75%

**Contributions**
### **========================== 1. MANDATORY TASKS ==============================**
**1.1 CM** 

In April, I have been more present on both Discord & Telegram for the french community and global community.  

The main activities have been:
**- Use of Phala products:** help on the issues on staking activities, help understanding the Phala products
**- Protection of the Phamily:** Remove scam contents, alert on scam contents
**- Computing activities:** Help the Phamily members facing issues with their workers infrastrures / Help others to install their workers

**- Phat Contract:** In the French communities, we have a dedicated working group for the Phat Contract implementation & promotion, every Wednesday , with all the ambassadors we organise a call at 9 PM CET and the community members interested to learn the Phat Contract. A printscreen of the project on which we are working with the FR community.

I was available to help and guide community members, on both Discord & Telegram. Stats available below.
![tg_combot](https://user-images.githubusercontent.com/58589481/235789350-6cb2aab2-59e1-4864-8f94-7d64bd18a618.png)

**1.2 CP**
As a starting month in the CP department, this month was more dedicated to testing & assist the community when needed.

- Tested the new node image for the PRB installation
- Setting the test environment for my local test environments
- Assist the Phamily if needed on the issues related to staking related tools & app.

In addition to the CP activities, I have been more actively working on PHAT Contract implementation. It was a busy month as we had to deliver the project for 21/04 for the Closed Beta. The learning process of this kind of activities are invisible but really heavy at the beginning and it will be really helpful for the community in the future. 
The code of the Phat contract related to the phat2meet could be found [==> here](https://github.com/PhalaTeamFR/Phat2meet-ClosedBeta/tree/main/Phat2meet-Contract)

![phat](https://user-images.githubusercontent.com/58589481/236320139-50ba887c-c3a2-4eab-95c6-263ab7f98f28.png)

![image](https://user-images.githubusercontent.com/58589481/236330831-0f2da033-d7da-4e53-be93-f0a515909aba.png)

### ========================== 2. SUPPLEMENTARY TASKS ==========================

**2.1 DEV** 
With the other french ambassadors, we have submitted the project on which we were working since the launch of the closed Beta. The Phat Contract is one of our priority. As an ambassador with a dev background, I found necessary to be active on the coding part in order to better understand the requirement of the Phat Contrat. The full project could be found on github [here](https://github.com/PhalaTeamFR/Phat2meet-ClosedBeta)

![phat_contract](https://user-images.githubusercontent.com/58589481/236331421-3d9dbe31-9abe-4417-af03-8dc5fa92f707.png)

Compared to December, I have developed:

- Rust dev skills => required for Phat Contract development
- Ink! => required for Smart contract development
- Phat Contract dev skills

**2.2 PM**
- As the previous month, I took part actively in the different community events organized by Phala_FR (Community FR Monthly AMA, Weekly Closed Beta)

- I have shared most of the Phala related subjects on Twitter to Promote events and products related to Phala & PhalaWorld.
![twitter_recap](https://user-images.githubusercontent.com/58589481/235790554-b060280f-7b27-40c2-937d-211a246bc80e.png)

![Capture d’écran du 2023-05-04 23-05-56](https://user-images.githubusercontent.com/58589481/236331861-f466f3aa-927c-464e-a707-fb7338f0ce0e.png)

### **========================== 3. CONCLUSION ==============================**
This month was excellent from DEV perspective as we were able to submit a community project on Phat Contract (knowing most of us had limited skills in Rust at the beginning. It was an exemple of involving the community in the implementation of the Phat Contrat.  As an ambassador with DEV background, this was necessary to understand the Phat Contract and its different possibilities. This is key step for our community.

In addition to that, I was most present on both Telegram to assist the community on differents topics related to Phala and its products.

During this month, my contributions were mainly:
-  The promotion of Phat Contract,
-  Assistance of the communities with Phat Contract use cases
-  Supports of Phamily members on both french and global network
-  Participation & promotion of differents events organised by both Phala and the Phala_FR
-  Submit the FR community project phat2meet for the Closed Beta

I will continue the development of my Phat Contracts skills in order to be in a position to assist the dev interest by the Phat Contracts. 

### ========================== 4. SUGGESTED SCORES ==============================
#CM : 38/40 with 75% CM => 57/60
#CP : 29/40 with 25% CP => 15/20
with the split 75% CM /25% CP and the suggested score above, the MD tasks suggested score is 72/80

#DEV : 10
#PM : 10

Overall : 92

**Comment by willphala** [comment]
Fantastic work. It's awesome to hear how your contributions have been very Phat Contract focused!
