### ISSUE TITLE
APRIL 2023 Contributions - {tioneb#4951}

### ISSUE THREAD

**Issue by tionebDotsamapha** [Phala-Network/growth-program#173]
Title: April 2023 Contribution - {tioneb#4951}
Telegram Username: [tioneb](https://t.me/tioneb)
Discord Username: tioneb#4951
Twitter Username: [tioneb_DotSama₱ha](https://twitter.com/tioneb442)
PHA Wallet Address: 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7

Departments : #CM & #CP
Department Score Weight : 70% & 30%

I feel like all of the BC communities I participate in as an administrator are experiencing better attendance.
Some people are starting to realize that the bear has probably hit bottom.
If we are at the beginning of the next cycle, I think this is the right season to think about aggressive marketing for next year. I hope PhalaNework has enough resources for that.

### Telegram :
Telegram activity is better than privious months. Some new followers are actifs and are studying PhalaNetwork deeply. That permit interesting discutions.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/16654460/236317860-2f896389-4c95-4184-b96c-9cd8a03e629a.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/16654460/236318308-b61f9bd4-5bd4-4311-993b-403cc9363267.png">

### Discord :
The activity on discord is less important. We was turn to the closedBbeta that need a lot of time for individual work with less interactions. An idea wich permit a new activity to include more the community would be great.
Statistics below are wrong but members number is good.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/16654460/236320230-e963b2ae-081a-485d-a91e-62594807336f.png">

### Github :
This month we delivered our Phat2Meet project for the closedBeta. It is operational but not yet ready for public use. At the end of the closedBeta, the development team needs to take a break. We had a meeting last Wednesday to discuss the next steps.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/16654460/236320825-c69bb8fe-ddf1-48b9-a5fc-09f4544fe0f6.png">

### Youtube :
The youtube account continue to grow. all deserve if for the friend gator with his vidéos wich meet a good success.
<img width="698" alt="image" src="https://user-images.githubusercontent.com/16654460/236325137-99c5d075-46c1-4097-8408-53631b0e5024.png">

### Twitter :
+22 followers !!! i'm enjoy to this. And i think it's related about the comeback of the interest from speculators. that continue on May.
<img width="710" alt="image" src="https://user-images.githubusercontent.com/16654460/236325905-4eda76f3-6dc2-43e6-a676-4fc44e81393e.png">
<img width="709" alt="image" src="https://user-images.githubusercontent.com/16654460/236326121-5cd5c519-5aa3-4aa3-b567-b13e1f7035c4.png">

## Compute
Before the lunch of the prbV3Beta i played the cobaye with the intallation on my infrastructure.
This new version will open a lot of new possibilities. I would like to test it but i'm not sure to found sufficient time.... 
![image](https://user-images.githubusercontent.com/16654460/236468027-13d21b09-78c3-4b8a-b051-193b400dcfd3.png)

## EM
We organized 3 meeteings the wednesady night to organise our Phat2Meet project and 
a PhatAMA which received a better audience than previons month : https://www.youtube.com/watch?v=emzBCPXJndU
Topics was : 
- Road Map 2023
- PhalaWorld
- Phat Contract
- Présentation of the Phat to Meet
 <img width="271" alt="image" src="https://user-images.githubusercontent.com/16654460/236325311-32bf8ef3-9fb1-4b45-bd9c-0fcd804a5118.png">
 
CM : 60
CP : 25
EM : 10
Total : 95

I continue my learning to the phatDev.

**Comment by willphala** [comment]
I agree with your insights about marketing and the current market cycle. Looking forward to seeing Phat2Meet go public too!
