### ISSUE TITLE
April 2023 Contributions - GatorKorps | Phala#7997

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#176]
![logo phala fr](https://user-images.githubusercontent.com/82824139/236563739-bdd04c8f-fef9-46dd-9aa8-710d5e435958.png)

Amb Rank : Senior Ambassador
Telegram Username: https://t.me/Gatorkorps
Discord Username: GatorKorps | Phala#7997
Twitter Username: https://twitter.com/gk18_dog
PHA Wallet Address: 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV

Hello Will,
Before I start my report I wanted to thank Rom1 for his support in many image and concept works. 

After a very quiet month of March on my side I passed the second. I tried to produce a lot of various videos and especially to bet on twitter products of circumstance.
You will find different type of twitter product that continues the marketing aspect of develloper as major accounts a brand identity according to the events of the month (Easter for example). The objective being to take advantage of these days to communicate on Phala to make known the bases of our brand identity and to gather new people.
Of course this concept is to be combined with video products that detail the idea and the reason for our protocol.

I won't say more, but each product is thought through a marketing strategy, the month has been dense and I think I had a beautiful efficiency. Let's go to the report.

![image](https://user-images.githubusercontent.com/82824139/236564290-9cdbecfa-3f5a-4b26-a221-1eda94413946.png)

![image](https://user-images.githubusercontent.com/82824139/236564411-4fdab807-e1e4-4bb0-8be9-48d75f3c2c82.png)

![image](https://user-images.githubusercontent.com/82824139/236564484-02805abd-8d8b-4a69-9118-1d4a7cb59640.png)

As you can see the engagement figures are good compared to the last month. More presence, more activity and therefore more results.

Best tweets :
1 
The main concept of using an international day with a worked image to gather in addition to Phala a maximum of projects worked well, a lot of interaction and an image that remains in mind certainly pushing many to interact. (166 engagements)
https://twitter.com/gk18_dog/status/1650756975116820485
![image](https://user-images.githubusercontent.com/82824139/236566174-608b8a33-65c8-4c55-9ee0-3a09f969b65a.png)

2
In support of the PhalaFR account, announcement of our AMA (find the report in the youtube twitch part)
A nice image, hashtags and people quoted give a good result, simple and effective, perfect to attract people for our AMA.
https://twitter.com/gk18_dog/status/1650756975116820485
![image](https://user-images.githubusercontent.com/82824139/236566444-e69efa36-30cb-42f4-84e1-ac60519a9964.png)

3
The first concept test of the Wallpapers. An encouraging reception giving me the idea for the next months to realize wallpapers with calendar. Objective, as often throw light on our protocol, satisfy the fan boys, circulate exclusive content and spread our brand. Effective and perfect in the long run.
https://twitter.com/gk18_dog/status/1652595322713960451
![image](https://user-images.githubusercontent.com/82824139/236567118-ca4398e5-5e7f-445d-b9ee-b447c68a6ea3.png)

4
A 9-part thread with 9 exclusive illustrations generated by AI and modified by graphic software. This Thread highlights the capabilities of PhalaNetwork for gamification. I remain convinced that gamification remains a gateway to attract developers and users, nobody likes LAG, Phala can counter this flaw. This Thread summarizes the possibilities of our protocol, objective, to attract gamers, developers. Phala's cloud computing service is multi-tasking.
https://twitter.com/gk18_dog/status/1650544734203420672
![image](https://user-images.githubusercontent.com/82824139/236567447-a7ca6ea2-07f8-460b-84fb-6a3a5ba2b2e6.png)

5
Announcement of the summary video (30min) of the month of April with all the news and infos. The only French tweet of this top5 shows that despite everything my French target audience is still fond of content in its language, so I will continue. Sharing the summary with an attractive image can only generate more curiosity, interraction and therefore benefit to our brand.
https://twitter.com/gk18_dog/status/1645389394667347969
![image](https://user-images.githubusercontent.com/82824139/236568085-339757ee-d3ee-4c89-8199-bf8f4b60174f.png)

![image](https://user-images.githubusercontent.com/82824139/236569171-cb9d9d5e-6ff0-409a-8b5d-8cfeb48a7a66.png)
Participation in AMAs and LIVE on Discord see below:

I was present at most of the workshop dev to listen and learn, I do not have a big level but I am impressed by their investment.

Wednesday April 5: Phat Contract Workshop 
Wednesday April 12: Phat Contract Workshop
Wednesday April 19: Phat Contract Workshop

Tuesday, April 26: Monthly AMA Phala FR
https://www.youtube.com/watch?v=emzBCPXJndU
The organization of AMA requires a lot of time and precision. Indeed, there are about 35 minutes of sound adjustments and test (thanks Rom1), there are then 15 minutes of sound adjustments with the other ambassadors, there is also a whole structure calling for the use of 6 software to allow a professional rendering with an optimal audio quality.

I would like to add that I also do the animation of the show by presenting, giving the rhythm and framing it.  This AMA remains one of my greatest satisfaction because the result is very clean. Indeed in addition to occupy the crypto field on twitch this retransmission on youtube makes triple support. Discord, Twitch and youtube, a perfect way to occupy the networks, to make people participate and to spread.
![image](https://user-images.githubusercontent.com/82824139/236569643-76122b64-4da2-4083-a3f0-dc54dfd1bcd3.png)

![youtube](https://user-images.githubusercontent.com/82824139/236571353-6da54dfa-1c29-4ecd-9911-7a57cb267e94.jpg)

As for the other sections youtube is not left out. **4 videos including** one of 30 minutes. Many exclusive creations (at least 4 miniatures, one of them with the help of Rom1), diversity with general AMA, stacking Tuto, PhalaWorld and the marketplace.

https://www.youtube.com/watch?v=emzBCPXJndU AMA April 2023
https://www.youtube.com/watch?v=719QE23vfTo Stacking V2 tutorial
https://www.youtube.com/watch?v=pegV12WL39Q Presentation of PhalaWorld Marketplace
https://www.youtube.com/watch?v=pgZqIyRoN5A What s happen in march for Phala ?

Youtube doesn't lie, to gain visibility you have to create, the rhythm of 4 videos per month is difficult to keep but I can guarantee at least 3. 

The numbers are very good, little by little our account takes subscribers and gains popularity, even if it is never enough these numbers in period of "bear" are very positive.

It is important to understand that the creation of a video is much longer and requires much more skill than articles or other media. 

The current reward system underestimates this major media which should be massively encouraged.
![image](https://user-images.githubusercontent.com/82824139/236571559-b50a18f3-886c-4742-ab64-f53987059c5e.png)
![real](https://user-images.githubusercontent.com/82824139/236572575-27915f53-704f-4668-8888-d48c9d76266e.jpg)
Yes, even in real life we will promote Phala.

The awesome Swag we received has been used. What could be better than the cocktail party of the gathering of more than 60 polakdot Europe ambassadors to wear the Bob Phala and the sweater. A perfect ice breaker to kick-start the conversation on our protocol and reveal all its potential and interest to our fellow ambassadors. Without forgetting that our table won the best Cocktai. Ask Zoe she remembers we were active, motivated and unmissable. (I never would have thought of wearing a bucket hat during a cocktail party).

In addition to the comic aspect, this experience shows that the spirit of enterprise must be present at all times and that every moment is good for getting our ideas across. An ambassador must influence the other ambassadors, yes we are at phala (we can always do better but I'm not complaining).

We represented our protocol with dignity that evening and we talked about it with many people.

![ffff45](https://user-images.githubusercontent.com/82824139/236572562-7488e00d-cb21-458d-9e04-221cadc7636f.jpg)

![image](https://user-images.githubusercontent.com/82824139/236570691-2b7c3f74-a9df-4cb6-bfc9-898cf0c1996d.png)

It is always a pleasure to work with other ambassadors and particulary Rom1! 

I'm proud to have participated in the Phat2Meet project as a member of the Phala Network FR team during the Phala closed beta. This project has been an incredibly enriching experience for me, as I was able to contribute to the creation of something truly special.

We have a lot of plan, and if we have more time we would do more....

SUGGESTED SCORES
#CC: 40/40
#MK: 40/40
#ART: 10/10
#EM: 5/10

Overall : 95 

Quote : "Every business is a living document, an algorithm that needs to be improved"

Thanks to Rom1 to help me to structure all this report.

Thank you Will to read all of this

And thanks to my family and my beautiful daughter, I love you :)

**Comment by willphala** [comment]
Excellent report and great work!! Its awesome hear that the cocktail party was a success and that Phala had the best cocktail ;)
