### ISSUE TITLE
Title: April 2023 Contribution - {Angie_ada#0973}

### ISSUE THREAD

**Issue by Angie-ada** [Phala-Network/growth-program#177]
1. Personal info:

- Amb rank: Official Ambassador 
- Telegram Username: @angie_ada
- Twitter URL: https://twitter.com/_encrypted_____/
- PHA Wallet Address: 42qf1tXPH8HfxBqUpTv79VHiTghEatoBnM1QULFgRRXeiUiL
- Departments: CM/CC
 
2. Departments:
 
· CM:
- participated in Global Discord and Telegram moderation, interacting with members and sharing information.
- Provided detailed plan on African regional community’s Incentivized events.
- Hosted the monthly African community call (planning, organization, & the google meet requirements)
- Successful executed educational  Phala-Themed presentations along with fellow Phala Africa regional ambassadors during the call.
- Created a mini quiz during the call via google forms, and collected the results through a google sheet.
- https://docs.google.com/spreadsheets/d/1m9JklCvMeHWZmouAjjEri73obyuiV344XHEOhMmp9I/edit 
- Executed simple Quiz event on Phala world discord (spearheaded by Scarlet). Participated in the planning, marketing, and moderation of the event. And assisting in collecting information follow up info.
- The Phala Africa ambassadors sponsored the incentives for both events.
- Drafted a new user welcome message for Phala Africa discord which has been approved by fellow ambassadors. Would be implemented after further scrutiny from Will and bot permission is granted.
- Contributed to the community digest.
- With the recent increase in security threats to our community, myself along with Gatorkorps brought up the suggestion of a ‘scam group reporting campaign’ for telegram. It’s not so fast in giving results but based on experience it is efficient.
- Here’s a compilation of some of these fraudulent clone groups https://docs.google.com/spreadsheets/d/1-fmipXp8s9t5fPgBxX4Pb8e4vjetiYu0-1UebUOE774/edit
![IMG_2362](https://user-images.githubusercontent.com/87555884/236565166-3d2e2c9d-ecc2-4462-b63c-802962739b32.png)
![IMG_2361](https://user-images.githubusercontent.com/87555884/236565178-204a4b0e-ec98-4c90-aad7-65d73134dc2b.png)
![IMG_2360](https://user-images.githubusercontent.com/87555884/236565181-682877d2-0257-4858-8d01-60083cc4ad36.png)
![IMG_2363](https://user-images.githubusercontent.com/87555884/236565331-c67f7a2c-5386-420e-b04d-8aa9c1ed4d9c.png)

Good Points:
- In global channel, more awareness about what phala does is being achieved.
- In regional channels, the response from the events hosted was quite positive and we welcomed more members during the call and after the call, a number of them have remained active in the group.
- We observed more engagement in the Telegram regional community during this period.
Ps. The Head Ambassador for Polkadot  Africa regional community graced our meeting with his presence, which increased the excitement during the call and I believe that was also rewarding to the community and also says alot about Phala Africa’s networking reach.

 Bad Points:
- Unfortunately the discord quiz event wasn’t so great in terms of turnout (this may be due to the change in venue and probably not enough marketing)
- The African discord community hasn’t really picked up in terms of engagements yet.

How to improve your performance for next month:
- We (African ambassadors) have learnt a couple more tips to help boost participation in the community building events, like proper marketing, ensuring that the venue is confirmed and set to avoid last minute changes, and picking more suitable times to host community events.
- Also intend to be more involved with the PhalaWorld server moving forward.
 
· CC:
- Created and managing Phala Africa YouTube channel and would be posting video contents on Phala themed topics, tutorials, community call recordings, etc.
- Created banners for my phala-themed medium posts.
- Created detailed infographic promoting Phala’s on-chain governance and Phat Contract launch 
- Provided support to official posts and influential Phala posts (eg from core team) through likes/comments/retweets
- Created the banner for Phala Africa’s quiz event on discord.
- Wrote a couple quality  twitter threads on Phat Contract launch and other shorter promotional tweets and shilling centered around updates on Phala network.
- Participated in 1st stage paper review task on Notion
- Wrote a detailed article about Phala Network’s Phat Contract Main launch, highlighting some of its features like the off-chain computing.
- ![IMG_2376](https://user-images.githubusercontent.com/87555884/236578236-680889f1-57f6-474b-b5ba-51524d5858c2.png)
![IMG_2377](https://user-images.githubusercontent.com/87555884/236578261-99070828-206b-42c6-bc30-7456a1458b73.png)

https://medium.com/me/stats/post/4dd34bfa79ae
![IMG_2369](https://user-images.githubusercontent.com/87555884/236573653-94d541b7-4f1a-43c6-baeb-487bdcd71f87.png)
![IMG_2368](https://user-images.githubusercontent.com/87555884/236573685-3ee2ac8f-9661-4cb2-9f4f-16c5107fb170.png)

![IMG_2358](https://user-images.githubusercontent.com/87555884/236570738-95a6e593-46c5-4adc-9f40-58097dfde7ef.png)
![IMG_2359](https://user-images.githubusercontent.com/87555884/236570771-c7482d98-58c3-42e9-a3b9-ae7c01fe77ea.png) ![IMG_2396](https://user-images.githubusercontent.com/87555884/236616661-50bd3922-a2a9-4234-8806-1408fc79fd13.png)
![IMG_2395](https://user-images.githubusercontent.com/87555884/236616669-d8e0f42b-5557-4caf-936c-711a1d7b81ca.png)
![IMG_2394](https://user-images.githubusercontent.com/87555884/236616670-d592e569-b7c6-4064-8384-4a6493ecea34.png)

Good Points:
 I made an improvement on my content contributions for this month in terms of quality, quantity and reach.

Bad points
Still room for improvement in the quantity of video and written content.

How to improve your performance for next month:
- Plan to tryout new video creation tools  to keep the YouTube channel active and engaging 
- Also gonna be adding more graphic content to tweet schedule.
 
3. Supplementary tasks:
 
· TT:
- Wrote a tutorial on medium
- https://medium.com/@Angie_ada/phala-network-on-chain-governance-how-to-vote-on-proposals-666192f7019f
 
![IMG_2367](https://user-images.githubusercontent.com/87555884/236572989-d668370d-7fda-4c9b-9eb3-f25e50ccefc2.png)
![IMG_2366](https://user-images.githubusercontent.com/87555884/236573010-42c7414b-d13a-4f58-9cf0-b33ada77ac85.png)

- Wrote on voting on proposals in Phala Network.. 
- The aim of writing this tutorial is to further develop awareness and support about Phala Network’s On-chain governance system. Following the recent issue (which was swiftly resolved)with voting with staked PHA, this tutorial could help reassure old and new members alike, how easy it is to participate in decision making on Phala network.
 
 HD; 
Here’s at least 5 instances where I assisted the community by answering impactful questions and sharing helpful resources on both discord and Telegram.

![IMG_2375](https://user-images.githubusercontent.com/87555884/236576713-e12fd331- 012a-479b-9dee-4e39543ca305.png)
![IMG_2374](https://user-images.githubusercontent.com/87555884/236576730-994c9575-e3c8-4ff1-ab1e-0fbeac66204b.png)
![IMG_2370](https://user-images.githubusercontent.com/87555884/236576731-3ee0a6ca-6aa1-4d22-b268-f7a0f847364d.png)
![IMG_2371](https://user-images.githubusercontent.com/87555884/236576733-47f54b29-8868-4377-aee6-5cf6e5ccc35e.png)
![IMG_2373](https://user-images.githubusercontent.com/87555884/236576738-fa007935-2de3-4233-89dc-493382890731.png)
![IMG_2372](https://user-images.githubusercontent.com/87555884/236576743-10948d16-0924-468d-bb29-7d2139c5c62f.png)

4. Suggested scores: 
 
- CM 37/40
- CC 36/40
 
- TT 10/10
- HD 7/10
 
- Overall suggested score: 90/100.
 
- My performance for April has significantly increased due to my hands on participation in intuitive tasks and departmental contributions.
- I hope that my contributions for April were significant enough and also impactful, and also follows the grading guidelines.

**Comment by willphala** [comment]
Good work. Please note if you're in CM you cannot earn points for HD as there is an overlap between both tasks. Please re-review our scoring system and lmk if you have any questions :)
