### ISSUE TITLE
April 2023 Contributions - (johnrhodel#8162)

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#178]
Telegram Username: https://t.me/johnrmb
Discord Username: johnrhodel#8162
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

CC: 40/40

In content creation I made some videos of Phala that were given a strike by youtube, I warned Will about what happened.

I replied to them, but in the reach tags I left out the words "Crypto" and "token" due to YOUTUBE Brazil's policies regarding these names.

https://www.youtube.com/watch?v=CVXeA3wQFN0 - Recap Março (not striked)
https://www.youtube.com/watch?v=-makUaHp2Sc striked and reposted
https://www.youtube.com/watch?v=nqEDFM5usaY striked and reposted
https://www.youtube.com/watch?v=DzzOcsXAx44 striked and reposted

Also in the content creation part, I published important translations of the phala into the FILIPINO language, I will ask Will to create the channel in Filipino:

Filipino Translations:

https://polkaverse.com/11194/kontrata-ng-phat-hello-diyan-38240
https://polkaverse.com/11194/phala-2022-taon-sa-pagsusuri-38233
https://polkaverse.com/11194/pagpapakilala-ng-phat-contract-38234
https://polkaverse.com/11194/buwanang-newsletter-ng-phala-marso-2023-38235
https://polkaverse.com/11194/mga-gawain-sa-pag-compute-ng-tee-workers-panimula-38236
https://polkaverse.com/11194/roadmap-ng-phala-network-2023-38237
https://polkaverse.com/11194/ibahagi-pagsubaybay-sa-pagmamay-ari-ng-pool-38238
https://polkaverse.com/11194/kontrata-ng-phat-ano-ang-dadalhin-ng-bagong-produkto-ng-38239
https://polkaverse.com/11194/kontrata-ng-phat-hello-diyan-38240
https://polkaverse.com/11194/buwanang-newsletter-ng-phala-abril-2023-38246

I also translated 1 article into Portuguese and reviewed 3 of Gabriel's articles:

Translated:

https://medium.com/@phalaptbr/boletim-informativo-mensal-da-phala-mar%C3%A7o-de-2023-8c117d2fa5be

Revised:

https://medium.com/@phalaptbr/cloud-computing-com-a-phala-network-b4747145effe
https://medium.com/@phalaptbr/gerenciamento-de-nft-com-phat-contract-d63178f2382a
https://medium.com/@phalaptbr/funcionalidades-do-phat-contract-69fced43b480

I also set the goal of translating the PHALA wiki into Portuguese and Filipino, I divided the task into 3 months counting, April, May and June to end.

The first part in Portuguese is here:

https://docs.google.com/document/d/1LUGJHMyMwxgA8ayO6BIbkNq05ieaA0G9oqPjm7fHZH8/edit

The first part in Filipino is here:

https://docs.google.com/document/d/1NsukDrI2YltHuxhFfWIr2-X7BT2gETquEJGlLqLPFn8/edit

CC:Feedback

All of this was content creation, I think the wiki part is the most complicated, and also these youtube strikes got in my way, but I hope to increase the quality in May.

MK: 25/40
![april john](https://user-images.githubusercontent.com/77474076/236574942-c1ac857c-2e6f-4184-8357-d4b087e9d14a.JPG)

![april impressions](https://user-images.githubusercontent.com/77474076/236574929-2f83bc1d-1105-460b-ba19-86347e7113d9.JPG)

![phala twitter](https://user-images.githubusercontent.com/77474076/236575292-1d402788-33dc-4e6c-964d-03536ec5d3f0.JPG)

![phala twitter impressions](https://user-images.githubusercontent.com/77474076/236575314-95722cc2-21d6-40ee-8551-805f05e2a554.JPG)

Like RT Quoted
https://twitter.com/parachainboy/status/1648320446289395713
https://twitter.com/parachainboy/status/1651577466706702340
https://twitter.com/parachainboy/status/1649152745427857426
https://twitter.com/parachainboy/status/1648792451199410176
https://twitter.com/parachainboy/status/1651420694394052608
https://twitter.com/parachainboy/status/1651397890529533952
https://twitter.com/parachainboy/status/1651277840107577344
https://twitter.com/phalaportugues/status/1636933258645495808
https://twitter.com/phalaportugues/status/1650486521407963136
https://twitter.com/phalaportugues/status/1648376977026433027
https://twitter.com/phalaportugues/status/1647701338141212672
https://twitter.com/phalaportugues/status/1642685541723389957
https://twitter.com/Rubywangh/status/1649271705658073089
https://twitter.com/marvin_tong/status/1645329291562082304
https://twitter.com/PhalaNetwork/status/1649310726669103104
https://twitter.com/PhalaNetwork/status/1651574787049938944
https://twitter.com/zoemcfox/status/1651600584137654273
https://twitter.com/PhalaNetwork/status/1651656735344435224
https://twitter.com/aj_asterio/status/1651668294917660675
https://twitter.com/joinwebzero/status/1651681371251699754
https://twitter.com/PhalaNetwork/status/1652547136758730753
https://twitter.com/PhalaNetwork/status/1652094934025904128
https://twitter.com/PhalaNetwork/status/1650654493657137158
https://twitter.com/marvin_tong/status/1650759183447494659
https://twitter.com/hashwarlock/status/1651030053336096769
https://twitter.com/PhalaNetwork/status/1651253189054742529
https://twitter.com/aj_asterio/status/1651380640233791490
https://twitter.com/PhalaNetwork/status/1643453798197731328?s=20
https://twitter.com/PhalaNetwork/status/1643080025665667072?s=20
https://twitter.com/PhalaNetwork/status/1642961385121259522?s=20
https://twitter.com/PhalaNetwork/status/1642802623311904768?s=20
https://twitter.com/PhalaNetwork/status/1642705316167970819?s=20
https://twitter.com/PhalaNetwork/status/1645124118394576896?s=20
https://twitter.com/PhalaNetwork/status/1645124130784567297?s=20
https://twitter.com/PhalaNetwork/status/1645124131795419136?s=20
https://twitter.com/PhalaNetwork/status/1644749337988157447?s=20
https://twitter.com/PhalaNetwork/status/1644527581100752896?s=20
https://twitter.com/PhalaNetwork/status/1644177429748150272?s=20
https://twitter.com/PhalaNetwork/status/1645917071103131648?s=20
https://twitter.com/bgmshana/status/1645822165747646464?s=20
https://twitter.com/PhalaNetwork/status/1645489828467810329?s=20
https://twitter.com/PhalaNetwork/status/1645457323228315648?s=20
https://twitter.com/PhalaNetwork/status/1645370516403007488?s=20
https://twitter.com/PhalaNetwork/status/1649079583667306496?s=20
https://twitter.com/PhalaNetwork/status/1648968093866270720?s=20
https://twitter.com/PhalaNetwork/status/1648863831995686915?s=20
https://twitter.com/PhalaNetwork/status/1648863833560162307?s=20
https://twitter.com/PhalaNetwork/status/1648726133662183425?s=20
https://twitter.com/PhalaNetwork/status/1650654493657137158?s=20
https://twitter.com/PhalaNetwork/status/1650215955807477767?s=20
https://twitter.com/PhalaNetwork/status/1650215966675017732?s=20
https://twitter.com/PhalaNetwork/status/1650215968256282624?s=20
https://twitter.com/PhalaNetwork/status/1651253189054742529?s=20

Marketing: This month I made some retweets and translations of some of our official posts to generate engagement with our ecosystem with Portuguese speakers. I think I can improve next time and do more in May.

Supplementary tasks:

10/10 - Art
As planned, I always do the arts from the previous month to be posted in the next month, I have 4 arts to be posted in sequence on our twitter and groups in Portuguese, creating the Filipino group I can do the arts too.
![Visão](https://user-images.githubusercontent.com/77474076/236575344-1bd93e95-e6cd-4808-ba6c-824ac78c8bd6.png)
![4 fun facts](https://user-images.githubusercontent.com/77474076/236575357-d2c7f304-ec71-4f80-8ba0-1cf9da745237.png)
![dados definir id](https://user-images.githubusercontent.com/77474076/236575367-c96540a9-7269-4f73-8479-fbf480b8f294.png)
![Governança](https://user-images.githubusercontent.com/77474076/236575405-5042c1f7-441e-4589-baf5-7c2fd65edc25.png)

Recruiter?/10( I don't know how scoring works ):
I invited some ecosystem insiders to be ambassadors, I will post here all the prints of the submissions and invitations.
![Adrian invite](https://user-images.githubusercontent.com/77474076/236574380-fef5d1c7-e82e-401e-bd21-577adbd200e4.JPG)
![gomski invite](https://user-images.githubusercontent.com/77474076/236574426-efb00fc6-d838-489a-baa7-fc16df0c750e.JPG)
![giorge invite](https://user-images.githubusercontent.com/77474076/236574447-13c113c2-8ce6-4ae9-96db-53cba3d4d11f.JPG)
![carlos invite](https://user-images.githubusercontent.com/77474076/236574464-775be6d4-d321-49fd-bae8-7865215f3e61.JPG)
![Leo invite](https://user-images.githubusercontent.com/77474076/236574472-f613acf4-126b-429c-85c6-e372833cbc7d.JPG)
![agashi aruna invite](https://user-images.githubusercontent.com/77474076/236574491-835db27a-1803-49ce-ace3-4146fb13cf4c.JPG)
![kelvin invite](https://user-images.githubusercontent.com/77474076/236574500-a055d4e0-1920-4119-84bb-d2dce705ce4c.JPG)
![green invite](https://user-images.githubusercontent.com/77474076/236574511-abb5f6c8-5240-436a-b10f-f46d31671a3e.JPG)
![polkadot filipinos invite](https://user-images.githubusercontent.com/77474076/236574530-5c04e982-4fcf-4bd2-8f5d-c0716abc6e09.JPG)

Others extra 10/10:

I continue to help Notion with tasks to revise articles to post on our website:

![task website](https://user-images.githubusercontent.com/77474076/236573178-a2d69235-9749-42b9-9731-007854f2131b.JPG)

I hope you got at least 85 points

40 CC
25 MK
20 sup

if count

10 Extra task

**Comment by willphala** [comment]
Good work!
