### ISSUE TITLE
July 2022 contributions

### ISSUE THREAD

**Issue by darknight7** [Phala-Network/growth-program#18]
Telegram: randomusernameidontneed
Discord: DKSM#0396
PHA Address: 427s7coF6yveYnXPNvCc1BtKgkHABxwgZpcwbFXbpJE9X1iP

**CM**
Have I participated in Discord Channel Moderation (choose)? No, only telegram, I keep minimal presence on discord (not taking bridges into account)

_Phala Italian Channel_ link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a
Comments:
- How many people increased or decreased? Why?
No significant variation
- What was good?
- What was bad?
Still no questions about mining despite my guide, apparently no new miners are coming from Italy.
Minimal questions about staking (I made a comprehensive guide months ago, it may explain the lack of questions)
- How can I improve this next month?
I may write a guide for PhalaWorld once the full process is clear but channel activity depends on "hype" and Phala is a marathon not a sprint, interest will come slowly at this point until some juicy news hit.

_Phala Mining Channel_ link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a
Comments: the gemini wave has gone by now, a few people still join and ask questions on a weekly basis. Some very active members are doing a great job at answering them, I keep contributing as time allows as I always did since I joined.

**VSM**
_Twitter as Official Ambassador_ : https://twitter.com/twdksm
https://analytics.twitter.com/user/twdksm/tweets
My presence on twitter is minimal but I do follow my senior ambassador's guide and like/retweet to increase visibility.

**CC**
Quality translations of articles on Medium: [1](https://medium.com/phala-italia/le-ricompense-per-il-crowdloan-phala-sono-state-distribuite-ritirate-i-vostri-pha-ffd62231bb12) [2](https://medium.com/phala-italia/la-partecipazione-di-phala-a-polkadot-decoded-2022-%C3%A8-stata-molto-soddisfacente-la-nuova-versione-174ce996be43) [3](https://medium.com/phala-italia/distribuite-le-ricompense-per-il-crowdloan-la-pagina-della-storia-di-phalaworld-sar%C3%A0-presto-553f7f45b168)

**Comment by lubi-hub** [comment]
For the question "Have I participated in Discord Channel Moderation (choose)? No, only telegram, I keep minimal presence on discord (not taking bridges into account)"

My answer is 'We should maintain both discord and telegram, not all channels have bridge connections. Both telegram and discord are important community platforms for phala, and both need to respond to various community issues in a timely manner.'
