### ISSUE TITLE
May 2023 contributions report {tori#2692}

### ISSUE THREAD

**Issue by toriribolla** [Phala-Network/growth-program#180]
PERSONAL INFO
Amb Rank : Candidate Ambassador
Telegram: @ToriRibolla
Twitter: @ToriRibolla
PHA Address : 435b1mp9FuSY4X6NNMTN6mALfyeChiQU1htPViw7hnD26sEM

Departments: #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

Contributions:
MK & CC -  I promoted Phala on Twitter and on YouTube,As well as writing and translated some articles on the Medium.

CC:

Tweets about Phala Network:
https://twitter.com/ToriRibolla/status/1655495533073661953?s=20
https://twitter.com/ToriRibolla/status/1659478359435513857?s=20
https://twitter.com/ToriRibolla/status/1659960279990665216?s=20
https://twitter.com/ToriRibolla/status/1660254249668816908?s=20
https://twitter.com/ToriRibolla/status/1660616565203558402?s=20
https://twitter.com/ToriRibolla/status/1660979107822202880?s=20
https://twitter.com/ToriRibolla/status/1661341960341274624?s=20
https://twitter.com/ToriRibolla/status/1661777886230216704?s=20
https://twitter.com/ToriRibolla/status/1662066437999960064?s=20
https://twitter.com/ToriRibolla/status/1662428732844384256?s=20
https://twitter.com/ToriRibolla/status/1663158711442092034?s=20
https://twitter.com/ToriRibolla/status/1663211785959399424?s=20
https://twitter.com/ToriRibolla/status/1663212423778807808?s=20
https://twitter.com/ToriRibolla/status/1663455298894569472?s=20
https://twitter.com/ToriRibolla/status/1663483361971818496?s=20

Retweets about Phala Network:
https://twitter.com/PhalaNetwork/status/1660439954865131521?s=20
https://twitter.com/PhalaNetwork/status/1661759709400154113?s=20
https://twitter.com/polkaworld_org/status/1662369923811905537?s=20
https://twitter.com/PhalaNetwork/status/1662848405302026243?s=20
https://twitter.com/PhalaNetwork/status/1663643099044651008?s=20

MK:

Twitter analytics shows incorrect values in the first screenshot, I tried to figure it out, but I didn't find a solution to the problem, so I counted the values that I can count such as the number of tweets and views.
![Screenshot_153](https://github.com/Phala-Network/growth-program/assets/132458076/1ddc20f7-34fd-4802-9335-b5b04ff92013)
![Screenshot_154](https://github.com/Phala-Network/growth-program/assets/132458076/9597e460-5eb7-488d-b17e-1a6806231f37)
![Screenshot_155](https://github.com/Phala-Network/growth-program/assets/132458076/e8643328-2930-4963-9ae1-49f95b08f1dd)

These values are for the last week
![Screenshot_152](https://github.com/Phala-Network/growth-program/assets/132458076/43af65e9-19c7-49cc-8874-d5db3ae7f49a)

The values that I recalculated manually
Tweets: 83
Impressions: 15663

YouTube analytics
![Screenshot_158](https://github.com/Phala-Network/growth-program/assets/132458076/3e04be64-0794-4ef2-9028-f09b1454f7f2)
![Screenshot_160](https://github.com/Phala-Network/growth-program/assets/132458076/fadbee41-16f2-473d-957f-8a44fce2bccb)
![Screenshot_159](https://github.com/Phala-Network/growth-program/assets/132458076/d5802190-5602-409d-879f-eaf74bbe8600)

Supplementary tasks:

I remember that I cannot perform supplementary tasks from my departments, but I do not know where I should add these works, so I will show them here.

CC:
YouTube videos:
Everything what you need to know about Phala Network:
https://youtu.be/NyG44E9Iy4o

Collab with InfaceAi about Phala Network and how to stake PHA:
https://youtu.be/MCEXCyLEVEk

In this collaboration, we teamed up with Inface in order to tell and show what Phala is and how to stake PHA, Inface wrote the text for the video and recorded his part about staking, I recorded my theoretical part, edited the video, made the cover and wrote the subtitles manually.

Article:
What is TEE and how does Phala Network uses this technology? - 1440 words:
https://medium.com/@ribollavvv/c980c6f9141a

Translation:
What is TEE and how does Phala Network uses this technology? RU - 1185 words:
https://medium.com/@ribollavvv/5049fa827746

ART:
![Screenshot_161](https://github.com/Phala-Network/growth-program/assets/132458076/e00ded26-0701-4fd1-acf3-83d79f1817ab)
![Screenshot_162](https://github.com/Phala-Network/growth-program/assets/132458076/e14fb9ef-1dfc-4d7b-99ab-71c9c616bcb6)
![Screenshot_163](https://github.com/Phala-Network/growth-program/assets/132458076/36adee65-b5c8-48cc-a786-f90ad247c639)
![Screenshot_164](https://github.com/Phala-Network/growth-program/assets/132458076/39d61298-f531-43ae-bb95-726561553c74)
![Screenshot_165](https://github.com/Phala-Network/growth-program/assets/132458076/a8dc5b54-9497-462c-82bb-769a7ccbaf70)
![Screenshot_166](https://github.com/Phala-Network/growth-program/assets/132458076/4a64f957-1945-4e57-92d1-0307eb4d7fa5)

HD:
I tried to help a few people with their questions about Phala Network

![photo_2023-06-01_15-35-29](https://github.com/Phala-Network/growth-program/assets/132458076/401ad204-5fea-4a39-8300-732dec4883b7)
![photo_2023-06-01_15-35-24](https://github.com/Phala-Network/growth-program/assets/132458076/4587ba61-2c37-4d42-92fc-f6ebc4875f36)

SUGGESTED SCORES
#CC : 35
#MK : 25
#CC : 10
#ART : 10
#HD : 4
Overall : 84

*I counted the supplementary tasks that are included in my department, because I saw that other ambassadors do this, let me know if It do not need to be counted at all, I will take this into for the next time.

This month I focused on quality, all my Twitter posts were with a unique picture made by me. I also improved the video editing. I also really liked the collaboration experience and we will make another video with Inface later, when it becomes possible to stake PHA on the Phala network. In addition, I tried to be more active in the chat. And finally I was able to join the ambassador's call, because before that I was on flights, I really liked the call and left a very pleasant impression, and it was very useful, I made myself some notes from this call to improve my content. The only thing I didn't really like this month was that Twitter analytics showed the wrong values, but I wrote to support and I hope this problem will be fixed.

Thank You. Tori.

**Comment by willphala** [comment]
Good work. Thanks for the detailed report! I can see that you have already made big improvements from last month which is fantastic! I was especially happy to see you collaborating with Inface via videos. 

In regards to supplementary tasks, they're only included in your final score if they're separate from your selected departments. For example, if you belong to CM you can't do HD as they're essentially the same task. But if you're in CM you can do PM. You belong to CC so you can't earn points for doing ART etc. 

Moving forward I would like to see you engaging more with other team members publicly in the amb Discord channels. We need to create a team vibe and I want the rest of the Pham to hear your great thoughts/suggestions too. Emoji reactions at a minimum would be a good start too. 

Doing both will enable you to get 80+ points.
