### ISSUE TITLE
MAY 2023 Contribution - Kamala Immaculate

### ISSUE THREAD

**Issue by KAMALAIMMACULATE** [Phala-Network/growth-program#183]
1. Personal info:
Amb Rank: Ambassador
Telegram Username: @kamalaimmaculate
Twitter URL:https://twitter.com/Immei256
PHA Wallet Address: 46KQkYs3uxsS8zxVGKK9BpdcaVt2vUaspA2Rn45mkmCehEjr
Departments: CM/CC

2.Departments:
**CM**
I participated in the local telegram group for Phala Africa posting updates about Phala Network and welcoming new members.
Participated in the preparation for our Monthly event with different ideas how we can have a successful one

I contributed on inviting our friends from Astar Africa that is Chris and Brian who are Official Ambassadors for Astar Network to have a collaboration event with them and the event was hosted successfully as planned.

Arranged and prepared enough information about this collaboration Event by providing necessary requirements from the main speakers and also created a min group that helped us to discuss how our event will be held.

I was the host of our monthly community call for May, I organized all the presentations for all the speakers together, including the the quiz presentation.
Did a presentation about the Phala Builders program during our event.

For the month of May, I tried to improve on my participation in the local Telegram group compared to the previous months
![an1](https://github.com/Phala-Network/growth-program/assets/61009431/3f2110e7-e70b-4001-887a-de45826e96e0)

**Link to the Monthy community Call**
https://twitter.com/PhalaAfrica/status/1659207968011980803?s=20
https://twitter.com/PhalaAfrica/status/1662052808701476871?s=20

**Good Points:**
Creating more awareness about Phala Network and Phalaworld is being achieved
Managed to collaborate with other local communities and having other member join us
There is an improvement with our community calls 
Improved participation from the community members during the event e.g asking questions
I also improved on my personal participation the telegram group

**Bad Points**
Our monthly community call attendance is still small
Need to engage on the discord channels 
The telegram group is still not too active 

**How to improve your performance for next month:**
Create enough time to arrange and advertise our next community call
We African Ambassadors will plan for other activities that will make the community members active
Collaborating with other local communities to improve on the number of attendees and engagement

 **CC**
Managing the twitter account for Phala Africa, created some content, posting updates about Phala Network and also designing some inforhraphics
Created detailed infographic promoting Phala Network and Phat Contract launch
Supported the Official Phala posts by Liking and retweeting
I wrote some twitter threads on Phat Contract launch and other promotional tweets about Phala Network Events and twitter spaces.

**Twitter Activity Analytics**
My account couldn't show all the tweets and decided to export the data to CSV
![an2](https://github.com/Phala-Network/growth-program/assets/61009431/e826da02-c607-4ba1-91e6-61888497bd04)
![snip (85)](https://github.com/Phala-Network/growth-program/assets/61009431/6b1cc6b3-8950-4387-bc41-94d27e6ad998)
![snip (86)](https://github.com/Phala-Network/growth-program/assets/61009431/13c76992-e64b-437e-be88-b2b0628deeeb)
![snip (87)](https://github.com/Phala-Network/growth-program/assets/61009431/31edb1c3-481c-4439-98ec-ef7a440e452f)

**Twitter Links**
https://twitter.com/Immei256/status/1664887395026698240?s=20
https://twitter.com/Immei256/status/1664270684070227977?s=20
https://twitter.com/Immei256/status/1663922652627566596?s=20
https://twitter.com/Immei256/status/1663061626419806209?s=20
https://twitter.com/Immei256/status/1662785533720895489?s=20
https://twitter.com/Immei256/status/1662065049727270912?s=20
https://twitter.com/Immei256/status/1661715418652766209?s=20
https://twitter.com/Immei256/status/1661045737486942209?s=20
https://twitter.com/Immei256/status/1660547831873019906?s=20
https://twitter.com/Immei256/status/1660337660315983873?s=20
https://twitter.com/Immei256/status/1659986429684924416?s=20
https://twitter.com/Immei256/status/1659591299241000961?s=20
https://twitter.com/Immei256/status/1659209472630460416?s=20
https://twitter.com/Immei256/status/1658418339973062659?s=20
https://twitter.com/Immei256/status/1656277034463555586?s=20
https://twitter.com/Immei256/status/1655991531843485697?s=20
https://twitter.com/Immei256/status/1655974470320898048?s=20
https://twitter.com/Immei256/status/1654477354335363077?s=20

**Tweet Activity Analytics Phala Africa Account**
![ana3](https://github.com/Phala-Network/growth-program/assets/61009431/0ea3aa08-ee61-48e5-a7c1-54bd2efd4e84)
![snip (88)](https://github.com/Phala-Network/growth-program/assets/61009431/02fa0a1c-b5cc-4f03-9599-3fe901f46a75)

**Good Points:**
I made an improvement on my content contributions for this month in terms of quality, quantity and reach.

**Bad points**
The quality of my content and quantity

**How to improve your performance for next month:**
Increase on the number of tweets in this month of June
Try to use colors on the inforhraphics 

SCORE
MK 37/40
CC 38/40
PM 8/10
TOTAL 83/100

My performance for the month of MAY increased compared to the last month of April 
I have to improve on my engagement in the discord channels in the month of June
Increase on the number of tweets in this month of June

Thank you
Kamala Immaculate

**Comment by willphala** [comment]
Good work Kamala. 

In regards to supplementary tasks, they're only included in your final score if they're separate from your selected departments. For example, if you belong to CM you can't do HD as they're essentially the same task. But if you're in CM you can do PM. You belong to MK so you can't earn points for doing PM.

Moving forward I would like to see you engaging more with other team members publicly in the amb Discord channels. We need to create building a team vibe. I want you to start conversations and not just react to them too. 

I need to see both of the above to give you 80+ points. However as you played a key role in facilitating the event with Chris.
