### ISSUE TITLE
May 2023 Contributions {favour_cy#5138}

### ISSUE THREAD

**Issue by BBoss01** [Phala-Network/growth-program#184]
Amb Rank : Ambassador 
Telegram username : @solomon_fav
Discord : favour_cy#5138
Twitter Link : https://twitter.com/official_bles1?t=KxG2C9hboz6Tm2dZ5nyL7A&s=09
PHA address : 41dNB3qCWz1m4b874815wYnthsbSUvmKUws6624wRrjX4tnL
Department : MK & CC

MK
• I promoted Phala on Twitter and Reddit in order to create brand awareness.

• Engaged in the marketing channel.

• Engaged in Links posted by other members of the department and also engaged on other ambassadors posts on Twitter.

• Engaged in global Phala tweets and local community posts on Twitter.

Reddit Insight : https://drive.google.com/drive/folders/1-Uk2u3CXo8-KgBikxjJEiQ1cptFi73uV

Phala Reddit : https://www.reddit.com/r/PhalaNetwork?utm_medium=android_app&utm_source=share

Reddit account  : https://www.reddit.com/u/favour_cy?utm_medium=android_app&utm_source=share

Twitter Link - https://twitter.com/official_bles1?t=M9WJRnQWGhRUEoAHu_iL8g&s=09

https://twitter.com/search?q=from%3A%40official_bles1%20Phala%20Network&t=tB90Viyk2Mlm7IhLfUahrA&s=09

https://twitter.com/search?q=from%3A%40official_bles1%20Phat%20Contract&t=zAAZgWZnnx-RYpqFmqPHDg&s=09

https://twitter.com/search?q=from%3A%40official_bles1%20SubBridge&t=XrDzIXkA208DnyM7yrzQXg&s=09

Total tweets - 58
Total impression - 9,523
![20230604_084924_0000~2.png](https://github.com/Phala-Network/growth-program/assets/116058765/c7f7e550-40e5-42d4-a1f8-81f51737c46d)![20230604_085048_0000~2.png](https://github.com/Phala-Network/growth-program/assets/116058765/34c6e99b-8263-478d-a84d-b1307bb3b28b)

Good points
• Increased engagement on Reddit and Twitter
• Increased impression than the previous month on Twitter 
• increased insight on Reddit 

Bad point
• Twitter stat was not accurate so I had to do it manually.

How to improve
• I'll keep creating awareness on Twitter and Reddit so as to increase usage and community growth.

CC
• I engaged in Phala African channel, sharing ideas and creating awareness for the community call.

• Participated in the community call
Slide Link - https://docs.google.com/presentation/d/1_HatT4GI5HkcmRHHlfvW4rUUDLbcP-wRVetCmBpIwdc/edit?usp=drivesdk
Call recording - https://drive.google.com/file/d/1dhdBeBkp-Zyoem9KD1xJkqRqFW7MiJ-M/view?usp=drivesdk ( recorded by Scarlet)

• Created a Recap for the community call  (uploaded by Kamala)
Medium - https://medium.com/@phalaafricacommunity/phala-african-and-astar-african-community-call-recap-3f5bf5e6cf64
Twitter - https://twitter.com/phalaafrica/status/1663517634980085762?s=46&t=z5sTWVG_vXFxXhwoy3_gig

• Created a banner for the Recap
![png_20230529_115658_0000.png](https://github.com/Phala-Network/growth-program/assets/116058765/50358b5c-c2ea-47f0-a077-b5382c59567b)

• Engaged in the Content channel.

• Created a guide on how to create Phala account on polkadot extension
Medium Link - https://link.medium.com/qZ5NZpmTlAb

• Created  and shared quality infographics about Phala and Phat Contract 
Links - https://twitter.com/official_bles1/status/1663572051213287425?t=LIHUBm4_MwLYIlx33dclcA&s=19
https://twitter.com/official_bles1/status/1662857814392426499?t=DuCLMJkpjWad8hiloav-MQ&s=19
https://twitter.com/official_bles1/status/1661064743036108886?t=97D-WP2Szsb6k3ldAN4aCA&s=19
https://twitter.com/official_bles1/status/1660600647199145985?t=feovdi-sm9QXr24M0_ZZJQ&s=19
https://twitter.com/official_bles1/status/1658920364422975490?t=fLTtwRZuUCwr-zxyPWBkNA&s=19
https://twitter.com/official_bles1/status/1658508769347739648?t=RjPgy9KB2Ep0GVc4cWSJMg&s=19
https://twitter.com/official_bles1/status/1657062502184648714?t=uzaausUkmyrcCkJi-UEezA&s=19
https://twitter.com/official_bles1/status/1656930342693924865?t=7p9EMxhaRZru_nbVs6X_Pg&s=19
https://twitter.com/official_bles1/status/1656299653757902848?t=J0d2nrb8OESdZRk0Ys8TVg&s=19
https://twitter.com/official_bles1/status/1656231421000704001?t=C-OkwIeaMACx69QrafrV5Q&s=19
https://twitter.com/official_bles1/status/1656221443342970884?t=0OmIKRk16cxl_fb1yUk3zA&s=19
https://twitter.com/official_bles1/status/1654817940552708098?t=u6okxp46FAfW0o2uNOZCHA&s=19

• I added some community questions to the community digest docs ( Phat Contract questions for May)
Link - https://docs.google.com/document/d/14B3F4YEnmmm5d7Wc6JEusohRt0XgflbaEbk6tqXA1Os/edit

• All ambassadors contributed to the Incentives for the community call winners.

Good point
• We had a successful community call
• I was able to improve my community call presentation

Bad point
• Low turn up for the community call

How to improve
• I'll keep working closely with other ambassadors and I'll keep working on quality of contents.

SUPPLEMENTARY TASKS

HD

I engaged in Phala African Discord and telegram community, sharing important Updates and attended to some questions.

![Screenshot_20230604_101909.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/4b9d5d24-1d75-44d5-9baa-62b0cecd166f)![Screenshot_20230604_101950.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/6f3f63d3-f87f-4e83-b5fa-1e3a319f16e8)

Suggested Score
MK : 40/40
CC : 40/40
HD : 10
Total  : 90

Closing Comment

It was great working closely with other ambassadors on various platforms and department. My performance had improved than the previous month. I improved the quality of My contents while following the branding guidelines, I improved my presentation and community engagement, and I try to improve how I submit my report.

**Comment by willphala** [comment]
Good work. Moving forward I would like to see you engaging more with other team members publicly in the amb Discord channels. We need to create building a team vibe. I want you to start conversations and not just react to them too.
