### ISSUE TITLE
MAY 2023 Contribution - Gabriel_VDS#7586

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#185]
Telegram : @gabekoin
Discord : Gabriel_VDS#7586
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of May:
Candidate

**CONTENT (CC):**

Articles created:
Latência Zero com Phat Contract:
https://medium.com/@phalaptbr/lat%C3%AAncia-zero-com-phat-contract-a538a5ea774c

Off-Chain Computation com o Phat Contract:
https://medium.com/@phalaptbr/off-chain-computation-com-o-phat-contract-c34d20b761e5

Preservação de privacidade com Phat Contract:
https://medium.com/@phalaptbr/preserva%C3%A7%C3%A3o-de-privacidade-com-phat-contract-b573edc76bf5

Threads created:
Latência Zero com Phat Contract:
https://twitter.com/phalaportugues/status/1654537245796323328

Off-Chain Computation com o Phat Contract:
https://twitter.com/phalaportugues/status/1658810789531115529

Preservação de privacidade com Phat Contract:
https://twitter.com/phalaportugues/status/1661388319425540098

I created 3 authoral articles and 3 threads that have been posted in Twitter and all Portuguese channels (Telegram and Discord)

• Participated in the community call

Good Point
We increased the number of portuguese people reading our content and learning about Phala

Bad Point
Not many interactions in the community call 

How to improve
Create more methods to the community participate (polls, fun facts, calls)

**COMMUNITY (CM):**
Main

![phala grafico 1](https://github.com/Phala-Network/growth-program/assets/112413448/f326c1c9-914b-4fda-a851-6553de232e9c)
![phala grafico 2](https://github.com/Phala-Network/growth-program/assets/112413448/bb9a87ad-5e35-4784-862a-191dfa0fbc95)
![phala messages oficial](https://github.com/Phala-Network/growth-program/assets/112413448/afda48e2-f90f-4142-bcc9-0caf28357ae9)

--------------------------------------------------------------------------------------------------------------------------------------------------
Portuguese

![phala grafico 1 PT](https://github.com/Phala-Network/growth-program/assets/112413448/6fa3ad2e-dfc8-4ee5-83a8-aed52e7afc33)
![phala grafico 2 PT](https://github.com/Phala-Network/growth-program/assets/112413448/1a417723-5dcb-4d62-8e2a-3e825080619f)
![phala messages pt](https://github.com/Phala-Network/growth-program/assets/112413448/c8bbe029-1a1c-436c-8d86-d8b73eddacd9)

SUPPORT Messages

![Phala 1](https://github.com/Phala-Network/growth-program/assets/112413448/a94fe093-5628-470b-aa1f-b826db8e6ae4)
![Phala 2](https://github.com/Phala-Network/growth-program/assets/112413448/475d4ecb-cded-4633-885b-e80da591ff8f)
![Phala 3](https://github.com/Phala-Network/growth-program/assets/112413448/f1bbcf81-7d04-436c-84da-4a559a9d78c4)
![Phala 4](https://github.com/Phala-Network/growth-program/assets/112413448/07333ac7-a5e3-4c98-830d-36a9387b5ef4)
![Phala 5](https://github.com/Phala-Network/growth-program/assets/112413448/524fd789-e46d-4f35-85c7-ada775b08fe7)
![Phala 6](https://github.com/Phala-Network/growth-program/assets/112413448/7528586c-0e39-49ad-9768-863f49f060fc)
![Phala 7](https://github.com/Phala-Network/growth-program/assets/112413448/40771128-e183-4067-b58d-c456425ba280)
![Phala 8](https://github.com/Phala-Network/growth-program/assets/112413448/19e64a0d-d2fe-4ed4-a14a-2fb989267d43)
![Phala 9](https://github.com/Phala-Network/growth-program/assets/112413448/0b8e9fd8-9543-4b1a-8088-73f208c4bff6)
![Phala 10](https://github.com/Phala-Network/growth-program/assets/112413448/36649be9-4906-4b94-a14c-37c94f0e9057)
![Phala 11](https://github.com/Phala-Network/growth-program/assets/112413448/52589710-fa3d-4565-991a-1ee695135118)
![Phala 12](https://github.com/Phala-Network/growth-program/assets/112413448/123e4d9a-4408-44da-8576-1db90f685d55)
![Phala 13](https://github.com/Phala-Network/growth-program/assets/112413448/b0838878-9da6-4ddc-9b2c-ab2afcad54ae)
![Phala 14](https://github.com/Phala-Network/growth-program/assets/112413448/d042ebea-a8a0-4bcd-8591-aed69537a4e6)
![Phala 15](https://github.com/Phala-Network/growth-program/assets/112413448/87ee5868-0a83-4ba5-96dd-e8f6019849da)
![Phala 16](https://github.com/Phala-Network/growth-program/assets/112413448/ac2a10b8-7ece-4b14-98c5-e7fa38ade927)

Good Point
This month was simply amazing, we had many people interacting in the portuguese group and loving the project

Bad Point
Many bots joint both groups this month and everyone was upset with it

How to improve
Try a different bot blocking method

**Contributions: ART & MK**

ART:
Infographics Created:

https://twitter.com/phalaportugues/status/1656006269935788041

https://twitter.com/phalaportugues/status/1660261789982945283

https://twitter.com/phalaportugues/status/1662932802038267905

![Phala Funcionalidades 8](https://github.com/Phala-Network/growth-program/assets/112413448/9f9ee247-f070-447a-9c40-40b8b11aca2e)
![Phala Funcionalidades 6](https://github.com/Phala-Network/growth-program/assets/112413448/254c924f-83e6-4fca-9d0d-e984e419ab85)
![Phala Funcionalidades 7](https://github.com/Phala-Network/growth-program/assets/112413448/baa76099-09b3-4172-a8e5-847269f3575f)

MARKETING (MK):
Tweets (RT & LIKE)
https://twitter.com/PhalaNetwork/status/1632728319354609664?s=20
https://twitter.com/PhalaNetwork/status/1655278173154689026?s=20
https://twitter.com/PhalaNetwork/status/1655278356793884673?s=20
https://twitter.com/PhalaNetwork/status/1654526793163087872?s=20
https://twitter.com/PhalaNetwork/status/1658486434591019015?s=20
https://twitter.com/PhalaNetwork/status/1658210202964094976?s=20
https://twitter.com/PhalaNetwork/status/1657892163672510465?s=20
https://twitter.com/PhalaNetwork/status/1657892183788388352?s=20
https://twitter.com/PhalaNetwork/status/1657892186950881280?s=20
https://twitter.com/PhalaNetwork/status/1656945119248134144?s=20
https://twitter.com/PhalaNetwork/status/1660133567652065281?s=20
https://twitter.com/PhalaNetwork/status/1660104147864293376?s=20
https://twitter.com/PhalaNetwork/status/1660439954865131521?s=20
https://twitter.com/PhalaNetwork/status/1660439970384080896?s=20
https://twitter.com/PhalaNetwork/status/1659670943084744704?s=20
https://twitter.com/PhalaNetwork/status/1658820360433963011?s=20
https://twitter.com/PhalaNetwork/status/1658849784520638465?s=20
https://twitter.com/PhalaNetwork/status/1661759709400154113?s=20
https://twitter.com/PhalaNetwork/status/1661759729193095170?s=20
https://twitter.com/PhalaNetwork/status/1662848405302026243?s=20
https://twitter.com/PhalaNetwork/status/1662849490817282055?s=20
https://twitter.com/PhalaNetwork/status/1662849951020486658?s=20
https://twitter.com/gabekoin/status/1663518929568899073?s=20
https://twitter.com/PhalaNetwork/status/1663506867228901377?s=20

SUGGESTED SCORES
#CC : 30/40
#CM: 32/40
#ART 10/10
#MK 10/10

Total: 82

Notes:
This month we had a good engagement in the portuguese group with a lot of new members and people believing in Phala.

The plans for June is bring more people to the Phamily through our content and the so expected Phat Contract

**Comment by willphala** [comment]
Good work! Moving forward I would like to see you engaging more with other team members publicly in the amb Discord channels. We need to create building a team vibe. I want you to start conversations and not just react to them too. Keep it up!

**Comment by gabekvds** [comment]
Copy that bro!

Will be working on it right now

Cheers
