### ISSUE TITLE
July 2022 Contributions - {rafaccc#5473}

### ISSUE THREAD

**Issue by rafaccc** [Phala-Network/growth-program#19]
Telegram : [rafaccc](https://t.me/rafaccc)
Discord : rafaccc#5473
Dirección PHA: 42LYD29z2f6hYQeuamH5puXTGa1KHhWd6YxYSHXzRjih4xJd

Phala Spanish Channel link: https://t.me/phalaspanish
Have I participated in Discord Channel Moderation (choose)? Yes, actively every day
Combot Link : https://combot.org/c/-1001463390461/a?start=2022-07-01&end=2022-07-31

![image](https://user-images.githubusercontent.com/97988345/182612591-26d0e86d-8c9f-4ad1-9d70-a271220b9d7f.png)
![image](https://user-images.githubusercontent.com/97988345/182477101-b129ed92-28ed-4ed7-9046-98674db96adb.png)

Comments :
How many people increased or decreased, why?
17 people increased
What was good?
Many people interested in the PhalaWorld metaverse and mining.
What was bad?
Crypto market down, and that makes users less active.
How can I improve this next month?
Participating in text AMAs in other channels of other projects, and this way many join our channel to learn more about the project.

Comments :
Last month's impressions went from 7.3k to 16.9k.
all types of statistics with respect to the month of June have been multiplied minimally
Create Tutorial
Create Thread
Translated Medium article
Create Meme
I have retweeted in Spanish the tweets sent by the official Twitter accounts of Phala Network and Phala World.

![image](https://user-images.githubusercontent.com/97988345/182476665-14264b0c-d6fb-4860-b54b-bd7d6dffb01e.png)
![image](https://user-images.githubusercontent.com/97988345/182477979-8b52c208-c087-4ff0-bf2f-43a8126c52a2.png)

My supplementary(advanced) contributions for July:

CC(Content Creation):
Article translation:
1- https://medium.com/@rafacabilla/conozca-la-comunidad-francesa-de-phala-en-el-parisdotcomm-la-historia-de-phalaworld-y-su-p%C3%A1gina-b67564c811
2- https://medium.com/@rafacabilla/se-distribuyeron-las-recompensas-de-phala-crowdloan-reclame-sus-pha-ahora-33a4b1548fbe

EM:  AMA text
Participation in an AMA text on Integritee's Spanish channel.
https://twitter.com/Integriteesp/status/1552327697241554944

TT:
https://medium.com/@rafacabilla/tutorial-como-enviar-el-token-phala-desde-nova-a-kucoin-por-la-red-khala-608fe3e1ca60?postPublishedType=initial

**Comment by lubi-hub** [comment]
Well done! Your point is over 90%. Thank you so much for your excellent social media presence in July, and please continue to post quality content and attend high-level events.
