### ISSUE TITLE
May 2023 contributions - {pigro85#6032}

### ISSUE THREAD

**Issue by pigro85** [Phala-Network/growth-program#192]
Telegram: Pigro85
Discord: pigro85#6032
Twitter: https://twitter.com/pigro85
PHA Wallet Address: 44Rc9bxvmfyVJx1qmKThhUXUCuyhU6tqULvM5QKxtxks19uH

[CM]
Phala Italian Channel link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a

<img width="1187" alt="Screenshot 2023-06-05 alle 23 14 43" src="https://github.com/Phala-Network/growth-program/assets/92217448/48a688cf-0acd-4aba-a9e3-045c3b733d78">

Phala Mining Channel link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a

<img width="1061" alt="Screenshot 2023-06-05 alle 23 16 02" src="https://github.com/Phala-Network/growth-program/assets/92217448/2720c992-e538-4cb3-a5c8-9fd75e9f1094">

Phala Network Official link: https://t.me/phalanetwork
Combot Link: https://combot.org/c/1421178003/a

![immagine](https://github.com/Phala-Network/growth-program/assets/92217448/221e0210-b7af-4ebd-8b4f-3b5ed73667a1)

Have I participated in Discord Channel Moderation? Not so active on discord this month.
Have I participated in Telegram Channel Moderation? Yes
Standard chat operations and a still continuing banning huge amount of spammers/bot.

[CC]
Stil in difficult to findout how to produce original and valuable content. Trying to figureout how to afford HW to start testing new "HW combination".

[MK]
Standard activity on Twitter. Something wrong with the analitycs.

<img width="920" alt="Screenshot 2023-06-05 alle 23 23 03" src="https://github.com/Phala-Network/growth-program/assets/92217448/2dc27d3f-abfe-41e3-ad79-e49d44af5d3c">

<img width="920" alt="Screenshot 2023-06-05 alle 23 23 50" src="https://github.com/Phala-Network/growth-program/assets/92217448/806eef7a-5cc1-4ba4-990b-47bcf03a0c3f">

<img width="920" alt="Screenshot 2023-06-05 alle 23 24 11" src="https://github.com/Phala-Network/growth-program/assets/92217448/b81f87b4-9e09-4e0b-b171-f40a142d6104">

SUGGESTED SCORES

CM: 35
CC : 0
MK : 10

**Comment by willphala** [comment]
"Stil in difficult to findout how to produce original and valuable content." - Thanks is a very helpful insight.
