### ISSUE TITLE
May 2023 Contributions - (johnrhodel#8162)

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#197]
Telegram Username: https://t.me/johnrmb
Discord Username: johnrhodel#8162
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

CC:30/40

Translated Article portuguese:
https://medium.com/@phalaptbr/boletim-mensal-phala-abril-de-2023-506465d52779

Translated article to filipino:

https://polkaverse.com/11194/pagpapakilala-ng-phat-contract-38234
https://polkaverse.com/11194/buwanang-newsletter-ng-phala-abril-2023-38246
https://polkaverse.com/11194/ibahagi-pagsubaybay-sa-pagmamay-ari-ng-pool-38238
https://polkaverse.com/11194/kontrata-ng-phat-ano-ang-dadalhin-ng-bagong-produkto-ng-38239
https://polkaverse.com/11194/kontrata-ng-phat-hello-diyan-38240

Twitter create a post about ID portuguese

https://twitter.com/phalaportugues/status/1662529710587248647

Twitter create a post about 4 fun facts in portuguese
https://twitter.com/phalaportugues/status/1663539234278350850

Twitter create a post about Phala vision
https://twitter.com/parachainboy/status/1658112219438088194

Talk about Polkadot and Phala in DYDX portuguese Youtube

https://www.youtube.com/watch?v=M0Rln9Hd5vM&t=43s

Talk about Polkadot and Phala in spaces "verbo da sabedoria"

https://twitter.com/i/spaces/1OwxWwdmYnjxQ?s=20

MK:(30/40)

Manage Phala twt account

We increase after spaces and youtube more than 100 followers from 37 followers to 137

![phala pt br](https://github.com/Phala-Network/growth-program/assets/77474076/ab751094-a0c1-40fa-aaf0-2672a5ef422f)

![phala](https://github.com/Phala-Network/growth-program/assets/77474076/4b23d464-3904-4f40-a480-147593dc66df)

Post, Like and RT:
https://twitter.com/parachainboy/status/1652886711922196480
https://twitter.com/parachainboy/status/1653914366662541315
https://twitter.com/parachainboy/status/1657041590760636421
https://twitter.com/parachainboy/status/1658112219438088194
https://twitter.com/phalaportugues/status/1663539234278350850
https://twitter.com/phalaportugues/status/1662528780898803719
https://twitter.com/PhalaNetwork/status/1632728319354609664?s=20
https://twitter.com/PhalaNetwork/status/1655278173154689026?s=20
https://twitter.com/PhalaNetwork/status/1655278356793884673?s=20
https://twitter.com/PhalaNetwork/status/1654526793163087872?s=20
https://twitter.com/PhalaNetwork/status/1658486434591019015?s=20
https://twitter.com/PhalaNetwork/status/1658210202964094976?s=20
https://twitter.com/PhalaNetwork/status/1657892163672510465?s=20
https://twitter.com/PhalaNetwork/status/1657892183788388352?s=20
https://twitter.com/PhalaNetwork/status/1657892186950881280?s=20
https://twitter.com/PhalaNetwork/status/1656945119248134144?s=20
https://twitter.com/PhalaNetwork/status/1660133567652065281?s=20
https://twitter.com/PhalaNetwork/status/1660104147864293376?s=20
https://twitter.com/PhalaNetwork/status/1660439954865131521?s=20
https://twitter.com/PhalaNetwork/status/1660439970384080896?s=20
https://twitter.com/PhalaNetwork/status/1659670943084744704?s=20
https://twitter.com/PhalaNetwork/status/1658820360433963011?s=20
https://twitter.com/PhalaNetwork/status/1658849784520638465?s=20
https://twitter.com/PhalaNetwork/status/1661759709400154113?s=20
https://twitter.com/PhalaNetwork/status/1661759729193095170?s=20
https://twitter.com/PhalaNetwork/status/1662848405302026243?s=20
https://twitter.com/PhalaNetwork/status/1662849490817282055?s=20
https://twitter.com/PhalaNetwork/status/1662849951020486658?s=20
https://twitter.com/PhalaNetwork/status/1663506867228901377?s=20
https://twitter.com/phalaportugues/status/1662528536068997123?s=20
https://twitter.com/phalaportugues/status/1662529710587248647

QC(10/10):

Reviewed article and threads structure for Gabe:

https://medium.com/@phalaptbr/por-dentro-da-governan%C3%A7a-da-phala-741f51a5944e
https://medium.com/@phalaptbr/preserva%C3%A7%C3%A3o-de-privacidade-com-phat-contract-b573edc76bf5
https://medium.com/@phalaptbr/off-chain-computation-com-o-phat-contract-c34d20b761e5
https://medium.com/@phalaptbr/por-dentro-da-governan%C3%A7a-da-phala-741f51a5944e

Threads:
Latência Zero com Phat Contract:
https://twitter.com/phalaportugues/status/1654537245796323328

Off-Chain Computation com o Phat Contract:
https://twitter.com/phalaportugues/status/1658810789531115529

Preservação de privacidade com Phat Contract:
https://twitter.com/phalaportugues/status/1661388319425540098

second review of articles waiting ok to post in website
![second review of articles waiting ok done](https://github.com/Phala-Network/growth-program/assets/77474076/1fe6313c-f245-49dc-975f-47b75e8a6f81)

ART(10/10)

As planned, I always do the arts from the previous month to be posted in the next month June, I have 4 arts to be posted in sequence on our twitter and groups in Portuguese

![1](https://github.com/Phala-Network/growth-program/assets/77474076/7b434e1d-74a6-456d-8088-5e918cbd8fe6)
![2](https://github.com/Phala-Network/growth-program/assets/77474076/49c5b17b-7c44-4bab-9614-68f97db80a38)
![3](https://github.com/Phala-Network/growth-program/assets/77474076/1c53b629-f0f6-477c-b53a-ab8b26f1198a)
![4](https://github.com/Phala-Network/growth-program/assets/77474076/94fc4486-94bf-4368-ab9d-79c89b9e1d32)

**Comment by willphala** [comment]
Great work. I'm especially happy with you recruiting Leo!
