### ISSUE TITLE
July 2022 Contributions - {tioneb#4951}

### ISSUE THREAD

**Issue by TionebErtahcnom** [Phala-Network/growth-program#20]
Discord : tioneb#4951
Telegram : @tioneb
PHA Address : 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7

My Mandatory (Basic) Contributions of July:
Senior-ambassador

twitter Account : https://twitter.com/tioneb442
Have I participated in Discord Channel Moderation (choose)? Yes
Have I participated in Telegram Channel Moderation (choose)? Yes

Combot Link PhalaFR : https://combot.org/c/-1001424849386/a
![image](https://user-images.githubusercontent.com/16654460/183030769-1c510001-f5b0-474f-aad9-32c979541861.png)

Comments :

How many people increased or decreased? Why?
- many bots have invaded the TG in the last months but some real people arrived on the channel following our AMA at Binance. 
What was good?
- The price of pha being considered low, I see many more people announcing that they want to buy PHA and / or buy equipments to mine 
What was bad?
- The bear market calm that we are fighting is now doubled by the summer vacations.
How can I improve this next month?
I am contacted by several people who want to start mining without having any knowledge of linux and docker. I think that helping them will require a lot of my time.

VSM(Twitter Virals)
Twitter as Official Ambassador : https://twitter.com/tioneb442

Comments :
As co-organizer of the ParisDOTcomm the number of followers for my twitter account has increased by 20%.
As my twitter account being almost totally focused on Phala-Network & Phala-World, this represents a significant number of people who do not know Phala-Network yet. 

![image](https://user-images.githubusercontent.com/16654460/183032723-460041a9-c15e-4acb-b8ff-985c9b45ab24.png)

VSM(YT Virals)
![image](https://user-images.githubusercontent.com/16654460/183047018-ec9f0f06-983e-472c-b8e9-161037668d3d.png)

#My Supplementary(Advanced) Contributions of July:#

## AMA ##
Our monthly AMA for the month of July was organized on the French Binance community discord.
This allowed us to get out of our Phala-Network community and introduce ourselves to an audience that doesn't know the project. 
There is no video of this AMA but an audio recording: 
https://drive.google.com/file/d/1kfND4XeHZGbPk9ff6IqSgjzKsPddUBeI/view

On the 5 Phala-World WhiteLists we had obtained for the fr, we kept 2 to offer the shellNFT whose mint fee will be paid by @Blackstone and myself.
At this AMA we offered our first shellNFT.

Thanks to @blackstone for the organization of this AMA!

## ParisDOTcomm ##
As a co-organizer of the [ParisDOTcomm](https://parisdotcomm.org/), I participated in the organization of the Phala-Network event with @zoé and @ruby. I also took care of the proposal made to the council and proceeded to the payment of the sponsor contribution of Phala to the organization of the event.
https://khala.subsquare.io/treasury/proposal/24

## Networking ##
Transmitted by PM to @Rhee.

**Comment by lubi-hub** [comment]
Well done Toined! Your point is over 90% even without TT. Thank you so much for your excellent social media presence in July.
