### ISSUE TITLE
JUNE 2023 Contribution - GabeKoin

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#205]
Telegram : @gabekoin
Discord : Gabriel_VDS#7586
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of June:
Candidate

CONTENT (CC): 40/40

Slides for Phala Event
https://docs.google.com/presentation/d/1bVoPmj9Jj3K4hAUAYk4TSQ3HQJuhWjQL27prdHKvTZo/edit?pli=1#slide=id.g1e3d9b35c7d_0_48

Articles created:
Por dentro da Governança da Phala:
https://medium.com/@phalaptbr/por-dentro-da-governan%C3%A7a-da-phala-741f51a5944e

Compatibilidade do Phat Contract:
https://medium.com/@phalaptbr/compatibilidade-do-phat-contract-aeb82ca745fc

Insight sobre Web3 Oracles e integração com a Phala Network:
https://medium.com/@phalaptbr/1164ccc0d878

Translated articles:
Phat Contract: Contratos Inteligentes. Agora mais inteligente. (With John)
https://medium.com/@phalaptbr/phat-contract-contratos-inteligentes-agora-mais-inteligente-c80c16adc67e

LensAPI Oracle: potencialize seu aplicativo Web3 Social (With John)
https://medium.com/@phalaptbr/lensapi-oracle-potencialize-seu-aplicativo-social-web3-bd1a0026b29

Advancing Off-chain Computation for Web3 Social: Phala Network and Lens Protocol Join Forces: (With John)
https://medium.com/@phalanetwork/advancing-off-chain-computation-for-web3-social-phala-network-and-lens-protocol-join-forces-5998edcc52bd

Translated threads:
https://twitter.com/phalaportugues/status/1670845809099784206

https://twitter.com/phalaportugues/status/1671158582430277638

Threads created:
Por dentro da Governança da Phala:
https://twitter.com/phalaportugues/status/1665350545727422465

Phat Contract:
https://twitter.com/phalaportugues/status/1668260753931993092

Insight sobre Web3 Oracles e integração com a Phala Network:
https://twitter.com/phalaportugues/status/1673464789815762946?s=20

Compatibilidade do Phat Contract:
https://twitter.com/phalaportugues/status/1669336538931662848

Statistics:
![image](https://github.com/Phala-Network/growth-program/assets/112413448/d075db2e-2e21-4d47-97f9-07b55d88a191)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/035265ad-a8f0-4c42-940a-4cd1c42b11e7)

Feedback: No bad points this month. Was really happy about the content, I've made many articles and threads that the whole community loved. Also we had a great reach and impressions.
For next month, keep the good work and spread more about our PhatContract.

CM: 33/40

Phala Global
![image](https://github.com/Phala-Network/growth-program/assets/112413448/0e235cf9-2e38-42b0-ac5f-ffa8cd70d965)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/24c2dfea-f489-409c-9532-7a04a10e69d6)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/6d2ba20c-c9f9-430c-8616-0e2ed524efc7)

Phala Brazil
![image](https://github.com/Phala-Network/growth-program/assets/112413448/e5a29e2a-497e-43b2-9dd5-ded649d8261d)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/4288e457-aa81-4e72-bd6b-fa990fa615f6)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/fa853412-0f84-450e-847e-23a36dc4a19a)

Questions / Support:

![Phala 1](https://github.com/Phala-Network/growth-program/assets/112413448/ac58fb45-3cb4-4824-bacd-4657b47bfa5f)
![Phala 2](https://github.com/Phala-Network/growth-program/assets/112413448/08529370-8387-4e52-9d4e-9acbb9ba4a7e)
![Phala 3](https://github.com/Phala-Network/growth-program/assets/112413448/e22ae88c-8756-4c0f-8341-6c47209de1f7)
![Phala 4](https://github.com/Phala-Network/growth-program/assets/112413448/f05a529a-5053-4f95-83b7-f5623b3c34e4)
![Phala 5](https://github.com/Phala-Network/growth-program/assets/112413448/bf5448cd-2a80-43cf-8861-063fab9be2de)
![Phala 6](https://github.com/Phala-Network/growth-program/assets/112413448/e3ff9f18-f115-41cb-9de2-d158b7ad41d1)
![Phala 7](https://github.com/Phala-Network/growth-program/assets/112413448/3f44c141-ad8d-441c-9c5b-eecc5a2b7cde)
![Phala 8](https://github.com/Phala-Network/growth-program/assets/112413448/01cab5f5-8b8c-46fe-9de3-d0e03a111e93)
![Phala 9](https://github.com/Phala-Network/growth-program/assets/112413448/8f76635d-3ad3-4051-afd3-4ca9d9a1dbd9)
![Phala 10](https://github.com/Phala-Network/growth-program/assets/112413448/9294726a-9efe-40a3-883d-71271007b0d2)
![Phala 11](https://github.com/Phala-Network/growth-program/assets/112413448/25548f93-824d-41af-a634-e0aade11715b)
![Phala 12](https://github.com/Phala-Network/growth-program/assets/112413448/6531137f-6ba3-42cf-8293-7e3f5aaeec15)
![Phala 13](https://github.com/Phala-Network/growth-program/assets/112413448/27990bf6-987e-421a-84ed-56a95af0a016)
![Phala 14](https://github.com/Phala-Network/growth-program/assets/112413448/c7f08b09-0445-46e4-8b0b-3889967fe7ea)
![Phala 15](https://github.com/Phala-Network/growth-program/assets/112413448/c7ed7d23-7567-4677-bc10-82b6894b28bb)

This month I've started to be more active in the Discord and I simply loved it. I felt that we are getting more engagement and this is amazing. 
The telegram global was normal, somedays with a lot of ppl and others quiet.

For next month, keep working on the Brazilian Community engagement.

SUPLEMENTARY 20/20

EM 10/10:

We had an amazing event that we could spread about Phala to our local community:

![evento 2](https://github.com/Phala-Network/growth-program/assets/112413448/ced7bd2f-e61a-483b-a68d-b778795303d7)
![evento 1](https://github.com/Phala-Network/growth-program/assets/112413448/a0f4442c-e2fb-4028-9cc7-87b0c4b8e566)
![evento 3](https://github.com/Phala-Network/growth-program/assets/112413448/d8f0c7f5-2f78-4e84-8f4d-b2854e3278e7)
![photo1688231177 (1)](https://github.com/Phala-Network/growth-program/assets/112413448/43b891fa-0dc5-4a2b-bff6-4ac524e03c1b)
![photo1688231177](https://github.com/Phala-Network/growth-program/assets/112413448/038bfc16-547d-4ace-a686-f42b2a702b5c)
https://github.com/Phala-Network/growth-program/assets/112413448/450a5869-b314-4cb6-8843-e9cd02649c06
https://github.com/Phala-Network/growth-program/assets/112413448/9f1f3d18-3888-4918-894b-84dc2e98e0e5

MK 10/10:

Tweets (RT & LIKE)
https://twitter.com/phalanetwork/status/1664273437395918850?s=46&t=HmOP4AKlKnR1d4vxOVWYcw
https://twitter.com/marvin_tong/status/1664550903289094144?s=20
https://twitter.com/PhalaNetwork/status/1664621019082964996?s=20
https://twitter.com/PhalaNetwork/status/1664614543257903104?s=20
https://twitter.com/PhalaNetwork/status/1664346136331558931?s=20
https://twitter.com/PhalaNetwork/status/1664300836808278016?s=20
https://twitter.com/PhalaNetwork/status/1665344130602647559?s=20
https://twitter.com/PhalaNetwork/status/1664812548653305858?s=20
https://twitter.com/PhalaNetwork/status/1664948956479062016?s=20
https://twitter.com/PhalaNetwork/status/1664980619670196224?s=20
https://twitter.com/PhalaNetwork/status/1665706872597512194?s=20
https://twitter.com/ink_lang/status/1665708577645027328?s=20
https://twitter.com/PhalaNetwork/status/1665635707728060421?s=20
https://twitter.com/PhalaNetwork/status/1665723589901860869?s=20
https://twitter.com/PhalaNetwork/status/1667173918313009155?s=20
https://twitter.com/PhalaNetwork/status/1666792118122336257?s=20
https://twitter.com/PhalaNetwork/status/1666843365470511104?s=20
https://twitter.com/PhalaNetwork/status/1666792132139708416?s=20
https://twitter.com/PhalaNetwork/status/1666407813650710530?s=20
https://twitter.com/PhalaNetwork/status/1666327992577163265?s=20
https://twitter.com/PhalaNetwork/status/1665903006607618048?s=20
https://twitter.com/PhalaNetwork/status/1665744340491333633?s=20
https://twitter.com/PhalaNetwork/status/1668308294241333265?s=20
https://twitter.com/PhalaNetwork/status/1668986879255928835?s=20
https://twitter.com/PhalaNetwork/status/1668924704415965185?s=20
https://twitter.com/PhalaNetwork/status/1668708557057929219?s=20
https://twitter.com/WillCottrell_io/status/1669010447968739329?s=20
https://twitter.com/PhalaNetwork/status/1670425480804139010?s=20
https://twitter.com/PhalaNetwork/status/1670425505504321538?s=20
https://twitter.com/PhalaNetwork/status/1670425503445004358?s=20
https://twitter.com/PhalaNetwork/status/1670425500638904321?s=20
https://twitter.com/PhalaNetwork/status/1670425498600570881?s=20
https://twitter.com/PhalaNetwork/status/1671149329321709572?s=20
https://twitter.com/PhalaNetwork/status/1671864318126686217?s=20
https://twitter.com/PhalaNetwork/status/1674386684429959172?s=20
https://twitter.com/PhalaNetwork/status/1674343273442291712?s=20
https://twitter.com/PhalaNetwork/status/1674310164856356864?s=20

![image](https://github.com/Phala-Network/growth-program/assets/112413448/334229d5-5067-4213-a7a2-77ac5ff4cd88)

LINKEDIN (SHARE & LIKE)
https://www.linkedin.com/posts/phala-network_phat-contract-smart-contracts-now-smarter-activity-7071473513060052992-QgQu?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_phatcontract-ink-phalanetwork-activity-7074505727540686849-q7S2?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/feed/update/urn:li:activity:7072756576717062144?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_buidlasia-seoul-korea-activity-7071667877258399744-x-n3?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/feed/update/urn:li:activity:7072877282314342400?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_evm-substrate-activity-7071636821616570369-86De?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_evm-substrate-activity-7071636821616570369-86De?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_what-is-phat-contract-activity-7071500925269397506--P26?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_revolutionary-stake-to-compute-model-takes-activity-7072195517249720320-dkvB?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/feed/update/urn:li:activity:7059288069127950336?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_phatcontract-activity-7074860561452183552-zyK3?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/feed/update/urn:li:activity:7078069747690479616?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7078069747690479616%29

https://www.linkedin.com/posts/phala-network_bos23-phatcontract-phalanetwork-activity-7075238043556728832-QIrR?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_polkadot-decoded-2023-june-28-29-copenhagen-activity-7075007419919044608-47-I?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_polkadot-decoded-opening-night-activity-7075283343432429568-44h3?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/feed/update/urn:li:activity:7077183489510424576?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7077183489510424576%29

![image](https://github.com/Phala-Network/growth-program/assets/112413448/492a1ef4-c9ec-4635-8d51-20ea54ee118b)

This month I've shared everything about Phala in Linkedin too with almost 8k users.
Twitters impressions increased a lot too.

ART: Doesnt' count (2 suplementary) but here is it:

Infographics Created:

https://twitter.com/phalaportugues/status/1666279998968287233?s=20

https://twitter.com/phalaportugues/status/1668996645151817733

https://twitter.com/phalaportugues/status/1671932804639211537?s=20

4. Suggested scores: 
 
- [CC] 40/40
Produced many content (Articles, Threads and Translations)
- [CM] 33/40
Keep growing our local community engagement 

- [EM] 10/10
Our event was a complete sucess, many ppl interesed in Phala
- [MK] 10/10
Many impressions and ppl reading all content about Phala in Twitter and Linkedin
- [ART] 
 Inforgraphics are always cool, they will be always here

- Overall suggested score: 93/100.

My performance incresed a lot this month, I'm really happy about that and my plan is to keep pushing. 
I'm more active in the Discord and this made me feel better and more close to the team

For the next month: Do better

**Comment by willphala** [comment]
Great stuff. It's also been great to see your increased activity on Discord, great work!
