### ISSUE TITLE
June 2023 Contribution - 102j#2259

### ISSUE THREAD

**Issue by ZunkCii** [Phala-Network/growth-program#208]
Amb Rank: Ambassador
Telegram Username: @J102J (치포)
Twitter Username: https://twitter.com/ZunkCii
PHA Wallet Address: 3zkfLRrjyCy33f9xTNHDwAEjdjJknx4W6ZQ6GVTk5ffJcpck

1. CM (Community Management )
 Have I participated in Telegram Channel Moderation (choose)? Yes

Phala Korean Channel link: https://t.me/phalakorean
Combot Link : https://combot.org/c/1340032853/a?start=2023-06-01&end=2023-06-30

<img width="1298" alt="image" src="https://github.com/Phala-Network/growth-program/assets/96286632/b6d3a49f-ac7c-4b71-8ad2-bb4158af7a1a">
<img width="1261" alt="image" src="https://github.com/Phala-Network/growth-program/assets/96286632/b0665e0d-7445-494b-a171-ea92c45dec20">
<img width="1232" alt="image" src="https://github.com/Phala-Network/growth-program/assets/96286632/cf80aa28-4438-41fa-8766-23bc23c12a73">

2. VSM (Twitter Virals)

Twitter as Official Ambassador : https://twitter.com/ZunkCii
Analytic : https://analytics.twitter.com/user/ZunkCii/tweets

<img width="1257" alt="image" src="https://github.com/Phala-Network/growth-program/assets/96286632/a2b99405-c21e-4c0b-8b91-c7e4505bec8a">
<img width="1213" alt="image" src="https://github.com/Phala-Network/growth-program/assets/96286632/5c122d69-b2a9-40a6-994f-e998ae11c617">

**Comment by willphala** [comment]
72
