### ISSUE TITLE
July 2022 Contributions - {0xJUDAAS#4536}

### ISSUE THREAD

**Issue by Judaass** [Phala-Network/growth-program#21]
Telegram : @gulnarnecdet
Discord : 0xJUDAAS#4536
PHA Address : 45yVZUSPyvTk4fwxYGAo9T3KjvfnVN2aNRwVDZrYT7cQDbAE
My Mandatory (Basic) Contributions of July:
Ambassador
Phala Turkish Channel link: https://t.me/PhalaNetworkTurkey
Have I participated in Discord Channel Moderation (choose)? Yes
Have I participated in Telegram Channel Moderation (choose)? Yes

Comments :

How many people increased or decreased? Why?
Our community has just been established. I aim to increase the number of people in the future.
What was good?
People were very happy to have a Turkish community
What was bad?
Introducing people to mining is still difficult, but there have been some users who have purchased and delegated the PHA token for the first time.
How can I improve this next month?
I will continue to explain Phala from scratch and make videos. It will be best for us to create Phala culture

VSM(Twitter Virals)
Twitter as Official Ambassador : https://twitter.com/JudaasR
Twitter as Official Local Phala Account : https://twitter.com/PNetworktr
Analytic :https://analytics.twitter.com/user/JudaasR/home
Analytic : https://analytics.twitter.com/user/PNetworktr/home

My Supplementary(Advanced) Contributions of July:

CC(Contents Creation)
An introduction to the Phala Network
https://medium.com/@phalanetworktr/phala-network-nedir-neyi-ama%C3%A7l%C4%B1yor-phala-network-101-a0a9d689804

**Comment by lubi-hub** [comment]
Welcome to Phamily. when submitting your report, please note that install Combot on your Telegram channel so that you can provide the statistics with Combot link. And you need to share your Twitter analytics with screeshot.
