### ISSUE TITLE
June 2023 Contributions - {Rom1.io#5329}

### ISSUE THREAD

**Issue by Rom1io** [Phala-Network/growth-program#215]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/63704652/216827308-dd6a24be-5517-4e09-9c0e-c65a763aca3b.png">

Amb Rank : Ambassador
Telegram Username: https://t.me/Imo_999
Discord Username: Rom1.io#5329
Twitter Username: https://twitter.com/RCajina
PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q

Departments : #CC & #MK

**Contributions:**

Hello, it's been a very quiet month for me, as I've been away on business,  I still contributed to the community and made translations.

![image](https://user-images.githubusercontent.com/63704652/222117520-bf30a95b-18be-44e8-9e0f-aad3e09f879c.png)

Twitter analytics: [Here](https://analytics.twitter.com/user/RCajina/home)

![image](https://github.com/Phala-Network/growth-program/assets/63704652/3c599764-51c2-4deb-b5d8-b7dbce29b61b)

**Best Tweets:** 
- Tweet 1: [Here](https://twitter.com/RCajina/status/1665697479973801996)
- Tweet 2: [Here](https://twitter.com/RCajina/status/1668576766066151424)
- Tweet 3: [Here](https://twitter.com/phala_fr/status/1664920896627175425)

![image](https://user-images.githubusercontent.com/63704652/222134127-67fe6ec1-f49c-43d7-a391-f681d8d5a87e.png)

Here are the translations I made with a total of 3226 words  : 

- [Newsletter mensuelle Phala : Mai 2023](https://medium.com/phala-fran%C3%A7ais/newsletter-mensuelle-phala-mai-2023-e144b4ee8074)
- [Le modèle révolutionnaire Stake-to-Compute entre en scène avec la dernière mise à jour du Phat Contract Tokenomics
](https://medium.com/phala-fran%C3%A7ais/le-mod%C3%A8le-r%C3%A9volutionnaire-stake-to-compute-entre-en-sc%C3%A8ne-avec-la-derni%C3%A8re-mise-%C3%A0-jour-du-phat-f5dcfd405a9c)
- [LensAPI Oracle : Donnez un coup de boost à votre application sociale Web3
](https://medium.com/phala-fran%C3%A7ais/lensapi-oracle-donnez-un-coup-de-boost-%C3%A0-votre-application-sociale-web3-9b18aadcd9c9)

![image](https://user-images.githubusercontent.com/63704652/222134855-7eff0b13-3d74-4aad-a848-63d581a00c44.png)

With the release of Phat Contract, I'm confident that next month we'll be creating stunning and informative infographics that will capture the attention of our audience and strengthen our online presence.

I'll also be at [ParisDOTcomm](https://www.parisdotcomm.org/) to support Phala Network.

![image](https://github.com/Phala-Network/growth-program/assets/63704652/396b2b0e-328e-484d-89db-a906d4043e3c)

## SUGGESTED SCORES
#CC: 30/40
#MK: 20/40

Other:
#CC: 10/10

Overall : 60

***Quote*** : ""Life is like a bicycle, you have to keep moving forward so you don't lose your balance." -- Albert Einstein

**Comment by willphala** [comment]
Solid work 🙌
