### ISSUE TITLE
June 2023 Contributions - {TIONEB}

### ISSUE THREAD

**Issue by tionebDotsamapha** [Phala-Network/growth-program#218]
Telegram Username: [tioneb](https://t.me/tioneb)
Discord Username: tioneb#4951
Twitter Username: [tioneb_DotSama₱ha](https://twitter.com/tioneb442)
PHA Wallet Address: 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7

Departments : #CM & #CP
Department Score Weight : 90% & 10%

# Community Management
## Telegram :
<img width="515" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/2536402d-a62d-44ba-a999-3947aa874570">
<img width="496" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/a8398c4b-01e7-40ee-bea7-b23b855bbe1c">

## Discord :
<img width="734" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/65986d60-e06b-4d61-9629-2778a0e3d32d">

## Youtube :
<img width="688" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/26701c08-bcdf-49e7-8c5b-938b8b9f4039">

## Twitter :
<img width="455" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/04a5aba9-f4b7-4439-b1cc-55a43160b333">

Here's the shortest report I've written since becoming an ambassador.....
Sorry....
as I've already told you @will I'll be taking some time off in July.
I hope to come back with some great ideas !!!!

CM : 50
Total : 50

**Comment by willphala** [comment]
No problem at all for the short report. Thank you for all of your contributions and I hope you have a very well deserved break! 🫶
