### ISSUE TITLE
July 2023 Contribute - { terrencejinq#3868 }

### ISSUE THREAD

**Issue by terrencejinqu** [Phala-Network/growth-program#219]
Telegram Username: https://t.me/terrencejinq
Discord Username: terrencejinq#3868
PHA Wallet Address: 44c5wJNfegNPCMMxuccgm8PqnqbsZn2Z4h5CApXHJYbmmQxA
Departments: CM/CC

CC: 
LensAPI Oracle demo ： https://weixin.qq.com/sph/AgQRoL 
对话Privadex创始人kapil ：https://weixin.qq.com/sph/AAGLUu
LensAPI Oracle已成功集成到Lens协议文档：https://twitter.com/BM_Labs/status/1681208543381422080
https://mp.weixin.qq.com/s?__biz=Mzg3Njg3MzY0MQ==&mid=2247492413&idx=1&sn=ae393de588d1d7d3740a309f9dbc6325&scene=19#wechat_redirect
CM: 
We hold a community event for W3A in our Wechat communities this month, and collect 118 users for W3A WL.
We also make weekly reports for our community members every week.
DEV:
We launched our Phala Dashboard V1 this month, and it'll upgrade in next 2 months with wallet connect function and stake function.
Here is the test link: http://172.16.15.8:8000/#/secssc/

**Comment by willphala** [comment]
Hi @terrencejinqu! Thanks for the information. Can you please do the following? 

1) Follow our report structure. There are sections missing. For example, no analysis about your performance and no suggested score. 
2) Provide links that work. The only link I seem able to personally open is the Twitter link.
