### ISSUE TITLE
July 2022 Contributions - {GatorKorps | Phala Amb#7997}

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#22]
Hello and welcome :)

PhalaFR https://www.youtube.com/channel/UCGlb62d16v-IH2FFP5l9XpA
Discord : GatorKorps | Phala Amb#7997
TG: @Gatorkorps
PHA Address : 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV
Have I participated in Discord Channel Moderation (choose)? Yes
Have I participated in Telegram Channel Moderation (choose)? Yes

**_Youtube channel :_**

![image](https://user-images.githubusercontent.com/82824139/183245758-c2eea933-10f0-4efe-bec9-a73d62b3acee.png)

_Comments :_

How many people increased or decreased? Why?
The number of views drop during this month, most of the time has been used to create content but not online yet.

Next vidéo: interview of Zoe in Paris Ready to go out ASAP (target monday)

![image](https://user-images.githubusercontent.com/82824139/183246214-fcafb65d-680c-41a0-9022-634e2b75f778.png)

How can I improve this next month?
More content focused on the Lore the use of Phala.

Twitter as Official Ambassador : https://twitter.com/gk18_dog
Analytic : https://analytics.twitter.com/user/gk18_dog/tweets

![image](https://user-images.githubusercontent.com/82824139/183245959-40d8ab72-eddf-4c23-9b4a-131c7ac6ed27.png)

![image](https://user-images.githubusercontent.com/82824139/183246049-d8a963e8-2b3d-47b9-8c81-1948e3b60d87.png)

Comment:
I always retweet and tweet Phala with my main account to boost the visibility of the Phala Content and news. The best tweet around Phala was a thread create in english to add information of a visual around Phala by  [@PolkadotInsider](https://twitter.com/PolkadotInsider)
Still on the hunt to promote Phala in every conversation related to our quality.

**_Telegram:_** 

![image](https://user-images.githubusercontent.com/82824139/183246148-f04c4383-0f00-4b76-be00-28d7ea8456e7.png)

Still very active on the Telegram
All the analytics are viewable on the TIONEB post.

**_Event :_**

ParisDotCom Event Was a really great event, all the only represent of Phala with Zoe I was very busy to speak about Phala, what it brings and bring more French Noode Operator in the game. 
Participation to event -and more local event) are very important to explain face to face what Phala bring and the innovation. 
I've speak to more than 50 people of Phala, the staking, th epossibility, the ideology, the innovation and the node operation possibility. It was a great succes (1 french node operator will start to "mine" , and almost 5 others were really interessted) and I bring almost 10 more people to staking the PHA so yeah it was usefull.
We should definitely be more present to the event.

![image](https://user-images.githubusercontent.com/82824139/183246361-f688e4c9-cd25-48a7-88ca-2047c93af593.png)

https://www.youtube.com/watch?v=6WJBU5RRPOY   (a cool video I've create during the event)

**_AMA_**

I've also participated to a dailys AMA on the account of Polkadot Francophonie to speak about Phalaworld mainly. (every thusday)
https://twitter.com/Polkadot_FR

Our monthly AMA for the month of July was organized on the French Binance community discord.
This allowed us to get out of our Phala-Network community and introduce ourselves to an audience that doesn't know the project.
There is no video of this AMA but an audio recording:
https://drive.google.com/file/d/1kfND4XeHZGbPk9ff6IqSgjzKsPddUBeI/view

On the 5 Phala-World WhiteLists we had obtained for the fr, we kept 2 to offer the shellNFT whose mint fee will be paid by https://github.com/blackstone and myself.
At this AMA we offered our first shellNFT.

Thanks to https://github.com/blackstone for the organization of this AMA!

**_Article translation :_**

Translation of the last Lore Article around the chapter and story of Phalaworld
https://app.subsocial.network/@gatorkorps.dot/chapitre-1-l-eveil-de-l-ia-l-ia-alice-a-toujours-34904
![image](https://user-images.githubusercontent.com/82824139/183246490-8c6c040d-cfd4-430c-82b2-fc7b7ead600d.png)

**_Conclusion :_**

The highlight of July is the event ParisDotCom where I was able to explain and speak about Phala to many people it was really usefull.
July was a busy month for me, I didin't have time to create and publish all I wanted....but I had a busy monh with my main job....
August is here with many more content ready to be published. I will focus my next activity on a more tutorial video for PhalaFR and more thread to explain our great protocol.

**Comment by lubi-hub** [comment]
Really enjoyed your video and look forward to the content in August.
