### ISSUE TITLE
July 2023 Contribution - {ChrisBck#1751}

### ISSUE THREAD

**Issue by chrisbck** [Phala-Network/growth-program#230]
### A.	Personal info:
Ambassador Rank: Candidate
Telegram Username: [@chrisbck](https://github.com/chrisbck)
Twitter Url: https://twitter.com/BckChris
PHA Wallet Address: 43ZKJ2DEBagpMyn4EQvTu7niH1xRYGvfCJyGZYZyW6STFCbd
Departments: CC/CM
Department Score Weight: 70/30

![image](https://github.com/Phala-Network/growth-program/assets/32775411/09b095fb-74b1-428d-aa5e-fda8cbd1471a)

![image](https://github.com/Phala-Network/growth-program/assets/32775411/4df905c0-3a9d-4fe6-aabb-b0b376d5d6bc)

### B. Departments:
CC:
- Wrote a PhalaWorld article, which is the 2nd part of a series of 4. It focusses on the strength attribute and how the score is calculated and how it can be maximised.   [https://medium.com/@ChrisBck/phalaworld-attributes-strength-34b7e3586088](https://medium.com/@ChrisBck/phalaworld-attributes-strength-34b7e3586088)
- Created a thread on Powering up your app using Phat Contracts. Intended to catch the eye of Lens Developers. [https://twitter.com/BckChris/status/1683832414114832385](url)
- Infographic highlighting the potential of connecting to ChatGPT through a Phat Contract.
- Graphic promoting the partnership between Phala and Lens protocol. I used their mascot new mascot to hopefully catch the attention of their community. [https://twitter.com/BckChris/status/1686028681141952514](url)

CM:
Been a quiet month for me again in the community. I have been mostly active in the PW discord, which is still quiet, but I feel it is important to ensure that concerns like [this ](https://discord.com/channels/920642630835138601/920642633011953697/1128898591411425403)are addressed to help upkeep community trust and keep anxieties low.
I have continued to update the community digest.

### C. Supplementary tasks:
ART:
Created a looping 3D animation to accompany the PW article. It represents using PHA tokens to build strength attribute

https://github.com/Phala-Network/growth-program/assets/32775411/262800a7-acaa-44e4-9e82-addcb9a66fac

Original infographic in the style of no-code logic nodes.
![image](https://github.com/Phala-Network/growth-program/assets/32775411/cca3b866-f2a1-42c7-938d-b6423653a6c6)

Phala x Lens Graphic, customised their mascot with a Phala shirt. 
![image](https://github.com/Phala-Network/growth-program/assets/32775411/4c8eba98-fd96-4bd1-8a57-088829549447)

Video game style Phat Contract power up
![image](https://github.com/Phala-Network/growth-program/assets/32775411/54bc3ec2-a948-49b6-8d30-94c6a0326b62)

PM:
Engage and retweet almost all Phala tweets and react to discord announcements. Like and retweet fellow ambassadors content.

### 4. Suggested scores:

CC: 40
CM: 20
ART: 7
PM: 4
Total: 71

**Comment by willphala** [comment]
Great content as per usual!!
