### ISSUE TITLE
July 2023 Contribution - {GabeKoin}

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#231]
Telegram : @gabekoin
Discord : gabekoin
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of July:
Candidate

CONTENT (CC): 40/40

Articles created:
1/ Phala in EthParis:
https://medium.com/@phalaptbr/conhe%C3%A7a-a-ethglobal-e-saiba-mais-sobre-esse-grande-evento-67fe96abbdb1
![image](https://github.com/Phala-Network/growth-program/assets/112413448/a825ab56-07c9-4aea-9325-4f5156c22294)

2/ Detalhes sobre blueprints:
https://medium.com/@gabekoin/detalhes-sobre-blueprints-e-personaliza%C3%A7%C3%A3o-do-phat-contract-9f2e553ce831?postPublishedType=initial
![image](https://github.com/Phala-Network/growth-program/assets/112413448/0a7af78b-6742-4772-bf49-7c00deded712)

Threads created:
1/ Phala in ETHParis
https://twitter.com/gabekoin/status/1684211240019664897
![image](https://github.com/Phala-Network/growth-program/assets/112413448/98ae7f4f-d5c0-4c7e-b5c2-2d5a0de1266f)

2/ E a semana já começou ON FIRE pro time da[ @PhalaNetwork](https://twitter.com/PhalaNetwork)
https://twitter.com/phalaportugues/status/1683477382525513732
![image](https://github.com/Phala-Network/growth-program/assets/112413448/73ed02e6-bb69-4090-b72a-c4dd2c912038)

3/ We had the opportunity to show our local community about 
https://twitter.com/gabekoin/status/1676233530395721728?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/05407934-60ae-4c93-831b-94dfbf30a1a7)

4/ O Phat Contract foi projetado para ser seguro, eficiente e fácil de usar. 
https://twitter.com/phalaportugues/status/1678874670303420420?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/825663ab-3477-4b70-b7b5-5a9d2e627c99)

5/ Concomitantemente com os Blueprints, o[ #PhatContract](https://twitter.com/hashtag/PhatContract?src=hashtag_click) é totalmente personalizável
https://twitter.com/phalaportugues/status/1681381723605434369?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/8107b012-14dd-45d5-b722-52c2009afe4a)

Threads Translated:
Phala World:
https://twitter.com/phalaportugues/status/1681668969852174336?s=20
Boletin Weekly:
https://twitter.com/phalaportugues/status/1676644852875018246
Boletin Weekly 2:
https://twitter.com/phalaportugues/status/1679245141511479297?s=20
Aplausos de pé:
https://twitter.com/phalaportugues/status/1682391801657786368?s=20
Discutimos tendências e ferramentas:
https://twitter.com/phalaportugues/status/1682392192290115586?s=20

Balançou o palco:
https://twitter.com/phalaportugues/status/1682392693425467392?s=20
ETH Global:
https://twitter.com/phalaportugues/status/1683838732728930309?s=20
Plygonx:
https://twitter.com/phalaportugues/status/1685340886639468544?s=20

Metrics:
![31 engagement](https://github.com/Phala-Network/growth-program/assets/112413448/48178c19-daa4-4e43-9828-dccaa13891b3)
![phala melhores tweets](https://github.com/Phala-Network/growth-program/assets/112413448/86ed038e-ba2c-49f5-84ec-e76b62242311)
![Twitter gabe 1](https://github.com/Phala-Network/growth-program/assets/112413448/c96a5021-e704-4d28-ad87-3417bd3b9453)
![Twitter gabe 2](https://github.com/Phala-Network/growth-program/assets/112413448/c57e9334-9a31-4478-8e09-042de6a27c0f)
![Twitter phala 1](https://github.com/Phala-Network/growth-program/assets/112413448/689cdbda-0c61-493d-b3e0-2e67a38cb715)
![Twitter phala 2](https://github.com/Phala-Network/growth-program/assets/112413448/77d8367c-44a1-48b9-8a41-186cd57dcdd7)
![Twitter phala 3](https://github.com/Phala-Network/growth-program/assets/112413448/20ccf185-9f16-4054-98c8-969f79046c9e)

Community Manager (36/40)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/855b663e-da6a-40ce-9ae3-30d1d5570750)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/4c4b6f29-7987-4f83-9a69-6cd997f1e333)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/34ca1d76-2940-4d1e-8548-3a2eaa0f353b)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/b643da17-ef93-4caa-8985-016dd817b350)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/90c1bd34-a35c-4bac-8ce8-0084855d537c)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/da1df804-6650-4ae5-a99f-9857f3c806a4)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/7ceb5cf9-f201-4d6b-816f-53f68adedb2e)

![Phala 1](https://github.com/Phala-Network/growth-program/assets/112413448/5dc33444-f970-4ac0-9c08-4f61bae7db03)
![Phala 2](https://github.com/Phala-Network/growth-program/assets/112413448/e7a913a7-2a70-4d2c-94cb-48c3b1cdcdce)
![Phala 3](https://github.com/Phala-Network/growth-program/assets/112413448/bd2d7265-2571-4482-b46d-387f70980dde)
![Phala 4](https://github.com/Phala-Network/growth-program/assets/112413448/6e537e37-e7a6-4540-be8a-433d843ebdd8)
![Phala 5](https://github.com/Phala-Network/growth-program/assets/112413448/2dfe5608-98ba-4e33-9ec7-8d24639b0b7e)
![Phala 6](https://github.com/Phala-Network/growth-program/assets/112413448/047e2648-1176-4955-86e7-01568f505a6b)
![Phala 7](https://github.com/Phala-Network/growth-program/assets/112413448/9cddd325-aa25-454d-9432-88b9b3e301ad)
![Phala 8](https://github.com/Phala-Network/growth-program/assets/112413448/c3a3c01b-4e23-4d68-b886-7cdaaaf42e9e)
![Phala 9](https://github.com/Phala-Network/growth-program/assets/112413448/d664cbfb-b368-4f7a-9cc0-7d0da0c84e63)
![Phala 10](https://github.com/Phala-Network/growth-program/assets/112413448/cda5c570-44b6-46a1-9b09-5c9073fa485e)
![Phala 11](https://github.com/Phala-Network/growth-program/assets/112413448/6c9bcf1c-55a4-486a-aa0d-3e5d75c0012c)
![Phala 12](https://github.com/Phala-Network/growth-program/assets/112413448/2fa78658-2f3a-4728-ab00-c9afc6fa377f)
![Phala 13](https://github.com/Phala-Network/growth-program/assets/112413448/885f5f38-a292-47a7-af11-b2688cb50395)
![Phala 14](https://github.com/Phala-Network/growth-program/assets/112413448/50c50a35-6acb-4797-ba83-5052eafde51b)
![Phala 15](https://github.com/Phala-Network/growth-program/assets/112413448/3a714b83-e4f2-44ad-bc43-c73827676952)
![Phala 16](https://github.com/Phala-Network/growth-program/assets/112413448/894b1c59-95b3-469a-9eca-92ef5eeeaedf)
![Phala 17](https://github.com/Phala-Network/growth-program/assets/112413448/fc0e9649-6f47-4d20-bd1a-194e4bb3d4c4)
![Phala 18](https://github.com/Phala-Network/growth-program/assets/112413448/0bb72d1c-a219-4e86-91f4-4c2d568df76a)
![Phala 19](https://github.com/Phala-Network/growth-program/assets/112413448/abcb177c-0fa0-478a-99c7-52b8ca419330)
![Phala 20](https://github.com/Phala-Network/growth-program/assets/112413448/56988344-0c00-497e-8963-7e5249e34a56)
![Phala 21](https://github.com/Phala-Network/growth-program/assets/112413448/5b9e117f-e54f-4f1c-8d04-20575202902e)
![Phala 22](https://github.com/Phala-Network/growth-program/assets/112413448/ad174d57-16d1-4294-9158-8eb60a400781)
![Phala 23](https://github.com/Phala-Network/growth-program/assets/112413448/903d7f99-f979-4a02-a5d7-e5d869e3b651)
![Phala 24](https://github.com/Phala-Network/growth-program/assets/112413448/b2c79a44-e9d8-4fd6-8ebe-cfa0374443e5)
![Phala 25](https://github.com/Phala-Network/growth-program/assets/112413448/530b9fb4-e3b2-41cb-a453-23a8527fa2b1)

Contributions: EM & MK (20/20)

Event Manager: 10/10
Hosted 3 Twitter Spaces with Brazilian community

First:
![Spaces 1](https://github.com/Phala-Network/growth-program/assets/112413448/024dcd68-0f16-4375-a959-cbba25e1cf3f)
![Spaces 2](https://github.com/Phala-Network/growth-program/assets/112413448/8f73226b-6483-483e-a0dd-8b3f4d73ee03)
![Spaces 3](https://github.com/Phala-Network/growth-program/assets/112413448/1d6c5465-a28d-4117-aa81-7c164bf6c31c)

Second:
![Spaces 4](https://github.com/Phala-Network/growth-program/assets/112413448/daf4885b-61cf-4bd5-8d87-0bee3d986798)

Third:
![Spaces 6](https://github.com/Phala-Network/growth-program/assets/112413448/96ea5530-8521-4d1c-b472-9d7411fa0517)

Marketing: 8/10
Tweets (RT & LIKE)
https://twitter.com/parachainboy/status/1676591535658246145?s=20
https://twitter.com/PhalaNetwork/status/1676604920923914240?s=20
https://twitter.com/PhalaNetwork/status/1676604924929404929?s=20
https://twitter.com/PhalaNetwork/status/1676172981817729024?s=20
https://twitter.com/PhalaNetwork/status/1676127307382104064?s=20
https://twitter.com/PhalaNetwork/status/1676127333307101189?s=20
https://twitter.com/PhalaNetwork/status/1676127330924736512?s=20
https://twitter.com/PhalaNetwork/status/1676127318522097670?s=20
https://twitter.com/PhalaNetwork/status/1677355700652060673?s=20
https://twitter.com/PhalaNetwork/status/1679111562949214208?s=20
https://twitter.com/PolimecProtocol/status/1679105411016712192?s=20
https://twitter.com/PhalaNetwork/status/1679065028282966016?s=20
https://twitter.com/gabekoin/status/1680011037313998850?s=20
[https://twitter.com/WillCottrell_io/status/1679828454907281409?s=20](https://twitter.com/WillCottrell_io/status/1679828454907281409?s=20https://twitter.com/PhalaNetwork/status/1679200946893516804?s=20)
[https://twitter.com/PhalaNetwork/status/1679200946893516804?s=20](https://twitter.com/WillCottrell_io/status/1679828454907281409?s=20https://twitter.com/PhalaNetwork/status/1679200946893516804?s=20)
https://twitter.com/PhalaNetwork/status/1679200913230032898?s=20
https://twitter.com/PolkadotInsider/status/1680593552936689665?s=20
https://twitter.com/PolkadotInsider/status/1679581468593643520?s=20
https://twitter.com/PhalaNetwork/status/1681326214403993603?s=20
https://twitter.com/zoemcfox/status/1681610709908570115?s=20
https://twitter.com/dabeibleibn/status/1681668988068036608?s=20
https://twitter.com/PhalaNetwork/status/1681751878449733632?s=20
https://twitter.com/PhalaNetwork/status/1682114765152296960?s=20
https://twitter.com/PhalaNetwork/status/1682381761546792962?s=20
https://twitter.com/zoemcfox/status/1684717073723785216?s=20
https://twitter.com/marvin_tong/status/1684625931619504133?s=20
https://twitter.com/PhalaNetwork/status/1683116553204580352?s=20
https://twitter.com/marvin_tong/status/1684258492117286923?s=20
https://twitter.com/phalaportugues/status/1683477382525513732?s=20
https://twitter.com/PhalaNetwork/status/1684937726787723264?s=20
[https://twitter.com/PhalaNetwork/status/1685244413088317440?s=20](https://twitter.com/PhalaNetwork/status/1685244413088317440?s=20https://twitter.com/PhalaNetwork/status/1685292147543523328?s=20)
[https://twitter.com/PhalaNetwork/status/1685292147543523328?s=20](https://twitter.com/PhalaNetwork/status/1685244413088317440?s=20https://twitter.com/PhalaNetwork/status/1685292147543523328?s=20)

LINKEDIN:
Phala News Created:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_bos23-activity-7089349987444125696-vB63?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-we-discussed-trends-and-tooling-activity-7089351250323869696-rQxZ?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phatcontract-activity-7089350872312295424-dNWY?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-join-us-tomorrow-at-5pm-activity-7089606746381406209-oUFz?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-wow-what-a-week-in-paris-activity-7089674515240091648-RGAW?utm_source=share&utm_medium=member_desktop

(SHARE & LIKE)
https://www.linkedin.com/posts/phala-network_phat-contract-smart-contracts-now-smarter-activity-7071473513060052992-QgQu?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_devx-global-tour-is-coming-to-europe-in-july-activity-7078800949326090240-CUzc?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_phat-bricks-demo-deploying-a-lensapi-oracle-activity-7079277158799474688-L0MJ?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_polkadotsummit-phatcontract-phalanetwork-activity-7079435022088175616-wHUr?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/phala-network_phatcontract-activity-7074860561452183552-zyK3?utm_source=share&utm_medium=member_desktop

Marketing Metrics:
![image](https://github.com/Phala-Network/growth-program/assets/112413448/9b6f008d-22f7-40ff-828b-04df00b41bfe)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/69b3a151-a881-4902-b1ac-c50b90eea66b)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/34c29042-e06e-4cf1-ac58-9cbc3fad1774)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/dec0f4d2-643b-43f5-8c23-0701841ab29e)

Infographics Created:
https://twitter.com/phalaportugues/status/1679943713827553282?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/7cf06ec3-d14d-49dd-aa8c-e98e7457352f)

Suggested scores:
[CC] 40/40
Produced many content (Articles, Threads and Translations) 
Many views and good engajement

No bad points, I'm really happy about this month, great content and many people liked our content.
For next month keep the good work and try to reach more people

[CM] 36/40
This month we had more members talking around Telegram and Discord, many newcommers and this is perfect.
To the next month, keep growing Portuguese Unit

[EM] 10/10
We started to host some Spaces and was a complete sucess. Many people joint and loved.

[MK] 8/10
The impressions and engagement is growing and thats amazing.

Overall suggested score: 94/100.

I had sucess in doing more this month than in the last one, happy about that.

For the next month: Do better

**Comment by willphala** [comment]
Great work. I can see a big improvement from you and John! 

One piece of constructive feedback though is that if you're unsure about something please double check with someone in the team about what information we should be giving community members. For example, we should not be directing queries about cyber security to our Builders Programme. I hope that makes sense? This is a very easy mistake to make so don't worry. 

Keep up the good work and the good energy Pham!
