### ISSUE TITLE
September 2023 Contributions - {ivakhnenko_dmitriy}

### ISSUE THREAD

**Issue by MrDobby007** [Phala-Network/growth-program#270]
**Personal Information:**
**AMB Rank:** Candidate Ambassador
**Discord:** ivakhnenko_dmitriy
**Telegram:** @Ivakhnenko_Dmitriy
**Twitter:** https://twitter.com/Dima35109517
**PHA Address:** 457dtbUfSkGAHGzD97qWicrCJWGpDjAHjcHYBuPBnkiuW1KT

**Departments:** #CC / #CM
**Department Score Weight:** 50% (40) / 50% (40)

**Contributions:**
In September, I was very actively engaged in promoting the Phala Network project, as well as all the products within the Phala ecosystem, on Twitter, Medium, the Phala Discord and various social media platforms. This also included our shared/local/national chats in Discord, including Ukrainian and Russian chats. During this month, I created numerous engaging and informative images and memes that promoted the principles of the Phala Network project. I also wrote two captivating articles about Phala Network and Phala World, using a free writing style without delving into highly technical details. Instead, I aimed to inform our users about all the advantages and technical achievements of Phala in simple language and a friendly atmosphere. Additionally, I designed two unique and impressive infographics highlighting the technical aspects of Phala Network to introduce more users to the behind the scenes development of Phala. I published all these materials on my Twitter and in the Discord channels of Phala Network and Phala World. I integrated and used all my materials in my content rich tweets to provide our users and those who are not yet familiar with Phala with up to date information every day. This information covers not only the technical aspects of the project but also the entire ecosystem, its operations, community interactions, and social activities within the vast world of WEB3. I devoted time to assisting my fellow Ambassadors in promoting their Phala related materials and content and whenever possible, I helped spread them on Twitter and in our Discord channels. I consistently supported, quoted and promoted all tweets from the official Phala Network account, as well as from all active team members of Phala. I also disseminated this information in our Telegram and Discord communities. Throughout September, I actively participated in various discussions and dialogues in our general, regional, and local Telegram and Discord chats. I frequently responded to user queries within our community, quickly and efficiently removed harmful or fraudulent content by users in our communities. Additionally, I distributed Phala related information within our communities to ensure that our users remained informed about all developments. This month, I continued to foster our Ukrainian Phala community on Discord and Twitter. Together with infaceAi, we collaborated on creating content on Twitter, increased engagement on Discord, and drew in new Ukrainian audiences to the Phala project. Additionally, in Discord and on Twitter, we provided support to the Russian speaking community, aiding its growth and development. September was an incredibly busy and successful month in terms of work, and I have a lot to show and tell you. Below, I've shown absolutely everything I've done this month. Thank you in advance for reviewing my work!

### **Analytics September 2023 stats:**

![115](https://github.com/Phala-Network/growth-program/assets/68858747/6b6394cf-c2e1-4c99-be54-ec1ff1ac3af6)
![116](https://github.com/Phala-Network/growth-program/assets/68858747/edad0cf8-7129-490f-b62d-d2f9e6522730)

**In September, I had a lot of successful, interesting, and engaging tweets. I produced twice as many compared to the previous month. I made significant progress in terms of both quality and quantity, putting in meticulous effort into each piece of work. Below, I will present all my work for this month along with detailed statistics:**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/180642c4-3272-4ebd-aa03-f8441e6db0f1)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/b7af4589-68de-4cf8-9c2f-bd7f2cba9b18)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/4b8ba2f8-ebb6-440a-9ef4-b16393283a39)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/eeffb2fc-8f08-47c7-a3e0-af631400c22c)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/bf83b2f9-27d7-43c4-8f76-7df331e908a4)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/8877d613-c638-4b72-b19b-e3682d94ba95)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/90a873e0-44a1-4cec-b544-4065b79599df)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/47b9cacf-bf3f-4a20-ac7c-4b0100b6ae68)
![9](https://github.com/Phala-Network/growth-program/assets/68858747/633a4955-0510-4e7e-a47f-2bba45cd5739)
![10](https://github.com/Phala-Network/growth-program/assets/68858747/5e150b3e-a018-4b99-8768-fe857b705690)
![11](https://github.com/Phala-Network/growth-program/assets/68858747/8756f57e-1bfb-4e51-a66a-fb44e3d9e765)
![12](https://github.com/Phala-Network/growth-program/assets/68858747/7910459f-8e4d-4931-a034-4de31dec5486)
![13](https://github.com/Phala-Network/growth-program/assets/68858747/56ecdc0d-ff67-4dfb-83db-6c032124c41a)
![14](https://github.com/Phala-Network/growth-program/assets/68858747/18d3d7ac-0e30-499e-9465-a7fc42a55c87)
![15](https://github.com/Phala-Network/growth-program/assets/68858747/ab3944d1-b74c-40d6-9e15-f5039c5bc735)
![16](https://github.com/Phala-Network/growth-program/assets/68858747/d2527aed-e899-4aa7-9f5c-d68d7cd0d7c1)
![17](https://github.com/Phala-Network/growth-program/assets/68858747/da6f8369-b29d-4dd9-8cbf-7f303b9642d3)
![18](https://github.com/Phala-Network/growth-program/assets/68858747/f9775b28-0511-4d7c-857f-7d4cb0dbd792)
![19](https://github.com/Phala-Network/growth-program/assets/68858747/9b692880-2de4-4842-96e4-f9e666eb5205)
![20](https://github.com/Phala-Network/growth-program/assets/68858747/750e4aee-e65a-4584-bb22-cfde7bcd7087)
![21](https://github.com/Phala-Network/growth-program/assets/68858747/2f47757b-106b-489b-89e0-9bb299e09fcb)
![22](https://github.com/Phala-Network/growth-program/assets/68858747/3ebaa184-a85c-468c-9bdf-24c5a3a96925)
![23](https://github.com/Phala-Network/growth-program/assets/68858747/5e552e5c-99e0-4727-afc3-b065902280e7)
![24](https://github.com/Phala-Network/growth-program/assets/68858747/11377641-9857-4398-afc5-1a8a2999509e)

**Below, I will present my quotes from various tweets about Phala, their retweets, and my personal tweets without images**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/ced51fce-d17c-4d98-a0e2-dc5386c7635a)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/3a121f5b-997b-49d8-bb86-5acc3535822d)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/bdb28fdd-f003-428c-afe4-eea41e0f7809)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/19c21c49-d2b2-4000-9231-98ca5e51ea3b)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/55fd2e22-aaed-4cf3-9931-67ca14a88c7d)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/a4c96b24-3fe7-4323-934d-cc39023e1614)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/1748aacf-e107-41dc-acc6-6ea9fa2a2d2f)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/a06f214b-dc27-4272-881f-0c6c36d5590d)
![9](https://github.com/Phala-Network/growth-program/assets/68858747/2874b7de-641c-4ee7-ad56-2527cf621630)
![10](https://github.com/Phala-Network/growth-program/assets/68858747/4d6ec984-a43f-42db-80b5-448484e1ef5e)
![11](https://github.com/Phala-Network/growth-program/assets/68858747/9f38f268-49ca-44bb-8609-0c341295ba71)
![12](https://github.com/Phala-Network/growth-program/assets/68858747/ccbd97ef-64b7-4ec3-9019-e8169e5f3796)
![13](https://github.com/Phala-Network/growth-program/assets/68858747/e6960f70-e4cd-423e-ac4b-0a438fab92c5)
![14](https://github.com/Phala-Network/growth-program/assets/68858747/c0631368-0c3f-4115-9585-99cc2722c2ac)
![15](https://github.com/Phala-Network/growth-program/assets/68858747/0a8e6f2f-f154-4797-ba01-8feb0ffecce5)
![16](https://github.com/Phala-Network/growth-program/assets/68858747/58d221ee-31fd-421a-b475-973765a14552)
![17](https://github.com/Phala-Network/growth-program/assets/68858747/5d080c52-20b8-4f1f-b5eb-35a0bc9e8d22)
![18](https://github.com/Phala-Network/growth-program/assets/68858747/1fa5ab0b-5753-467a-acf5-372327a07a1c)
![19](https://github.com/Phala-Network/growth-program/assets/68858747/802f15fe-1015-4b3a-a30c-1ddcae926b3a)
![20](https://github.com/Phala-Network/growth-program/assets/68858747/314f5017-ba13-48c1-8a6f-1fecbcba618e)
![21](https://github.com/Phala-Network/growth-program/assets/68858747/9506030d-3bd1-4fa6-8c1c-9500903dfb9d)
![22](https://github.com/Phala-Network/growth-program/assets/68858747/59326900-d41e-4888-a3cd-c1200d14a825)
![23](https://github.com/Phala-Network/growth-program/assets/68858747/904d0ca8-a3f8-462f-baa2-baa227d400d7)
![24](https://github.com/Phala-Network/growth-program/assets/68858747/0f980d39-c657-411e-af6c-78b95e39e0b1)
![25](https://github.com/Phala-Network/growth-program/assets/68858747/47b7cb18-d4fb-48d7-a6ce-9b1cf5af79d9)
![26](https://github.com/Phala-Network/growth-program/assets/68858747/9bece0e0-d47a-4bd2-9ad0-6faadd430ad7)
![27](https://github.com/Phala-Network/growth-program/assets/68858747/88e65392-2f02-41fe-9142-57bf56eeea1c)
![28](https://github.com/Phala-Network/growth-program/assets/68858747/14e81667-6157-4566-a9e0-fb244fa49dac)
![29](https://github.com/Phala-Network/growth-program/assets/68858747/e2dcb7a6-812d-465e-9980-8320c9b95f8b)
![30](https://github.com/Phala-Network/growth-program/assets/68858747/73e063f6-d20b-47f7-acf9-ef20b0f9b3bd)
![31](https://github.com/Phala-Network/growth-program/assets/68858747/010297ea-7a7f-4b91-9eda-b9711c914653)

**Below, you can see how my level in the Phala Discord has changed over September. I was active every day this month, engaging with the community, fostering pleasant conversations in our chats, and answering various questions related to the Phala ecosystem:**

![1,](https://github.com/Phala-Network/growth-program/assets/68858747/0ddc06d2-eb00-4698-995d-c75c7f2b4e22)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/c83e3d4b-f9f9-4539-906a-2a620d28bda7)

**In September, Phala hosted 2 Twitter Spaces with various guests and other projects. I attended all of these events and tried to support the people representing Phala:**

![photo_2023-09-06_19-24-09](https://github.com/Phala-Network/growth-program/assets/68858747/5499152c-da23-44a8-9d6e-089f901911d2)
![photo_2023-09-06_17-06-10](https://github.com/Phala-Network/growth-program/assets/68858747/95cecd08-f267-4379-b8d9-7814edaa0a77)

**In September, I focused on actively engaging with and assisting our community, both in technical matters and in terms of communication and interaction with the Phala ecosystem:**

![photo_2023-09-06_17-07-43](https://github.com/Phala-Network/growth-program/assets/68858747/41d42eb2-6c75-4686-8964-2a6a494bfe68)
![photo_2023-09-13_00-53-22](https://github.com/Phala-Network/growth-program/assets/68858747/dfad13c8-2e42-409b-9ed6-03ebe74bb027)
![photo_2023-09-27_17-08-19](https://github.com/Phala-Network/growth-program/assets/68858747/d698f1d5-619f-470c-aaee-c5331834c682)
![photo_2023-10-01_02-17-33](https://github.com/Phala-Network/growth-program/assets/68858747/1093c010-5e55-4726-9c44-4012475b2d0a)
![photo_2023-09-29_11-41-19](https://github.com/Phala-Network/growth-program/assets/68858747/1bab378b-883a-456f-940f-af2aff7d0695)
![photo_2023-09-27_17-14-17](https://github.com/Phala-Network/growth-program/assets/68858747/5d989309-fed7-4458-b898-492ca619d421)

**Recently, a new user joined our community and approached me with a request to explain everything related to the Phala Ambassador program. I provided him with detailed information, and he successfully submitted his application for consideration:**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/bc61b9fe-51fe-4d0e-8834-084ff2288320)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/30e6968e-0ee8-4b66-9301-9d34e6dab180)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/025b23a1-12f1-4796-9bf7-4e7d529a5abd)

**Below, you will find statistics on user activity in the official Phala Telegram channel. I'm also included in this list, and you can see my activity for September:**

![272066826-e47a2289-435c-460a-826f-b00abf5586c6](https://github.com/Phala-Network/growth-program/assets/68858747/ef7b11bf-274b-4221-a857-d8934b8b2bf7)

**In September, as always, I was active in our "Meme" chat and regularly posted my created works about Phala Network and Phala World in our Discord community:**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/a99094c4-18aa-415c-8933-2ad02a6f442d)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/80aa9ab7-ff43-4b98-aac6-d54690cabeae)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/df929191-a040-49c9-8ed9-190935ec9bfa)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/b8444336-7cfc-4de7-b195-aa0c5fadb24f)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/094d4f67-cabc-410c-b396-29f55a053269)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/948b7535-18ba-4a7c-8107-3373cdff56ac)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/fcf179e0-c6d0-4807-bede-f03373d1c144)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/e36a6f86-bb3a-47ae-818c-9e6bbfc60ff0)
![9](https://github.com/Phala-Network/growth-program/assets/68858747/9f8ce55a-794d-4216-b9e9-ecb0f4ea8a51)
![10](https://github.com/Phala-Network/growth-program/assets/68858747/e5ffad69-523e-47c5-a2b8-6c00dfc8c8cc)
![11](https://github.com/Phala-Network/growth-program/assets/68858747/b3124b07-3970-4aed-8397-8859f23621ec)
![12](https://github.com/Phala-Network/growth-program/assets/68858747/db46a8d0-2c62-4497-9891-7c1312c97609)
![13](https://github.com/Phala-Network/growth-program/assets/68858747/73f3bb34-413f-463a-b070-b06f03f1347b)
![14](https://github.com/Phala-Network/growth-program/assets/68858747/63e54e2a-dec3-41fc-b85e-6040ce80d2fc)

**This month, I paid special attention to moderating our Phala Discord community. I was constantly online, monitoring all incoming messages in all chats, and promptly removing spammy or fraudulent content from users. I would do the same in our Telegram, but for now, I can't delete harmful messages myself. However, I point out this issue to other ambassadors to help me address it:**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/fe83b6b7-e9d8-431a-bb1d-37154bfba352)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/2769710c-1550-4e7a-a38e-015d2ce2104e)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/84068359-dd28-4f42-a4e4-eee2f02f37fb)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/807fe029-cbcc-416c-b38a-ea81d4231ab6)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/ca19d869-2aed-40fa-bc56-aa4dad68b063)

**In September, I continued to develop our Ukrainian community on Discord and Twitter. In the Discord local chat, I fostered friendly and pleasant communication, shared my own created content that unites the ideas of the Ukrainian community and the Phala Network project. Additionally, in collaboration with infaceAi, we continued to develop the Ukrainian Twitter account. We posted engaging and informative tweets, shared important retweets and quotes from Phala official accounts, and created many cool images for our community. This helped us make significant progress during the month and attract new audiences to the Phala Network ecosystem. In October, we are also continuing to develop our community and aim to take it to the next level, attracting even more enthusiasts from Ukraine to the Phala project**

![1,](https://github.com/Phala-Network/growth-program/assets/68858747/afed3749-6a6b-4763-8d96-382f35efa8b1)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/1fedeefe-a0a6-4ea5-8062-64da739d63c3)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/7710be71-b0ff-491b-94ae-bceed795f061)

### **Analytics September 2023 stats:**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/f7ec076f-4aee-4351-92b4-91a345d27af6)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/a7d6327d-e071-4118-925b-0ecffd9a82df)

### **Below, you will find tweets in which the content I created was used. We, in collaboration with infaceAi, successfully posted this content on Twitter and shared it with our community on Discord:**

![3](https://github.com/Phala-Network/growth-program/assets/68858747/3f84fd54-6351-47e9-b6e5-9820ef223ad0)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/c2271451-4189-434d-be7f-2a66d1723eea)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/1a9e768e-058f-41d8-bb46-4d7f8b542fd6)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/d5287e9b-ce17-430c-8752-f950816205ca)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/5eff8286-3c57-4544-bd49-86197c8b1f92)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/8aa42379-08b1-42fb-8d59-7ca9e1534673)

### **My additional posts on the Ukrainian Twitter account:**

1) https://x.com/PhalaUkraine/status/1708047809755132233?s=20
2) https://x.com/PhalaUkraine/status/1704830949026886058?s=20
3) https://x.com/PhalaUkraine/status/1704452125261009230?s=20
4) https://x.com/PhalaUkraine/status/1704056163971534946?s=20
5) https://x.com/PhalaUkraine/status/1702992199619608744?s=20

### **Supplementary Tasks:**

During this month, I wrote two extensive and engaging articles about Phala Network and Phala World. Additionally, I created two informative infographics about the technical aspects of Phala Network and its products. These works turned out to be excellent and received a great response from a broad audience on Twitter and among our Phala community users. This time, I made an effort to make these works even better than they were in the previous month. I don't like to stand still. I always strive for continuous improvement

**#CC - I wrote 2 articles about Phala Network and Phala World**

1) https://medium.com/@MrDobby/phala-network-by-the-people-for-the-people-d170297197d2

First, I decided to write an article about Phala Network. My goal was to provide both new Phala users and those already part of the project with an interesting and engaging article about the technical advantages, functionality and potential use cases in the world of WEB3. I used a free writing style based on my knowledge and experience gained during my time with Phala. I attempted to make this article more lively and reader friendly so that everyone who reads it can clearly understand what this project is about and what it can offer them. I believe I succeeded in creating an excellent narrative that received a large and positive response in our community

2) https://medium.com/@MrDobby/phala-world-become-a-survivor-in-the-immersive-world-87467b817f4f

For my second article, I decided to focus on Phala World. I chose to completely revamp the main narrative concept and write about the Phala World universe from my own perspective, how I personally see it, and how I envision it as an active member of the Phala community. I retained all the core ideas that were originally laid out, so the technical meaning remained unchanged. I crafted the story in a simple and engaging format, avoiding complex constructions to make it enjoyable and understandable for all readers. To my surprise, the article was very well received by a wide range of people, both those familiar with Phala World and those who were not. That's when I realized I had done everything right and should continue in this direction. Phala World is a vast and multifaceted universe, and there is much more to write about, which I plan to do in the coming month

**#ART - I created 2 informative infographics about the technical functionality of the Phala ecosystem and how Phat Contract operates in real-world conditions**

1) https://x.com/Dima35109517/status/1707029482463248396?s=20
2) https://x.com/Dima35109517/status/1707367580925661548?s=20

In these infographics, I used a technical tone in the text but tried not to overdo it. I aimed to make each work visually appealing and interesting. I employed two different styles for creating the infographics. Compared to what I did in previous months, I completely revised my approach and will continue to develop this working style while coming up with new and engaging ideas along the way

**#ART - I have created many pictures, memes and images related to Phala Network**

Here are all the links to my Twitter posts that I created this month. Earlier in this report, you could find more detailed information about these tweets. I carefully worked on each image and tweet before posting it to ensure that readers received only relevant and accurate information and could form a positive impression of the Phala Network project. I put in a lot of effort in September and have already continue active activities in October

1) https://x.com/Dima35109517/status/1698671502869106824?s=20
2) https://x.com/Dima35109517/status/1699187174308974697?s=20
3) https://x.com/Dima35109517/status/1699198754606268440?s=20
4) https://x.com/Dima35109517/status/1699927795139223648?s=20
5) https://x.com/Dima35109517/status/1700272048281436434?s=20
6) https://x.com/Dima35109517/status/1701236907944915302?s=20
7) https://x.com/Dima35109517/status/1701536520979554790?s=20
8) https://x.com/Dima35109517/status/1701951587202036158?s=20
9) https://x.com/Dima35109517/status/1702256357317976101?s=20
10) https://x.com/Dima35109517/status/1702688273427030450?s=20
11) https://x.com/Dima35109517/status/1703397529381937264?s=20
12) https://x.com/Dima35109517/status/1703476536609734764?s=20
13) https://x.com/Dima35109517/status/1703844584948699269?s=20
14) https://x.com/Dima35109517/status/1704107473915781414?s=20
15) https://x.com/Dima35109517/status/1704817849787650405?s=20
16) https://x.com/Dima35109517/status/1705179159981359379?s=20
17) https://x.com/Dima35109517/status/1705237617942335650?s=20
18) https://x.com/Dima35109517/status/1706247354817347879?s=20
19) https://x.com/Dima35109517/status/1706333979626951144?s=20
20) https://x.com/Dima35109517/status/1706672846242451478?s=20
21) https://x.com/Dima35109517/status/1707029482463248396?s=20
22) https://x.com/Dima35109517/status/1707304877796253935?s=20
23) https://x.com/Dima35109517/status/1707367580925661548?s=20
24) https://x.com/Dima35109517/status/1707903433666142293?s=20
25) https://x.com/Dima35109517/status/1708223896887919023?s=20

In addition to my Twitter posts and all this information, I also quoted tweets from the official Phala Network accounts, as well as from my fellow ambassadors, helping to promote specific content among my audience. I also didn't miss opportunities to mention Phala in other tweets and show users its multifaceted nature in terms of development and technical innovations. This month, I accomplished a lot and I definitely won't stop here

1) https://x.com/Dima35109517/status/1697590236065280082?s=20
2) https://x.com/Dima35109517/status/1697913697249669220?s=20
3) https://x.com/Dima35109517/status/1698005336131600732?s=20
4) https://x.com/Dima35109517/status/1698319004891250813?s=20
5) https://x.com/Dima35109517/status/1699211785570504775?s=20
6) https://x.com/Dima35109517/status/1699219264547275008?s=20
7) https://x.com/Dima35109517/status/1699390285300511044?s=20
8) https://x.com/Dima35109517/status/1700163811074814126?s=20
9) https://x.com/Dima35109517/status/1700608087160131850?s=20
10) https://x.com/Dima35109517/status/1701270630304281039?s=20
11) https://x.com/Dima35109517/status/1701723976110608528?s=20
12) https://x.com/Dima35109517/status/1702038306416914912?s=20
13) https://x.com/Dima35109517/status/1702228175269269904?s=20
14) https://x.com/Dima35109517/status/1702233045825212495?s=20
15) https://x.com/Dima35109517/status/1703340654078656913?s=20
16) https://x.com/Dima35109517/status/1703352148996571597?s=20
17) https://x.com/Dima35109517/status/1703366317061910807?s=20
18) https://x.com/Dima35109517/status/1703381117460512938?s=20
19) https://x.com/Dima35109517/status/1703713557727072354?s=20
20) https://x.com/Dima35109517/status/1704071746960126014?s=20
21) https://x.com/Dima35109517/status/1704432591137337854?s=20
22) https://x.com/Dima35109517/status/1704443645351305617?s=20
23) https://x.com/Dima35109517/status/1704773837680734625?s=20
24) https://x.com/Dima35109517/status/1704780893871649026?s=20
25) https://x.com/Dima35109517/status/1704784427639824703?s=20
26) https://x.com/Dima35109517/status/1704988744615358635?s=20
27) https://x.com/Dima35109517/status/1705142433372151822?s=20
28) https://x.com/Dima35109517/status/1705346762419097668?s=20
29) https://x.com/Dima35109517/status/1706012572678250974?s=20
30) https://x.com/Dima35109517/status/1706342084188295543?s=20
31) https://x.com/Dima35109517/status/1706577725580791957?s=20
32) https://x.com/Dima35109517/status/1707045759839879240?s=20
33) https://x.com/Dima35109517/status/1707158944257290729?s=20
34) https://x.com/Dima35109517/status/1707352950799016005?s=20
35) https://x.com/Dima35109517/status/1708057525965177165?s=20

### **September Result:**

September turned out to be a very busy month for me, rich in various events and multifaceted in terms of work. I tried to contribute to the Phala project every day through my actions. I've set a great pace of work. I'll keep working and striving to make October even more successful, both for myself and for the Phala ecosystem. 

**Thank you for reading my report
Best regards
Dmitriy**

**Suggested Scores:**
**#CC:** 36/40
**#СМ:** 36/40
**#CC:** 8
**#ART:** 10
**Overall:** 90

**Comment by willphala** [comment]
Phantastic work! A solid improvement from last month. It's great that you have provided a report with so much information too. 

One important piece of constructive feedback is ensure there is no overlap between your department choices and your supplementary task choices. 

E.g. If you're in the CM department you can't additionally earn rewards for the HD supplementary task as they're essentially the same and you'll earn twice the rewards for the same actions. 

I've highlighted this as you've selected CC as a department, as well as CC and ART as supplementary tasks. 

Feel free to reach out to me if you need additional info :)
