### ISSUE TITLE
September 2023 report {infaceAi#5149}

### ISSUE THREAD

**Issue by infaceAi** [Phala-Network/growth-program#271]
PERSONAL INFO
**Amb Rank**: Senior Ambassador
Discord: infaceAi
Telegram:[ @infaceAi](https://t.me/infaceAi)
Twitter: https://twitter.com/infaceAi
PHA Address: 45vo82ABupacJoafLRW8oVWiYyErk9UqZLpfBn8wtE1zcB4M

**Departments** : #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

**Contributions**:
MK & CC -  I promoted PhalaNetwork with its killer features PhatContract on Twitter, Discord and Phala general and local telegram chats.
Also we started 2 Phala local X accounts.
Most of the time I was present in Phala's main telegram chat, answering questions and maintaining a friendly atmosphere.
 
**X analytics** September 2023 stats:

Twitter analytics and https://analytics.twitter.com/user/infaceAi/home

![X Phala](https://github.com/Phala-Network/growth-program/assets/112633185/335f9cca-6e72-4066-af57-23946bb31d93) ![X Phala1](https://github.com/Phala-Network/growth-program/assets/112633185/679212df-d9aa-4db9-b736-41a13d63e486) ![inFace1](https://github.com/Phala-Network/growth-program/assets/112633185/fcc66698-9075-405c-8620-c6ccd7df43c9)
![inFace2](https://github.com/Phala-Network/growth-program/assets/112633185/8372fd8b-3c63-48ed-9e07-d4e0cbed46c5) ![inFace3a](https://github.com/Phala-Network/growth-program/assets/112633185/7381998a-21d8-4645-8e67-e34bdc7ef8f6) ![inFace4a](https://github.com/Phala-Network/growth-program/assets/112633185/e56e8c2e-ab3d-4ac3-859d-ccd543e122e4)
<img width="579" alt="stats Sept23" src="https://github.com/Phala-Network/growth-program/assets/112633185/6f4e92a7-0f0b-428f-993f-8b20de40b6cb">

Phala Ru (local) - Channel link: @phalaworld_ru
https://combot.org/c/1649002165/a

![tg1](https://github.com/Phala-Network/growth-program/assets/112633185/ddc25071-c2b8-4ae2-9b1e-d7d36c4225f4)

**X local**
<img width="1230" alt="Phala Ukraine" src="https://github.com/Phala-Network/growth-program/assets/112633185/0b366ec1-2166-4759-bd6e-e175bbdc7cbd"> <img width="930" alt="phala urk3" src="https://github.com/Phala-Network/growth-program/assets/112633185/b9cfd9e4-3df6-4277-957e-58ba88049742"> <img width="930" alt="phala urk1" src="https://github.com/Phala-Network/growth-program/assets/112633185/4e91faa6-c7fd-4c54-966e-e8004cddea42"> <img width="930" alt="phala urk2" src="https://github.com/Phala-Network/growth-program/assets/112633185/8169f6e2-1ca8-4463-8a8f-7b8fd34b3077"> <img width="930" alt="phala urk" src="https://github.com/Phala-Network/growth-program/assets/112633185/9d7ad9fa-3073-4098-98f7-f5e5c5f6d3d8"> <img width="930" alt="phala urk4" src="https://github.com/Phala-Network/growth-program/assets/112633185/d7552ba1-0dd9-487f-943b-1a5d791f3adc">

**SUPPLEMENTARY TASKS**
**#HD** (or #CM)
Seems it is a thing I am good with, I mean Phala telegram where I do explanations of basic stuff about Phala Network and its products. I notice that other guys are good at Discord support or at keeping Discord conversation (that is a good deal too).

**#CC**  - 3 articles about Phala Network and Phat Contracts translated into Ukrainian.
https://medium.com/@PhalaUkraine/59542793f9a1
https://medium.com/@PhalaUkraine/523fd84f49d8
https://medium.com/@PhalaUkraine/85c89b1a2163

**#ART** - I was trying to be creative and add more attraction to the Phala Ambas program (that I am planning to do this month too).

https://twitter.com/infaceAi/status/1706915576646651960
https://twitter.com/infaceAi/status/1706187027484377384
https://twitter.com/infaceAi/status/1705841495503200697
https://twitter.com/infaceAi/status/1702203020849860812
https://twitter.com/infaceAi/status/1704743510606565769

**SUGGESTED SCORES**
#CC : 31/40
#MK: 40/40
#HD: 10
#CC: 10
#ART: 10
Overall: 91

**This month** was similar to the previous one, but Dmitriy and I started a new X local account that showed very good results. So this is why I rated MK as a max, despite X shows moderate stats (tbh it is a bit strange, but again the message tell that “stats could be incorrect”)
Tori started another local X account. And I hope she can fully concentrate on Phala stuff in the upcoming months. 
I like what Dmitriy has done so far, I wish him further development as community supporter.
Also we are going to make local tg voice chat in October.

**Comment by willphala** [comment]
Great work!
