### ISSUE TITLE
September 2023 Contribution - Gabekoin

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#272]
Telegram : @gabekoin
Discord : gabekoin
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of Aug:
Ambassador

MARKETING (MK): 40/40

Blockchain RIO:
https://x.com/gabekoin/status/1701662205639274661?s=20
https://x.com/gabekoin/status/1702390855095419025?s=20
https://x.com/gabekoin/status/1703017577671192944?s=20

![photo1696447423 (11)](https://github.com/Phala-Network/growth-program/assets/112413448/2f2bdace-78d9-4bd3-8b5b-10e84d5bca0d)
![F6AbdBKWoAAJorG](https://github.com/Phala-Network/growth-program/assets/112413448/fb30888f-86fe-4fab-aaff-3f3d49e1ee34)
![F6AbdBMXUAA7IJL](https://github.com/Phala-Network/growth-program/assets/112413448/13620802-5ad2-40d9-a9dc-e3fc0a4d3d8a)
![F6AbdBNXcAA1s_g](https://github.com/Phala-Network/growth-program/assets/112413448/16ed1b01-fe56-4db8-9ca7-bce230b0cc64)
![photo1696447423 (1)](https://github.com/Phala-Network/growth-program/assets/112413448/2c786618-c4fa-4311-9f8e-08d5c03c3c3c)
![photo1696447423 (5)](https://github.com/Phala-Network/growth-program/assets/112413448/f54eea51-0b83-464c-a264-5464343084b9)

PolygonDevX RIO:
https://x.com/gabekoin/status/1702769479644524563?s=20

![F6Fzz2YXQAAJo8j](https://github.com/Phala-Network/growth-program/assets/112413448/501ba02c-7407-4868-b6c9-4d03718be0d8)
![photo1696447423 (6)](https://github.com/Phala-Network/growth-program/assets/112413448/156a7285-ce3d-4ea4-bf31-7e665901aa79)
![photo1696447423 (7)](https://github.com/Phala-Network/growth-program/assets/112413448/31fd9c8f-55ca-4102-b596-52f0103c3b72)
![photo1696447423 (12)](https://github.com/Phala-Network/growth-program/assets/112413448/840c9f7b-3800-45f9-a2e9-f0f38360c105)
![photo1696447423 (14)](https://github.com/Phala-Network/growth-program/assets/112413448/ada52a6b-e24a-41de-bb68-2bca28bebe8d)
![photo1696447423 (15)](https://github.com/Phala-Network/growth-program/assets/112413448/c86433c9-b83f-4125-a3fb-1969f0805121)
![F6Fzz2SWYAA9jA4](https://github.com/Phala-Network/growth-program/assets/112413448/a9f1589d-7234-4169-87a0-5863d279b1fb)
![F6Fzz2SX0AAr8Tb](https://github.com/Phala-Network/growth-program/assets/112413448/5ed79d44-94ca-47fa-b00f-469361850028)
![F6Fzz2WXcAEdg5F](https://github.com/Phala-Network/growth-program/assets/112413448/306cdcbd-d207-48e6-9d3f-fa7e5ed42436)

PolygonDevX Buenos Aires:
https://x.com/gabekoin/status/1705547037335232836?s=20
https://x.com/gabekoin/status/1705153680624730238?s=20

https://github.com/Phala-Network/growth-program/assets/112413448/3e74c90b-7552-40a4-98d0-7a80225df07b
https://github.com/Phala-Network/growth-program/assets/112413448/c4fa46a5-b3fb-40a8-91a7-7f5b3d79c174
![photo1696447423 (9)](https://github.com/Phala-Network/growth-program/assets/112413448/6bfe29b9-a062-4156-bc1b-43ab9890e92e)
![photo1696447423 (13)](https://github.com/Phala-Network/growth-program/assets/112413448/4fca6c5f-3030-454c-8236-1068b4d249f1)
https://github.com/Phala-Network/growth-program/assets/112413448/3b8e8573-cf0b-4b97-9b4b-e0d664215108
![F6qDBJYXIAEbnRf](https://github.com/Phala-Network/growth-program/assets/112413448/bdefe4db-b93b-4506-b520-a79132eb6e91)
![F6qDBJZXgAAALTG](https://github.com/Phala-Network/growth-program/assets/112413448/6075db18-f5b8-4443-a530-9a9011ccadcf)

Twitter Spaces 1:
![spaces 1](https://github.com/Phala-Network/growth-program/assets/112413448/ad4dd9b8-2756-44aa-93a1-1047e51d0b00)
![spaces 11](https://github.com/Phala-Network/growth-program/assets/112413448/6df8423b-adaa-4b7a-8da0-9149b6e8f003)

Twitter Spaces 2:
![Spaces 2](https://github.com/Phala-Network/growth-program/assets/112413448/a4182e80-a7f3-421f-9f36-b03cd86b6f1b)
![Spaces 22](https://github.com/Phala-Network/growth-program/assets/112413448/f3b6e955-a84e-44f3-9259-038ae049fb33)

Threads created:
Off-Chain Computation PT:
https://twitter.com/phalaportugues/status/1697602271981285885?s=20

Off-Chain Computation:
https://twitter.com/gabekoin/status/1699882773417205919?s=20

Omnichain:
https://twitter.com/phalaportugues/status/1698705354568171640

Interview:
https://x.com/gabekoin/status/1707029011979735531?s=20

Event:
https://x.com/gabekoin/status/1705547037335232836?s=20

https://x.com/gabekoin/status/1705298416484368691?s=20

https://x.com/gabekoin/status/1705153680624730238?s=20

https://x.com/gabekoin/status/1702769479644524563?s=20

Threads Translated:
Hackathon Announce:
https://twitter.com/phalaportugues/status/1698785028732256570

Ink Partnership:
https://twitter.com/phalaportugues/status/1701308653188329480

Tweets (RT & LIKE):
https://twitter.com/Brushfam_io/status/1697935223382499416?s=20
https://twitter.com/PhalaNetwork/status/1697995187472257082?s=20
https://twitter.com/marvin_tong/status/1698725696380792869?s=20
https://twitter.com/marvin_tong/status/1699085474231685626?s=20
https://twitter.com/PhalaNetwork/status/1700493728840819047?s=20
https://www.linkedin.com/posts/zora-meckbach_berlinblockchainweek-activity-7106950338674348034-qA5a?utm_source=share&utm_medium=member_desktop
https://twitter.com/PhalaNetwork/status/1704146571158327692
https://x.com/PhalaNetwork/status/1704880904563204537?s=20
https://x.com/PhalaNetwork/status/1704146571158327692?s=20
https://twitter.com/0xPolygonDevs/status/1706761825616896260?t=goSotT1wd0tNg5CWkMc1uw&s=19
https://x.com/PhalaNetwork/status/1704880904563204537?s=20
https://x.com/PhalaNetwork/status/1704756536428413256?s=20

![image](https://github.com/Phala-Network/growth-program/assets/112413448/e9af926a-1933-453a-bdb4-f2b5b56a49ce)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/88bdb25b-a723-4a2b-b7b0-131704a3ab95)

COMMUNITY (CM): 34/40
![image](https://github.com/Phala-Network/growth-program/assets/112413448/7a2f424b-af58-4fbd-8eb2-cd4a92ff2cb5)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/88ebe635-b49c-4bb9-a1b6-63d8ce3fec2d)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/417a24ef-51ef-43ca-9cc6-328cbe1a42c0)

![1](https://github.com/Phala-Network/growth-program/assets/112413448/d10dfa50-aca2-43a4-9a69-d214ed38850c)
![2](https://github.com/Phala-Network/growth-program/assets/112413448/f09c4a7a-1356-480c-9c67-6b367d972b59)
![3](https://github.com/Phala-Network/growth-program/assets/112413448/9ad2ca54-787c-4cfd-8190-638be4733c60)
![4](https://github.com/Phala-Network/growth-program/assets/112413448/19bbcfa0-b46e-44d1-b431-2ad5849d55ed)
![5](https://github.com/Phala-Network/growth-program/assets/112413448/9ee32465-c3fe-4f7a-9cbe-2eebf3d89c04)
![6](https://github.com/Phala-Network/growth-program/assets/112413448/c7eaa824-4483-44bb-8e84-9ed6eb2ee39f)
![7](https://github.com/Phala-Network/growth-program/assets/112413448/3d726e58-afee-45ab-968b-6d3bc0bcf089)
![8](https://github.com/Phala-Network/growth-program/assets/112413448/b5db9b75-929a-46b3-84ed-0bd9363849c1)
![9](https://github.com/Phala-Network/growth-program/assets/112413448/4a3a694b-7e11-4021-a7d8-75a8b653aa61)

Supplementary: ART & CC (20/20)

ART: 10/10
Omnichain:
https://x.com/phalaportugues/status/1704153809788768488?s=20

Trading Bot:
https://x.com/phalaportugues/status/1704951102733464060?s=20

Trading Bot 2:
https://x.com/phalaportugues/status/1706051319893520473?s=20

Segurança:
https://x.com/phalaportugues/status/1706735907309830607?s=20

Phat e offchain:
https://x.com/phalaportugues/status/1708115796793421826?s=20

CC: 10/10

Articles translated:
Phala Monthly:
https://medium.com/@phalaptbr/boletim-mensal-phala-agosto-de-2023-49662b2c3341

Crypto Trading Bot:
https://medium.com/@phalaptbr/phat-contract-redefinindo-a-seguran%C3%A7a-do-trading-bot-3b9fd4edaa5d

LINKEDIN POSTS CREATED:
Developer DAO Winners:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-lensapi-oracle-challenge-activity-7104529231153405952-mRGQ?utm_source=share&utm_medium=member_desktop

LINKEDIN RT:
https://www.linkedin.com/posts/zora-meckbach_berlinblockchainweek-activity-7106950338674348034-qA5a?utm_source=share&utm_medium=member_desktop

PHALA BUENOS AIRES:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_gabekoin-on-x-activity-7112498125382049793-C22l?utm_source=share&utm_medium=member_desktop

Phala Buenos Aires 2:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phatcontract-activity-7112498641012965376-S8Nh?utm_source=share&utm_medium=member_desktop

Phala RIO:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phatcontract-activity-7112499207835385857-yUql?utm_source=share&utm_medium=member_desktop

Phala Block RIO:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phatcontract-activity-7112499613772713984-jfKt?utm_source=share&utm_medium=member_desktop

Suggested scores:
[MK] 40/40
This month was phantastic, I'm totatlly happy about it. We managed to attend 3 events representing Phala and the opportunity to speech about PhatContract to many people and we made some interesing contacts that we will try to onboard in Phala.
I've noticed a huge increase of impressions and I will keep working on that.

No bad points, we hosted 2 spaces to tell everyone about the events and last updates.
For next month keep the good work and try to reach more people

[CM] 34/40
This month was less active than the last one, but we kept the good energy and enganging with our community.
Brasilian community is growing and we are happy about that.
Next month try to bring more exclusive content.

[ART] 10/10
I've produced 5 Infographics with useful information and we had great reach.

[CC] 10/10
I've translated the main articles from our blog and created many posts in Linkedin that had good impressions

Overall suggested score: 94/100.

By far the best month ever! So happy about it, I'm already missing it. 
Great times ahead

For the next month: Do better

**Comment by willphala** [comment]
Smashed it bro!!! Keep it up 🫶
