### ISSUE TITLE
September 2023 Contributions -Coinisan

### ISSUE THREAD

**Issue by coinisan** [Phala-Network/growth-program#273]
- Amb rank: Candidate
- Telegram Username: Coinisan
- Twitter : https://twitter.com/Coinisan
- PHA Wallet Address: 3zwt5nXfYZYcZMVHbdB72QPc64TfkG2DrUyk5ds7vuCemWwj

Hello, I am Coinisan. I joined Phala 45 days ago. In my first days, I explained to my community what Phala is and what we can do in the Phala ecosystem, in the simplest way and from scratch. I supported Phala Turkey and Phala posts. I could not send a report because 15 days had passed since I became a member last month. It will be a 45-day report.
Thanks

Phala Türkiye
Twitter:https://twitter.com/PhalaTurkiye
Telegram:https://t.me/PhalaTurkce
Medium: https://medium.com/@enesfaruk.sahin01 

🌟Phala Ambassador Announcement
https://x.com/Coinisan/status/1691746394304897305?s=20

<img width="300" alt="1" src="https://github.com/Phala-Network/growth-program/assets/106899931/529a01e5-d4b1-443b-a847-83adfa356dd0">

🌟What is Phala?
https://x.com/Coinisan/status/1692606800477012411?s=20

<img width="283" alt="2" src="https://github.com/Phala-Network/growth-program/assets/106899931/2a16d2de-91a2-4ae0-b338-a2edbdecf304">

🌟Phala Wallet Setup 1
https://x.com/Coinisan/status/1694310797009117322?s=20

<img width="313" alt="3" src="https://github.com/Phala-Network/growth-program/assets/106899931/f9869777-7086-4e5d-9bb3-5796267b8dd5">

🌟Phala Wallet Setup 2
https://x.com/Coinisan/status/1694952913603326318?s=20
<img width="308" alt="4" src="https://github.com/Phala-Network/growth-program/assets/106899931/0c863691-b4fa-4118-be12-e9629f869bfa">

🌟Phala TR Weekly update QRT
https://x.com/Coinisan/status/1695871179326705893?s=20
<img width="311" alt="5" src="https://github.com/Phala-Network/growth-program/assets/106899931/6975a94e-4877-46fa-b89e-417bae7abfa9">

🌟Phala Wallet Setup 3
https://x.com/Coinisan/status/1696508291440902257?s=20
<img width="317" alt="6" src="https://github.com/Phala-Network/growth-program/assets/106899931/1adff504-e615-4db3-a9be-23806406a87e">

🌟Phala Network user guide 1/1 (+Phala TR Medium)
https://x.com/Coinisan/status/1698452509805695008?s=20
<img width="313" alt="7" src="https://github.com/Phala-Network/growth-program/assets/106899931/e0fe703d-f013-4a27-b65e-880bc5217bff">

🌟Phala Network user guide 1/2 (+Phala TR Medium)
https://x.com/Coinisan/status/1699180152834417045?s=20
<img width="308" alt="8" src="https://github.com/Phala-Network/growth-program/assets/106899931/277570b0-2d97-43f4-9c8d-5ac8bfad31e5">

🌟 Phala Network Hackathon QRT
https://x.com/Coinisan/status/1700582555718758507?s=20
<img width="319" alt="9" src="https://github.com/Phala-Network/growth-program/assets/106899931/6ed1e005-d401-493e-8dba-90536a0ba1ed">

🌟Phala Network user guide 2 (+Phala TR Medium)
https://x.com/Coinisan/status/1701701437615747235?s=20
<img width="317" alt="10" src="https://github.com/Phala-Network/growth-program/assets/106899931/cbf280a2-60a3-41e7-8347-4b2bd62688c2">

🌟Phala Weekly update QRT
https://x.com/Coinisan/status/1704226004414107835?s=20
<img width="321" alt="11" src="https://github.com/Phala-Network/growth-program/assets/106899931/829e43d2-15aa-4c4d-b24b-03896d5428a4">

🌟Phala Network Scam Alert QRT
https://x.com/Coinisan/status/1704762315877331194?s=20
<img width="296" alt="12" src="https://github.com/Phala-Network/growth-program/assets/106899931/78a63da0-ae74-4344-a15f-ac625ad1dd1f">

🌟Phala TR QRT
https://x.com/Coinisan/status/1706761116674933163?s=20
<img width="314" alt="13" src="https://github.com/Phala-Network/growth-program/assets/106899931/5f8884cb-499f-4976-9014-3277aadcff57">

🌟Phala TR QRT
https://x.com/Coinisan/status/1708061937878142976?s=20
<img width="309" alt="14" src="https://github.com/Phala-Network/growth-program/assets/106899931/02eeaec2-4c39-4bca-bbe9-c8242a5ebd39">

Good point:
I increased its engagement by producing regular content and contributing to Phala accounts on Twitter.

Bad point:
I could not provide many users as followers to the Telegram and Twitter community.

CM:
Although our Turkish community is small at the moment, we are in a good situation in terms of interaction. Many new people have gotten to know the Phala project and continue to get to know it.

CC
I think my score should be high because my content is of high quality and interaction is high

Scores:
*CC: 40
*MK: 40
*CC: 10

**Comment by willphala** [comment]
A great start! Congratulations. Here is some constructive feedback: 

1) Ensure there is no overlap between your department choices and your supplementary task choices. 

E.g. If you're in the CM department you can't additionally earn rewards for the HD supplementary task as they're essentially the same and you'll earn twice the rewards for the same actions. 

2) While it's great to focus the majority of your efforts on the new Turkish community, you also need to engage with our global English community too to earn 90+ points. 

If you need further support please send me a DM. We're stoked that you're a member of our amb Phamily and I look forward to seeing your next report 👏
