### ISSUE TITLE
September 2023 Contributions - {Rom1.io#5329}

### ISSUE THREAD

**Issue by Rom1io** [Phala-Network/growth-program#275]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/63704652/216827308-dd6a24be-5517-4e09-9c0e-c65a763aca3b.png">

Amb Rank : Ambassador
Telegram Username: https://t.me/Imo_999
Discord Username: Rom1.io#5329
Twitter Username: https://twitter.com/RCajina
PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q

Departments : #CC & #MK

**Contributions:**

Hello, it's been a quiet month for me, but I've still contributed to the community, doing a few translations, threads.

![image](https://user-images.githubusercontent.com/63704652/222117520-bf30a95b-18be-44e8-9e0f-aad3e09f879c.png)

Twitter analytics: [Here](https://analytics.twitter.com/user/RCajina/home)

![image](https://github.com/Phala-Network/growth-program/assets/63704652/d4dc6275-76e9-4c62-90e1-19e2372c4f94)

Tweet 1 : [Here](https://twitter.com/RCajina/status/1704754938822209672)
Tweet 2 : [Here](https://twitter.com/RCajina/status/1699367367220793344)

![image](https://user-images.githubusercontent.com/63704652/222134127-67fe6ec1-f49c-43d7-a391-f681d8d5a87e.png)

Here are the translations I made with a total of **2852** words  : 

- [Comprendre l’importance et les nuances d’un Smart Contract vérifié](https://medium.com/phala-fran%C3%A7ais/comprendre-limportance-et-les-nuances-d-un-smart-contract-v%C3%A9rifi%C3%A9-c7e324fabcbc)
- [La nouvelle aventure de PhalaWorld](https://medium.com/phala-fran%C3%A7ais/la-nouvelle-aventure-de-phalaworld-3814d0a11fc)
- [Newsletter mensuelle Phala : Août 2023](https://medium.com/phala-fran%C3%A7ais/newsletter-mensuelle-phala-ao%C3%BBt-2023-c4fd98c9a6c1) 

![image](https://user-images.githubusercontent.com/63704652/222134855-7eff0b13-3d74-4aad-a848-63d581a00c44.png)

## SUGGESTED SCORES
#CC: 30/40
#MK: 20/40

Other:
#CC: 10/10

Overall : 60

***Quote*** : "Success is not final, failure is not fatal. It is the courage to go on that counts" - Winston Churchill.

**Comment by willphala** [comment]
Good work! I love the quotes 😎 Please keep in mind there can't be overlap between departments and supplementary tasks e.g. CC and CC.
