### ISSUE TITLE
September 2023 Contributions - {TIONEB}

### ISSUE THREAD

**Issue by tionebDotsamapha** [Phala-Network/growth-program#276]
Telegram Username: [tioneb](https://t.me/tioneb)
Discord Username: tioneb#4951
Twitter Username: [tioneb_DotSama₱ha](https://twitter.com/tioneb442)
PHA Wallet Address: 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7

Departments : #CM & #MK
Department Score Weight : 50% & 50%

I'm back in the game after a long 2-month break.

# Community Management
## Telegram : 
<img width="767" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/85cfd905-f171-4b0e-8019-555d8b32b228">
<img width="745" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/899fd3ee-be5a-468d-9fd4-2f12f17dfac9">

## Discord :
<img width="746" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/b4510568-d34f-4850-b212-bbc2c298a9ee">

## Youtube :
<img width="1147" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/5eaf525a-f179-4afb-8bba-cd31a7b91754">

## Twitter :
<img width="448" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/39a68bc1-9ace-4044-bc97-f4f10af9f355">

# Marketing

In September, after discussions on Twitter, I obtained the creation of two discussion threads by two influencers. 
I'm happy with the reach these threads have had.

## @muaddibeth (329 followers)
https://twitter.com/muaddibeth/status/1703722050345382326
https://x.com/muaddibeth/status/1703722948983505300?s=20
<img width="397" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/ad2e6348-ce13-4e07-bbba-9c4438de2594">

## @Altcoins France (1 884 followers)
https://twitter.com/AltcoinsFrance/status/1707428494962024959
<img width="449" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/dbc01b96-d9f3-487d-b555-7a881b849d3f">

# CP
I took part in Gxdoyle's appeal to ambassadors who share computing power to run tests on their own machines. 
<img width="823" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/2fab4169-b7d2-4d8a-838c-523e2ec4bb08">

# BD
I'm in touch with @willphala to try and organize a meeting between the DEV team and an existing polkadot ecosystem project that wants to improve its web3 approach thanks to Phala.

CM : 40
MK : 40
CP : 5
BD : 10

Total : 95

**Comment by willphala** [comment]
Welcome home Pham 🫶
