### ISSUE TITLE
September 2023 Contributions - {defiguy}

### ISSUE THREAD

**Issue by astardefi** [Phala-Network/growth-program#278]
## Departments

Telegram Username: @defiguy2022

AMB Rank: Candidate Ambassador

Discord Username: defiguy

Twitter Username: @defiguy22

PHA Wallet Address: 44PTq2ZCxXxPM3FYubiPtMw53WCXNdXUfNDnCE6c7wFixMbB

Departments: #CC / #CM

I helped spread information about Phala Network on Twitter, reaching thousands of users. I also created content for a more specialized audience on LinkedIn using infographics. Additionally, I established an account for the Brazilian community on TikTok.

I provide weekly updates on my YouTube channel https://www.youtube.com/watch?v=z577xf6aT70 about the Polkadot ecosystem and have a segment dedicated to sharing updates on Phala Network. **Average views close to 300**

# CC 
![Screen Shot 2023-10-05 at 18 44 15](https://github.com/Phala-Network/growth-program/assets/104277195/23afac6d-4787-45bd-98e6-f5d70e9d5e04)

Livestream - Phala Segment (1) - start at minute 52:02
https://youtube.com/live/Rfy3MtI7QAQ

Livestream - Phala Segment (2) - start at minute 56:04
https://www.youtube.com/watch?v=5qEmrUOpKTE

Livestream - Phala Segment (3) - start at minute 55:04
https://youtube.com/live/vyOXB9xDZck

# HD and CM
# Question about Phala on Telegram
![Screen Shot 2023-10-05 at 15 21 47](https://github.com/Phala-Network/growth-program/assets/104277195/5d6e6014-c834-49cf-973f-7331d9e5ce14)

# Question about Phala on Instagram (big brazilian youtuber)
![Screen Shot 2023-10-05 at 15 23 46](https://github.com/Phala-Network/growth-program/assets/104277195/9e66fc96-d519-432f-9329-57d840f710d0)

# User wants a fundamental analysis of Phala
![Screen Shot 2023-10-05 at 15 25 53](https://github.com/Phala-Network/growth-program/assets/104277195/092a3ad5-c985-4477-809b-2f8d61c2b48e)

# Youtuber and well know brazilian crypto analyst wants to schedule a talk about Phala
![Screen Shot 2023-10-05 at 15 32 52](https://github.com/Phala-Network/growth-program/assets/104277195/758116b8-943c-4d72-882c-e3f993b22ce8)

# CC Retweets
![Screen Shot 2023-10-05 at 18 58 34](https://github.com/Phala-Network/growth-program/assets/104277195/c6ce8c76-6711-4569-83fe-339f888e50dd)
https://twitter.com/developer_dao/status/1707811049011925196

![Screen Shot 2023-10-05 at 18 59 10](https://github.com/Phala-Network/growth-program/assets/104277195/2e67673c-1940-43d0-8074-a61aedff5b21)
https://twitter.com/marvin_tong/status/1708201692561588703

![Screen Shot 2023-10-05 at 18 59 57](https://github.com/Phala-Network/growth-program/assets/104277195/cef22201-1372-4385-bec7-00ef6a762b3f)
https://twitter.com/phalaportugues/status/1708116794911629675

https://twitter.com/marvin_tong/status/1705019580362482003

https://twitter.com/PhalaNetwork/status/1704880904563204537

https://twitter.com/PhalaNetwork/status/1704146571158327692

https://twitter.com/PhalaNetwork/status/1701258723568566648

# ART

![Phala Network - Introduction](https://github.com/Phala-Network/growth-program/assets/104277195/2e608a6c-7043-4aeb-943d-d158439f201c)
#CC: 30/40

#СМ: 10/40

#CC: 10

#ART: 5

#HD : 5

Overall: 65

**Comment by willphala** [comment]
Solid work Pham! Two piece of constructive feedback: 

1) When picking supplementary tasks, you can't be rewarded for them when there is an overlap with your departments. Otherwise you would be getting rewarded twice for the same tracks of work. For example, the CC department includes all content creation activities, so picking ART as a supplementary task is redundant. 

The supplementary tasks are available to provide flexibility and an earning opportunity for those who want to participate outside of their departments.

2) When creating graphics please use Phala's modern colour scheme of white, green, black and purple. Please ping me if you need any support with this :)
