### ISSUE TITLE
September 2023 Contributions -gatorkorps

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#280]
Hey welcome here :)

TG: https://t.me/Gatorkorps
Discord: Gatorkorps
Twitter: @gk18_dog
PHA Adresse : 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV

Contributions:

MK & PM

Promotion of Phala on My accoutn and the Phala Fr account

![image](https://github.com/Phala-Network/growth-program/assets/82824139/2f3c5a25-c9ce-4c27-b8cc-ba7170b74988)

https://twitter.com/gk18_dog/status/1703369134786920883
https://twitter.com/gk18_dog/status/1702732921625317438

https://twitter.com/phala_fr/status/1707059209894862982

![image](https://github.com/Phala-Network/growth-program/assets/82824139/56325126-9748-4439-ace2-de91eca8f869)

https://twitter.com/gk18_dog/status/1707621320316399975
https://twitter.com/gk18_dog/status/1703784141685194778

A translated article:

https://medium.com/phala-fran%C3%A7ais/phat-contract-red%C3%A9finition-de-la-s%C3%A9curit%C3%A9-des-bots-de-trading-ba3fbf99a88c

Managing the Phala FR twitter account and Phala FR TG
Quiet activity this month
Daily presence on TG, Discord, international channels, and FR channels delete message from individual when inapropriate behaviour

CC: 30
MK 30
Others 20

70

Thanks and have a great day !

**Comment by willphala** [comment]
Good work. I hope the family is well! 🫶
