### ISSUE TITLE
September 2023 Contributions - (johnrhodel#8162)

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#281]
Telegram Username: https://t.me/parachainboy
Discord Username: johnrhodel#8162
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

CC : 40/40

Translated Articles Portuguese/Filipino and Slides for Devx Global Tour Portuguese/Spanish

Portuguese:
https://medium.com/@phalaptbr/phat-contract-redefinindo-a-seguran%C3%A7a-do-trading-bot-3b9fd4edaa5d -Translated W/Gabe
https://medium.com/@phalaptbr/boletim-mensal-phala-agosto-de-2023-49662b2c3341 - Reviewed article

Filipino:

https://polkaverse.com/11194/kontrata-ng-phat-muling-pagtukoy-sa-seguridad-ng-trading-39417
https://polkaverse.com/11194/panimula-sa-mga-gawain-sa-pag-compute-para-sa-mga-manggagawa-39180
https://polkaverse.com/11194/buwanang-newsletter-ng-phala-agosto-2023-phala-network-39416

Portuguese Devx Presentation:
https://docs.google.com/presentation/d/1xi1qnGNHwxMtx6SOOYcAhyIHbxd0FHjQGjd5_6QJ3Xs/edit?usp=sharing

Spanish Devx Presentation:
https://docs.google.com/presentation/d/11Duc7eY4vsavZmV_A_58FrH-kijBa8JaA-wKFMxoVPg/edit?usp=sharing 

Slides Class Keep Bored:
![IMG_2951](https://github.com/Phala-Network/growth-program/assets/77474076/19122807-246d-4f95-92cf-8bf23d6464c4)

MK(40/40)
![twitter john](https://github.com/Phala-Network/growth-program/assets/77474076/a689181e-1349-41fe-af76-6b144f90c869)

Twt, RTW and Like:
https://twitter.com/parachainboy/status/1702792676565807168
https://twitter.com/parachainboy/status/1704978868946293230
https://twitter.com/parachainboy/status/1705297552919183401
https://twitter.com/parachainboy/status/1705737663532122244
https://twitter.com/PhalaNetwork/status/1704146571158327692
https://x.com/PhalaNetwork/status/1704880904563204537?s=20
https://x.com/PhalaNetwork/status/1704146571158327692?s=20
https://twitter.com/0xPolygonDevs/status/1706761825616896260?t=goSotT1wd0tNg5CWkMc1uw&s=19
https://x.com/PhalaNetwork/status/1704880904563204537?s=20
https://x.com/PhalaNetwork/status/1704756536428413256?s=20

Spaces:
https://twitter.com/phalaportugues/status/1707036553829114044
https://twitter.com/phalaportugues/status/1708116794911629675

Events:

Keep Bored Class Polkadot and Parachains:
![image](https://github.com/Phala-Network/growth-program/assets/77474076/1668e56b-15cf-4b84-835f-c4bd03de440b)
![IMG_2951](https://github.com/Phala-Network/growth-program/assets/77474076/74874f3c-8739-48ef-95d0-68db81af4b7a)

Blockchain Rio Presentantion Main stage about Polkadot and Phala:
![F5_rhLsaAAEN1kf](https://github.com/Phala-Network/growth-program/assets/77474076/0a55cec4-c677-4265-a56a-c8bed3d940e5)

Blockchain Rio Presentation Side Stage about Phala and polkadot usecases:
![F52ITfBWIAAl6-l](https://github.com/Phala-Network/growth-program/assets/77474076/8bc3aa10-e933-46a2-bd92-14fd9a7ebd5a)

Blockchain Rio Side event Phala usecases with Gabe:
![F5_shRKbsAA-MGw](https://github.com/Phala-Network/growth-program/assets/77474076/772bc05b-3bff-4adf-9842-b9137c1a68ec)
![IMG_3214](https://github.com/Phala-Network/growth-program/assets/77474076/e97b1fa7-ac55-4e76-af06-31d989cbb947)

Devx Global Tour Rio:
![IMG_3329](https://github.com/Phala-Network/growth-program/assets/77474076/6b4b8239-87ce-46f2-818b-9f540aad83c2)
![IMG_3331](https://github.com/Phala-Network/growth-program/assets/77474076/5cc0e763-cb13-49e4-a94b-cc027671d20a)
![IMG_3337](https://github.com/Phala-Network/growth-program/assets/77474076/a033b527-d44b-443e-a0ae-5fe8848d3fb1)
![IMG_3343](https://github.com/Phala-Network/growth-program/assets/77474076/c751a2a9-6dbb-4726-90f1-6e8063d2580b)
![IMG_3346](https://github.com/Phala-Network/growth-program/assets/77474076/7fc06a56-ae09-4b17-be69-2a0e916a4436)
![IMG_3349](https://github.com/Phala-Network/growth-program/assets/77474076/28442750-c250-45da-a7dc-95135a686a42)

Devx Global Tour Buenos Aires:
![F6qDBJYXIAEbnRf](https://github.com/Phala-Network/growth-program/assets/77474076/b5e89f1a-1a99-43de-a33f-2c1583025a2c)
![F6qDBJZXgAAALTG](https://github.com/Phala-Network/growth-program/assets/77474076/867d4d4f-bb1b-4d52-a030-3087e631f2e4)
![F6v_W1KXkAAPtAB](https://github.com/Phala-Network/growth-program/assets/77474076/4dae50ae-a17e-4850-a97c-42fa95335672)

Extra Points:
HD (10/10):
![jack](https://github.com/Phala-Network/growth-program/assets/77474076/43cc5f09-b4ba-4c9b-a1bb-e6ee9acf7331)
![hehehe](https://github.com/Phala-Network/growth-program/assets/77474076/24572b0e-d510-4714-a774-d71d4554275f)
![photo_2023-10-04_12-09-33](https://github.com/Phala-Network/growth-program/assets/77474076/0f3a4783-903f-423f-8f1f-5be2330c6ae0)
![photo_2023-10-04_10-16-41](https://github.com/Phala-Network/growth-program/assets/77474076/5b3ab7b7-9181-40e5-8e94-2aa4a69c4a98)
![photo_2023-10-02_12-29-19](https://github.com/Phala-Network/growth-program/assets/77474076/d64d9da5-fd32-4073-bd27-2ce20256ddf2)
![photo_2023-10-01_10-19-38](https://github.com/Phala-Network/growth-program/assets/77474076/893ae224-9421-4042-90a2-64aabeea151d)
![photo_2023-10-01_10-14-24](https://github.com/Phala-Network/growth-program/assets/77474076/2581d957-8879-4945-80d8-0f25a459fc00)
![photo_2023-10-01_10-06-53](https://github.com/Phala-Network/growth-program/assets/77474076/0724cd7e-e449-444b-b39d-9348b64c0bae)

ART(10/10):

![1](https://github.com/Phala-Network/growth-program/assets/77474076/ba6e0a1f-e226-4272-9a1a-fcb9ba4a283f)
![2](https://github.com/Phala-Network/growth-program/assets/77474076/245bae75-def9-4ab4-b052-74f0a0a12b5c)
![3](https://github.com/Phala-Network/growth-program/assets/77474076/e1956289-a7ad-47a6-b3df-3cc06b6f0714)
![4](https://github.com/Phala-Network/growth-program/assets/77474076/84a4728d-5052-4839-bc27-243b6bf86185)

This month was a crazy and very productive month, Gabe and me managed to spread the word about Phala Network in Brazil at events and in Buenos Aires in Argentina, I believe it was one of the most productive months I had on the project, I hope something in around 95 Points for all contributions to the Phala Network ecosystem!

Keep Building LFG

**Comment by willphala** [comment]
Amazing work. Congrats and well deserved!
