### ISSUE TITLE
October 2023 Contributions - {Janema#7205}

### ISSUE THREAD

**Issue by Janemake** [Phala-Network/growth-program#291]
Telegram Username: @Janemake
Discord Username: @janema
Twitter Username: https://twitter.com/JanemakeCrypto
PHA Wallet Address: 41owbtwKf7dfZxEfdfhRfey4uGLkg8V9iLG74ZhTQnMnsAwA

**Departments** : #CP & #CM
**Department Score Weight** : 25% & 75%

**Contributions**
### **========================== 1. MANDATORY TASKS ==============================**
**1.1 CM** 
The main activities have been:
- help on the issues related to different activities on Phala
- Remove scam contents, alert on scam contents, ban scam accounts from Telegram
I was available to help and guide community members when needed. 

![image](https://github.com/Janemake/govBot-squid/assets/58589481/59baf4ca-c8e4-4766-bea9-32a83ea13400)

**1.2 CP**
During this month, i have implemented a squid for stakepool cumulative rewards following a question from a community member. 
For a dedicated stakepool, with this squid, the owner could track the cumulative rewards of his pool since the creation of the pool. It was mainly inspired from the computation squid used for the phala app.
![Capture d’écran du 2023-10-31 10-18-12](https://github.com/Janemake/govBot-squid/assets/58589481/5d4efecf-42b7-4645-a626-8de4aa78dd4e)

Source code github link available [here](https://github.com/Janemake/stakepool-rewards)
![image](https://github.com/Janemake/govBot-squid/assets/58589481/c69aad8a-a2e8-4898-8ede-2998aa5d4067)

### **========================== 2. SUPPLEMENTARY TASKS ==========================**
2.1 PM
- I shared some of the Phala related thread and news on Twitter to Promote events and products related to Phala.
![image](https://github.com/Janemake/govBot-squid/assets/58589481/0b5d0e46-dc2d-4c24-a110-735a0d6614a3)

### ========================== 3. SUGGESTED SCORES ==============================
#CM : 28/40 => with CM weight of 75% in the MD Tasks: 42
#CP :  25/40  => with CP weight of 25% in the MD Tasks: 13
with the split 75% CM / 25% CP and the suggested score above, the MD tasks suggested score is 55/80

#PM : 10

Overall : 65

**Comment by willphala** [comment]
👏
