### ISSUE TITLE
October 2023 Contribution - Leo

### ISSUE THREAD

**Issue by LeoNeurolanche** [Phala-Network/growth-program#292]
Hello, I am Leo. This month was my fifth month in the Phala Network Ambassador program. During this month, I had the opportunity to translate various sections of the Whitepaper into Turkish, and create to how phat contract developing guide. Personal Information Telegram: @neurolauncher Twitter : https://twitter.com/neurolauncher Personal Medium: https://medium.com/@enesfaruksahin LinkedIn: https://www.linkedin.com/in/enesfaruksahin Phala Network Turkey Medium: https://medium.com/@enesfaruk.sahin01 Phala Network turkey Twitter account: https://twitter.com/phalaturkiye?s=21&t=ISh07fvjMqpmUg40w5HqBg  Pha Walled Adress: 46HWuhMvjTLqWRjRETUnnFC6pmUimvpkKByCgUZSKwTREFku Turkey Telegram: https://t.me/PhalaTurkce

**Content Creation ** November was fifth month as an ambassador in the Phala Network. During third month, I tried to contribute by creating various content for my own community and the Phala Network family. I will now share with you the content I produced this month.Firstly I want to my Twitter activity: 372k ![image](https://github.com/Phala-Network/growth-program/assets/126774982/69b0313e-9b52-4af4-b784-3bfea346615a)view.

https://twitter.com/phalaturkiye/status/1712121306613703149?s=46&t=ISh07fvjMqpmUg40w5HqBg

https://twitter.com/phalaturkiye/status/1713900887842705488?s=46&t=ISh07fvjMqpmUg40w5HqBg

https://twitter.com/phalaturkiye/status/1716557647502004492?s=46&t=ISh07fvjMqpmUg40w5HqBg

https://twitter.com/phalaturkiye/status/1717170854314860822?s=46&t=ISh07fvjMqpmUg40w5HqBg

https://twitter.com/phalaturkiye/status/1717601842522157169?s=46&t=ISh07fvjMqpmUg40w5HqBg

https://twitter.com/phalaturkiye/status/1717966908379554121?s=46&t=ISh07fvjMqpmUg40w5HqBg

https://twitter.com/phalaturkiye/status/1718307328246575594?s=46&t=ISh07fvjMqpmUg40w5HqBg

https://twitter.com/phalaturkiye/status/1718697141835571236?s=46&t=ISh07fvjMqpmUg40w5HqBg

https://twitter.com/phalaturkiye/status/1719033884757594548?s=46&t=ISh07fvjMqpmUg40w5HqBg

**The Content Creator: 800 world**

https://medium.com/@enesfaruk.sahin01/do%C4%9Frulanm%C4%B1%C5%9F-ak%C4%B1ll%C4%B1-kontrat%C4%B1n-%C3%B6nemi-ve-i%CC%87nceliklerini-a%C3%A7%C4%B1klamak-6f6cbc5b458a

CM
I tried to increase our Telegram community with regular posts by opening the Phala Network Turkey Twitter account. Although we currently have a small user base, I am striving to answer users' questions and grow the Turkish community by creating consistent content. Additionally, I am already working on building an encyclopedia for the users.

Good Point:
Accounts have been activated for our Turkish community. Preparations have started to assist the community by creating an encyclopedia.

Bad Point:
We are currently in a bear market during the crypto season, we have a limited community.

CC/ 20-40

We published regular content on the Türkiye channel.

CM/ 25-40
Our Twitter account opened and I tried to reach more people.

CC(+800 world task)/ 5-10
I make medium article more than 800 world.

**Comment by willphala** [comment]
Keep up the good work! 🙌
