### ISSUE TITLE
October 2023 Contributions- {the_scarlet_thread}

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#294]
Amb Rank: Ambassador
Telegram Username: @Scarlet_Thr
Discord Username: @the_scarlet_thread
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

### MANDATORY 
**CONTENT CREATION**
**_Article_**
I wrote an article discussing the existing Phat Contracts and Phat Contract 2.0
https://medium.com/@TheScarletThread/what-is-a-phat-contract-5f9d48362f13

Created the following graphics for the article:
![png_20231015_215744_0000](https://github.com/Phala-Network/growth-program/assets/99918790/6589c053-ea48-409b-8842-cdf07b49a936)
![20231016_140727_0000](https://github.com/Phala-Network/growth-program/assets/99918790/d2ec26e8-48ba-4054-b29d-fe580e1e1bce)

**_Threads_**
1. This thread I made for Phala Africa which discusses the PhalaWorld blog update:
https://twitter.com/PhalaAfrica/status/1710721367769743666?t=4zRPlXdD2X13n7wce0IuDw&s=19

2. This thread was about reasons why would developers use Phala Network rather than  existing centralized off-chain computation services ?
https://twitter.com/TheScarletThr/status/1716010915642929466?t=Vg0q-IOJsFT2iGMZTg6nKg&s=19

Created these graphics for this thread:
https://github.com/Phala-Network/growth-program/assets/99918790/f763653c-cbbe-4719-8a78-511bf5e36295

![20231022_021620_0000](https://github.com/Phala-Network/growth-program/assets/99918790/791660e1-a648-4e36-94ba-0376b551d1cd)

3. Long-form piece about Phala Builders Program
https://twitter.com/TheScarletThr/status/1719293628365893854?t=r0aNG--DIb2yynMZZmteyQ&s=19

Created the following graphics for this piece:
![1_20231031_114736_0000](https://github.com/Phala-Network/growth-program/assets/99918790/9c7c69cb-1aff-438a-92ea-c77a1e89154e)
![2_20231031_114736_0001](https://github.com/Phala-Network/growth-program/assets/99918790/522dbca0-ba16-46aa-aee8-c15e6235f3a0)

4. Long-form piece about Phat Contracts
https://twitter.com/TheScarletThr/status/1713892551017570365?t=aY2341of3icMfhat3mHx6g&s=19

Made this graphics: 
https://github.com/Phala-Network/growth-program/assets/99918790/a21831b1-1f9a-4244-a7d5-a37a09d3982f

5. Thread about Phat Contract 2.0
https://twitter.com/PhalaAfrica/status/1717981739132256754?t=ABMlJ7LZouGAs-Gx0ufvjA&s=19
Made these graphics:

https://github.com/Phala-Network/growth-program/assets/99918790/2e10c81b-b570-4a34-8fdd-b781f456b16c
![20231022_103244_0000](https://github.com/Phala-Network/growth-program/assets/99918790/3bd56525-ebaf-4a65-95e4-23abf9ec4dbd)
![20231027_011632_0000](https://github.com/Phala-Network/growth-program/assets/99918790/bae04459-46d8-49cc-ab87-e33d06300863)
![20231027_011632_0001](https://github.com/Phala-Network/growth-program/assets/99918790/525d22b8-b45d-4055-ba6f-a0711de2f3b8)

**_Infographics_**
1. Phat Contract Starter Kit https://twitter.com/TheScarletThr/status/1717766180243443864?t=CYYMN6jEkNx0SFeEK5wGaA&s=19

2. Phat Contracts
https://twitter.com/TheScarletThr/status/1717454068421890325?t=I0UcZvP4JpRVPgeiLyTvWA&s=19

3. Phat Contract Vs Smart Contract
https://twitter.com/TheScarletThr/status/1716711023292387585?t=gjDIrFru_r43uHwwJg8Jlg&s=19

4. Phat Contract 2.0
https://twitter.com/TheScarletThr/status/1714574865921904746?t=kZQXcsSNkA7KAu-ptw-Eqg&s=19

5. Why bring computation off-chain
https://twitter.com/TheScarletThr/status/1712804556038373727?t=jIknUrSpuQETnLyvI-xupA&s=19

**_Meme_**
1. Find this meme posted here:
https://discord.com/channels/697726436211163147/766661203111575553/1168468705622097990

![Iceberg 3555](https://github.com/Phala-Network/growth-program/assets/99918790/58b8199f-8faa-459a-ab83-c2712c49f482)

2. Find this meme posted here: https://discord.com/channels/697726436211163147/766661203111575553/1168133005261410334

https://twitter.com/TheScarletThr/status/1718631455931122101?t=J7R0Zji7m8wFOuQGKRJHcg&s=19

![ZomboMeme 6126](https://github.com/Phala-Network/growth-program/assets/99918790/0631eabe-c295-4be6-b361-835c598b928e)

3. Find this meme posted here:
https://discord.com/channels/697726436211163147/766661203111575553/1166267305089572865 
![smart contracts and phat contract meme](https://github.com/Phala-Network/growth-program/assets/99918790/845b6626-2bd9-4f50-95f6-281519d7c721)

4. Made this meme and posted in server and Twitter
https://discord.com/channels/697726436211163147/766661203111575553/1165783788941492325

https://twitter.com/TheScarletThr/status/1716366763812593886?t=K_JlJeI0hDe5JfBT7kRLyg&s=19

![Perfectly Balanced PHALA ](https://github.com/Phala-Network/growth-program/assets/99918790/f9cece13-93e6-4cef-92d0-e4c641bdd1e8)

5.  Find this meme posted there: https://discord.com/channels/697726436211163147/766661203111575553/1167013481074130994 

https://twitter.com/TheScarletThr/status/1717839211934495153?t=fdBSY2fRL1SxbkG55JDctA&s=19
![Phat Contract meme](https://github.com/Phala-Network/growth-program/assets/99918790/3e8fbdbd-14ff-4afd-b237-08990be616af)

**_Artwork_**
PhalaWorld fan art, posted here:
https://discord.com/channels/920642630835138601/958351476743364648/1161675018061750413

![Phalalworld Fan Art](https://github.com/Phala-Network/growth-program/assets/99918790/00e85bb9-0eaa-48dd-a21e-6c4be50b1e65)

**_Local Community Call_**
This month we hosted the local Phala Africa community call via Google Meet. I played my role by:

• Creating and presented on the topic of Phat Contract 2.0 with accompanying graphics.

Content
https://docs.google.com/document/d/1QEVPc-w51oQmSs9m-NeUpFck4_6CI5tQTP0tx5VCFUc/edit?usp=drivesdk

Slides
https://docs.google.com/presentation/d/1wPnxRI8gJuiYwAAelAztIo3nt3aV27i1lSn9fFUBwfU/edit?usp=drivesdk

•Guiding organization of call, initiated discussions about tasks and tracked progress, maintained constant presence if fellow ambassadors needed assistance. I hosted the rehearsal and the main call ( creating meetings links, sharing slides for all presentations, playing music in the  beginning...)

• Made banner
![20231021_162457_0000](https://github.com/Phala-Network/growth-program/assets/99918790/e343849a-e3ef-435e-9b21-12098ef85f22)

**GOOD POINTS**
Personal contribution:
I created many graphics and gifs with most of my written content that helped make the content more engaging and some of my threads got relatively good emgagement. I also made memes this month which expands the types of tasks I did. Made content itself more creative

Phala Africa: although community call attendance had new people attending which was great and our ambassadorwas able to attend.

**BAD POINTS**
Personal contribution: Would like to make videls as well so that I can expand the types of content I make. 

Phala Africa: We didn't post a lot of content aside on the Phala Africa X and Medium from recaps of the community call. 

**HOW TO IMPROVE**
Personal contributions: work on some short video content and more informative content. Improve my reach for content posted on X and Medium.

Phala Africa: work on getting more content such as infographics and threads aside from community call. Work on getting to at least 100 followers for this account on X. 

**COMMUNITY MANAGEMENT**
• Helpdesk and moderation. I assisted in monitoring the PhalaWorld, Phala Telegram, Phala Africa Telegram, and Phala Discord in order to eliminate spam, malicious content and answer questions of the community. 

• Offered feedback to new ambassadors and pre-advocates, networked with people in tech within Africa region. 

• Share helpful resources to community about Phala and partners.

• Research and strategies to manage and improve CM. Drafted a document with  strategies to improve our regional CM which include attracting more developers and tech enthusiasts to our local community. Discussed with fellow Phala Africa ambassadors about our need to reach out to tech enthusiasts within Africa and spread the word of Phala.  Providing feedback, assistance and guidance to Phala Africa community and ambassadors - aim is to build a more vibrant community.

• Participated in community ambassador channel, offering feedback and added relevant questions to community digest.

•stats
![Screenshot_20231103-121332_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/59ad25d9-3608-45d4-b670-95eb60770021)

![Screenshot_20231105-201310_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/ffc90df1-cf77-4f0f-a55c-25e166c2e012)

![Screenshot_20231105-201229_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/8b22fcdc-c829-4a90-a39f-e6de9589f977)

![Screenshot_20231103-121244_Samsung Internet-02](https://github.com/Phala-Network/growth-program/assets/99918790/0e1d25b9-515a-497c-96b7-d9df8c6582ca)

**GOOD POINTS**
Personal contributions: I was present in both telegram and discord as well as on X  (both our regional group and the global group)

Phala Africa: improved collaboration between Phala Africa ambassadors in how to build on community amd strategizing. 

**BAD POINTS**
Personal Contribution: Didn't have many linger conversations/chat generation with community as much this month. Mostly answering questions and removing spam

Phala Africa: little to no engagement from community to content and announcement

**HOW TO IMPROVE**
Personal contribution: engage in meaningful chat generation

Phala Africa: Carry out more ideas from my research and strategizing ( also get the input from fellow Phala Africa ambassadors and encourage them to prepare new ideas) and  evaluate if that makes an impact on our CM.

### SUPPLEMENTARY 
**PM**
Busy month with launch of Phat Contract 2.0. I  promoted Phala Network and its technology on X. I actively shared updates, engaged with the community, and discussed  Phat Contracts, PhalaWorld.

I've also engaged through liking, commenting and retweeting content from: Phala Network ambassadors, Partners, Phala Network Twitter, fellow ambassadors and Phala Team members.

 I will continue working on improving my reach and genuinely enhancing the quality and quantity of my posts to educate the Web3 community about Phala Network's innovations.

![Screenshot_20231103-120948_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/03a14cfa-14af-4c96-9727-a775061f4f58)

![Screenshot_20231103-120942_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/777720da-0e89-4111-a027-9437f2a38612)

![Screenshot_20231103-120936_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/3fe73c55-8b68-4385-9dd3-2078efa3f995)

![Screenshot_20231103-120926_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/11c49eb6-fcf0-4430-9514-feb0b08947c6)

**RC**
Reccomended a talented developer from Africa to apply for Phala Africa ambassador program and she was accepted as a candidate and has already begun using Phat Contract:
https://x.com/ayomide_bajo?t=mGNZQYNRUnWxuR1GlIP2qQ&s=09

**SCORES**
**CC** 40/40
**CM** 37/40
**PM** 10/10
**RC** 5/10
**TOTAL** 92

**CLOSING COMMENTS**
This month was busy with launch of Phat Contract 2.0 so lots of activity for Phala this month. 
Engagement is low in our regional community however myself and other Phala Africa ambassadors continue to post updates and announcements in local group. We will keep working together to improve our community engagement and host some fun events for the community and post content.

Thank you 
Scarlet

**Comment by willphala** [comment]
Great work! Especially in regards to RC
