### ISSUE TITLE
October 2023 Contribution - Gabekoin

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#295]
Telegram : @gabekoin
Discord : gabekoin
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of Out:
Ambassador

CONTENT (CC):40/40

Articles Created:
Abrindo os horizontes:
https://medium.com/@phalaptbr/abrindo-os-horizontes-dos-trading-bots-com-o-poder-do-phat-contract-14544c65d6c3

Omnilanguage:
https://medium.com/@gabekoin/capacidade-omnilanguage-dos-phatcontracts-f16e203d5795

Threads created:
Trading Bot 1:
https://twitter.com/phalaportugues/status/1709676118297497750

Live Hazim:
https://x.com/phalaportugues/status/1710368554984374317?s=20

Evento Crypto:
https://x.com/gabekoin/status/1710696041777954871?s=20

Vantagens Bot:
https://x.com/phalaportugues/status/1711500138751922634?s=20

Capacidade Omni:
https://x.com/phalaportugues/status/1712202187080679587?s=20

Omnilanguage:
https://x.com/phalaportugues/status/1713921030727573833?s=20

Community Call:
https://x.com/phalaportugues/status/1717166987917308045?s=20

Partnership:
https://x.com/gabekoin/status/1719053626742612013?s=20

Articles Translated:
Omnilanguage Capability:
https://medium.com/@gabekoin/phat-contracts-omnilanguage-capability-8a909ba0cee8

Threads Translated:
PC 2.0:
https://x.com/phalaportugues/status/1719353636071903438?s=20

1/ What is Omnilanguage:
https://x.com/gabekoin/status/1713930526623424940?s=20

Phala Weekly 19/10:
https://x.com/phalaportugues/status/1715104154866085966?s=20

Inface Workers:
https://x.com/phalaportugues/status/1716458956187418750?s=20

Phat Contract 2.0 PT:
https://x.com/phalaportugues/status/1718277478077051339?s=20

Phat Contract 2.0:
https://x.com/gabekoin/status/1718276216577302931?s=20

Zurf:
https://x.com/phalaportugues/status/1719054929501773877?s=20

Infographic PC 2.0:
https://x.com/phalaportugues/status/1719449616570110459?s=20

![image](https://github.com/Phala-Network/growth-program/assets/112413448/e937e2b6-0882-44b8-a7ba-92b22502bdd8)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/099d0528-26b2-4599-ad61-20071e1cd87d)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/876bf1af-c99e-42d4-bcdd-8ca3ff45341f)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/14191d96-be5e-44ba-ae54-1971e752be50)

LINKEDIN POSTS CREATED:

Evento Crypto:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_curitibacryptoday-phatcontract-blueprints-activity-7116499294404132864-mDn1?utm_source=share&utm_medium=member_desktop

Phala Hack DevX:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_dorahacks-on-x-activity-7117520221610881025-XAIn?utm_source=share&utm_medium=member_desktop

Capacidade Omnilanguage:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_capacidade-omnilanguage-dos-phatcontracts-activity-7117979282349436928-8z3S?utm_source=share&utm_medium=member_desktop

Phala Buenos Aires:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phatcontract-phala-activity-7117981360408977408-iql_?utm_source=share&utm_medium=member_desktop

Phala Polygon RIO:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phatcontract-activity-7117981748193300480-kq04?utm_source=share&utm_medium=member_desktop

Omnilanguage Capabilty:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-phat-contracts-omnilanguage-activity-7120500831258390528-SFOk?utm_source=share&utm_medium=member_desktop

Unleash the power:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-verifiable-computation-for-activity-7122222303697911809-jwUb?utm_source=share&utm_medium=member_desktop

Community Call:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-join-us-to-get-the-latest-activity-7122683006946848768-fnTr?utm_source=share&utm_medium=member_desktop

Phat Contract 2.0:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-on-x-activity-7124064281402236928-2ZTy?utm_source=share&utm_medium=member_desktop

Zurf:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-today-on-the-eve-of-pc-20-activity-7124826186475577345-jE36?utm_source=share&utm_medium=member_desktop

PC 2.0:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-phat-contract-20-is-now-live-activity-7125120490578337793-UnvU?utm_source=share&utm_medium=member_desktop

COMMUNITY (CM): 34/40
Phala Global:
![image](https://github.com/Phala-Network/growth-program/assets/112413448/0b471fc0-08ae-4701-8c6d-7a6ecfdf8831)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/502e959b-1675-4309-af17-ba58ff70d4f7)

Phala Portuguese:
![image](https://github.com/Phala-Network/growth-program/assets/112413448/8bd84c05-b8e2-4c1d-89ad-a25b7ba86a22)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/cfbdb8e6-7f18-436a-8231-d467578e996b)
![1](https://github.com/Phala-Network/growth-program/assets/112413448/fa60b69a-a641-4ca5-9fcc-3e9d77ee6e49)
![2](https://github.com/Phala-Network/growth-program/assets/112413448/a2659834-2006-46d7-a86c-64ec85958a73)
![3](https://github.com/Phala-Network/growth-program/assets/112413448/19312118-b0dd-4239-95c7-c37619010dd7)
![4](https://github.com/Phala-Network/growth-program/assets/112413448/32fbe0fe-5263-4c07-9b3c-35013ee14e6e)
![5](https://github.com/Phala-Network/growth-program/assets/112413448/e8525725-36d8-422b-978e-8cee969f737e)
![6](https://github.com/Phala-Network/growth-program/assets/112413448/954932fd-3726-4947-b919-9945f596d071)
![7](https://github.com/Phala-Network/growth-program/assets/112413448/6ba439f1-5a48-4375-b8e7-dd6bb718946c)
![8](https://github.com/Phala-Network/growth-program/assets/112413448/fd907ae5-61a9-411d-83b8-da60ae83c602)
![9](https://github.com/Phala-Network/growth-program/assets/112413448/4498cd12-1cf8-4cc2-804b-ee14cd2d37ce)
![10](https://github.com/Phala-Network/growth-program/assets/112413448/fa578ed3-eb8b-4dd5-b501-ec44e9c6a899)
![11](https://github.com/Phala-Network/growth-program/assets/112413448/547b9e93-dc78-4430-892d-6529fe657376)
![12](https://github.com/Phala-Network/growth-program/assets/112413448/cf8e6922-4718-4573-a814-fe1c0261158a)
![13](https://github.com/Phala-Network/growth-program/assets/112413448/0cc3e2f9-9758-4a7a-b0a7-e71437c62248)
![14](https://github.com/Phala-Network/growth-program/assets/112413448/026a89ec-bef0-402c-8898-62fddb49ef7f)
![15](https://github.com/Phala-Network/growth-program/assets/112413448/b0411f55-b390-47f6-9473-5eeaf25c7fb6)
![16](https://github.com/Phala-Network/growth-program/assets/112413448/2184d5a0-a675-4536-8aa3-9837db406890)
![17](https://github.com/Phala-Network/growth-program/assets/112413448/e0b88c07-da2e-428d-aacc-83cdbf68c618)

Supplementary: EM & MK (20/20)

EM: 10/10
CryptoDayCuritiba:
https://x.com/gabekoin/status/1710696041777954871?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/3f91c837-9929-44c6-945c-f0cb0b2ffc94)

Spaces Polkadot Brasil / PhalaWorld:
https://x.com/phalaportugues/status/1713219305641251132?s=20
https://x.com/i/spaces/1djGXNgpRANxZ
![Spaces 111](https://github.com/Phala-Network/growth-program/assets/112413448/931816ff-a46b-484b-b812-33953cdb92bf)
![Spaces 1111](https://github.com/Phala-Network/growth-program/assets/112413448/b32a47ed-260c-4122-bc34-f0e56a475988)
![Spaces 1](https://github.com/Phala-Network/growth-program/assets/112413448/efe7305c-9a91-4e09-8c77-2c4fded27070)
![Spaces 11](https://github.com/Phala-Network/growth-program/assets/112413448/4570ff0b-eb1a-4459-b25e-c9baa1271788)

Spaces Mensal:
https://x.com/phalaportugues/status/1719453879526474022?s=20
![Spaces 2](https://github.com/Phala-Network/growth-program/assets/112413448/1b73bbcc-1180-4bc4-b711-67322528822b)

PM: 10/10
Tweets (RT & LIKE):
https://x.com/gabekoin/status/1708828383226876059?s=20
https://x.com/gabekoin/status/1708563789442953564?s=20
https://x.com/phalaportugues/status/1709676118297497750?s=20
https://x.com/developer_dao/status/1707811049011925196?s=20
https://x.com/hashwarlock/status/1709795589427187976?s=20
https://x.com/PhalaNetwork/status/1711751051429236773?s=20
https://x.com/gabekoin/status/1711759934864474219?s=20
https://x.com/hashwarlock/status/1712398883815293081?s=20
https://twitter.com/hashwarlock/status/1712398883815293081
https://x.com/marvin_tong/status/1716433375630930346?s=20
https://x.com/PolkadotInsider/status/1716033616579629485?s=20
https://x.com/DoraHacks/status/1714726944489828827?s=20
https://x.com/infaceAi/status/1715247984563130695?s=20
https://x.com/PhalaNetwork/status/1719348284584497211?s=20
https://x.com/CryptoCappex/status/1716427805280399390?s=20
https://x.com/PhalaNetwork/status/1716862862239428740?s=20
https://x.com/PhalaNetwork/status/1716807121927291328?s=20
https://x.com/gabekoin/status/1717525634685993271?s=20
https://x.com/gabekoin/status/1718719149428392324?s=20
https://twitter.com/PhalaNetwork/status/1719049170319736912?s=20
https://x.com/gabekoin/status/1718276216577302931?s=20

LINKEDIN RT:

https://www.linkedin.com/feed/update/urn:li:activity:7114470632108523520?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/alephzero_aleph-zero-has-teamed-up-with-astar-network-activity-7106989892966002688-pbjC?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/joshua-waller-33935773_waiting-for-on-chain-latency-makes-blockchain-activity-7115854330301206528-3NlI?utm_source=share&utm_medium=member_desktop

Suggested scores:
[CC] 40/40
This month was amazing, with many new content with a great reach. Our Twitter is beign viewed and interacted by many people.
For next month keep the good work and try to reach more people

[CM] 34/40
This month was pretty good, Telegram and Discord had many interactions
Brasilian community is growing and we are happy about that.
Keep growing our local community

[EM] 10/10
Hosted 3 Spaces with the community, all of the with many people and good content.

[PM] 10/10
Shared all oficial content in all main social medias.

Overall suggested score: 94/100.

By far the best month ever! So happy about it, I'm already missing it.
Great times ahead

For the next month: Do better

**Comment by willphala** [comment]
Awesome stuff!
