### ISSUE TITLE
October 2023 Contributions - GatorKorps

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#296]
Telegram Username: @gatorkorps
Discord Username: gatorkorps
Twitter Username: https://twitter.com/gk18_dog
Twitter Phala French speaker community : https://twitter.com/phala_fr
PHA Wallet Address: 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV

Contributions:

MK & PM

I promoted Phala on Twitter and onseveral crypto community discord and TG server
I focused my activity mainly on talking about Phala on French influencer accounts and relaying official communication. I was much more active with the Phala FR account.

https://twitter.com/gk18_dog/status/1718144630691082483 
https://twitter.com/phala_fr/status/1718171176965427515
https://twitter.com/gk18_dog/status/1710923582597992739
https://twitter.com/gk18_dog/status/1708524401358946699
https://twitter.com/gk18_dog/status/1717114556277764177
https://twitter.com/gk18_dog/status/1715318625794482227
https://twitter.com/gk18_dog/status/1711792985791234326
https://twitter.com/gk18_dog/status/1709921744020963335

![image](https://github.com/Phala-Network/growth-program/assets/82824139/b5265e11-3e59-4c3e-84a0-fec42e91045b)

Amplification and help to Tioneb and his very nice initiative : https://twitter.com/tioneb442/status/1714948891727073555

CM

Managing the Phala French twitter account / TG and discord and creating native language content

https://twitter.com/phala_fr/status/1719358695929245927
https://twitter.com/phala_fr/status/1717854501724405922
https://twitter.com/phala_fr/status/1716126260613480919 - article translation (reviewed by arno)
https://twitter.com/phala_fr/status/1717852585095319572 - article translation by Rom1

![image](https://github.com/Phala-Network/growth-program/assets/82824139/7c75d8f6-c3b6-4b15-861b-96f1f3cae880)

![image](https://github.com/Phala-Network/growth-program/assets/82824139/77875064-9b09-4302-ae43-c7658f51cb5c)
![image](https://github.com/Phala-Network/growth-program/assets/82824139/ddd6b653-0eed-4931-8021-d410070e925b)
![image](https://github.com/Phala-Network/growth-program/assets/82824139/855a0e6e-8609-4632-b6bb-a2b2c47dd78a)

Physic Meeting with a (maybe) futur phala ambassador.

Active participation within the Ambassador group.
Monitoring and possible correction of content shared with the communty by internal ambassador program members and external members

CC Content Creator

1 Article translated: https://twitter.com/phala_fr/status/1716126260613480919 - article translation (reviewed by arno)
2 Thread translated about Phat Contract 2.0 : 
https://twitter.com/phala_fr/status/1719358695929245927
https://twitter.com/phala_fr/status/1717854501724405922

Alice is awake - Gameboy Game for PhalaWorld:
Following ChrisBck's wonderful initiative, I spent many hours practicing pixel art to help him create models and understand how this gameboy development for Phala (Alice is awake) works.

![image](https://github.com/Phala-Network/growth-program/assets/82824139/2b7e5e36-2264-4de7-b8fe-91a58b4e916a)

![map1](https://github.com/Phala-Network/growth-program/assets/82824139/051344e7-baea-4b0d-88a5-3b1c81834265)

![test 1 scene](https://github.com/Phala-Network/growth-program/assets/82824139/a21072e3-4be6-4f63-ad16-d06b3c3d65d8)

I gonna continue to help him the best I can to accelerate the process and create many pixel art model with Gimp and Tiled.

I expect a result  better than the other months 90%:

MK: 40/40
CM: 40/40
CC: 10

**Comment by willphala** [comment]
Nice work! I'm really happy that you're collaborating with Chris. I am excited to see the outcome!
