### ISSUE TITLE
October 2023 Contributions - {TIONEB}

### ISSUE THREAD

**Issue by tionebDotsamapha** [Phala-Network/growth-program#297]
Telegram Username: [tioneb](https://t.me/tioneb)
Discord Username: tioneb#4951
Twitter Username: [tioneb_DotSama₱ha](https://twitter.com/tioneb442)
PHA Wallet Address: 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7

Departments : #CM & #MK
Department Score Weight : 50% & 50%

# Community Management
## Telegram : 
<img width="728" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/92fd0322-4325-472e-8f0e-508c55cc1d35">
<img width="738" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/6c653e88-da0a-4cb9-b3d3-1789cf67e1d6">

## Discord :
<img width="745" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/1555663c-7ca7-4277-a1e6-ac214f4cddaa">

## Youtube :
<img width="654" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/9f2c991b-c4f6-47f6-924a-2fbc0ae6f3bc">

## Twitter :
<img width="703" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/4798b942-9d65-4e08-a37a-084c37f8c97e">

# Marketing

This month I've put the PhatContract in the spotlight.
I was invited to speak at Alyra, the only Blockchain school in France, during a course aimed at developers.
My aim was to demonstrate to future developers just how powerful PhalaNetwork and its PhatContract are. During this event, I invited the students and then my community to another event that took place the following week.  
 Here, what I put forward in terms of MK and has worked well in my opinion (+22 followers on twitter and lot of new MP by Linkedin).
 
 https://www.linkedin.com/posts/benoit-monchatre_dev-workshop-phatcontract-activity-7120689631330742273-7fUh/
<img width="401" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/7f55f021-4908-4827-8da0-206b5f4a20b4">
753 impressions on this linkedin post, just with a simple text without  photo or article.
 
 https://twitter.com/tioneb442/status/1714930987233165458
 https://x.com/tioneb442/status/1714948891727073555?s=20
 https://x.com/tioneb442/status/1715698129175998472?s=20
 https://x.com/tioneb442/status/1716566785883820458?s=20
 
 # EM+DEV+TT
 ## Workshop to the Alyra BC shcool
<img width="669" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/d5e66891-1b1d-408a-a2d4-ee114c171a41">

For this presentation of PhalaNetwork and its PhatContract, I presented them in a very arrogant way, accompanied by a great deal of humor : 🤣
" PhalaNetwork is the GameKiller about the future of smartcontracts and i'll prove it to you."😎
 🔢- First part, i presented shortly the DEC cloud computing game + SGX technology + Rollup. the interrest of mixed ON/OFF chain.
 🔢- Before this event i prepared a dedicated Github Repo whit a quick intall dev env in a docker. Thank this you have a new dev envinronnement ready to play in 10 minutes.
 https://github.com/tionebDotsamapha/WorkShop-Alyra-1_basicInstall
 By this way i presented in a first time the fundamentals about Rust, Cargo, Ink contracts with the flip contract built by the installation.
 🔢- In a second part, i presented a little oracle as exemple code. I show how to get the value of the $PHA from 3 exchanges (gate,kuckoin,mexc), and return the average price.
 I compiled it and upload it on the Poc5 testnet to demonstrate the rapidity.
At this step the teacher was sincerly surprised, astonish by the simplicity and rapidity ! 😯
🔢- My third demonstration killed everyone !
I built a program to mix payements by a lottery game. If A want to send 90$ to B, he add 10$ (or more) to participate to the lottery.
To deguise the amont B send 20$ to himself.
Everyone can play to the lotterie and by this way nobody can know who pay who and how many. 
So it's use the previous oracle, a management of float numbers, the encrypted recording of datas on a  S3 Storage.
- "why are you storing, the email address ?"
- "Because in a near future phatContracts will permit you to send email thanks the API of Dmail"
- 😏"???!!! What !!!????😏"

During the event i invited everyone to come at my personal course on bases of dockers containers that i organised the next week. 
I explained that a lot of people use docker thanks some copy/past command lines since read me documents. But few people know bases and how it works.
I organised this meeting on phalateamFr discord. A ruse that allowed me to bring a dozen more people into the community. 
I'm waiting for them to finish their training before pinging them.

Thanks a lot to @Rom1io who accompanied me to the event to handle chat questions and spread the links about the community and the workshop.  🙏🤲😘

CM : 30
MK : 30
EM+DEV+TT : 40

Total : 100

**Comment by willphala** [comment]
Phantastic!
