### ISSUE TITLE
October 2023 Contributions - (johnrhodel#8162)

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#301]
Telegram Username: https://t.me/parachainboy
Discord Username: johnrhodel#8162
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

CC : 40/40

Youtube Class about Phala:

https://www.youtube.com/watch?v=xty6sOADUMg&t=2118s

Translated/Created/ Reviewed Articles Portuguese/Filipino

Portuguese:
https://medium.com/@phalaptbr/boletim-mensal-phala-setembro-de-2023-45dfcd19467b
https://medium.com/@phalaptbr/phat-contract-2-0-contratos-inteligentes-agora-conectados-416802611443

Filipino:
https://polkaverse.com/11194/q-and-a-isang-malalim-na-pagsisid-sa-proyekto-at-ecosystem-39766
https://polkaverse.com/11194/kakayahang-omnilanguage-ng-phat-contracts-39631
https://polkaverse.com/11194/binubuksan-ang-mga-abot-tanaw-ng-trading-bots-gamit-ang-39630
https://polkaverse.com/11194/buwanang-newsletter-ng-phala-setyembre-2023-39629

Reviewed Article:
https://medium.com/@phalaptbr/capacidade-omnilanguage-dos-phatcontracts-cb255402f986
https://medium.com/@phalaptbr/abrindo-os-horizontes-dos-trading-bots-com-o-poder-do-phat-contract-14544c65d6c3

MK(40/40)

![280531665-876bf1af-c99e-42d4-bcdd-8ca3ff45341f](https://github.com/Phala-Network/growth-program/assets/77474076/106dc9f2-8db0-4244-9c9d-6642ba3f8816)

![eresf](https://github.com/Phala-Network/growth-program/assets/77474076/98405712-2a24-4119-b49a-769cfa46b643)

CryptoDayCuritiba:
![280531557-3f91c837-9929-44c6-945c-f0cb0b2ffc94](https://github.com/Phala-Network/growth-program/assets/77474076/585dd29b-54a7-423f-979e-e86e6fe0b176)

Spaces Polkadot Brasil / PhalaWorld:
![280531567-931816ff-a46b-484b-b812-33953cdb92bf](https://github.com/Phala-Network/growth-program/assets/77474076/0ab90877-824b-4931-a9f5-73a84a75b18e)

https://x.com/phalaportugues/status/1713219305641251132?s=20
https://x.com/i/spaces/1djGXNgpRANxZ

Spaces Mensal:
![280531583-1b73bbcc-1180-4bc4-b711-67322528822b](https://github.com/Phala-Network/growth-program/assets/77474076/c05332e4-56c5-4007-a8b9-4d909bbfa755)

https://x.com/phalaportugues/status/1719453879526474022?s=20

Live Joao Hazim:
![photo_2023-10-10_07-44-37](https://github.com/Phala-Network/growth-program/assets/77474076/ad2d4adc-d0dc-4097-823f-7fb18ce91ed3)

![photo_2023-10-10_07-45-17](https://github.com/Phala-Network/growth-program/assets/77474076/9aff865d-9e53-49d2-be73-35e5992a9256)

Live alpes cripto discord:
![photo_2023-10-31_20-00-43](https://github.com/Phala-Network/growth-program/assets/77474076/73be924a-68af-4972-b356-8587f2a30b34)
![photo_2023-11-06_14-13-17](https://github.com/Phala-Network/growth-program/assets/77474076/9e9ee244-dec3-4b24-b64b-c603fc6195ef)
![photo_2023-11-06_14-13-18](https://github.com/Phala-Network/growth-program/assets/77474076/35de330c-e821-4180-9c8c-4c455f1abc9a)

Oficina cripto : Polkadot ana parachains, talked about phala:
![photo_2023-10-08_20-38-06](https://github.com/Phala-Network/growth-program/assets/77474076/7f16d178-fe64-437d-9814-96ad75ee194e)

Tweets (RT & LIKE):

https://twitter.com/parachainboy/status/1710351266528772409
https://x.com/hashwarlock/status/1712398883815293081?s=20
https://twitter.com/hashwarlock/status/1712398883815293081
https://x.com/marvin_tong/status/1716433375630930346?s=20
https://x.com/phalaportugues/status/1709676118297497750?s=20
https://x.com/developer_dao/status/1707811049011925196?s=20
https://x.com/hashwarlock/status/1709795589427187976?s=20
https://x.com/PhalaNetwork/status/1711751051429236773?s=20
https://x.com/PhalaNetwork/status/1719348284584497211?s=20
https://x.com/PhalaNetwork/status/1716862862239428740?s=20
https://x.com/PhalaNetwork/status/1716807121927291328?s=20
https://twitter.com/PhalaNetwork/status/1719049170319736912?s=20
https://x.com/CryptoCappex/status/1716427805280399390?s=20
https://x.com/PolkadotInsider/status/1716033616579629485?s=20
https://x.com/DoraHacks/status/1714726944489828827?s=20
https://x.com/infaceAi/status/1715247984563130695?s=20

Extra Points:
HD (8/10):

![265752495-b98227b6-ce0b-47a7-a42e-b0b50f5b10b0](https://github.com/Phala-Network/growth-program/assets/77474076/8368dd62-e348-4015-87dd-430a01607abc)
![265880963-30fcd701-58d3-4dc8-b733-eafad079692c](https://github.com/Phala-Network/growth-program/assets/77474076/fdeee2c2-7bbc-447f-b00b-ec1f9345ef99)
![Capturar](https://github.com/Phala-Network/growth-program/assets/77474076/0735d22b-1278-494f-93f0-f3383c424b34)
![photo_2023-10-30_10-38-07](https://github.com/Phala-Network/growth-program/assets/77474076/e2776e10-059f-46f5-94f2-f23762098163)

Art(10/10)
![1](https://github.com/Phala-Network/growth-program/assets/77474076/e26ebb48-feba-4576-94e0-73cc45ae8214)
![2](https://github.com/Phala-Network/growth-program/assets/77474076/c538e111-4bae-48e6-9974-4577249e170d)
![3](https://github.com/Phala-Network/growth-program/assets/77474076/40d3a925-a132-44d5-b215-b84314963505)
![4](https://github.com/Phala-Network/growth-program/assets/77474076/ca2f45d9-2625-48c0-b3ec-43ab09e06833)

This month I did well in content and marketing (40 and 40)

I didn't get that many questions, I answered 4 out of 5 of the average that asks for HD (8/10)

Art I made 4 arts out of 1 requested (10/10)

total: 98 or 96

**Comment by willphala** [comment]
Excellent work!
