### ISSUE TITLE
November 2023 contributions .dksm

### ISSUE THREAD

**Issue by darknight7** [Phala-Network/growth-program#304]
Telegram: randomusernameidontneed
Discord: .dksm
PHA Address: 427s7coF6yveYnXPNvCc1BtKgkHABxwgZpcwbFXbpJE9X1iP

MK: I do not contribute to this department.

CM
Have I participated in Discord Channel Moderation (choose)? Yes, telegram too.

Phala Italian Channel link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a
Comments: only remark is that there were a few posts in the Italian community that reveal a bit of "wearyness" about token performance, maybe after recent announcements they expected some pump.
Transition to compute still on hold, pending developments.
CM end.

CC
Translated [Dynamic NFTs](https://medium.com/phala-italia/nft-dinamici-un-cambio-di-paradigma-per-il-web3-fdafdf4cb7aa) medium article
Translated [Phala & Airstack](https://medium.com/phala-italia/linfrastruttura-social-web3-cresce-phala-e-airstack-avviano-una-collaborazione-f7851a301ece) medium article

Resource toolkit for videos on hold until team is ready to tackle the matter.
CC end.

PM
No twitter/X impressions.
PM end.

HD
Phala Mining Channel link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a
Comments: nothing noteworthy, in my opinion the overwhelming majority of miners now is made of veterans and decentralization is slowly shrinking as the market becomes more mature and "professional". There has been at least one case of a veteran stopping his pools this month citing unacceptable losses as soon as the next halving hits in december.
HD end.

My self evaluation:
MK: -
CM: 25
CC: 30
PM: 3/10
HD: 3/10
PM end.

**Comment by willphala** [comment]
Excellent work. Also again, I appreciate your thorough review of our inDEX article too! I can always count on your detailed feedback with these tasks which is sincerely appreciated.
