### ISSUE TITLE
November 2023 contributions report {toriribolla}

### ISSUE THREAD

**Issue by toriribolla** [Phala-Network/growth-program#305]
**PERSONAL INFO**
Amb Rank : Ambassador
Telegram: @toriribolla
Twitter: @toriribolla
PHA Address : 435b1mp9FuSY4X6NNMTN6mALfyeChiQU1htPViw7hnD26sEM

**Departments: #CC & #MK
Department Score Weight : 50%(40) & 50%(40)**

CC Contributions:

X @toriribolla:
1 https://x.com/ToriRibolla/status/1719719854154920093?s=20
2 https://x.com/ToriRibolla/status/1720002891400810586?s=20
3 https://x.com/ToriRibolla/status/1721876286493381015?s=20
4 https://x.com/ToriRibolla/status/1722192422833136096?s=20
5 https://x.com/ToriRibolla/status/1722554744202211742?s=20
6 https://x.com/ToriRibolla/status/1722917256701657102?s=20
7 https://x.com/ToriRibolla/status/1724019432446402703?s=20
8 https://x.com/ToriRibolla/status/1724382101766549606?s=20
9 https://x.com/ToriRibolla/status/1724744116624380019?s=20
10 https://x.com/ToriRibolla/status/1725106438161195153?s=20
11 https://x.com/ToriRibolla/status/1726602577314460057?s=20
12 https://x.com/ToriRibolla/status/1726707832555511819?s=20
13 https://x.com/ToriRibolla/status/1728045891175551229?s=20
14 https://x.com/ToriRibolla/status/1730231124813578729?s=20
15 https://x.com/ToriRibolla/status/1730314013643341973?s=20

Retweets
1 https://x.com/PhalaNetwork/status/1719724960233509128?s=20
2 https://x.com/PolkadotInsider/status/1720614623429222824?s=20
3 https://x.com/marvin_tong/status/1720468467428831296?s=20
4 https://x.com/PhalaNetwork/status/1721585312407732711?s=20
5 https://x.com/PhalaNetwork/status/1722145210166022472?s=20
6 https://x.com/PhalaNetwork/status/1722592228499956201?s=20
7 https://x.com/PhalaNetwork/status/1724790790583718304?s=20
8 https://x.com/marvin_tong/status/1727389509141286917?s=20
9 https://x.com/ToriRibolla/status/1729508974683165001?s=20
10 https://x.com/polkadex/status/1729317990095901109?s=20
11 https://x.com/CryptoCappex/status/1730299050342117732?s=20
12 https://x.com/PhalaNetwork/status/1730638690030932389?s=20

![image](https://github.com/Phala-Network/growth-program/assets/132458076/d389ce2e-49d9-4d4c-90f2-e66aed4a51d6)

X @PhalaRussia

1 https://x.com/PhalaRussia/status/1719711379702026258?s=20
2 https://x.com/PhalaRussia/status/1720174299292578278?s=20
3 https://x.com/PhalaRussia/status/1721889623830560933?s=20
4 https://x.com/PhalaRussia/status/1722886891370946570?s=20
5 https://x.com/PhalaRussia/status/1723249219740266904?s=20
6 https://x.com/PhalaRussia/status/1723989276738637884?s=20
7 https://x.com/PhalaRussia/status/1724351619653840945?s=20
8 https://x.com/PhalaRussia/status/1724713987806318905?s=20
9 https://x.com/PhalaRussia/status/1725076273846800563?s=20
10 https://x.com/PhalaRussia/status/1725438631819583829?s=20
11 https://x.com/PhalaRussia/status/1726556210348904716?s=20
12 https://x.com/PhalaRussia/status/1727324272337854680?s=20
13 https://x.com/PhalaRussia/status/1729507642052075916?s=20

![image](https://github.com/Phala-Network/growth-program/assets/132458076/6fcadbb7-922c-4491-95b0-f636c21b571b)

MK Contributions:

X analytics @toriribolla

![image](https://github.com/Phala-Network/growth-program/assets/132458076/790e99ee-cb19-4806-86c1-297aaacd3a7e)

X analytics @PhalaRussia

![image](https://github.com/Phala-Network/growth-program/assets/132458076/7d5f7e3d-1a02-40f5-8c9a-d9f7e94b1bec)

CC:

Medium article:
Understanding Off-Chain with Phala Network - 810 words
https://medium.com/@ribollavvv/3e74cbe71ab9

Medium translation:
Понимание off-chain на примере Phala Network - 720 words
https://medium.com/@ribollavvv/b1fbf6da22b8

Medium translation:
Все о новых партнерствах Phala Network - 2072 words
https://medium.com/@ribollavvv/fc180d5fb89b

ART: 

![1hgjg](https://github.com/Phala-Network/growth-program/assets/132458076/d35f40fa-ed5c-4f37-ad54-2c03d28b0979)
![2hgjhg](https://github.com/Phala-Network/growth-program/assets/132458076/6978a26d-c1ea-418c-8896-f467f012f97c)
![3jhgjh](https://github.com/Phala-Network/growth-program/assets/132458076/cb5447de-c110-42d9-b3a5-246f8ce67885)
![5ghgj](https://github.com/Phala-Network/growth-program/assets/132458076/bafd018f-5e4c-4a5b-90ff-41358f4573ec)
![7hgh](https://github.com/Phala-Network/growth-program/assets/132458076/34552627-a511-4620-b9e0-dbab059123e0)
![jkhkjh](https://github.com/Phala-Network/growth-program/assets/132458076/6875b433-722b-45ba-830f-ac4b704b5f5c)
![орпропо](https://github.com/Phala-Network/growth-program/assets/132458076/39026cde-cb0f-4cd9-886c-a81f214f0a0a)

Also this month, I started drawing stickers for Phala Network 
![gyuguy](https://github.com/Phala-Network/growth-program/assets/132458076/94f97d62-549a-45e4-baa6-92ededd4642d)

SUGGESTED SCORES
#CC : 40
#MK : 40
#ART : 10
Overall : 90

This month I've been giving more attention to quality over quantity of content, trying to come up with and produce more creative work. I also made quite a few useful connections. I've been subscribed to a couple of great Influencers, PolkadotInsider, Kusamarian and MAD.cripto. 

![image](https://github.com/Phala-Network/growth-program/assets/132458076/6e3716a9-1689-4fcc-bb1f-fd65148867e8)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/7aa5ce8e-aab2-4e0c-a97e-c5776f416100)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/5c22ac15-2133-4d60-ba7f-2f4e7606e1d3)

**Comment by willphala** [comment]
Great work Tori. I especially like the first 3 images you have listed in ART. Keep it up!
