### ISSUE TITLE
November 2023 Contributions - {Cappex#7765}

### ISSUE THREAD

**Issue by cappehub** [Phala-Network/growth-program#306]
Telegram Username: @cryptocappex
Discord Username: cappex
Twitter Username: https://twitter.com/CryptoCappex
PHA Wallet Address: 46FGLnh69wQ2EQU6gotqhmZjq9foVCF4vYSYaaLmxKViPGTr

Contributions:

MK & PM
- I promoted Phala on Twitter and on Polkadot and Kusama's official discord servers!
- November was another record month with 650,000 impressions and I gained 150 new followers!
All the details of my social activity (twitter) have been shared here: https://docs.google.com/spreadsheets/d/1jw-Rr95gozF6K0ibWub5JlJvKNgmTYsEIV-lyyy9i6M/edit#gid=0
https://twitter.com/search?q=%40phalanetwork%20(from%3Acryptocappex)%20until%3A2023-11-30%20since%3A2023-11-01&src=typed_query&f=top
https://twitter.com/search?q=%23phalanetwork%20(from%3Acryptocappex)%20until%3A2023-11-30%20since%3A2023-11-01&src=typed_query&f=top
https://twitter.com/search?q=%24PHA%20(from%3Acryptocappex)%20until%3A2023-11-30%20since%3A2023-11-01&src=typed_query&f=top
![cappex NOV23](https://github.com/Phala-Network/growth-program/assets/57374748/8e14a46d-8ea9-4847-9a37-a65bc8a9eb63)

CM
- Managing the Phala Italy twitter account and creating native language content
![PHA community nov23](https://github.com/Phala-Network/growth-program/assets/57374748/b6fae94e-241b-48ad-b835-f8576e1cc2eb)
![PHA community nov23_1](https://github.com/Phala-Network/growth-program/assets/57374748/6100be57-eae6-4a0a-a091-f37cb9797843)

- Full details of social activity related to Phala Italy's twitter account have been shared here: https://docs.google.com/spreadsheets/d/1jw-Rr95gozF6K0ibWub5JlJvKNgmTYsEIV-lyyy9i6M/edit#gid=0
![PHA community nov23_2](https://github.com/Phala-Network/growth-program/assets/57374748/beaf0ecd-bf34-419e-b4d5-b3df4ea80b20)

HD
- Active participation within the Ambassador group.
- Monitoring and possible correction of content shared with the communty by internal ambassador program members and external members
- Constant presence in chat (discord and telegram), moderation, answering users' questions, removing spam and banning users who don't follow the rules!
![PHA community nov23_3](https://github.com/Phala-Network/growth-program/assets/57374748/3d3091ff-75a4-4f95-b9f9-9a42ba6b8629)
![cappex nov](https://github.com/Phala-Network/growth-program/assets/57374748/03c9d9b4-b3ee-49e4-943f-32332f882a90)

CC Content Creator
- Series of informative twitter threads on various aspects of Phala, shared in the dedicated discord channel.
- Translation of articles on Medium: https://medium.com/phala-italia/latest

Bonus
- Collaborated in retrieving the necessary information in order to prepare the [survey for listing on HydraDX](https://twitter.com/CryptoCappex/status/1727391859486740633) and also the proposal being developed by the team.

I expect a result in line with other months 90%:
MK: 40/40
CM: 40/40
CC: 10

**Comment by willphala** [comment]
Congrats on 650 impressions. Well deserved! Excellent work.
