### ISSUE TITLE
November 2023 Contribution - ChrisBck

### ISSUE THREAD

**Issue by chrisbck** [Phala-Network/growth-program#308]
### A. Personal info:
Ambassador Rank: Candidate
Telegram Username: [@chrisbck](https://github.com/chrisbck)
Twitter Url: https://twitter.com/BckChris
PHA Wallet Address: 43ZKJ2DEBagpMyn4EQvTu7niH1xRYGvfCJyGZYZyW6STFCbd
Departments: CC/CM
Department Score Weight: 70/30

### B. Departments:
**CC:**
Again I am focusing mostly on the Alice is Awake project. I have been mostly working on mechanics and working out a system that allows a rudimentary form of Phat Contract integration. I will present a demo to Leechael soon to het his thoughts and possibly some support on this feature.
As part of the intro level there will be a dojo that teaches the basics of the combat system. I have the basics of this sorted out, I am just fleshing out this level now.
Project Activity: https://github.com/chrisbck/Alice-is-Awake/activity
![AiAGIF](https://github.com/Phala-Network/growth-program/assets/32775411/beb255ab-9078-4364-9e59-7fac0eaba46f)

Gator has been a big help with the pixel art again, doing an excellent job with the dojo graphics. We also had a call to discuss the collab in more detail. 

Wrote a thread on the back of Pnin's video he did on Dynamic NFTs. I wanted to add my visions of what can Phat Contracts and NFTs can do and also reinforce that Phala is pioneering this concept of embedding AI into NFTs.
https://twitter.com/BckChris/status/1724997623311171613

**CM:**
Another quiet month for me on the socials. Most attention spent on PhalaWorld. 

![image](https://github.com/Phala-Network/growth-program/assets/32775411/4533421d-e103-43a7-a6b0-ec723dd03f56)

### 3. Supplementary Tasks:
**PM**
Retweet and engage Official Phala and Ambassador tweets.

### 4. Suggested Score:
Overall it has been a busy month on the game but I do not have much to show for it at this point therefore I would suggest a score of 60/100.

**Comment by willphala** [comment]
Nice! Love to hear that you and Gator continue to collab
