### ISSUE TITLE
November 2023 Contribution {infaceAi#5149}

### ISSUE THREAD

**Issue by infaceAi** [Phala-Network/growth-program#310]
PERSONAL INFO
Amb Rank: Senior Ambassador
Discord: infaceAi
Telegram:[ @infaceAi](https://t.me/infaceAi)
Twitter: https://twitter.com/infaceAi
PHA Address: 45vo82ABupacJoafLRW8oVWiYyErk9UqZLpfBn8wtE1zcB4M

Departments : #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

**Contributions:**
MK & CC -  I promote PhalaNetwork & PhatContract on Twitter, Discord & Phala general and local telegram chats & Phala local X account.
I have been doing a lot of support in Phala's main telegram chat.
 
Twitter analytics November 2023 stats:
Twitter analytics and https://analytics.twitter.com/user/infaceAi/home
<img width="629" alt="stats Nov23" src="https://github.com/Phala-Network/growth-program/assets/112633185/5e52686a-f3fc-4b8e-be27-2312afe9698d">

**X main**

<img width="946" alt="X" src="https://github.com/Phala-Network/growth-program/assets/112633185/e2448c73-e571-4e88-b6f7-dc7eb8caa915">
...
<img width="926" alt="X1" src="https://github.com/Phala-Network/growth-program/assets/112633185/0ed17e65-c44f-4030-b7e2-3bc3e658383d">

... 
<img width="953" alt="X2" src="https://github.com/Phala-Network/growth-program/assets/112633185/ef7d2a1c-47bb-421b-8024-6dff62398786">
...
<img width="880" alt="X3" src="https://github.com/Phala-Network/growth-program/assets/112633185/25b0a719-2e13-4558-9eff-d15a262debb2">

**X local**

...
<img width="935" alt="X ukr" src="https://github.com/Phala-Network/growth-program/assets/112633185/032a39a8-2a4d-4121-a92b-1ddd3bd0675a">
...
<img width="925" alt="X ukr1" src="https://github.com/Phala-Network/growth-program/assets/112633185/f18f420c-b125-47da-9975-459e0c87094b">
...
<img width="677" alt="Phala Ukraine" src="https://github.com/Phala-Network/growth-program/assets/112633185/b5a94d61-8bfa-48d0-acd7-2ce93c408c06">
...
<img width="942" alt="Phala Ukraine2" src="https://github.com/Phala-Network/growth-program/assets/112633185/19e4f733-9afe-446d-a553-fb8e2f1089bd">

...
Phala (local) 
https://combot.org/c/1649002165/a

<img width="676" alt="tg nov 23" src="https://github.com/Phala-Network/growth-program/assets/112633185/12006c48-0592-4c02-b782-8d0857d47f4f">

SUPPLEMENTARY TASKS
**#HD (or #CM)**
I did much HD(CM) this month again in Phala (main) telegram. Also I want to say that a lot of high quality work in Phala (main) telegram has been done by CaPPex! 

**#CC** 
I translated 3 articles:
https://medium.com/@PhalaUkraine/c3f82dd4005c
https://medium.com/@PhalaUkraine/dd8fd55c58f5
https://medium.com/@PhalaUkraine/ec82435a749d
And make this Phala FAQ in English based on all info about Phala.
https://medium.com/@PhalaUkraine/phala-network-faq-00558e4c49be

**#ART** 
I continue to play with different art styles. Some of the nice pics here.
https://twitter.com/infaceAi/status/1724749837453963770
https://twitter.com/infaceAi/status/1728209639433494699
https://twitter.com/infaceAi/status/1721429206813253935
https://twitter.com/infaceAi/status/1726502637065896158
https://twitter.com/infaceAi/status/1723976743353290847
https://twitter.com/infaceAi/status/1722147439820362200
https://twitter.com/infaceAi/status/1727956478244376957

**SUGGESTED SCORES**
#CC : 35/40
#MK: 40/40
#HD: 5
#CC: 10
#ART: 10
Overall: 90
I think I worked well in Nov. Also, I want to say that Dmitriy did a very good job in Nov, he was very active in Phala’s Discord and tg.

**Comment by willphala** [comment]
Great work! Kind reminder that your supplementary tasks can't overlap with your department choices. E.g. you can't choose CC (department) and CC (supplementary task) as they're essentially the same thing.
