### ISSUE TITLE
November 2023 Contribution {rafaccc#5473} 

### ISSUE THREAD

**Issue by rafaccc** [Phala-Network/growth-program#311]
Telegram : [rafaccc](https://t.me/rafaccc)
Discord : rafaccc#5473
Dirección PHA: 42LYD29z2f6hYQeuamH5puXTGa1KHhWd6YxYSHXzRjih4xJd
------------------------------------------------------------------------------------------------------------------------

**MARKETING AND CONTENT**

1) https://twitter.com/PhalaEspanol/status/1719801982150463900
Groups where they were published:
https://t.me/polkadotespanol/173112

2) https://twitter.com/PhalaEspanol/status/1724209387382645122?s=20
Groups where they were published:
https://t.me/KusamaESP/69097
https://t.me/polkadotespanol/173864

3) https://twitter.com/PhalaEspanol/status/1725226913814241424
Groups where they were published:
https://t.me/polkadotespanol/173975
https://t.me/KusamaESP/69118

4) https://twitter.com/PhalaEspanol/status/1725683344845795638
Groups where they were published:
https://t.me/polkadotespanol/174065
https://t.me/LetrasCripticas/1/21122

5) https://twitter.com/RafaelCabilla/status/1726372598198706301
Groups where they were published:
https://t.me/polkadotespanol/174136
https://t.me/KusamaESP/69155

6) https://twitter.com/PhalaEspanol/status/1730383526057435541
Groups where they were published:
https://t.me/polkadotespanol/174784
https://t.me/KusamaESP/69281

7) https://twitter.com/RafaelCabilla/status/1729560663394038050
Groups where they were published:
https://t.me/polkadotespanol/174682
https://t.me/KusamaESP/69262
![01P](https://github.com/Phala-Network/growth-program/assets/97988345/7fbb9f1d-8541-4eb8-905b-80cbc7055a1d)

8) https://twitter.com/RafaelCabilla/status/1729975949179990499
![02P](https://github.com/Phala-Network/growth-program/assets/97988345/1987c48c-e3b9-4ec2-a0c5-0e3896d3c70f)

9) https://twitter.com/RafaelCabilla/status/1727859863684882624
![03P](https://github.com/Phala-Network/growth-program/assets/97988345/7cea2d60-04e1-48cd-a6c6-bca7f9e343d9)

10) https://twitter.com/RafaelCabilla/status/1724224332652544083
![04P](https://github.com/Phala-Network/growth-program/assets/97988345/4bcc300a-1145-4dba-b368-6a4c94052567)

11) https://twitter.com/RafaelCabilla/status/1722040758713159852
![05P](https://github.com/Phala-Network/growth-program/assets/97988345/58cb02a2-69c5-4e1b-81c1-1191a3fc65ef)

12) https://twitter.com/RafaelCabilla/status/1724765320823402908
![WALLET](https://github.com/Phala-Network/growth-program/assets/97988345/387b7871-a7a7-4ab5-8f0b-370987f21789)

13) https://twitter.com/RafaelCabilla/status/1725300959125926222
![HALVING](https://github.com/Phala-Network/growth-program/assets/97988345/3a388230-006b-4b2b-9f72-910caf74cf73)

------------------------------------------------------------------------------------------------------------------------

**GIF & MOVIE**

1) https://twitter.com/RafaelCabilla/status/1721380989853696466
![06´P](https://github.com/Phala-Network/growth-program/assets/97988345/e1ac9aa0-5f04-416b-a0cd-1af5e5be8471)

------------------------------------------------------------------------------------------------------------------------

**TWITTER (X)**

https://analytics.twitter.com/user/RafaelCabilla/home
Half of the total Twitter accounts are from Phala, and the statistics doubled compared to the previous month.

![image](https://github.com/Phala-Network/growth-program/assets/97988345/f993069a-4cf5-4649-9c63-4e98d8eb4d9b)

https://docs.google.com/spreadsheets/d/1p948CPSDOTq0EG1s6p4_9NjEf0uguJNvtwordYuBrx0/edit?usp=sharing
![015p](https://github.com/Phala-Network/growth-program/assets/97988345/22a9e124-0937-4992-8bd8-ff261dc7a5f8)

------------------------------------------------------------------------------------------------------------------------
**TELEGRAM**

![image](https://github.com/Phala-Network/growth-program/assets/97988345/fb2b0092-6518-4711-8732-e1e29f20902a)

------------------------------------------------------------------------------------------------------------------------
**AMA SPANISH**

https://twitter.com/PhalaEspanol/status/1729332333046579369
![COM512](https://github.com/Phala-Network/growth-program/assets/97988345/3a357381-fc2a-41c3-b4cc-0a86ddb1880f)

Monthly conversation with the community, great participation with 7 users who participated in the AMA. We talk about Phala, its updates and everything that happened in the month of November.
![AMa pha28](https://github.com/Phala-Network/growth-program/assets/97988345/fb16bc61-aba6-4239-ba7b-4e133f06ee63)

------------------------------------------------------------------------------------------------------------------------
**TRANSLATED ARTICLES SPANISH (8)**

1) https://medium.com/@rafacabilla/potenciando-la-comunicaci%C3%B3n-de-audio-y-v%C3%ADdeo-web3-phala-y-huddle01-unen-fuerzas-2b2c7b1ceff7
2) https://medium.com/@rafacabilla/nft-din%C3%A1mico-cambiador-de-juego-web3-60a0d95004d7
3) https://medium.com/@rafacabilla/avance-de-la-infraestructura-social-web3-phala-y-airstack-celebran-su-asociaci%C3%B3n-66d29c5ab50f
4) https://medium.com/@rafacabilla/contratos-inteligentes-verificados-qu%C3%A9-son-y-por-qu%C3%A9-son-importantes-3e233122dcc2
5) https://medium.com/@rafacabilla/casos-de-uso-de-phat-contract-2-0-resumen-del-d-d-hackathon-40db18b67bf0
6) https://medium.com/@rafacabilla/gu%C3%ADa-nft-din%C3%A1mico-basado-en-el-clima-local-43121219fe29
7) https://medium.com/@rafacabilla/gu%C3%ADa-nft-din%C3%A1micos-y-juegos-de-progresi%C3%B3n-social-web3-fac095d866fc
8) https://medium.com/@rafacabilla/gu%C3%ADa-nft-din%C3%A1micas-que-evolucionan-140d69db701e

------------------------------------------------------------------------------------------------------------------------
**ARTICLE CREATION** : MONTHLY ARTICLE

1) https://medium.com/@rafacabilla/resumen-mensual-de-phala-network-f13c39c5f30e

DIFFUSION
https://twitter.com/PhalaEspanol/status/1730025040509358156
https://t.me/polkadotespanol/174730
https://t.me/KusamaESP/69269

![5NOV](https://github.com/Phala-Network/growth-program/assets/97988345/24ffa8f9-f7bb-4a8e-b6e7-d00483153f60)

------------------------------------------------------------------------------------------------------------------------
**PARTICIPATION IN LABITCONF EVENT - ARGENTINE**

https://twitter.com/PhalaEspanol/status/1723710786789405060?s=20
![512P](https://github.com/Phala-Network/growth-program/assets/97988345/fc7b009c-922e-40ab-9ca0-4ed313273867)

I met with people to talk about Phala technology, gave away stickers, and invited them to join the community.
![1P](https://github.com/Phala-Network/growth-program/assets/97988345/1d2dfac3-854e-4753-9c28-e870bff888fa)
![2P](https://github.com/Phala-Network/growth-program/assets/97988345/de3f651f-fd1d-4831-9c45-05307c97d178)
![3P](https://github.com/Phala-Network/growth-program/assets/97988345/cf4bab7f-ed41-42c4-a433-49300f8d8c5d)
![4P](https://github.com/Phala-Network/growth-program/assets/97988345/fc1f1286-3f7d-4317-ac32-987f39feb254)
![5P](https://github.com/Phala-Network/growth-program/assets/97988345/1de88838-e416-4b66-a113-fbca95e0e78f)
![6P](https://github.com/Phala-Network/growth-program/assets/97988345/ff37bc8c-a124-4d50-9ea5-f390fc0f1f28)
![7P](https://github.com/Phala-Network/growth-program/assets/97988345/8f46b207-4249-4b3c-98e9-77cde8c8a041)
![8P](https://github.com/Phala-Network/growth-program/assets/97988345/9f3c5422-0e28-4d97-afb1-aae5c3ab179d)
------------------------------------------------------------------------------------------------------------------------

**DISCORD TRADING SECTION**
https://discord.com/channels/697726436211163147/940292866876522566/1175617993867264061

![TRADING](https://github.com/Phala-Network/growth-program/assets/97988345/871270f3-9ac9-42a8-9b8b-ab203555a3fd)
I made a comparison table between bitcoin and phala, so that the user can see that the price movements have actually been similar in %, giving the user peace of mind.

------------------------------------------------------------------------------------------------------------------------

MK: 40/40
CC: 40/40
ART: 10/10
EM 10/10
PM 10/10

This month I have developed all aspects to be as complete as possible: from content creation, marketing, event participation, translations, article creation, community help, AMA & monthly call with the community etc. I have made an effort to I can reach 90 points, I hope I can achieve it.

**Comment by willphala** [comment]
Great work. Your charts to put price action into perspective were especially helpful. Congrats. I hope we can have a meeting soon so we can discuss how you can consistently keep your score 90+ moving forwards :)
