### ISSUE TITLE
November Contributions 2023 - Ayomide Bajo

### ISSUE THREAD

**Issue by ayomidebajo** [Phala-Network/growth-program#312]
Telegram username @dev_bekka
twitter url: https://twitter.com/ayomide_bajo
wallet address: 44tESPUBzt5wbrSnT1VHxqKXugWEDBsChG4ybY2GnUR39knc
departments: MK/CC

Contributions
I participated in the Phala Ambassador channel learning how things were done, I joined the community calls and I took some notes on Phala's dynamic NFTs. 

I also promoted Phala on Twitter during my stay in Istanbul where I met the core team members like Zoe and the CTO. I also interacted with Phala Network's Official tweets by sharing and liking them, as well as doing the same for my fellow Ambassador's tweets.

Tweets, Retweets and Likes (links)
https://x.com/ayomide_bajo/status/1724402234954309908?s=46&t=uBdd6OiatuNR4yl1vQ55Rg
https://x.com/ayomide_bajo/status/1724798820108927083?s=46&t=uBdd6OiatuNR4yl1vQ55Rg
https://x.com/phalanetwork/status/1727286786458829075?s=46&t=uBdd6OiatuNR4yl1vQ55Rg
https://x.com/marvin_tong/status/1727389509141286917?s=46&t=uBdd6OiatuNR4yl1vQ55Rg
https://x.com/phalanetwork/status/1727286759195849135?s=46&t=uBdd6OiatuNR4yl1vQ55Rg
https://x.com/PhalaNetwork/status/1727286754024280234?s=20
https://x.com/TheScarletThr/status/1727208313744715808?s=20
https://x.com/zoemcfox/status/1725830297957065146?s=20
https://x.com/zoemcfox/status/1725443027676631499?s=20
https://x.com/zoemcfox/status/1724041637033132282?s=20
https://x.com/marvin_tong/status/1725305327988727821?s=20
https://x.com/zoemcfox/status/1724709710354354557?s=20
https://x.com/PhalaNetwork/status/1722951151132254267?s=20
https://x.com/TheScarletThr/status/1724368392247808275?s=20
https://x.com/PhalaNetwork/status/1722257816654856678?s=20
https://x.com/zoemcfox/status/1721904981580931217?s=20
https://x.com/TheScarletThr/status/1719935771941974371?s=20

Tweet analytics
<img width="1488" alt="Screenshot 2023-12-05 at 08 18 04" src="https://github.com/Phala-Network/growth-program/assets/54250291/6b8d2e67-fc43-45af-8886-a48a04afebe7">
<img width="1068" alt="Screenshot 2023-12-05 at 08 18 27" src="https://github.com/Phala-Network/growth-program/assets/54250291/c94ec84f-a9bb-4c34-b9fc-c09cbc37bb40">
<img width="1172" alt="Screenshot 2023-12-05 at 08 18 38" src="https://github.com/Phala-Network/growth-program/assets/54250291/ae66edfd-227c-422b-b14c-ad4e4b58808f">

I took some pictures of the panel session. These pictures were also used in Phala Network's Official Twitter posts🥳. Here is the post from me:
https://x.com/ayomide_bajo/status/1724798820108927083?s=20

Here are the posts from Phala Network Official Twitter handle:
https://x.com/PhalaNetwork/status/1727286759195849135?s=20
https://x.com/PhalaNetwork/status/1727286786458829075?s=20

In the Phala Africa ambassador (TG) channel, I also monitored the channel, deleted spam messages and interacted with the community. 

Score
Mk: 40
CC: 10
ART: 10
QC: 5

Total = 65

Conclusion
I'm gradually integrating into Phala network's community, I have met some of the core team members and I have been more open to the team members. I have also been promoting Phala network for the first weeks since I joined. Moving forward I'll be creating content like blog posts and threads and improving my content creations in Phala network. I'll continue working towards expanding the Phala Africa community with my fellow ambassadors.

**Comment by willphala** [comment]
Nice work! We look forward to you diving deeper :)
