### ISSUE TITLE
November 2023 Contributions- {the_scarlet_thread} 

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#313]
Amb Rank: Ambassador
Telegram Username: @Scarlet_Thr
Discord Username: @the_scarlet_thread
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

### MANDATORY

💫**CONTENT CREATION** 💫
**Article**
I wrote an article about how Phala Network connects the on-chain world and off-chain world and posted this on Medium. 
https://medium.com/@TheScarletThread/how-phala-network-connects-on-chain-and-off-chain-worlds-17cb1af31253
I made the following graphics for this article:
![20231124_094728_0000](https://github.com/Phala-Network/growth-program/assets/99918790/934fb746-8991-487c-9c68-3a706f6bed68)
![1_20231124_092858_0000](https://github.com/Phala-Network/growth-program/assets/99918790/ea84de37-55ba-4259-9ad3-7dc927ef9991)
![2_20231124_092858_0001](https://github.com/Phala-Network/growth-program/assets/99918790/e8d5c6eb-fce4-40d6-89fc-c7c2e2811d23)
![3_20231124_092858_0002](https://github.com/Phala-Network/growth-program/assets/99918790/c27382d1-ee5e-495c-8fdd-8bd47d5fd528)

**Threads/Long-form posts**
1. I created this thread discussing how Phala takes off-chain computation to the next level. 
https://twitter.com/TheScarletThr/status/1725094232333976017?t=-XEVQmvSnK-xVUQXbpr4PQ&s=19

Made these videos and  graphics for this thread
![20231116_120314_0000](https://github.com/Phala-Network/growth-program/assets/99918790/9d74a850-0ad1-47c7-9ff9-42c54adc040a)

![20231116_120314_0002](https://github.com/Phala-Network/growth-program/assets/99918790/0b6e6e7b-eb9a-4d5e-9273-b5fb9101e8b0)

![20231116_120314_0001](https://github.com/Phala-Network/growth-program/assets/99918790/062e05fd-4d07-444a-b5ba-c251b9fc1661)

https://github.com/Phala-Network/growth-program/assets/99918790/c8e2259f-5583-4427-a9ba-f76ffac4c315

2. I created this thread discussing some use cases that Phat Contract  is currently being implemented in:
https://twitter.com/TheScarletThr/status/1727208313744715808?t=s2lSZWK1PW7Jc7R1NP5hew&s=19

Made these videos and graphics for this thread:

https://github.com/Phala-Network/growth-program/assets/99918790/489ec44d-9f86-4e9f-b2a5-5bec42e12e04

https://github.com/Phala-Network/growth-program/assets/99918790/ad23e564-2b86-41bc-b711-410f98e441ee

![1_20231122_075911_0000](https://github.com/Phala-Network/growth-program/assets/99918790/082cabe7-e007-40fa-b911-acfe59c54ff5)
![3_20231122_075911_0001](https://github.com/Phala-Network/growth-program/assets/99918790/4f205041-fad1-4290-aaf0-fa9bfb722892)
![4_20231122_075911_0002](https://github.com/Phala-Network/growth-program/assets/99918790/a9ea15a3-473a-4369-a132-acd6e7bded39)

3. I wrote this thread for Phala Africa which discussed what Phala is, aimed at Web3 enthusiasts who are new.
https://twitter.com/PhalaAfrica/status/1727031145324564757?t=qmZTzYbwvv4bsxpakcRR7A&s=19

Made these graphics for this thread:
![2_20231121_161118_0000](https://github.com/Phala-Network/growth-program/assets/99918790/3159f021-78b5-4054-b5cc-7a385ca6b2f5)
![3_20231121_161118_0001](https://github.com/Phala-Network/growth-program/assets/99918790/1391a31f-fe74-4c70-a7aa-d75279276ed6)
![4_20231121_161118_0002](https://github.com/Phala-Network/growth-program/assets/99918790/2d3fcc63-7f99-47ad-a005-283645fecf2c)
![5_20231121_161118_0003](https://github.com/Phala-Network/growth-program/assets/99918790/d0ea920e-afe6-47dc-8a60-3f0ce304bd0b)
![6_20231121_161118_0004](https://github.com/Phala-Network/growth-program/assets/99918790/59365880-941f-4336-8d40-ae99084c901f)

4.  Wrote this thread as a recap of my presentation that I gave at the November community call 
https://twitter.com/PhalaAfrica/status/1728144399912051158?t=ljBpVmo4CuKEGA9Vod0m9Q&s=19

5. I wrote this long-form tweet, discussing how Phala Network connects on-chain and off-chain worlds, and linked my article for November.
https://twitter.com/TheScarletThr/status/1728416717913633152?t=N_S9cICtWkCQ8jLiXz3IaQ&s=19

I used an animated version of the graphic I made for the article.

https://github.com/Phala-Network/growth-program/assets/99918790/3370a5c3-eeb4-4b8f-8a6a-e66427c745f2

**Memes** 
I made some memes about Phala and posted them on the server:

1. Drake Meme

https://discord.com/channels/697726436211163147/766661203111575553/1172122706917990420

2. Success Kid

https://discord.com/channels/697726436211163147/766661203111575553/1175927620429422735

3. Galaxy Brain

https://discord.com/channels/697726436211163147/766661203111575553/1173271314916720650

4. Pumped Spongebob

https://discord.com/channels/697726436211163147/766661203111575553/1176528751752904815

5. Distracted Boy Meme

https://discord.com/channels/697726436211163147/766661203111575553/1176811329965793310

6. Gatsby 

https://discord.com/channels/697726436211163147/766661203111575553/1177619406646423622

7. Butterfly 

https://discord.com/channels/697726436211163147/766661203111575553/1178732588811173908

**Infographic** 
I made this infographic which explained the features of Phat Contract Starter Kit.
https://twitter.com/TheScarletThr/status/1722555374409040179?t=5YSAx9UK7vH5dnk0PDTB8g&s=19

I created this infographic, showing features of Phat Contract
https://twitter.com/TheScarletThr/status/1725804930659652085?t=2_OvBrn8EUSKHSZXLjDTsw&s=19

I made this graphic which explains uses of the PHA token
https://twitter.com/TheScarletThr/status/1730186147106599267?t=B0PaBs2rLKqmc6NMaYKZOQ&s=19

**Ambassador Starter Kit**
I've noticed that it may be overwhelming for new ambassadors to learn the ropes so I created  a document called "Ambassador Starter Kit" to help make onboarding easier for new ambassadors and advocates. I outlined some tips, amd guidelines that we follow as ambassadors. Also included important resources and ambassador-only documents. Purpose of this document is to find most of the ambassador  know-how linked in one place.  Other ambassadors have collaborated too, by including a some suggestions in this document.
https://docs.google.com/document/d/12BKZiahFs9mWkqMCOpqvNX6SrAVcq8FfvUUVYHFnO-g/edit?usp=drivesdk

**Community Call** 
This month the call was hosted on Google Meet. I played my role in this call by:

• Guiding the organization of the call; initiated discussions about various aspects of organising and doing tasks;  delegated roles;  brainstorming ideas for the event; and tracked progress

• Maintained constant presence if fellow ambassadors needed assistance. 

• I created the banner to announce this event
![Phala_Africa_November_Banner_2023](https://github.com/Phala-Network/growth-program/assets/99918790/710ae078-4558-4a57-b5c1-65a35b990719)

• Created and gave a presentation on "Dynamic NFTs". 
Content 
https://docs.google.com/document/d/1siFO4JchluHvOw3ZRNvnAViFm_oGJBd39Zdk__n5EEg/edit?usp=drivesdk

Slides: 
https://docs.google.com/presentation/d/1i-w1iaqF5KfBMDO5GnE0WLg_M0HIE9UGJVxOgplCpWA/edit?usp=drivesdk

• As a group, we decided to have the quiz event to boost engagement and make the call fun. All the ambassadors contributed to the pool of 400 PHA. I created the three questions based on my presentation, which I gave to Favour who announced them and made three slides. I created the Google Form which we used to collect answers and feedback, we got some good feedback and new participants.  I sent the rewards to the winners and followed up. Thereafter I evaluated the feedback we got and made some notes on ideas to implement for the local community. We did get a little engagememt after the call, on the Telegram. Overall, the quiz made the call more fun but helped participants to remember what was discussed.
![Screenshot_20231205-140425_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/90781b9f-9e60-406c-b2fa-6745d0f6dc70)
![Screenshot_20231205-140429_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/4f42dee9-99ae-49c9-9ae4-66adf8921560)
![Screenshot_20231205-140435_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/2c266cf3-0066-48ce-b4e9-3d576b327685)
![Screenshot_20231205-140439_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/626a5ca5-0bb3-45ff-833b-005129e216d4)

**GOOD POINTS**
I created a helpful document that can be used to refer to ambassador guidelines and onboard more easily. Also, pleased that I was more creative in the graphics that I created. Even though I had a very stressful month, I still managed to create enough content and focused on the details/ wrote for the various audiences that piece was targeting. 

**BAD POINTS**
I didn't create as many infographics as I was aiming for, and my X stats didn't grow according to plan. 

**HOW TO IMPROVE**
Set a reasonable plan to grow my X stats for each post, to ensure they reach a wider audience. Create and post more infographics and content that offers different insight to Phala and Phat Contract and is interesting to read.

💫**COMMUNITY MANAGEMENT**💫

• Helpdesk and moderation. I assisted in monitoring the PhalaWorld, Phala Telegram, Phala Africa Telegram, and Phala Discord in order to eliminate spam, malicious content and answer questions of the community. 

Addressing and resolving negative feedback when I can.  I have also been looking at discussions on X regarding Phala and what the community sentiment is, and conveying this to team via community channel. 

Some examples:
![Screenshot_20231205-154939_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/340cab2d-3e83-46f5-93d1-fd9573590bf7)
![Screenshot_20231205-154955_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/0a92cc0c-7fc9-425b-946d-efab8761f1e9)
![Screenshot_20231205-155030_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/dec4d15d-bf6e-4034-978f-e64a1b1f546c)
![Screenshot_20231205-155046_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/bad315e2-9bc0-4097-9ae0-b60cb2951ae9)
![Screenshot_20231205-155112_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/cc1e3cdd-ec8d-4096-b3d7-ff4de1d1fdf4)
![Screenshot_20231205-154934_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/558b96d9-175d-4878-bed8-9d1d387208cb)
![Screenshot_20231205-161631_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/4ee1c464-f741-4603-8003-f4c8b133aa4c)
![Screenshot_20231205-161647_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/ea2beba5-f0ca-4e5b-bf1f-ae7a349c5331)
![Screenshot_20231205-161701_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/1368cf35-8aa2-43ba-9d16-7af01ec98d95)
![Screenshot_20231205-161653_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/f55546a4-4b9f-4268-8987-906f38acb3c5)

•  Managing Phala Africa 
Assisting new ambassadors with  learning the system that we use, learning about Phala Network, provided guidance and assistance with various Phala related aspects. I've also been working closely with our  new advocate who has shown much enthusiasm. Also evaluated their performance and gave feedback so that they can grow and work towards being an ambassador.

Providing guidance, feedback and assistance to Phala Africa ambassadors, delegating tasks and tracking progress being done. Evaluating areas of strength and what needs to be improved . 

Research, planning and creating strategies to grow the community and ways that our Phala Africa team can improve collaboration within the team and increase output. Also I have been evaluating our efforts, to find what works best and what doesn't.

• Share helpful resources to community about Phala and partners.

• Participated in community ambassador channel, offering feedback.

• Stats
![Screenshot_20231205-155744_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/4efbc7b9-5097-4281-a630-b0f46ff29a5c)
![Screenshot_20231205-160120_Discord-01](https://github.com/Phala-Network/growth-program/assets/99918790/7ae4f6c8-56d8-4627-bc05-47f63260d59c)
![Screenshot_20231205-155341_Chrome-01](https://github.com/Phala-Network/growth-program/assets/99918790/c26d6a85-b610-49c3-ac06-b3cedea59b5e)
![Screenshot_20231205-155535_Chrome-01](https://github.com/Phala-Network/growth-program/assets/99918790/76226995-8591-4d21-b3f2-bf13fed3eb76)

**GOOD POINTS**
We implemented a small change in the way we do  the community call this month, where we decreased the number of presentations, included a fun activity and allowed time for questions. This lead to an improvement in engagement. Attendance wasn't what I would have liked but it was certainly an improvement. I provided a lot of assistance in Phala Africa.

**BAD POINTS**
I wasn't as active as I wanted to be on the Phala Telegram. I did engage in that channel but not as much as I wanted. 

**HOW TO IMPROVE**
Allocate time to engage on Phala  Global Telegram so I can talk with community members, answer questions, manaintain constant presence in the Phala Global Telegram.

### SUPPLEMENTARY 

💫**PM**💫

Throughout November, I remained dedicated to contributing to Phala Network's visibility and impact across various platforms. Beyond  promoting Phala, I worked on showcasing its revolutionary aspects through posting on Twitter, Telegram and Discord. I actively engaged with the community by consistently sharing updates and initiating insightful discussions about Phat Contracts and PhalaWorld, aiming to provide valuable educational content and foster a vibrant atmosphere within the community. I've also engaged through liking, commenting and retweeting content from: Phala Network ambassadors, Partners, Phala Network Twitter, fellow ambassadors and Phala Team members. I promoted events that Phala had, updates and various forms of content.
![Screenshot_20231205-163405_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/8dc04870-e86d-4d7e-8b14-4e5a7dad4e29)
![Screenshot_20231205-163423_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/f871d293-e8d5-4435-bcb0-d984594f00c3)

**SCORES**
**CC** 40/40
**CM** 40/40
**PM** 10/10
**TOTAL** 90

CLOSING COMMENTS
This month there was a lot of price talk from community, I saw this as an opportunity to work on my skill in addressing negative sentiment, identifying and removing scams faster etc. 
I will work together with Phala Africa team to improve our community engagement and host some fun events for the community. We started posting more content on the Phala X account, and will continue to improve that. As always, I will work on showing progress in the quality and quantity of my contributions. 

Thank you very much 

Scarlet

**Comment by willphala** [comment]
Great work!
