### ISSUE TITLE
November 2023 Contribution - Gabekoin

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#314]
Telegram : @gabekoin
Discord : gabekoin
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of Nov:
Ambassador

CONTENT (CC):40/40

**Articles Created:**
FaaS:
https://medium.com/@phalaptbr/pioneirismo-em-faas-descentralizado-com-o-pc-2-0-83b4ea82ba7e

PhatContract e dNFT:
https://medium.com/@phalaptbr/phat-contract-e-o-futuro-dos-nfts-din%C3%A2micos-dnft-6cde705d6f61

**Threads created:**
dNFT eng article:
https://x.com/gabekoin/status/1729162496806948900?s=20

dNFT full:
https://x.com/gabekoin/status/1727391400797548864?s=20

FaaS:
https://x.com/phalaportugues/status/1720429803940057199?s=20

FaaS Eng:
https://twitter.com/gabekoin/status/1721168515250470976

Dive deep:
https://x.com/gabekoin/status/1721901607460430207?s=20

dNFT:
https://twitter.com/gabekoin/status/1722258293656289595

Zoe Event:
https://x.com/gabekoin/status/1724090571000533325?s=20

LensApi Workshop:
https://twitter.com/gabekoin/status/1724484956359942482

nft nomad:
https://twitter.com/gabekoin/status/1725152880741494909

Cyptoday:
https://vxtwitter.com/gabekoin/status/1725592107035865244

O Que são nfts dinamicos:
https://x.com/phalaportugues/status/1726965301131292960?s=20

Don trust, Verify:
https://vxtwitter.com/gabekoin/status/1728144307985518619?s=20

**Articles Translated:**
Contratos inteligentes verificados:
https://x.com/phalaportugues/status/1722370723153359223?s=20

FAQ:
https://medium.com/@phalaptbr/phala-network-faq-baf98601f724

**Threads Translated:**

Review Istanbul:
https://twitter.com/phalaportugues/status/1727324916343619947

 #InDEX:
[https://twitter.com/phalaportugues/status/1724795880287662527](https://vxtwitter.com/phalaportugues/status/1724795880287662527)

Huddle:
https://x.com/phalaportugues/status/1719764329635979577?s=20

Phat Contract 2.0 in action.
https://x.com/gabekoin/status/1720411722182262911?s=20

3 parceria:
https://x.com/phalaportugues/status/1721560694972150264?s=20

dNFT:
https://x.com/gabekoin/status/1722258293656289595?s=20

Istambul:
https://x.com/phalaportugues/status/1722259823809757562?s=20

Série de conteúdo:
https://twitter.com/phalaportugues/status/1722619374794895709

eth devconnect:
https://x.com/phalaportugues/status/1725163504770908310?s=20

**LINKEDIN POSTS CREATED:**
PhatContract e dNFT:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phat-contract-e-o-futuro-dos-nfts-din%C3%A2micos-activity-7133823367945568256-lFM2?utm_source=share&utm_medium=member_desktop

#Web3📷 group in #Curitiba:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phatcontract-web3-curitiba-activity-7131643989794902019-TAm9?utm_source=share&utm_medium=member_desktop

Phat 2.0 showcase:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-dont-miss-out-on-a-live-demo-activity-7126211020682911745-obkk?utm_source=share&utm_medium=member_desktop

FaaS:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_pioneirismo-em-faas-descentralizado-com-o-activity-7127016871492526080-1huS?utm_source=share&utm_medium=member_desktop

Dive deep:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_bkv-novz-azr-activity-7127667681213788161-UrBL?utm_source=share&utm_medium=member_desktop

dNFT:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_dynamic-nft-web3-game-changer-activity-7128029265417109505-2r_p?utm_source=share&utm_medium=member_desktop

Istambul:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-on-x-activity-7128029664920358912-SgK_?utm_source=share&utm_medium=member_desktop

Infragarden:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_devconnect-2023-infra-gardens-istanbul-activity-7128739964598558720-7GAi?utm_source=share&utm_medium=member_desktop

EfDevonnect:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-has-arrived-at-efdevconnect-activity-7130006880331964416-nXE6?utm_source=share&utm_medium=member_desktop

Polkadex referendum
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_the-first-ever-democratic-polkadex-orderbook-activity-7132732240832135169-BmJ8?utm_source=share&utm_medium=member_desktop

![image](https://github.com/Phala-Network/growth-program/assets/112413448/93154f25-991b-4736-a867-e3946e207c10)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/f8280864-0aa4-463d-bff7-6f6588146b9c)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/7bf8a039-f051-4755-87ca-0be9a6528857)

COMMUNITY (CM): 36/40
**Phala Global:**
![image](https://github.com/Phala-Network/growth-program/assets/112413448/4d0c81d0-36d0-4767-a717-9e6e9e259df6)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/2f1492c0-b0cd-4a70-9f79-da29ad1287f5)

**Phala Portuguese:**
![image](https://github.com/Phala-Network/growth-program/assets/112413448/5973a17a-4b25-4c2c-bc1b-a0aa21bb016e)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/a43ee834-a84f-4cee-bd08-e5bb890eac5e)

![1](https://github.com/Phala-Network/growth-program/assets/112413448/bd36e2c3-5041-4f6d-af03-3f9ab2b42699)
![2](https://github.com/Phala-Network/growth-program/assets/112413448/acb4c571-51cc-452c-9151-2498aed9b5aa)
![3](https://github.com/Phala-Network/growth-program/assets/112413448/a61d511f-6ace-431c-ba45-89ee575628b3)
![4](https://github.com/Phala-Network/growth-program/assets/112413448/544ae5fd-d557-42ef-b380-1bb8b20c61da)
![5](https://github.com/Phala-Network/growth-program/assets/112413448/f6a8669e-1996-495d-9fc9-4c7e07839a49)
![6](https://github.com/Phala-Network/growth-program/assets/112413448/a86951aa-1b22-45c2-9a27-e7963e5e826a)
![7](https://github.com/Phala-Network/growth-program/assets/112413448/8c096080-92a8-4145-8165-f3524e7df3eb)
![7](https://github.com/Phala-Network/growth-program/assets/112413448/6f3be605-bc33-4534-9f7d-651f30f9cb5c)
![8](https://github.com/Phala-Network/growth-program/assets/112413448/78deac91-4c62-4ac1-b82e-89fee223b532)
![9](https://github.com/Phala-Network/growth-program/assets/112413448/3b78826c-0ac2-472b-87a7-65d31e6a1c60)
![10](https://github.com/Phala-Network/growth-program/assets/112413448/51ca85b0-5968-46c2-9697-4e97d4b33f7e)
![11](https://github.com/Phala-Network/growth-program/assets/112413448/4dbb1ffe-ebea-460d-8da0-5b5a517750e9)
![12](https://github.com/Phala-Network/growth-program/assets/112413448/d812fb40-6619-464b-8f1a-863ca0ab2309)
![13](https://github.com/Phala-Network/growth-program/assets/112413448/4e33ca90-5868-4dca-9c43-d77095400246)
![13](https://github.com/Phala-Network/growth-program/assets/112413448/b5bbe1f9-536b-467c-9570-abf71fca46e1)
![14](https://github.com/Phala-Network/growth-program/assets/112413448/568c3d94-38b7-44f1-ae70-ed9045c2b4c0)
![15](https://github.com/Phala-Network/growth-program/assets/112413448/305ca245-4c31-453b-b44b-21d2ef6c3315)
![16](https://github.com/Phala-Network/growth-program/assets/112413448/28a7cf60-dff3-4a21-8532-545c70cd490a)
![17](https://github.com/Phala-Network/growth-program/assets/112413448/30c567bb-5ab7-413f-9fe8-55e6282751b8)

Supplementary: ART & PM (16/20)

**ART: 8/10**

Dnft ingles:
https://twitter.com/gabekoin/status/1724780733523497265
![image](https://github.com/Phala-Network/growth-program/assets/112413448/62ce7e6a-c9ce-4452-989d-e922e9b17553)

Dont trust verify:
https://vxtwitter.com/gabekoin/status/1728144307985518619?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/bb29fbe5-5b51-4ea7-a349-12500d098f43)

Infographic dnft:
https://twitter.com/phalaportugues/status/1723697889283580335
![image](https://github.com/Phala-Network/growth-program/assets/112413448/08d9c385-b836-4308-b95c-e6ebe8323f1b)

FAAS:
https://vxtwitter.com/phalaportugues/status/1726634772192248006?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/c75a83ad-f1f3-4c88-80f3-c7588ce5be5d)

**PM: 8/10**
**Tweets (RT & LIKE):**

https://x.com/marvin_tong/status/1720468467428831296?s=20
https://twitter.com/PhalaNetwork/status/1721585312407732711
https://x.com/hashwarlock/status/1721923150693490809?s=20
https://x.com/test_ut/status/1721839804332044464?s=20
https://twitter.com/PhalaNetwork/status/1722257816654856678
https://x.com/PhalaNetwork/status/1725161702071611858?s=20
https://twitter.com/gabekoin/status/1722973205076361242
https://x.com/PhalaNetwork/status/1722951151132254267?s=20
https://x.com/DIAdata_org/status/1725114486112084136?s=20
https://twitter.com/gabekoin/status/1723709886062559253
https://x.com/PhalaNetwork/status/1724790790583718304?s=20
https://x.com/parachainboy/status/1729485041992966444?s=20
https://x.com/gabekoin/status/1729263721049145762?s=20
https://x.com/zoemcfox/status/1725830297957065146?s=20
https://twitter.com/gabekoin/status/1726703180422295840

**LINKEDIN RT:**
https://x.com/gabekoin/status/1720411722182262911?s=20
https://www.linkedin.com/posts/joshua-waller-33935773_upgrade-your-smart-contracts-with-phat-contract-activity-7127795336185593856-yJ1K?utm_source=share&utm_medium=member_desktop

**EM:**

**Cyptoday:**
https://vxtwitter.com/gabekoin/status/1725592107035865244

![image](https://github.com/Phala-Network/growth-program/assets/112413448/7338e6fb-b300-4edb-8390-6011dbbc994e)

**Monthly Spaces:**
https://x.com/phalaportugues/status/1729960125954228734?s=20

![image](https://github.com/Phala-Network/growth-program/assets/112413448/b92411ed-1f68-4b1b-882a-0fdc41cd0a24)

Suggested scores:
[CC] 40/40
This month was incredible, I've created many content and had a great reach/engagement.
For next month keep the good work and try to reach more people

[CM] 36/40
This month our Telegram/Discord were way more active and many new users, that's amazing.
Brasilian community keep growing and we have noticed more ppl asking about staking.
Keep growing our local community

[ART] 8/10
Created 4 infographics for Brazilian community and we had good interactions too

[PM] 8/10
Shared all oficial content in all main social medias.

[EM] --
We had the opportunity to present Phala during a local meeting in our city and it was great.

We hosted our monthy recap on Twitter Spaces, good attendance.

Overall suggested score: 92/100.

Totally happy about this month, seen some new users and thats great!
Noticed some people interessed on PhatContract and I've doing my best to help them onboard into Phala

For the next month: Do better

**Comment by willphala** [comment]
Good work!!
