### ISSUE TITLE
November 2023 Contribution - defiguy

### ISSUE THREAD

**Issue by astardefi** [Phala-Network/growth-program#316]
Telegram Username: @defiguy2022

AMB Rank: Candidate Ambassador

Discord Username: defiguy

Twitter Username: @defiguy22

PHA Wallet Address: 44PTq2ZCxXxPM3FYubiPtMw53WCXNdXUfNDnCE6c7wFixMbB

Departments: #CC / #CM

# Contributions

I helped spread information about Phala Network on Twitter, reaching thousands of users. I also created content for a more specialized audience on LinkedIn using infographics. Additionally, I established an account for the Brazilian community on TikTok.

I provide weekly updates on my YouTube channel https://www.youtube.com/watch?v=z577xf6aT70 about the Polkadot ecosystem and have a segment dedicated to sharing updates on Phala Network. **Average views close to 300**

![Screen Shot 2023-12-05 at 16 40 00](https://github.com/Phala-Network/growth-program/assets/104277195/1584bfa2-ce54-4941-a3c8-c2420ee430ee)

# Supplementary Tasks

# PM

## Partnership with Phala on Neurolanche projects (Astar Strike and Firolauss)

![image](https://github.com/Phala-Network/growth-program/assets/104277195/1a426506-aed7-44aa-bda3-063c00d0454a)

Link - https://twitter.com/defiguy22/status/1729491319997726947

# ART

# CC

## Retweets
![Screen Shot 2023-12-05 at 14 52 24](https://github.com/Phala-Network/growth-program/assets/104277195/dd963e6a-6cfd-40bd-aeef-51e57c1d6138)

![Screen Shot 2023-12-05 at 16 28 08](https://github.com/Phala-Network/growth-program/assets/104277195/4e87a294-425c-4e10-98fb-6ebc6294e217)

## Tweets
**1180 views**
https://twitter.com/defiguy22/status/1727298841416695830
**485 views**
![Screen Shot 2023-12-05 at 14 53 36](https://github.com/Phala-Network/growth-program/assets/104277195/57650747-b745-43a8-b12e-31e9b37b514a)

https://twitter.com/defiguy22/status/1726683658877083831

![Screen Shot 2023-12-05 at 16 26 59](https://github.com/Phala-Network/growth-program/assets/104277195/37f354e4-2195-4efb-a33d-28682585da2a)
https://twitter.com/defiguy22/status/1724797846682219004

## INTERVIEWS

![image](https://github.com/Phala-Network/growth-program/assets/104277195/b3d77053-b3c3-4f6d-a7a7-622753f84668)
https://www.youtube.com/watch?v=YfghnUWwX04

## PHALA SEGMENT 
![Screen Shot 2023-12-05 at 16 33 58](https://github.com/Phala-Network/growth-program/assets/104277195/e8ea3d81-0674-4a8d-8eb4-b958a35ef023)
https://www.youtube.com/watch?v=7mWtn5MWmy4

![Screen Shot 2023-12-05 at 16 35 30](https://github.com/Phala-Network/growth-program/assets/104277195/7b4f5cd6-1ebc-40c4-ac0a-30f692b219d1)
https://youtu.be/bLJBNBFL1ec?t=3413

![Screen Shot 2023-12-05 at 16 36 33](https://github.com/Phala-Network/growth-program/assets/104277195/5278b667-f577-4133-9b74-91f5be881837)
https://youtu.be/TZtTy1yG52s?t=2560

# HD

## SPAM REPORT 

![HD-phala](https://github.com/Phala-Network/growth-program/assets/104277195/f1c6eb1f-edb8-4418-9245-30158494d55f)

## Community updated about Phala on my Telegram group (portuguese/brazilian community)
![Screen Shot 2023-12-05 at 13 45 00](https://github.com/Phala-Network/growth-program/assets/104277195/a861dcff-bbb2-4808-b95e-57c0fd94d6bd)

Suggested Scores:

#CC: 35/40

#СМ: 30/40

#CC: 7

#HD : 2

Overall: 74

All ambassadors must select 2/4 of the following departments.

**Comment by willphala** [comment]
Good work!
