### ISSUE TITLE
November 2023 contribution - {pigro85#6032}

### ISSUE THREAD

**Issue by pigro85** [Phala-Network/growth-program#317]
Telegram: Pigro85
Discord: pigro85#6032
Twitter: https://twitter.com/pigro85
PHA Wallet Address: 44Rc9bxvmfyVJx1qmKThhUXUCuyhU6tqULvM5QKxtxks19uH

[CM]
Phala Italian Channel link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a

Phala Mining Channel link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a

Phala Network Official link: https://t.me/phalanetwork
Combot Link: https://combot.org/c/1421178003/a

I'm slowly retrarting my acrivieties on phala network.
Have I participated in Discord Channel Moderation? Not so active on discord this month.
Have I participated in Telegram Channel Moderation? Yes
Standard chat operations and a still continuing banning huge amount of spammers/bot.

[CC]
Past month just translated an article but I had no report, I'm restarting my activities kn Phala.

[MK]
Minimal activity on twitter 

SUGGESTED SCORES

CM: 15
CC : 0
MK : 0

**Comment by willphala** [comment]
Excellent news! Welcome back. Take your time :)
