### ISSUE TITLE
November 2023 contribution - {102j#2259}

### ISSUE THREAD

**Issue by ZunkCii** [Phala-Network/growth-program#318]
Telegram : @j102j
Discord : @102j#2259
PHA Address : 3zkfLRrjyCy33f9xTNHDwAEjdjJknx4W6ZQ6GVTk5ffJcpck

Have I participated in Telegram Channel Moderation (choose)? Yes

CM

Phala Korean Channel link: https://t.me/phalakorean
Combot Link : https://combot.org/c/-1001340032853
<img width="1211" alt="image" src="https://github.com/Phala-Network/growth-program/assets/96286632/0b966127-dd77-4608-b59b-6a1f5c261bb7">

VSM
Twitter as Official Ambassador : https://twitter.com/ZunkCii
Analytic : https://analytics.twitter.com/user/ZunkCii/tweets

<img width="1189" alt="image" src="https://github.com/Phala-Network/growth-program/assets/96286632/1352218a-816b-4e7c-84e7-02702db09ca1">
<img width="1189" alt="image" src="https://github.com/Phala-Network/growth-program/assets/96286632/67790e53-8f5c-4917-96bd-aad5daa7eace">

Unfortunately, I couldn't do much last month.

**Comment by willphala** [comment]
Hi. Can you please update your reports with the new report structure and relevant departments? Thanks!

**Comment by ZunkCii** [comment]
> Hi. Can you please update your reports with the new report structure and relevant departments? Thanks!

Can you tell me the new report structure?

**Comment by willphala** [comment]
You can find it at the bottom of the page. If you need any assistance please message me on telegram @willcottrell https://github.com/Phala-Network/growth-program
