### ISSUE TITLE
November 2023 Contributions - {Rom1.io#5329}

### ISSUE THREAD

**Issue by xcRom1** [Phala-Network/growth-program#322]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/63704652/216827308-dd6a24be-5517-4e09-9c0e-c65a763aca3b.png">

Amb Rank : Ambassador
Telegram Username: https://t.me/Imo_999
Discord Username: Rom1.io#5329
Twitter Username: https://twitter.com/RCajina
PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q

Departments : #CM & #MK

**Contributions:**

Hello, it's been a quiet month for me, but I've still contributed to the community, doing a few translations.

![image](https://user-images.githubusercontent.com/63704652/222117520-bf30a95b-18be-44e8-9e0f-aad3e09f879c.png)

Twitter analytics: [Here](https://analytics.twitter.com/user/RCajina/home)

<img width="1017" alt="image" src="https://github.com/Phala-Network/growth-program/assets/63704652/32386c3a-d685-4f71-b946-616ad826f100">

![image](https://user-images.githubusercontent.com/63704652/222134127-67fe6ec1-f49c-43d7-a391-f681d8d5a87e.png)

Here are the translations I made with a total of **2079** words  : 

- [Cas d’utilisation du Contrat Phat 2.0 : Récapitulation du hackathon D_D](https://medium.com/phala-fran%C3%A7ais/cas-dutilisation-du-contrat-phat-2-0-r%C3%A9capitulation-du-hackathon-d-d-40892015fa33) 

![image](https://user-images.githubusercontent.com/63704652/222134855-7eff0b13-3d74-4aad-a848-63d581a00c44.png)

## SUGGESTED SCORES
#CM: 20/40
#MK: 20/40

Other:
#CC: 10/10

Overall : 50

***Quote*** : "If you look closely, most overnight successes take a long time." - Henri David Thoreau

**Comment by willphala** [comment]
Love the quotes!
