### ISSUE TITLE
November 2023 Contributions - (johnrhodel#8162)

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#324]
Telegram Username: https://t.me/parachainboy
Discord Username: johnrhodel#8162
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

CC : 40/40

Presentation Pattern for Lives, meetups and classes:(add tokenomics part)

https://docs.google.com/presentation/d/1xi1qnGNHwxMtx6SOOYcAhyIHbxd0FHjQGjd5_6QJ3Xs/edit?usp=sharing

Translated/Created/ Reviewed Articles Portuguese/Filipino

Portuguese:

https://medium.com/@phalaptbr/guia-nft-din%C3%A2mico-baseado-no-clima-local-0c545de3936b
https://medium.com/@phalaptbr/avan%C3%A7ando-a-infraestrutura-social-da-web3-phala-e-airstack-celebram-parceria-4d3ede9f7d3a
https://medium.com/@phalaptbr/impulsionando-a-comunica%C3%A7%C3%A3o-de-%C3%A1udio-e-v%C3%ADdeo-web3-phala-e-huddle01-unem-for%C3%A7as-0573f4b78a2a
https://medium.com/@phalaptbr/casos-de-uso-do-phat-contract-2-0-d-d-hackathon-recap-045dfcb5a671
https://medium.com/@phalaptbr/phat-contract-e-o-futuro-dos-nfts-din%C3%A2micos-dnft-6cde705d6f61

Filipino:

https://polkaverse.com/11194/mga-kaso-ng-paggamit-ng-phat-contract-2-0-d-d-hackathon-40206
https://polkaverse.com/11194/ano-ang-mga-dynamic-na-nft-40207
https://polkaverse.com/11194/pinapagana-ang-web3-audio-at-video-communication-phala-at-40208
https://polkaverse.com/11194/pagsulong-ng-web3-social-infrastructure-phala-at-airstack-40209
https://polkaverse.com/11194/gabay-dynamic-na-nft-batay-sa-lokal-na-panahon-40210

MK(36/40)

Event - Meet up About Polkadot in Honey Island - Phala Introduction

![IMG_4509](https://github.com/Phala-Network/growth-program/assets/77474076/a1df3112-7ced-4d15-8969-3aa7060a25d2)
![IMG_4510](https://github.com/Phala-Network/growth-program/assets/77474076/86f997e5-18b7-40b9-a8e2-389b92175bde)
![IMG_4515](https://github.com/Phala-Network/growth-program/assets/77474076/619f9a8c-e3fb-42ae-b2ea-c7bec5a001e4)

RT/LIKE/Post 

![Captura de tela 2023-12-06 234026](https://github.com/Phala-Network/growth-program/assets/77474076/47f8bc9a-dce6-45cb-84fa-0b4af433d098)

https://twitter.com/phalaportugues/status/1719764329635979577
https://twitter.com/phalaportugues/status/1720429803940057199
https://twitter.com/phalaportugues/status/1721560694972150264
https://twitter.com/phalaportugues/status/1721902256449298548
https://twitter.com/phalaportugues/status/1722257017010893275
https://twitter.com/phalaportugues/status/1722259838326202521
https://twitter.com/phalaportugues/status/1722370723153359223
https://x.com/phalaportugues/status/1722619374794895709?s=20
https://twitter.com/phalaportugues/status/1727324940318233032
https://twitter.com/phalaportugues/status/1727324920021946582
https://twitter.com/phalaportugues/status/1727324916343619947
https://twitter.com/parachainboy/status/1729485041992966444
https://twitter.com/parachainboy/status/1728857614812086424
https://twitter.com/phalaportugues/status/1729960125954228734

Youtube live with Artur Guimarães - https://www.youtube.com/watch?v=LNCXNg3uKSU

![Captura de tela 2023-12-07 000603](https://github.com/Phala-Network/growth-program/assets/77474076/cf42c519-0020-4a9a-9aef-65e1138fb0d4)
![Captura de tela 2023-12-07 000640](https://github.com/Phala-Network/growth-program/assets/77474076/e431e9ca-f47f-497c-a8cb-f5ac21a9f3a1)
![Captura de tela 2023-12-07 000715](https://github.com/Phala-Network/growth-program/assets/77474076/dfd022d2-1c05-4776-bad6-55a0945aa812)

Spaces - https://twitter.com/i/spaces/1yNxaZDQgBNKj?s=20
![photo_2023-12-06_23-55-55](https://github.com/Phala-Network/growth-program/assets/77474076/e2c81efb-fef7-477a-bbed-02745a42c4b5)

HD(10/10)

![Phala 5](https://github.com/Phala-Network/growth-program/assets/77474076/1d6acd03-dbf5-46a0-8bd2-61d04154869c)
![phala 6](https://github.com/Phala-Network/growth-program/assets/77474076/b0d97540-82a4-4272-8f1b-07228d14182d)
![photo_2023-12-01_08-49-44](https://github.com/Phala-Network/growth-program/assets/77474076/89888258-0f84-4428-9832-aeff88f42c50)
![photo_2023-12-01_08-49-45](https://github.com/Phala-Network/growth-program/assets/77474076/8db0190b-c681-4da6-a092-c0189f84a980)
![photo_2023-12-01_08-49-46](https://github.com/Phala-Network/growth-program/assets/77474076/a9c7332f-e4a6-4ae3-bead-8b534c4c1985)
![photo_2023-12-01_08-49-47](https://github.com/Phala-Network/growth-program/assets/77474076/d7cbae1f-1e10-4997-9f02-e3d2bccb7ed3)
![photo_2023-12-06_12-38-06 (2)](https://github.com/Phala-Network/growth-program/assets/77474076/7437c90e-40a9-404d-8c00-ffbbccf1db00)
![photo_2023-12-06_12-38-06](https://github.com/Phala-Network/growth-program/assets/77474076/695612da-993c-4627-a9ed-68ea45b15d7c)

ART(8/10)

![1](https://github.com/Phala-Network/growth-program/assets/77474076/536c813b-3b12-4be8-89d6-fcff83f531bc)
![2](https://github.com/Phala-Network/growth-program/assets/77474076/6923170a-e2b5-4af6-bb85-e7fb74c7a9b3)
![3](https://github.com/Phala-Network/growth-program/assets/77474076/117335a2-46c8-48f7-8660-1912f92a22b3)
![4](https://github.com/Phala-Network/growth-program/assets/77474076/52697a3a-bdc1-4088-b9de-2dd47331721d)

FEEDBACK:

This has been one of the most challenging months due to health reasons, but I managed to maintain my frequency and do my best. I want to improve every day as a Phala ambassador. In the coming months, I plan to delve more into the technical aspects and become increasingly proficient as an ambassador, and perhaps embark on my first projects on the network.

My score for this month would be 94!

**Comment by willphala** [comment]
Excellent work. I am sorry to hear about your health issues and I hope that you recover soon! 

Please note that your department choices can't overlap with your supplementary tasks. E.g. you can't choose CC (department) and ART as a supplementary task as they have major overlap. 

I look forward to seeing these technical advancements, which would be very valuable for our team :)
