### ISSUE TITLE
December 2023 report Gatorkorps

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#328]
Happy new years :)

Telegram Username: @gatorkorps
Discord Username: gatorkorps
Twitter Username: https://twitter.com/gk18_dog
PHA Wallet Address: 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV

A quiet month because I was more focus on family and christmas.

I was really happy finally to see Phala integrated the omnipool of hydraDX to facilitate toekn exchange and PHA newcomers on our ecosystem.
I proposed it the first time the 5th april 2023 : 
![image](https://github.com/Phala-Network/growth-program/assets/82824139/29b11d1f-bde5-4650-9c7d-cf40ca28ce68)

Community:

Phalafr twitter account management
phalaFR telegram
and ban several shitcoin chiller on the mainb Phalanetwork TG

Marketing 

PHA chilling:
https://twitter.com/gk18_dog/status/1741241230506213608
https://twitter.com/gk18_dog/status/1735291125705896024
https://twitter.com/gk18_dog/status/1735170185777008708
https://twitter.com/gk18_dog/status/1732416659602972744

OP Chain of Block
https://twitter.com/gk18_dog/status/1733520269615010175 Ask [A Chain of Blocks](https://twitter.com/ACOBJason)
[@ACOBJason](https://twitter.com/ACOBJason) to do a video about phala and with the support of Cappex it was a succes.
I would say one of my best marketing OP only with a short message and some support.

Result https://twitter.com/ACOBJason/status/1735380429086310736 more than 16k view and one of the better explanation of Phala.

I will no tlist all the main account amplification by my own account and the Phala French account.

Translation of an article:
https://medium.com/phala-fran%C3%A7ais/web3-social-cr%C3%A9er-et-mon%C3%A9tiser-avec-des-contrats-intelligents-c7e730ad62d5

CC Content Creator

I continue to help chris to create the pixel art picture for the PhalaWorld game, focusing on new stage and room.
Good progress and a cool activity.

![dojo_interior_placeholder gator3](https://github.com/Phala-Network/growth-program/assets/82824139/c42afec9-2250-47d5-9eb1-f9f59f80eb2e)

![doj_outside](https://github.com/Phala-Network/growth-program/assets/82824139/f4e1112b-e79f-487e-98d9-293f3d1a757f)

![proto2](https://github.com/Phala-Network/growth-program/assets/82824139/49a75741-b66e-42e7-8f06-69d120c5bec9)

![proto3 200px](https://github.com/Phala-Network/growth-program/assets/82824139/b461d1b9-3eae-4f01-87c3-b1bbd287bb3a)

I really enjoy to help Chris in this great idea and project.

- I stopped all the AI picture because now everyone is doing it. Too many noise, and can deserve the message. We should have by month typical language element to push. And to applicate BY COMMUNITY and BY LANGUAGE First. English is very important but it's a pity so see major community abandonned (germany). The brasilian-portuguese community become a major example.

I expect a result in line with other months 80%:

MK: 35/40
CM: 20
CC: 35

thank you, cheers

**Comment by willphala** [comment]
Great work! Especially with the influencer outreach.
