### ISSUE TITLE
December 2023 contributions report {toriribolla}

### ISSUE THREAD

**Issue by toriribolla** [Phala-Network/growth-program#329]
PERSONAL INFO
Amb Rank : Ambassador
Telegram: @toriribolla
Twitter: @toriribolla
PHA Address : 435b1mp9FuSY4X6NNMTN6mALfyeChiQU1htPViw7hnD26sEM

Departments: #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

CC Contributions:

X @toriribolla:
1. https://x.com/ToriRibolla/status/1733980659964625015?s=20
2. https://x.com/ToriRibolla/status/1734824554571218945?s=20
3. https://x.com/ToriRibolla/status/1735582857102323963?s=20
4. https://x.com/ToriRibolla/status/1736796073807540512?s=20
5. https://x.com/ToriRibolla/status/1737522137819185167?s=20
6. https://x.com/ToriRibolla/status/1737759946345738433?s=20
7. https://x.com/ToriRibolla/status/1740130174526734399?s=20
8. https://x.com/ToriRibolla/status/1741097267652661300?s=20

Retweets:
1. https://x.com/PhalaNetwork/status/1730638690030932389?s=20
2. https://x.com/PhalaNetwork/status/1734216606408933534?s=20

X @PhalaRussia:
1. https://x.com/PhalaRussia/status/1733945454033871028?s=20
2. https://x.com/PhalaRussia/status/1736038762851742071?s=20
3. https://x.com/PhalaRussia/status/1736673070666969505?s=20
4. https://x.com/PhalaRussia/status/1736823754133520607?s=20
5. https://x.com/PhalaRussia/status/1737035438215291192?s=20
6. https://x.com/PhalaRussia/status/1737397932125540855?s=20
7. https://x.com/PhalaRussia/status/1737760125580988728?s=20
8. https://x.com/PhalaRussia/status/1738122436653072569?s=20
9. https://x.com/PhalaRussia/status/1738484740577980623?s=20
10. https://x.com/PhalaRussia/status/1738846977532604651?s=20
11. https://x.com/PhalaRussia/status/1740125825348034658?s=20
12. https://x.com/PhalaRussia/status/1740129100549825019?s=20
13. https://x.com/PhalaRussia/status/1740296556937425171?s=20
14. https://x.com/PhalaRussia/status/1740658943347564611?s=20
15. https://x.com/PhalaRussia/status/1741021322895839561?s=20

MK Contributions:

X analytics @toriribolla
![image](https://github.com/Phala-Network/growth-program/assets/132458076/5e24bd67-33f7-4595-9715-1bd2d350125d)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/f1181354-a79d-4ad6-8fd6-75ed8cf5013d)

X analytics @PhalaRussia
![image](https://github.com/Phala-Network/growth-program/assets/132458076/2faa01ca-7640-4e85-8a78-0239b603235e)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/dcba8b61-ca1e-44ef-8b9e-eee6729ad21e)

CC:

translation:
1. Dynamic NFT: https://medium.com/@ribollavvv/27354be4ee97
2. Dynamic NFT: https://medium.com/@ribollavvv/729a2d3920ca
3. Dynamic NFT: https://medium.com/@ribollavvv/0587da3e81e3
4. Dynamic NFT: https://medium.com/@ribollavvv/f8125e8305e3
5. inDEX: https://medium.com/@ribollavvv/4309938dff28

ART:
![vgjhgjg](https://github.com/Phala-Network/growth-program/assets/132458076/ef8f973f-d505-4e0a-b00e-fccc2c23fd76)
![bhhjkji](https://github.com/Phala-Network/growth-program/assets/132458076/9279bad3-f24d-475b-b3c2-f28e663cc607)
![hihi](https://github.com/Phala-Network/growth-program/assets/132458076/9be552bc-84f1-49de-b811-f29cb7d5f521)
![мрогрмог](https://github.com/Phala-Network/growth-program/assets/132458076/c15fa49c-fdf1-4f69-ba8c-7f3a99718c9b)

SUGGESTED SCORES
#CC : 30
#MK : 30
#ART : 10
Overall : 70

Happy New Year! I am very happy with the work done in 2023, 2024 is waiting for new accomplishments!

**Comment by willphala** [comment]
Happy New Year! Great work on the graphics, I think they look great. Keep it up! :)
