### ISSUE TITLE
December 2023 contribution - {pigro85#6032}

### ISSUE THREAD

**Issue by pigro85** [Phala-Network/growth-program#335]
Telegram: Pigro85
Discord: pigro85#6032
Twitter: https://twitter.com/pigro85
PHA Wallet Address: 44Rc9bxvmfyVJx1qmKThhUXUCuyhU6tqULvM5QKxtxks19uH

[CM]
Phala Italian Channel link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a

Phala Mining Channel link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a

Phala Network Official link: https://t.me/phalanetwork
Combot Link: https://combot.org/c/1421178003/a

Standard acitivity on Discord/Telegram
Have I participated in Discord Channel Moderation? Yes
Have I participated in Telegram Channel Moderation? Yes
Standard chat operations and a still continuing banning huge amount of spammers/bot.

[CC]
none

[MK]
Minimal activity on twitter

SUGGESTED SCORES

CM: 30/40
CC : 0
MK : 0

**Comment by willphala** [comment]
It's great to see you back man! :)
