### ISSUE TITLE
December 2023 Contributions - {Rom1.io#5329} 

### ISSUE THREAD

**Issue by Rom1io** [Phala-Network/growth-program#336]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/63704652/216827308-dd6a24be-5517-4e09-9c0e-c65a763aca3b.png">

Amb Rank : Ambassador
Telegram Username: https://t.me/Imo_999
Discord Username: Rom1.io#5329
Twitter Username: https://twitter.com/RCajina
PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q

Departments : #CM & #MK

**Contributions:**

Hello, it's been a quiet month for me, but I've still contributed to help the community, doing a few translations.

![image](https://user-images.githubusercontent.com/63704652/222117520-bf30a95b-18be-44e8-9e0f-aad3e09f879c.png)

Twitter analytics: [Here](https://analytics.twitter.com/user/RCajina/home)

![image](https://github.com/Phala-Network/growth-program/assets/63704652/b56aef79-8c8b-433b-be20-913e43ab54cc)

![image](https://user-images.githubusercontent.com/63704652/222134127-67fe6ec1-f49c-43d7-a391-f681d8d5a87e.png)

Here are the translations  : 

- [Newsletter mensuelle Phala : Novembre 2023](https://medium.com/phala-fran%C3%A7ais/newsletter-mensuelle-phala-novembre-2023-5e149e6815f9) 

![image](https://user-images.githubusercontent.com/63704652/222134855-7eff0b13-3d74-4aad-a848-63d581a00c44.png)

I'm going to be more present on the networks and in the news about Phala in the New Year. The community has been very quiet lately, but I feel it's slowly picking up again. I'm in the process of setting up recurring infographics for each month :)

## SUGGESTED SCORES
#CM: 20/40
#MK: 20/40

Other:
#CC: 10/10

Overall : 50

***Quote*** : "The New Year promises a fresh start and fills every heart with hopes and aspirations. I wish you all the best for 2024."

**Comment by willphala** [comment]
Looking forward to the infographics Pham🫡
