### ISSUE TITLE
December 2023 Contributions - Gabekoin

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#338]
Telegram : @gabekoin
Discord : gabekoin
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of Dez:
Ambassador

CONTENT (CC): 40/40

**Videos Created:**
**Weekly 1:**
https://youtu.be/xgA3Gx5ZIdU?si=bIX4yRpV9W3olJ4k&t=159
https://x.com/gabekoin/status/1731114388524876203?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/6ad8cede-3074-410e-9b71-724c9049faaf)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/90438ab2-c0cb-49e9-a116-4bbddb6a1785)

**Weekly 2:**
https://youtu.be/VzjAwyTYMXE?si=NsaI2xljQr5uirqJ&t=154
![image](https://github.com/Phala-Network/growth-program/assets/112413448/3989f6f3-2a72-485a-8569-a024bbc1bf8b)

**Weekly 3:**
https://youtu.be/jALDwswGs34?si=AJ5xh2_R18G-Phno&t=84
![image](https://github.com/Phala-Network/growth-program/assets/112413448/826bd859-26a5-48d4-b350-322b851f5f2a)

**Multichain Speech Record:**
https://vxtwitter.com/phalaportugues/status/1738644632836178178?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/bfaa7e19-2330-4e4b-a0e0-17c1c324fec0)

**Weekly 4:**
https://youtu.be/Jue45DxlYJo?si=CiOZUb9KnG-HhQ6M&t=79
![image](https://github.com/Phala-Network/growth-program/assets/112413448/27146299-5204-4ee8-801b-7bfaccc31e52)

**Threads created:**

inDEX Full thread ENG:
https://x.com/gabekoin/status/1735264368013488405?s=20

inDEX Full thread PT:
https://x.com/phalaportugues/status/1734928462874325386?s=20

Guia: NFTs:
https://x.com/gabekoin/status/1731644889429938295?s=20

Polkadex:
https://x.com/gabekoin/status/1732043652523024732?s=20

Polkadex PT:
https://twitter.com/phalaportugues/status/1732044064068145477

Coiote NFT:
https://vxtwitter.com/phalaportugues/status/1732402177241465287?s=20

dNFT gaming:
https://x.com/gabekoin/status/1733881583868776493?s=20

Multichain:
https://x.com/gabekoin/status/1737841869604979081?s=20

Multichain PT:
https://x.com/phalaportugues/status/1737843505895248012?s=20

**Articles Translated:**
Web3 Social Monetize:
https://medium.com/@phalaptbr/web3-social-crie-e-monetize-com-contratos-inteligentes-93fa3a2f363d

inDEX Litepaper:
https://medium.com/@phalaptbr/index-liderando-a-revolu%C3%A7%C3%A3o-intentcentric-no-crosschain-trading-8b5096363d19

Guia: NFTs dinâmicos que evoluem:
https://medium.com/@phalaptbr/guia-nfts-din%C3%A2micos-que-evoluem-b6717f58eac5

Guia: NFTs dinâmicos e jogos de progressão social Web3
https://medium.com/@phalaptbr/guia-nfts-din%C3%A2micos-e-jogos-de-progress%C3%A3o-social-web3-e96ac9f3d433

Multichain:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_multichain-meetup-recycleminds-activity-7143612150345887744-2iXj?utm_source=share&utm_medium=member_desktop

Astar Strike Neurolanche:
https://x.com/phalaportugues/status/1740152800984920139?s=20

**Threads Translated:**
Phala weekly 1:
https://x.com/phalaportugues/status/1730645430386540803?s=20

Phala Weekly 2:
https://twitter.com/phalaportugues/status/1737200496836759656

Guia: NFTs dinâmicos que evoluem:
https://x.com/phalaportugues/status/1731649500924506462?s=20

Halving:
https://x.com/phalaportugues/status/1733121425374892333?s=20

inDEX:
https://x.com/phalaportugues/status/1734233683656167442?s=20

Sygma bridge:
https://x.com/phalaportugues/status/1734573706637119810?s=20

Weekly 2:
https://twitter.com/phalaportugues/status/1734996964020715535

**LINKEDIN POSTS CREATED:**

Multichain Speech Video:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_multichain-meetup-curitiba-activity-7145160656802033664-VFhj?utm_source=share&utm_medium=member_desktop

Guia: NFTs dinâmicos que evoluem:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_guide-dynamic-nfts-that-evolve-activity-7137415621905985536-qaXY?utm_source=share&utm_medium=member_desktop

Polkadex:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_pha-dex-orderbook-activity-7137840892895186945-u59x?utm_source=share&utm_medium=member_desktop

Guia: NFTs dinâmicos e jogos de progressão social Web3:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_guia-nfts-din%C3%A2micos-e-jogos-de-progress%C3%A3o-activity-7138168403294306305-B2KD?utm_source=share&utm_medium=member_desktop

Halving:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_geminitokenomics-phalanetwork-activity-7138896400712454146-NqN8?utm_source=share&utm_medium=member_desktop

inDEX:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_custom-domain-by-bitly-activity-7140074919412887552-xGy1?utm_source=share&utm_medium=member_desktop

Sygma Bridge:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_buildwithsygm-subbridge-activity-7140340442293858304-wQ53?utm_source=share&utm_medium=member_desktop

PDEX:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_pha-is-now-trading-on-orderbook-celebrate-activity-7141037356949692416-gPwl?utm_source=share&utm_medium=member_desktop

**COMMUNITY (CM): 34/40**

![image](https://github.com/Phala-Network/growth-program/assets/112413448/7c3434c4-06cc-447f-98f5-102681ce23d8)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/cb2696b6-3aca-4a78-bd1e-b02a22823f98)
![msg1007106156-66573](https://github.com/Phala-Network/growth-program/assets/112413448/cda42d43-64e0-43a3-bb85-b5a17dff6f41)
![msg1007106156-66667](https://github.com/Phala-Network/growth-program/assets/112413448/6c6c8bd6-5f3c-4ab1-b351-3e4474446f1f)
![msg1007106156-66668](https://github.com/Phala-Network/growth-program/assets/112413448/347773b7-92ab-4418-8a7e-9dc5919b5b08)
![msg1007106156-67126](https://github.com/Phala-Network/growth-program/assets/112413448/813441f8-eafa-41eb-9679-814120c6bef1)
![msg1007106156-67175](https://github.com/Phala-Network/growth-program/assets/112413448/bb8623ed-edab-4acf-a84b-0dccf16fe888)
![msg1007106156-67216](https://github.com/Phala-Network/growth-program/assets/112413448/8dea8899-46cf-42ac-8b60-85e9e7e42b0b)
![msg1007106156-67214](https://github.com/Phala-Network/growth-program/assets/112413448/a5da4bf1-74df-4873-a2e6-b5802b98e3cd)
![msg1007106156-66485](https://github.com/Phala-Network/growth-program/assets/112413448/1eb24cab-264b-4d20-a26d-a26db4f032a1)
![msg1007106156-66532](https://github.com/Phala-Network/growth-program/assets/112413448/565cdd94-33b0-4292-b77c-33eef6ab3772)
![msg1007106156-66533](https://github.com/Phala-Network/growth-program/assets/112413448/0b981e85-9863-481f-b18d-83b1dbf0f47f)

**Supplementary: PM & EM (20/20)**

**PM: 10/10**

https://x.com/polkadex/status/1732225279966515350?s=20
https://twitter.com/polkadex/status/1730644217427530150
https://twitter.com/PhalaNetwork/status/1730638690030932389
https://x.com/gabekoin/status/1732442295281074305?s=20
https://x.com/CryptoCappex/status/1733034356464120284?s=20
https://x.com/gabekoin/status/1733120987997102137?s=20
https://x.com/gabekoin/status/1734172475825570254?s=20
https://x.com/PhalaNetwork/status/1734571542644682966?s=20
https://x.com/nirajhodler/status/1738583196399206774?s=20
https://twitter.com/CryptoCappex/status/1738470748204007475
https://twitter.com/CryptoBourse_/status/1737505468757467285
https://twitter.com/nirajhodler/status/1738107355777397245
https://twitter.com/guinnessstache/status/1737865629351235798
https://twitter.com/Dima35109517/status/1738644282599178723
https://x.com/CryptoCappex/status/1738841398663618562?s=20
https://x.com/CryptoCappex/status/1738677602787708982?s=20
https://x.com/PhalaNetwork/status/1740047307393864184?s=20
https://x.com/marvin_tong/status/1739312288429940819?s=20
https://x.com/PhalaNetwork/status/1741536181769400348?s=20

**EM (10/10):** 
Multichain Curitiba:
https://twitter.com/phalaportugues/status/1738644632836178178?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/67667932-58cc-4965-a2f4-fae2c1c4cff4)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/827f07d7-8ee7-4e52-b9e8-1a633f00a52b)

Spaces de Natal:
https://x.com/phalaportugues/status/1739312297024106923?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/596a74fe-4f03-4776-b253-014b3743a3a1)

Spaces Encerramento Anual:
https://x.com/phalaportugues/status/1740477898891641105?s=20
![image](https://github.com/Phala-Network/growth-program/assets/112413448/57cb2837-29f9-4aac-a8d7-617774cbd0bf)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/4bcb4620-c282-41c4-bf9c-4c5547b4c7b0)

ART:
Balanceador:
https://vxtwitter.com/phalaportugues/status/1733135477182435469?s=20

**Suggested scores:**
[CC] 40/40
There wasn't a better way to end the last month of the yea., I've created many content and increased the reach/engagement.
For next month, make 2024 the best year for Phala!

[CM] 35/40
This month was better than I expected due to holidays, the activity was great and we kept good views in Twitter and Youtube
Brasilian community is growing faster, couldn't be happier.
For next month: Keep growing our local community and keep supporting International Phala Channels

[PM] 8/10
Shared all oficial content in all main social medias.

[EM] 10/10
We started and hosted an incredible event called Multichain Meetup with other networks in our city. Many important people were there and we had a great speech about Phala.

We hosted two Spaces (Xmas edition and Annual Recap). Was amazing and could resume the whole year to our community.

**Overall suggested score: 93/100.**

Totally happy about this month, excited about Phala's future and proud of 2023.
Many new users interesed in Phala's new products and asking about our recent partnerships, 2024 is our year!

For the next month: Do better

**Comment by willphala** [comment]
Brilliant!
