### ISSUE TITLE
December 2023 Contributions - the_scarlet_thread

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#339]
Amb Rank: Ambassador
Telegram Username: @Scarlet_Thr
Discord Username: @the_scarlet_thread
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

**MANDATORY**
_💫CONTENT CREATION 💫_

**Threads/Long-form posts**
1. Created this post explaining the Gatekeeper role in Phala, got a questions in the comments as well asking more about it
https://twitter.com/TheScarletThr/status/1733745950147989603?t=fH28JZqAV0Td49Gx4u4XeQ&s=19
Made this accompanying graphic:
![20240106_093946](https://github.com/Phala-Network/growth-program/assets/99918790/7bf3ddc6-8c5f-4d5a-80ef-70ae5209d336)

2. This thread was for the Phala Africa X page, explaining Phat Contracts to newer community members
https://twitter.com/PhalaAfrica/status/1735265119020417280?t=vz8HvQVsU2AuresS7diFjg&s=19
Made these accompanying graphics:
<img width="1200" alt="1_20231213_130307_0000" src="https://github.com/Phala-Network/growth-program/assets/99918790/d437220e-18aa-4846-ab78-db5f94e9a613">
<img width="1200" alt="2_20231213_130307_0001" src="https://github.com/Phala-Network/growth-program/assets/99918790/0fb614a2-554c-4a54-b48e-32a55094fe1d">
<img width="1200" alt="3_20231213_130308_0002" src="https://github.com/Phala-Network/growth-program/assets/99918790/c9567da1-b8ad-431f-bc4b-73ece51efff1">
<img width="1200" alt="4_20231213_130308_0003" src="https://github.com/Phala-Network/growth-program/assets/99918790/c691ec2f-cfb4-4dea-a896-24a41e3aab01">
<img width="1200" alt="5_20231213_130308_0004" src="https://github.com/Phala-Network/growth-program/assets/99918790/9cbdf6d5-fcac-4bc1-a43b-78f728e083f2">
<img width="1200" alt="6_20231213_130308_0005" src="https://github.com/Phala-Network/growth-program/assets/99918790/4b16439b-5816-471d-8548-cbedd1ce9d64">
<img width="1200" alt="7_20231213_130308_0006" src="https://github.com/Phala-Network/growth-program/assets/99918790/31ee0364-8f25-4bb5-95c3-be259bef24e9">
<img width="1200" alt="8_20231213_130308_0007" src="https://github.com/Phala-Network/growth-program/assets/99918790/a8749d3e-30ae-4b73-8478-4d28587cec52">

3. Made this thread about the “Web3 Social Monetization” topic
https://twitter.com/TheScarletThr/status/1737420444909593023?t=d-mqRtaCN5PbmobhMmnfUQ&s=19

Made these accompanying graphics and video:

https://github.com/Phala-Network/growth-program/assets/99918790/c1f81b19-cfe4-4c3e-b72d-be3c6bc4acd3

![20231220_123110_0001](https://github.com/Phala-Network/growth-program/assets/99918790/1997557e-85c5-44ac-a972-2033d3429d39)
![20231220_123110_0000](https://github.com/Phala-Network/growth-program/assets/99918790/7ea4263c-0865-4c27-bdf1-9115e36a470b)
![20231220_123110_0002](https://github.com/Phala-Network/growth-program/assets/99918790/42c64000-db81-4ca3-97f6-78c8a1957dca)
![20231220_123110_0003](https://github.com/Phala-Network/growth-program/assets/99918790/377059ff-c3b9-46a0-9de7-6a8ec1e91274)
![20231220_123110_0004](https://github.com/Phala-Network/growth-program/assets/99918790/37dcf964-5f4e-47f6-858d-09f1b8b583ce)

4. Made this post about what Phat Contract's universal compatibility means for end users
https://twitter.com/TheScarletThr/status/1740989629451395444?t=W4UHN4u576cga1P-DTgvAQ&s=19
Made this accompanying video:

https://github.com/Phala-Network/growth-program/assets/99918790/96b33dc0-ba8b-4ce6-bb01-f9ddfee44686

5. Made thread about the evolution of NFTs and digital ownership, and discussed Phat Contracts dynamic nfts usecase.
https://twitter.com/TheScarletThr/status/1740989629451395444?t=W4UHN4u576cga1P-DTgvAQ&s=19
Made these accompanying graphics and gifs:

![20231228_094136_0000](https://github.com/Phala-Network/growth-program/assets/99918790/a53078ce-4a58-4209-a738-c50c735e9ed8)
![20231228_095527_0000](https://github.com/Phala-Network/growth-program/assets/99918790/27c22566-4ada-4d55-8fee-523ef4ac0166)
https://github.com/Phala-Network/growth-program/assets/99918790/97d937f6-8f0b-402e-bda7-b90ba1ab0346

**Memes**
I made some memes about Phala and posted them on the server:

Dynamic nfts vs Static nfts
https://discord.com/channels/697726436211163147/766661203111575553/1186405092254023700

Excited Versus Exhausted SpongeBob Meme
https://discord.com/channels/697726436211163147/766661203111575553/1187670434343301130

Organs Talking
https://discord.com/channels/697726436211163147/766661203111575553/1189221899704737812

Two Slides Merging
https://discord.com/channels/697726436211163147/766661203111575553/1189609968014463127

Pushing a boulder
https://discord.com/channels/697726436211163147/766661203111575553/1189858355997589595

Anime Doomer Girl vs Doomer Girl
https://discord.com/channels/697726436211163147/766661203111575553/1190232717682548886

Woman holding Kevin Hart Meme
https://discord.com/channels/697726436211163147/766661203111575553/1190614393315131402

Snake Meme
https://discord.com/channels/697726436211163147/766661203111575553/1190947241691709450

**Infographic**
1. Created infographic on the various wallets that can be used on Phala Network
https://twitter.com/TheScarletThr/status/1736789951000273158?t=8idgVXafG6EYqlgBhH288g&s=19

2. Made infographic on the various forms the PHA token
https://twitter.com/TheScarletThr/status/1738100710846210523?t=pLse7RR8Ve4kpaiZDHI2LQ&s=19

**Community Call**
This month, the call format was different thanks to an idea by Bekka. We had a panel discussion on the topic “NFTs and the evolution of digital ownership” which was hosted as an X space.
![1000050316-01](https://github.com/Phala-Network/growth-program/assets/99918790/09e13b24-f41d-432c-accf-52ed10df2907)

I played my role in this call by:
• Guiding the organization of the call; initiated polls and discussions about various aspects of organising and doing tasks; delegated roles; brainstorming ideas for the event; and tracked progress.
• Maintained constant presence when fellow ambassadors needed assistance.
• I created the banner to announce this event
![20231217_155519_0000-1](https://github.com/Phala-Network/growth-program/assets/99918790/d1e17ac1-648a-41c6-998b-b826bf981c1c)

• Hosted the call (doing introduction, welcomes,asking questions to panel, announcing winners, sending prizes to winners) and gave a presentation on Phat Contracts usecase in dynamic nfts.
• As a group, we decided to have a giveaway during the event to boost attendance and make the call fun. We chose 3 winners at random at the end of the call, and each won 100 PHA.

**Support of advocate's event**
I attended and recorded the event that our advocate Mohammed Shakur had. I edited the footage, find the link here:
https://drive.google.com/file/d/1gaZJjL-tsje1IS2V2aV2G7QVv1NYlCut/view?usp=sharing

**GOOD POINTS**
We tried a different way of doing the community call and it was interesting, we also had a higher number of attendees than last month.

**BAD POINTS**
I haven't created any content targeted at the technical community to create awareness about Phala to people who will use Phat Contract.

**HOW TO IMPROVE**
I plan with to work with Bekka and learn from technically minded ambassadors on how to reach this primary audience better, especially to grow our Phala Africa community.

**💫COMMUNITY MANAGEMENT💫**

• **Helpdesk and moderation**.
 I participated in monitoring the PhalaWorld, Phala Telegram, Phala Africa Telegram, and Phala Discord in order to eliminate spam, malicious content and answer questions of the community.
Addressing negative feedback to the best of my ability. Like previously, I have also been looking at discussions on X regarding Phala and what the community sentiment is, and conveying this to team via community channel.
See a few examples below:
![1000051018-01](https://github.com/Phala-Network/growth-program/assets/99918790/9d315ea8-cc85-4115-ad8f-4155753e792f)
![1000051017-01](https://github.com/Phala-Network/growth-program/assets/99918790/c5b25330-9ffa-4fc7-af08-96e70491d216)
![1000051016-01](https://github.com/Phala-Network/growth-program/assets/99918790/09a07d47-1213-4103-a761-e73f6e3fb693)
![1000051015-01](https://github.com/Phala-Network/growth-program/assets/99918790/f5443c33-1521-4c94-8861-f0f99c21f121)
![1000051014-01](https://github.com/Phala-Network/growth-program/assets/99918790/e21d8a74-2510-4a61-be67-d7ec390def1f)
![1000051003-01](https://github.com/Phala-Network/growth-program/assets/99918790/39ee9dff-93f6-4856-bc0a-7d601594765e)
![1000051002-01](https://github.com/Phala-Network/growth-program/assets/99918790/94f09d5b-3331-4720-be93-42758faf0bfd)
![1000051001-01](https://github.com/Phala-Network/growth-program/assets/99918790/b90f9c8d-9c59-45a5-b654-c390879362ef)
![1000051000-01](https://github.com/Phala-Network/growth-program/assets/99918790/54679daf-150d-411a-b70f-12f9bcac4322)
![1000050999-01](https://github.com/Phala-Network/growth-program/assets/99918790/2a5b2821-bde9-4af9-ba34-fd615726c9c2)
![1000050998-01](https://github.com/Phala-Network/growth-program/assets/99918790/c0def2f3-8a9d-4a23-ac0b-477bb0980df2)
![1000050997-01](https://github.com/Phala-Network/growth-program/assets/99918790/b6939486-e9c9-4c41-b1a7-00498957302b)
![1000050996-01](https://github.com/Phala-Network/growth-program/assets/99918790/ba0a6ea5-004d-445d-b101-c837b638f899)
![1000050995-01](https://github.com/Phala-Network/growth-program/assets/99918790/5b1996bd-144a-442b-a3b9-c07f74da178b)

• **Managing Phala Africa**
I have been working alongside and coaching our advocate regularly with learning about Phala Network. I provided constant guidance and assistance
 ( also evaluated their performance and gave feedback so that they can grow and work towards being an ambassador). 
Providing guidance, feedback and assistance to Phala Africa ambassadors, delegating tasks and tracking progress being done. Evaluating areas of strength and what needs to be improved .
Research, planning and creating strategies to grow the community and ways that our Phala Africa team can improve collaboration within the team and increase output. During this month, I have continued to  evaluate our methods to find ways to can grow the community in a better way.

• Share helpful resources to community about Phala and partners.

• I added questions from the community to the community digest 

• Shared feedback/concerns in the ambassador-only community channel on Discord.

• Stats
![1000050968-01](https://github.com/Phala-Network/growth-program/assets/99918790/628b6ee8-7028-4789-a35e-47c23c86ffaa)
![1000050971-01](https://github.com/Phala-Network/growth-program/assets/99918790/5e96b84e-682b-455c-ac97-bc8111cce668)
![1000050965-01](https://github.com/Phala-Network/growth-program/assets/99918790/a0b77996-1a85-451a-93b6-54c399e58cab)
![1000050966-01](https://github.com/Phala-Network/growth-program/assets/99918790/b774fb47-4c38-470a-955d-f4e1b07136c3)

**GOOD POINTS**
I worked with Phala Africa advocate and ambassadors, and provided feedback to our advocate on how to improve ( he shows good work ethic and enthusiasm thus far). We had a little more engagement in Phala Africa this month. Teamwork improved from last month, especially thanks to our new members.  

**BAD POINTS**
Need to be more active in global channels

HOW TO IMPROVE
I can start by scheduling more time each week to engage more in the global channel and engage on there each day. 

### SUPPLEMENTARY
_💫PM💫_
During December, I worked on promoting Phala Network (local groups + global) and contributed to increasing visibility across various platforms. I've done this by showing Phala's various aspects through posting on Twitter, Telegram and Discord. I engaged with the community, sharing updates and initiating insightful discussions about Phala, Phat Contracts and PhalaWorld. I promoted Phala's content and monitored feedback from community (which was conveyed to team). I've also engaged through liking, commenting and retweeting content from: Phala Network ambassadors, Partners, Phala Network Twitter, fellow ambassadors and Phala Team members. I promoted events that Phala had, updates and various forms of content.
![Screenshot_20240103_190540_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/1cfa6146-94be-413e-a816-b3efad0bbdf4)
![Screenshot_20231230_091733_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/251e5980-6b04-4ecd-a724-5fa9ad946f09)
![Screenshot_20231230_091710_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/b1d9c4e8-067d-48d8-8230-6ab08159cc64)
![Screenshot_20231230_091706_Samsung Internet-01](https://github.com/Phala-Network/growth-program/assets/99918790/5020c3d6-2dfb-425f-a999-79a21e4f5311)

**QC**
I have done QC for the month of December, listed here:
https://docs.google.com/document/d/1QP__bWnmEg7w0RwmhIFijTd-jc0WKKTOv2GQhAC3USA/edit?usp=drivesdk

**SCORES**
**CC** **36/40
CM** 38/40
**PM** 8/10
**QC** 8/10
**TOTAL** 90

**CLOSING COMMENTS**
As I wrap up this report, I'm genuinely thrilled by the strides taken in December. I have learned a lot and put effort into content creation, community management and quality standards. I'm proud of the progress made in contributing to Phala Network's visibility and fostering engaging discussions. I will continue to work with my fellow ambassadors in innovative approaches to our community growth and continuous support. As always, quality and quantity will continue to be improved.
Moving forward, I plan to refine our strategies to connect with a broader technical audience and strengthen our teamwork. I'm excited to dive into 2024 with the same enthusiasm, aiming for greater milestones and growth.

Thank you ! 
Here's to an awesome 2024 🔥
Scarlet

**Comment by willphala** [comment]
Excellent work and report as always!
