### ISSUE TITLE
December 2023 Contributions - (johnrhodel)

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#341]
Telegram Username: https://t.me/parachainboy
Discord Username: johnrhodel
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

CC : 40/40

Filipino Translations:
https://polkaverse.com/11194/buwanang-newsletter-ng-phala-nobyembre-2023-40635
https://polkaverse.com/11194/in-dex-decoded-ang-multi-chain-intent-model-40636
https://polkaverse.com/11194/web3-social-gumawa-at-kumita-gamit-ang-mga-smart-contract-40637
https://polkaverse.com/11194/in-dex-nangunguna-sa-intent-centric-revolution-sa-cross-chain-40638

Portuguese Translation:

https://medium.com/@phalaptbr/boletim-mensal-phala-novembro-de-2023-3f9c687be1db
https://medium.com/@phalaptbr/index-decodificado-o-modelo-de-inten%C3%A7%C3%A3o-multicadeia-ba50a1ee1bdc

Multichain Speech Record:
https://vxtwitter.com/phalaportugues/status/1738644632836178178?s=20

Arts:

![1](https://github.com/Phala-Network/growth-program/assets/77474076/65dfb69f-6f32-4e96-84e2-7f5617c368f4)
![2](https://github.com/Phala-Network/growth-program/assets/77474076/a4b4cfb3-4de4-44dc-8d72-a4917a7ce22b)
![3](https://github.com/Phala-Network/growth-program/assets/77474076/64b21e06-cc6c-4f0f-acd5-b564c67ff618)
![4](https://github.com/Phala-Network/growth-program/assets/77474076/7e144bdd-cb35-4648-b052-1611a494c266)

MK:(40/40)

![Captura de tela 2024-01-05 221734](https://github.com/Phala-Network/growth-program/assets/77474076/4018dca2-9048-4844-a758-238e1c0905e2)
![Captura de tela 2024-01-05 222350](https://github.com/Phala-Network/growth-program/assets/77474076/8843418b-80e9-4068-9aa6-66fbec963386)

Spaces Encerramento Anual:
https://x.com/phalaportugues/status/1740477898891641105?s=20
![image](https://github.com/Phala-Network/growth-program/assets/77474076/40e65ed7-bb69-4023-a621-93c3b54b0ffc)
![IMG_5141](https://github.com/Phala-Network/growth-program/assets/77474076/b2d9ae85-4ea1-4d17-ba41-9ba78a20eccb)

Spaces de Natal:
https://x.com/phalaportugues/status/1739312297024106923?s=20
![photo_2023-12-25_16-17-13](https://github.com/Phala-Network/growth-program/assets/77474076/82d7a94e-0283-4355-a928-ef73594ce060)
![photo_2023-12-25_16-17-14](https://github.com/Phala-Network/growth-program/assets/77474076/cca5a8c0-82ae-4273-9ca7-f338fc437aec)

Spaces with Bankless DAO: Talked about parachains and polkadot
https://twitter.com/BanklessBR/status/1737905582806643072
![photo_2023-12-21_20-29-51](https://github.com/Phala-Network/growth-program/assets/77474076/7ed0a49b-49e0-4c32-973e-36a0cea97f0c)
![photo_2023-12-21_21-09-06](https://github.com/Phala-Network/growth-program/assets/77474076/88d822f8-ed5b-4b95-9d62-5842fec465b6)

Qual a lógica de um smart contract:
https://twitter.com/phalaportugues/status/1741595135207444963

Importancia dos metadados:
https://twitter.com/phalaportugues/status/1741595026910552401

Nft's Dinamicos:
https://twitter.com/phalaportugues/status/1741594938532298912

4 casos do uso do tokenomics:
https://twitter.com/phalaportugues/status/1741594802037100694]

Like, rt:
https://twitter.com/parachainboy/status/1741603861205323880
https://twitter.com/PhalaNetwork/status/1734216606408933534
https://twitter.com/PhalaNetwork/status/1735321235557323128
https://twitter.com/marvin_tong/status/1737629511515259215
https://twitter.com/PhalaNetwork/status/1741536181769400348
https://twitter.com/PhalaNetwork/status/1734984875306795157
https://twitter.com/PhalaNetwork/status/1735654415837589918
https://twitter.com/PhalaNetwork/status/1737066266651672603
https://twitter.com/PhalaNetwork/status/1738216644583805396
https://twitter.com/PhalaNetwork/status/1739218618628403552
https://twitter.com/PhalaNetwork/status/1740047307393864184
https://twitter.com/parachainboy/status/1740106175742705997
https://twitter.com/verbodotsama/status/1738554984927580171

HD:(10/10)

![photo_2023-12-01_08-49-47](https://github.com/Phala-Network/growth-program/assets/77474076/2c803ace-1997-4484-9f52-39f0d7b13343)
![photo_2023-12-28_20-04-08](https://github.com/Phala-Network/growth-program/assets/77474076/d2fd2993-d01a-4b92-bed3-1f26fb04057b)
![photo_2023-12-29_09-44-01](https://github.com/Phala-Network/growth-program/assets/77474076/85081dac-5dae-49c6-b119-575d95142330)
![photo_2023-12-30_15-20-58](https://github.com/Phala-Network/growth-program/assets/77474076/5317c733-2a30-4da9-b97c-59bc0597983a)
![photo_2023-12-30_15-29-48](https://github.com/Phala-Network/growth-program/assets/77474076/ef723730-a381-4eb7-aedd-acd021d60a26)

EM(10/10):
![br multi](https://github.com/Phala-Network/growth-program/assets/77474076/68a55229-7824-47ce-a0c3-dcde8c2fcdee)

Event in curitiba
https://twitter.com/phalaportugues/status/1738644632836178178?s=20

This month I was very active. I translated articles into Portuguese and Filipino, and presented at a multichain event with Gabriel, discussing Polkadot and Phala. We have a video about this. I participated in three "spaces", one with Bankless and two with the Phala community in Portuguese. I answered some questions in the group, created some artwork, and also organized an event in Curitiba, connecting multiple networks.

I believe I achieved 95 points this month.

Next month, I will continue to maintain the high standard that has always been entrusted to me by Will and the Phala Network.

**Comment by willphala** [comment]
Excellent work.
