### ISSUE TITLE
December 2023 Contributions - Arηo#8446

### ISSUE THREAD

**Issue by arnobase** [Phala-Network/growth-program#342]
Telegram Username: @arnobaze
Discord Username: Arηo#8446
Twitter Username: https://twitter.com/test_ut
PHA Wallet Address: 44siNV2pbrTSwiL3KdT4VVC1yqcSvfGzxcd7rHMD1cgQnjcn

mandatory tasks : CM & CP
ratio : 50%CM (40/80) - 50%CP (40/80)

## CM

support community in the public channel, give answers and reach out to the team when necessary
participate in internal discussions on the amb channels, proactive to propose improvements when possible

spam/scam work
remove spam/scam as a daily basis and warn/ban people when necessary

#### Phat contract testing
Deployed new version of price_feed phat contract on poc6 (previously on poc5)
<img width="1191" alt="Capture d’écran 2024-01-06 à 20 59 11" src="https://github.com/Phala-Network/growth-program/assets/8094810/ce6d8813-48b5-4816-8131-28b7e4b158ee">

#### help desk
provided help desk in the compute channel, reported to team when necessary

## CC
proofreading
https://medium.com/phala-fran%C3%A7ais/newsletter-mensuelle-phala-novembre-2023-5e149e6815f9 
https://medium.com/phala-fran%C3%A7ais/web3-social-cr%C3%A9er-et-mon%C3%A9tiser-avec-des-contrats-intelligents-c7e730ad62d5 

## DEV

Decentralized Oracle Graph API : a dApp to demonstrates the ability of an ink! smart contract on Astar Network and a Phat Contract on Phala Network to interact with each other using Phat Offchain Rollup.

code on github: https://github.com/decentralized-oracles/graph-api-ui
online here: https://graph-api-decentralized-oracle.substrate.fi/ 
<img width="810" alt="Capture d’écran 2024-01-05 à 20 18 15" src="https://github.com/Phala-Network/growth-program/assets/8094810/b2bd002f-4849-428d-90fc-6ced9ae0f3c1">

SUGGESTED SCORES
#CM : 20/40
#CP: 20/40
#CC/DEV : 20

Overall : 60

I've been less active in the chats this month but still present and proactive to secure the community by deleting scam/spam and ban unwanted users from our channels.
I continue to invest myself into phat contract dev. This month I delivered a UI that demonstrate how a phat contract (written by guigou) can be used to interact with a graph API like Subquery and Astar smart contract.

**Comment by willphala** [comment]
Love the PC contributions, keep up the great work!
