### ISSUE TITLE
January 2024 Contributions - {favour_cy}

### ISSUE THREAD

**Issue by BBoss01** [Phala-Network/growth-program#350]
Amb Rank : Ambassador
Discord username  : favour_cy#5138
Telegram username : @solomonfav 
Twitter Link : https://twitter.com/official_bles1?t=eR-KQW9NjmPi7pCNo7ziLg&s=09
PHA address : 41dNB3qCWz1m4b874815wYnthsbSUvmKUws6624wRrjX4tnL
Department : MK & CC
Score weight 50/50

CC

Departmental Channels - I actively participated in the Phala Africa ambassador channel, where I contributed ideas, planned events, and raised awareness for our community call. I also actively engaged in the content and marketing channel department with some engagement in CM channel.

CC - I wrote three articles about Phala Network

• The capabilities of Phat Contract 
https://medium.com/@boyesolomon8/the-capabilities-of-phat-contracts-b55d61e6277f

• The necessity of off-chain computation in the evolution of web3 development 
https://medium.com/@boyesolomon8/the-necessity-of-off-chain-computation-in-the-evolution-of-web3-development-0ddf317c398d

• Unleashing the potential of web3 with Phat Contract 
https://medium.com/@boyesolomon8/unleashing-the-potential-of-web3-with-phat-contracts-f16d73b8bb74

Community Call -  This month, we followed the previous routine for our community call, where I contributed as a speaker, sharing my insights in response to the prepared questions. Additionally, I shared relevant Phala Network links during the call.

TT - 
I made a guide on how to create a Phala account on subwallet extension 
https://medium.com/@boyesolomon8/how-to-create-phala-account-on-subwallet-extension-6d019b6ec96a

I made a YouTube video on introduction to Phala Network 
![Screenshot_20240204_145655.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/919c6f14-e50d-45d5-b615-b609391d6f3b)

https://youtu.be/gBdmRWoJja8?si=ItZ4rezkLytRcU9K

ART-
I Created and shared some infographics and banners about Phala Network
![Blue Gradient Company Business Profile Presentation_20240105_125146_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/33ed7d93-4c61-41e0-8540-5a19cee79cea)

![Blue Gradient Company Business Profile Presentation_20240108_113244_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/255770a9-4193-479c-92da-d7334179e460)

![Blue Gradient Company Business Profile Presentation_20240108_215654_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/8b4e0e09-c60e-4b64-926c-1edb819ff12e)

![Blue Gradient Company Business Profile Presentation_20240111_160034_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/50d6267e-ee04-4cc6-a6e6-dec332661802)

![20240111_182901_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/5831884e-055e-45e5-a978-6fb5abcfba85)

![Blue Gradient Company Business Profile Presentation_20240111_184518_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/8f08a5dd-4eeb-4d89-b151-d42b1adf4298)

![20240113_085033_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/03ddb58d-ff93-4107-aec1-62ab3d8577b8)

![20240114_164604_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/f92ed3dc-c40a-4cda-a638-f20650f7b80d)

![20240115_203526_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/bc234146-5af2-49cf-8be7-031dd57de4b4)

![Blue Gradient Company Business Profile Presentation_20240116_095932_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/42bd80ab-1ea6-4b29-b543-29f695560e89)

![Blue Gradient Company Business Profile Presentation_20240118_113902_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/0cd350b5-bf73-4b82-aeb6-5f9fb9a6d9aa)

![Blue Gradient Company Business Profile Presentation_20240118_205034_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/d3ef30f7-a992-4159-86ec-3d54b99aba95)

![Blue Gradient Company Business Profile Presentation_20240121_182637_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/4ea6b0c1-e6bc-499f-9beb-2151410e84f7)

![Blue Gradient Company Business Profile Presentation_20240123_211422_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/bf79d122-0795-4860-a6e5-89e46976cfca)

![Blue Gradient Company Business Profile Presentation_20240124_231936_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/2d2b2716-c5a9-4800-bf1e-40fdd5f68bb2)

![Blue Gradient Company Business Profile Presentation_20240126_205303_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/e6fd6bb6-4e6e-4484-bb35-e1caa3a88dcb)

![Blue Gradient Company Business Profile Presentation_20240127_150120_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/fcf6f930-546b-4aa0-84c2-c248ffeb9d31)

![Blue Gradient Company Business Profile Presentation_20240127_151705_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/f631ec3d-7cf6-444c-9012-f91c42767856)

![Blue Gradient Company Business Profile Presentation_20240128_101048_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/ac1969a7-b988-451a-a991-8664b5aedf75)

![Blue Gradient Company Business Profile Presentation_20240128_113412_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/79dc3096-5592-4c70-8578-72afc7e1eff6)

![Blue Gradient Company Business Profile Presentation_20240128_123822_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/f63b4de7-362b-4c75-ad76-1e0568a7d0bb)

![Blue Gradient Company Business Profile Presentation_20240128_130324_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/1ed4cd66-15ac-429c-b550-79550c9d5ab5)

![Blue Gradient Company Business Profile Presentation_20240128_131003_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/679d035a-76eb-48ab-b619-c24381f45967)

![20240129_094301_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/81df8ec1-115c-4b50-b568-1ac2140373f0)

![20240129_100805_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/dfcc1631-4e39-4317-b71f-e3183395fd41)

![Blue Gradient Company Business Profile Presentation_20240129_105206_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/9a05831a-5bef-4b7a-9c9f-17809ae8ee39)

![Blue Gradient Company Business Profile Presentation_20240129_113538_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/701d94ca-74c0-47d6-a6af-19d075678d25)

![20240129_114228_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/9ca79cdc-7761-4f14-bd5c-016db16888df)

![Blue Gradient Company Business Profile Presentation_20240130_173854_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/8b21d76c-af76-4f75-bcf6-eb5b25712ac5)

Good Points 
- Increased attendance at our community call and an interactive session was held. 
- Slight improvement in engagement within the Telegram community. 
- Enhanced quality of content produced
- Improved engagement in departmental channels.

Bad Point: - Low engagement levels in our African Discord community. 

How to improve:
 - I will continue to enhance both the quality and quantity of content. 
- I will collaborate more with fellow African ambassadors to foster community growth.

MK

I actively promoted Phala Network on multiple platforms, including X, LinkedIn, and Polkadot Community to enhance community involvement and expansion. My engagement extended to interacting with content from fellow ambassadors and participating in both global and local community posts by liking, reposting and quote posting.

Statistics :

https://x.com/search?q=from%3A%40official_bles1%20Phala%20Network&t=IPR0kLy9YIqadI9BW5I3pg&s=09

https://x.com/search?q=from%3A%40official_bles1%20Phat%20Contract&t=zmUPVSo2HvV-Pe8SZ5zoWw&s=09

![Screenshot_20240204_140206.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/25baf25d-e6ca-448f-a504-f7132b76542d)

LinkedIn Posts: 

- DeSoc Hackathon 
https://www.linkedin.com/posts/favour-solomon-99b430236_phala-network-phalanetwork-on-x-activity-7158620735756763136-l3jP

- Phala Network Roadmap 
https://www.linkedin.com/posts/favour-solomon-99b430236_phalanetwork-polkadot-web3-activity-7158037029883195392-ZrK_

- Phat Contract 
https://www.linkedin.com/posts/favour-solomon-99b430236_phalanetwork-web3-polkadot-activity-7157675908798001152-882f

- Phala Network 
https://www.linkedin.com/posts/favour-solomon-99b430236_phalanetwork-web3-polkadot-activity-7157299694430240768-6UiL?

- https://www.linkedin.com/posts/favour-solomon-99b430236_phatcontract-web3community-polkadot-activity-7151264494269128704-2iZn

- Promotion of Phala Network in the Polkadot Discord channel. 
![Screenshot_20240204_141116.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/71a6a45d-adaf-4ca1-845c-b29d8be4d9a5)

![Screenshot_20240204_141410.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/82ee5fbd-e7e0-4752-a3af-0ac792626e1e)

Good Points: 
- Improved post quality, resulting in increased impressions and interactions on X. 

Bad Points:
- Lower impressions on LinkedIn 

How to improve: - I will continue to produce high-quality content and improve my engagement on various platforms

SUPPLEMENTARY TASK

HD
I engaged in the Phala Africa Telegram and global Discord community, where I shared valuable information, welcomed new members, moderated spam and spammers, and provided answers to questions. I also had little engagement on PhalaWorld Discord.
![Screenshot_20240204_141445.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/ed8d4d24-b8f5-4fe8-b96b-90ca4be29fa6)

![Screenshot_20240204_141623.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/d361825c-c676-4a41-ac11-f0f8e2832318)

![Screenshot_20240204_140915.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/d5864f81-f7e4-4ffb-8005-b39c5694f464)

Suggested Scores
CC - 40
MK - 40
HD - 10
Total - 90

Closing Comment 
In general, my performance has improved compared to the previous month. I have improved my community engagement, produced more art, improved the quality of my articles and social media posts, and collaborated with ambassadors from other departments. I will continue to work closely with fellow ambassadors to further boost productivity and to improve the quality of my contents.

**Comment by willphala** [comment]
Good work Favour. You definitely stepped your game up this month! 🔥
