### ISSUE TITLE
January 2024 Contributions - Gabekoin

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#354]
Telegram : @gabekoin
Discord : gabekoin
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of Jan:
Ambassador

CONTENT (CC): 40/40

**VIDEOS CREATED:**

Weekly 1: 
https://youtu.be/iYSlWjL7xQM?si=oz2dhKcfBkfceEWf

![image](https://github.com/Phala-Network/growth-program/assets/112413448/fd062392-8732-459f-bec1-ce98d0682789)

Weekly 2:
https://youtu.be/3thYHubtg9o?si=JvpZnDMd55daf5Da&t=106

![image](https://github.com/Phala-Network/growth-program/assets/112413448/6ef0fb62-8a28-425f-b22c-ecd741fd0289)

Weekly 3:
https://vxtwitter.com/gabekoin/status/1750516035046785245?s=20

![image](https://github.com/Phala-Network/growth-program/assets/112413448/05a9c310-f086-4b56-9c63-10b523beeab0)

**THREADS CREATED:**

Phala Starter Kit:
https://x.com/gabekoin/status/1751958575168016720?s=20

inDEX Intention:
https://x.com/gabekoin/status/1742570687334686796?s=20

inDEX Intention PT:
https://x.com/phalaportugues/status/1743284128659706144?s=20

Sygma Bridge:
[https://x.com/gabekoin/status/1744442869396513207?s=20](https://vxtwitter.com/gabekoin/status/1744442869396513207?s=20) 

Solver and Intention:
https://x.com/gabekoin/status/1745207408568213721?s=20

Solver and Intention PT:
https://x.com/phalaportugues/status/1745914680848065004?s=20

DWFLabs Explanation:
https://x.com/gabekoin/status/1745906691940483537?s=20

DWFLabs Explanation PT:
https://x.com/phalaportugues/status/1747298764790874231?s=20

Dmail Partnership:
https://x.com/gabekoin/status/1747260243736928549?s=20

Phala The Graph PT:
https://x.com/phalaportugues/status/1749536747241800001?s=20

**ARTICLES TRANSLATED:**

Phala The Graph:
https://medium.com/@phalaptbr/the-graph-starter-kit-um-fluxo-de-dados-nativo-da-web3-para-contratos-inteligentes-baseados-em-aa1fe3c6fde4

**THREADS TRANSLATED**

Lens highlight:
https://x.com/phalaportugues/status/1752374286780608976?s=20

[@AcademyPolkadot](https://twitter.com/AcademyPolkadot), Hong Kong!
https://x.com/phalaportugues/status/1745216007063388360?s=20

Lens:
https://x.com/phalaportugues/status/1748395295749079393?s=20

CMC:
https://x.com/phalaportugues/status/1747296199260995665?s=20

TEE:
https://vxtwitter.com/phalaportugues/status/1747767276814663966?s=20

The Graph:
https://x.com/phalaportugues/status/1748067255005450469?s=20

data driven:	
https://x.com/phalaportugues/status/1748068212527247734?s=20

Polkadot Academy zhou:
https://vxtwitter.com/phalaportugues/status/1749763482830921969?s=20

**LINKEDIN POSTS CREATED:**

Slot #58:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_slot-58-belongs-to-phala-network-a-christmas-activity-7148343475686592512-zIDe?utm_source=share&utm_medium=member_desktop

inDEX:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_index-decoded-the-multi-chain-intent-model-activity-7148344166123565057-ysS2?utm_source=share&utm_medium=member_desktop

Year Recap:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_a-2023-marks-the-4th-year-of-phala-network-activity-7148776661767880705-WPDP?utm_source=share&utm_medium=member_desktop

Sygma Bridge:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-activity-7150210348606709760-4y4u?utm_source=share&utm_medium=member_desktop

Depin Smart Contracts:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_depin-smartcontracts-phatcontract-activity-7150982951663534082-U4Y-?utm_source=share&utm_medium=member_desktop

DWFLabs:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-the-global-digital-asset-market-activity-7151673721076822017-JiXv?utm_source=share&utm_medium=member_desktop

Dmail:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_depin-activity-7153036155804934144-AUsR?utm_source=share&utm_medium=member_desktop

TEES:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_debunking-tee-fud-a-brief-defense-of-the-activity-7153865759327203328-DsbM?utm_source=share&utm_medium=member_desktop

ink! Dev Hub!:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_kusama-activity-7155211425706127360-qPN1?utm_source=share&utm_medium=member_desktop

Zhou:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_polkadotblockchainacademy-phalanetwork-depin-activity-7155533083696340992-UwIc?utm_source=share&utm_medium=member_desktop
Phala Roadmap:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phalas-2024-path-coprocessor-for-blockchainsai-activity-7158137514136924160-D8Zi?utm_source=share&utm_medium=member_desktop

Tako Protocol:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-phalanetwork-on-x-activity-7158533664945942529-PVRQ?utm_source=share&utm_medium=member_desktop

COMMUNITY (CM): 36/40
![image](https://github.com/Phala-Network/growth-program/assets/112413448/54df44e0-eafe-4dba-a7ff-6575e93878c8)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/5f99a5b9-7a05-489b-9eef-d3cba84d5ea3)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/011839a9-0b0a-4088-ac6a-b0ed742d2f90)

![10](https://github.com/Phala-Network/growth-program/assets/112413448/69ee4cf9-7c14-4510-a003-d4fae150b9ba)
![11](https://github.com/Phala-Network/growth-program/assets/112413448/4ff1b97b-c1c0-492b-b47d-1c1e3069e1c6)
![12](https://github.com/Phala-Network/growth-program/assets/112413448/059c546a-20c6-4ae4-9f25-2962233783e4)
![13](https://github.com/Phala-Network/growth-program/assets/112413448/de6048c9-9081-4035-9cfa-344b25f71c1f)
![14](https://github.com/Phala-Network/growth-program/assets/112413448/f6bbab60-97d5-492b-b12a-91defe5a29af)
![15](https://github.com/Phala-Network/growth-program/assets/112413448/f28736e0-e21c-45ef-8075-47f110cc1519)
![16](https://github.com/Phala-Network/growth-program/assets/112413448/ae40996e-d26f-403c-8da5-20e2ad8789ba)
![17](https://github.com/Phala-Network/growth-program/assets/112413448/a7f14390-55c2-4d6f-8b09-a8110869939f)
![18](https://github.com/Phala-Network/growth-program/assets/112413448/cd659ca3-77ae-4f2b-89e8-bad6b805fa14)
![19](https://github.com/Phala-Network/growth-program/assets/112413448/420eb91b-2637-40e6-bc4f-7ab7bfed4cc6)
![1](https://github.com/Phala-Network/growth-program/assets/112413448/bc5c480a-56ae-45d8-a0fa-c9ef6b4dc491)
![2](https://github.com/Phala-Network/growth-program/assets/112413448/2608a172-c4f2-48df-8b48-7b56da6b4e2a)
![3](https://github.com/Phala-Network/growth-program/assets/112413448/679a17c9-516a-4081-9145-a2cb39f7b6f8)
![4](https://github.com/Phala-Network/growth-program/assets/112413448/61a01089-9d00-4b70-909a-edd0cfecae0d)
![5](https://github.com/Phala-Network/growth-program/assets/112413448/9ff9d978-34fe-4b67-b962-d254879f00f4)
![6](https://github.com/Phala-Network/growth-program/assets/112413448/56590921-942b-4eb9-bac0-b5cded88b686)
![7](https://github.com/Phala-Network/growth-program/assets/112413448/379a4e72-0bf6-48d5-b788-cc728e325dcd)
![8](https://github.com/Phala-Network/growth-program/assets/112413448/d2126172-7bbe-4d53-8eb0-4c94f7e7f548)
![9](https://github.com/Phala-Network/growth-program/assets/112413448/1cc2f086-4692-4f9f-8e19-1f5229b1912b)

Supplementary: EM & PM (18/20)

PM: 8/10
https://x.com/NovaWalletApp/status/1742541989231341836?s=20
https://x.com/PhalaNetwork/status/1742268679621091705?s=20
https://x.com/PhalaNetwork/status/1741536181769400348?s=20
https://x.com/zoemcfox/status/1744457497753079987?s=20
https://x.com/PhalaNetwork/status/1744407198636073012?s=20
https://x.com/CryptoCappex/status/1743940948101341349?s=20
https://www.linkedin.com/posts/joshua-waller-33935773_check-out-the-latest-workshop-with-the-graph-activity-7149566236014575616-UGbv?utm_source=share&utm_medium=member_desktop
https://x.com/PhalaNetwork/status/1747688010089717869?s=20
https://x.com/marvin_tong/status/1747676700132205001?s=20
https://x.com/Dmailofficial/status/1748311702410842217?s=20
https://x.com/PhalaNetwork/status/1748381017738481720?s=20
https://twitter.com/CryptoCappex/status/1748412248219906479
https://x.com/TheScarletThr/status/1748611209618682015?s=20
https://x.com/AstarNetwork/status/1748328716336537800?s=20
https://x.com/Immei256/status/1749408251525918895?s=20
https://x.com/PhalaNetwork/status/1749740500670632008?s=20
https://x.com/OrlandoG85/status/1750013376976077095?s=20
https://twitter.com/PhalaNetwork/status/1752370565380190614?s=20
https://x.com/gabekoin/status/1750562454042476863?s=20
https://twitter.com/marvin_tong/status/1751132745827594505
https://x.com/TakoProtocol/status/1750904894398328911?s=20
https://x.com/marvin_tong/status/1752372705318609224?s=20

EM (10/10)

Insights Phala 2024! Com Batman e Robin!
https://x.com/phalaportugues/status/1750566980552151330?s=20
![spaces phala jan](https://github.com/Phala-Network/growth-program/assets/112413448/0a06e9da-7a03-466b-88a0-085e2995beff)

Roadmap 2024:
https://x.com/phalaportugues/status/1752663624080904655?s=20
![Spaces roadmap](https://github.com/Phala-Network/growth-program/assets/112413448/be2ed2fb-77e1-4feb-87ef-1c778254a9d4)

Oráculos Descentralizados
https://x.com/verbodotsama/status/1752780885928140806?s=20

![spaces vds 2](https://github.com/Phala-Network/growth-program/assets/112413448/104b826b-631a-488d-b377-bf1b88184ad5)
![spaces vds](https://github.com/Phala-Network/growth-program/assets/112413448/f1bf2b92-9740-437f-b52e-a1bcbf85ffd5)

Suggested scores:

[CC] 40/40
This month was excellent, I've produced maaany content and we had great reach on Twitter and Youtube

[CM] 36/40
This month activity was great. Many new users in all channels and that's exciting!
Brasilian community is growing, developing some activities like spaces to keep them engaged.
For next month: Keep growing our local community and keep supporting International Phala Channels

[PM] 8/10
Shared all oficial content in all main social medias.

[EM] 10/10
We hosted three Twitter Spaces (Insights 2024, Roadmap and Oracles). 

Overall suggested score: 94/100.

Totally happy about this month.
Many new users interesed in Phala's new products and asking about our recent partnerships, 2024 is our year!

For the next month: Do better

**Comment by willphala** [comment]
Great report!
