### ISSUE TITLE
January 2024 Contributions - {the_scarlet_thread}

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#355]
Amb Rank: Ambassador
Telegram Username: @Scarlet_Thr
Discord Username: @the_scarlet_thread
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

### MANDATORY 
**CONTENT CREATION**
**_Threads/Long-form posts_**

1. Created this post about the Crowdloan Unlock that happened on January 16th. We had many ask about this so I made this thread for easy reference, linking helpful resources and information.
https://twitter.com/TheScarletThr/status/1745856512499593689?t=WwsPY4rvpt4LH7HtZaSyCA&s=19

Made 1 video/gif for this article
https://github.com/Phala-Network/growth-program/assets/99918790/6d8c4212-387f-47ca-a517-a716a20d6d5d

2. Created this thread discussing DePin and Phala (how Phala fits into DePin & what is Depin). I am using bold and italics fonts to break up long-form posts into sections so it doesn't look like one giant wall of text.
https://twitter.com/TheScarletThr/status/1750818723261264098?t=I2nhx03DW8p22iiUZzhFeQ&s=19
(The graphic used in this post, I used in my Medium article about this topic which I will list below).

3. This thread I created was about Phala's role as a coprocessor. 
https://twitter.com/TheScarletThr/status/1747207012096585907?t=6ICJwnWWcb2p93h840aPjg&s=19

Made 7 artwork pieces for this thread:

This is the first animation which I've made in blender (added the sound later in another app). Tried something new and I am happy with the result (for the first time). It took a lot of hours + trial and error to create which took a few days. Linked here👇
https://github.com/Phala-Network/growth-program/assets/99918790/bba7a304-0542-4b57-b65a-6f4aa409cb92

Video
https://github.com/Phala-Network/growth-program/assets/99918790/b85506c0-e2e6-4f81-9429-19287993a38d
Graphics 
![20240205_174919](https://github.com/Phala-Network/growth-program/assets/99918790/66069e94-1baf-4fcc-997f-c7faffe3402a)
![20240205_174922](https://github.com/Phala-Network/growth-program/assets/99918790/3f825a24-af36-4732-8968-363b20ca7347)
![20240205_174935](https://github.com/Phala-Network/growth-program/assets/99918790/8e3abaff-d782-456e-949b-8fd7d4a0387d)
![20240205_174913](https://github.com/Phala-Network/growth-program/assets/99918790/9454d33f-e911-4a2d-851a-ecbedb34748f)
![20240205_174926](https://github.com/Phala-Network/growth-program/assets/99918790/613cde46-8e3e-4942-bf7b-0cc437169881)

4. The topic of this post was how Phat Contracts can give smart contracts access to the internet. This post was also liked by The Kusamarian and Ajuna Network.
https://twitter.com/TheScarletThr/status/1751914253991235817?t=uVqQilfqy97mqB84LKS6jw&s=19

Video I made for this post:
I made a video with transitions and some music to make the post interesting and like a TL:DR for those who don't want to read the whole thing.
https://github.com/Phala-Network/growth-program/assets/99918790/787d405f-488f-42e0-b434-08c23e3c8981

5. This post is about cross-chain interoperability. It was a recap from Phala Africa's community call and conveyed the general idea of what all of us said. It was posted on Phala Africa's X page. This post was also liked by The Kusamarian.
https://twitter.com/PhalaAfrica/status/1751964560276193536?t=RLwtrDl60OmWZKm_2cob9A&s=19

I made  6 artwork pieces for this post:
Video:
https://github.com/Phala-Network/growth-program/assets/99918790/fdf448d5-649b-472d-9e09-aeb3fdd0f9af

Graphics 
![20240128_065838_0000](https://github.com/Phala-Network/growth-program/assets/99918790/351eb2a0-8e63-44db-a7c3-d29c631f5ca8)
![20240128_065838_0001](https://github.com/Phala-Network/growth-program/assets/99918790/6894b276-710c-47bd-b1d3-427b35d48401)
![20240128_065838_0002](https://github.com/Phala-Network/growth-program/assets/99918790/b94be214-5f0d-49b1-b6aa-b6ff1a566ff8)
![20240128_070227_0000](https://github.com/Phala-Network/growth-program/assets/99918790/09d2c9c5-1d19-4b76-b172-f3b003105c1a)
![20240128_065838_0004](https://github.com/Phala-Network/growth-program/assets/99918790/47248c2e-0527-4e90-aa71-0d8b8a3beadf)

6. This post is about the Verifiablity of Phat Contracts and Phala's off-chain computations.
https://twitter.com/TheScarletThr/status/1752754293860393036?t=eweH9vxPJvgF8sNvtw4GEw&s=19

Video made for this post:
Added transitions, music and some visuals to make this post interesting...and this is video is a short summary of the thread.
https://github.com/Phala-Network/growth-program/assets/99918790/0c42864a-090a-4b17-9fe7-d261fa40b857

**_Article_**
Topic for this article is Depin & Phala's role in it. After researching, I finally consulted a few main resources to create this article and listed them at the end of the article. I tried to keep buzzwords to a minimum and focus on the main point. 
https://medium.com/@TheScarletThread/depin-phala-network-decentralized-syngery-in-web3-90220d73d3d7

Graphics made for this article:
![1_20240125_101821_0000](https://github.com/Phala-Network/growth-program/assets/99918790/021d80c8-52c1-4d7f-8ea7-0787ac0a51f1)

![2_20240125_101821_0001](https://github.com/Phala-Network/growth-program/assets/99918790/cfe15398-7f47-48af-8450-5056ceb2741a)
![3_20240125_101821_0002](https://github.com/Phala-Network/growth-program/assets/99918790/87c222f0-3360-4f13-8496-9facd4ec2889)
![4_20240125_101821_0003](https://github.com/Phala-Network/growth-program/assets/99918790/3eeb50f6-8f40-4d0f-84bc-423b4aedb3a3)
![5_20240125_101821_0004](https://github.com/Phala-Network/growth-program/assets/99918790/687c7540-a2c6-41ee-911f-88180c1b69b4)

**_Infographics_** 
1. Lifecycle of delegation 

https://twitter.com/TheScarletThr/status/1747896598263202058?t=QCk5wPZLl2w6nMzqqH9xWQ&s=19
![20240118_101824_0000](https://github.com/Phala-Network/growth-program/assets/99918790/04e0d41d-af49-4c94-94bb-cfb55a28e7ed)

2. Delegation Essentials ( what you need, difference between stakepool and vault)
https://twitter.com/TheScarletThr/status/1748658127778566339?t=lLfifzQ7Jf1Unku4Gg-a4w&s=19
![20240120_124036_0000](https://github.com/Phala-Network/growth-program/assets/99918790/b466e33f-a386-4c54-92bb-0ff147ac38cb)

3. Phat Contracts Features
https://twitter.com/TheScarletThr/status/1749697736230801666?t=2Sw15dmlEwMSaeG7w4rcZg&s=19
![Delegators_20240123_092908_0000](https://github.com/Phala-Network/growth-program/assets/99918790/3fb5dc27-db87-462a-aca5-7c028a000751)

4. Airstack x Phat Contract
https://twitter.com/TheScarletThr/status/1751579610557411603?t=1Lub9ICsIIZ_7nWUhUV6WQ&s=19
![20240128_141038_0000](https://github.com/Phala-Network/growth-program/assets/99918790/d677e928-a49b-4daf-8747-472df929117e)

5. The Graph x Phat Contract
https://twitter.com/TheScarletThr/status/1752221571622535415?t=HokYJYlpGab04w_IPIu5dg&s=19
![20240130_083928_0000](https://github.com/Phala-Network/growth-program/assets/99918790/9bbb1ee4-ce6b-4c60-9913-402fc4f6be22)

**_Meme_**
1. Small Brain Man Shouting at Big Brain Man
https://discord.com/channels/697726436211163147/766661203111575553/1195105525772320879

2. Thanos Completes the Gauntlet 
https://discord.com/channels/697726436211163147/766661203111575553/1195488517346824202

3. Impressive Facts
https://discord.com/channels/697726436211163147/766661203111575553/1196065005666308196

4. Mercy offers hand
https://discord.com/channels/697726436211163147/766661203111575553/1196534484628148314

https://t.me/PhalaAfrica/5904

5. Two guys on a Phala bus 
https://discord.com/channels/697726436211163147/766661203111575553/1197265250169409558

6. Oprah shocked reaction
https://discord.com/channels/697726436211163147/766661203111575553/1197575640786927636

https://twitter.com/TheScarletThr/status/1748273846107476198?t=pigQfgcFU9f75-GyH5-8vg&s=19

7. Vegeta Oxygen Tank
https://discord.com/channels/697726436211163147/766661203111575553/1197980085370748958

https://t.me/PhalaAfrica/5926

8. Be Honest Beckham
https://discord.com/channels/697726436211163147/766661203111575553/1199259363194441829

9. Wake up 
https://discord.com/channels/697726436211163147/766661203111575553/1200027393461604433

10. Fastest things on earth meme
https://discord.com/channels/697726436211163147/766661203111575553/1200719673919033394

11. You Can Just Give This Kind Of Thing To Devs
https://discord.com/channels/697726436211163147/766661203111575553/1201157151599640656

12. Give me advice
https://discord.com/channels/697726436211163147/766661203111575553/1201647105148735529

13. Hulk Gives Taco
https://discord.com/channels/697726436211163147/766661203111575553/1202222560704471113

**Good Points**
I put a lot of time into each piece of content I create and constantly look to improve my content ( such as learning to making better videos, getting better graphics, making it more aesthetically pleasing, writing better content and getting points across in a more simple yet accurate way).
 
Tried something new this month which was making an animation and graphics myself on blender. 

**Bad Points**
Need to work harder on getting my points across in a simple way with less buzzwords. Work on widening my reach on X and Medium by engagement and networking.  

**How To Improve**
Research effective ways for writing and  practice. Network with other content creators and ambassadors. Look for ways to create more professional graphics. Engage in more communities on X. 

**COMMUNITY MANAGEMENT**
_**Moderation & Helpdesk**_
I participated in monitoring the PhalaWorld, Phala Telegram, Phala Africa Telegram, and Phala Discord to eliminate spam, malicious content, engage and answer questions of the community. Addressing negative feedback to the best of my ability. 

_See a few examples below:_
![1000054093-01](https://github.com/Phala-Network/growth-program/assets/99918790/6cb4caf7-128d-4888-af22-247209a3dc75)
![1000054094-01](https://github.com/Phala-Network/growth-program/assets/99918790/d5ac44ab-86fd-48da-8184-5a417cd765bd)
![1000054096-01](https://github.com/Phala-Network/growth-program/assets/99918790/31d2962e-7f40-466f-b525-f1cb546b0f8f)
![1000054097-01](https://github.com/Phala-Network/growth-program/assets/99918790/9ee42406-f293-46ae-b77b-e82901b09482)
![1000054098-01](https://github.com/Phala-Network/growth-program/assets/99918790/8196a447-b536-4d2f-b46a-6933ca9c46a4)
![1000054099-01](https://github.com/Phala-Network/growth-program/assets/99918790/12f18db2-569e-4ea9-b845-95dc2293186a)
![1000054100-02](https://github.com/Phala-Network/growth-program/assets/99918790/2c87f293-8b2e-4403-a981-6145c8e67625)
![1000054102-01](https://github.com/Phala-Network/growth-program/assets/99918790/40110367-80bf-40e2-9ad1-0e35612dc0f0)
![1000054103-01](https://github.com/Phala-Network/growth-program/assets/99918790/1dc30c8b-326d-469d-9a26-c54ae83c3b2a)
![1000054104-01](https://github.com/Phala-Network/growth-program/assets/99918790/f208b383-044c-4191-99da-53f4aebafd3d)
![1000054105-01](https://github.com/Phala-Network/growth-program/assets/99918790/d1f33fc3-3229-411f-89c6-02f374d19420)
![1000054106-01](https://github.com/Phala-Network/growth-program/assets/99918790/285ce3fc-4f81-4fa8-ac7e-9655bb5dc4eb)
![1000054107-01](https://github.com/Phala-Network/growth-program/assets/99918790/9448f964-9042-4b6d-9df9-3802db35b2b3)
![1000054110-01](https://github.com/Phala-Network/growth-program/assets/99918790/cb5d2442-3bf8-49cb-8648-c5ca3ab30363)
![1000054126-01](https://github.com/Phala-Network/growth-program/assets/99918790/14cae86e-3339-42f3-9ab2-ea88d03464fa)
![1000054128-01](https://github.com/Phala-Network/growth-program/assets/99918790/d4a07f2c-8d08-4ac8-aa2f-1474bf14e76d)
![1000054129-01](https://github.com/Phala-Network/growth-program/assets/99918790/6e2a618d-bba8-4e98-a290-5fbd1862f2cf)
![1000054131-01](https://github.com/Phala-Network/growth-program/assets/99918790/e985e353-0f5e-4128-b2c9-77cf5bfeaf39)
![1000054135-01](https://github.com/Phala-Network/growth-program/assets/99918790/eb650288-6244-47b5-b80d-413cf97bd85d)
![1000054132-01](https://github.com/Phala-Network/growth-program/assets/99918790/61d9108b-a845-4705-97e0-a5348371955b)

_**Phala Africa**_
Like last month, I've worked alongside our advocate. I provided constant coaching and assistance throughout the month (also evaluate their performance and give feedback so that they can grow and work towards being an ambassador).

Providing guidance, feedback and assistance to Phala Africa ambassadors, delegating tasks and tracking progress being done. Evaluating areas of strength and what needs to be improved.

Research, planning and creating strategies to grow the community and ways that our Phala Africa team can improve collaboration within the team and increase output. I have started working with our tech wiz Bekka to make content for technical community.  

• Share helpful resources to community about Phala and partners.

• Shared feedback/concerns in the ambassador-only community channel on Discord.

• Stats
Phala Discord
![1000054084-01](https://github.com/Phala-Network/growth-program/assets/99918790/a0e2b8cd-c78d-4511-a4d0-3f31a9280efe)
PW Discord
![1000054086-01](https://github.com/Phala-Network/growth-program/assets/99918790/140903ad-c04e-4def-9bac-1bad133cda62)
Phala Official Telegram
![1000054089-01](https://github.com/Phala-Network/growth-program/assets/99918790/362c21a0-0f9c-4d89-858f-691a4ddc57f5)
Phala Africa Telegram
![1000054090-01](https://github.com/Phala-Network/growth-program/assets/99918790/73629741-12ef-479d-a82b-8a02ac229de2)

**Good Points**
I had more participation in global channels. 
Improvement in collaboration in Phala Africa team. 

**Bad Points**
Need to give more focus to growing the Phala Africa technical community 

**How To Improve**
Work with Bekka on intiatives to reach tech communities within Africa

### SUPPLEMENTARY 
**PM**
I've been promoting Phala Network (local groups + global) and contributed to increasing visibility across various platforms. I contributed by talking about Phala's various aspects through posting on Twitter, Telegram and Discord. I engaged with the community, sharing updates and initiating insightful discussions about Phala, Phat Contracts and PhalaWorld. 

In addition to what is shown in the screenshots below, I've  engaged through liking, commenting and retweeting content from: Phala Network ambassadors, Partners, Phala Network Twitter, fellow ambassadors and Phala Team members. I promoted events that Phala had, updates and various forms of content.
![1000054142-01](https://github.com/Phala-Network/growth-program/assets/99918790/f9d46a70-095a-4682-9b72-f21fc9bf98c6)
![1000054143-01](https://github.com/Phala-Network/growth-program/assets/99918790/a3565160-3d40-4a12-974b-68906e79645c)
![1000054145-01](https://github.com/Phala-Network/growth-program/assets/99918790/af77e7f7-186e-468b-8db9-0da9ad2fa7f2)
![1000054146-01](https://github.com/Phala-Network/growth-program/assets/99918790/0a99dcbf-5647-4996-882d-97e75bd0713b)
![1000054149-01](https://github.com/Phala-Network/growth-program/assets/99918790/c4f5cbfb-70e3-4ad2-a0cb-344e253f3c12)

**EM**

**_Phala Africa January Community Call_**
We held a panel discussion on X, the topic was "cross-chain interoperability". Together we were able to hold an engaging call that had the highest attendance (we had around 33 attendees...after the call X showed 194 tuned in but I'm not sure how this is calculated). Our two latest ambassadors have especially contributed. This format works well and community seems more engaged by this format of call. We also had a few notable attendees who popped in at various parts of the call. Here is a screenshot of one particular part of the call.
![1000053037-01](https://github.com/Phala-Network/growth-program/assets/99918790/c9bf82c2-5fe9-4325-8abe-0f842f2ae79a)

I played my role in this event by:
• Guiding the organization of the call; initiated polls and discussions about various aspects of organising and doing tasks; delegated roles; brainstorming ideas for the event; tracked progress and finalizing details.

• Created banner for the announcement of the event.
![20240114_164506_0000](https://github.com/Phala-Network/growth-program/assets/99918790/f9641908-419e-493b-9ec9-bad637dc924d)

• Created the agenda and added 4 questions to be asked during panel discussion. Bekka also added a great question here. 
https://docs.google.com/document/d/13dinh8JRy1SRTbdNwSMIQ3bbNpSSvc-pPhQ_76XOsHs/edit?usp=drivesdk

• I was one of the panellists, so I prepared answers for each question
https://docs.google.com/document/d/1oxHBUrwTwF2wOoaMi7wC1QzVO8pzf7cnjFPFqthymO4/edit?usp=drivesdk

• Attended rehearsal for the call on 23 January (few days before call) to ensure everything went smoothly.

### SCORES
**CC**: 38/40
**CM**: 38/40
**PM**: 9/10
**EM**: 7/10
TOTAL: 92

**CLOSING COMMENTS** 
I'm trying new ways of making content and improving my skill. Also, for Phala Africa I'm working on shifting some focus to technical community, and shall work closely with Phala Africa ambassadors to get this done and improve our output. I look forward to doing collaborations with Gator and helping other ambassadors wherever possible. 

Thank you 🙏
Scarlet

**Comment by willphala** [comment]
Great work. As always, thank you for taking the time to write such a detailed report 👏
