### ISSUE TITLE
January 2024 Contributions - Gatorkorps

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#356]
Hello :-)

Telegram Username: @gatorkorps
Discord Username: gatorkorps
Twitter Username: https://twitter.com/gk18_dog
PHA Wallet Address: 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV

A good start for 2024 !

![image](https://github.com/Phala-Network/growth-program/assets/82824139/499868d1-a349-4ec0-82cd-8508cad0e07b)

Community:

Phalafr twitter account management
phalaFR telegram
and ban several shitcoin chiller on the main Phalanetwork TG

Marketing

PHA chilling:
https://twitter.com/gk18_dog/status/1750502578855559432

OP French Crypto Need to Know Phala
With Rom1 This one was very important, with our Polkadot and Phalanetwork flag we speak to almost 20 people about the capacity of PhatContract, a good way to evengelise french crypto community.

https://twitter.com/Blockchains_FR/status/1748756794510360651
https://www.youtube.com/watch?v=A72XJ5e8z4k
https://twitter.com/antoinemarchain/status/1749361022018695291

Blockchain addict a new french crypto media interviewed me with Tioneb to speak about Phala. I was the instigator (haha) of this interview and I invit Tioneb to help me on the Tech side. It was a great experience and we had more than 1 hour to speak about Phala and the capacity.  Blockchain addict is set up by the Cief redactor of "Le journal du Coin" one of the most read Blockchain media specialist in french langage.

https://twitter.com/gk18_dog/status/1751686923188334866
Op Push Depin Narrative : a simple message to promote Phala on another french blockchain media account

On line event networking : to exchange possibility I gave this contatc to tioneb where he speak (a lot) of Phala during the networking event, to a dedicated public here to speak about cloud and computation (a perfect target) mmore in his Report (I only gave him the info of the event)
https://twitter.com/waxzce/status/1745739611140227151

Amplification of Dr Kush live to present the Phat Contract
https://twitter.com/DrKidam/status/1751299893317054805

https://twitter.com/gk18_dog/status/1750038284623851560 We need decentralized Cloud / after a lot of discussion about the EU problem who will use US Cloud (microfost azure) I push the decentralized cloud narritive with Phala to bring exposure on anither target audience.

https://twitter.com/TheMoonBearer/status/1746557494057406720 Plant a seed it will give a tree one day

https://twitter.com/gk18_dog/status/1744648277574713788 PhalaFr best song adaptation to bring Good vibe on a Depin narrative tweet.

https://twitter.com/gk18_dog/status/1744431099458003134 more PHA push up

OP PINK:
https://twitter.com/gk18_dog/status/1743226188795986084
https://twitter.com/marvin_tong/status/1743336712867365355 Marvin answer
I was really happy to push the possibility to Phala to be a part of the Pink Glory. It was an easy way to bring sympathie and free marketing for the protocole. It will continue with the next Pink liberation token and the % who will be allocated to the Phala community (a great plan would be to communicate a lot about the possibility....) 
The core team played the game and that's why I love to be a part of the Phamily :-)

It was the most succefful engagement according to my january marketing plan (on line)

I will pass on all the amplification made by the Phala Fr account. You know what I mean :-)

What next ?

We plan A French Phala Network in May, more info to come :-)

CC Content Creator

Some Pixel art on preparation but we will come back next month with more things about it. My Content month was quiete (an  interview would be a content creation and marketing ^^)
I really enjoy to help Chris in this great idea and project.

According to the great month and succes of all the OP I would say that I deserve the bonus this month :-)

Thanks for reading, more collaboration with scarlet with come, if you need help the french community is here !

MK: 40/40
CM: 40
CC: 10

thank you, cheers

**Comment by willphala** [comment]
Great work! 🐊
