### ISSUE TITLE
January 2024 Contributions - {TIONEB}

### ISSUE THREAD

**Issue by tionebDotsamapha** [Phala-Network/growth-program#358]
Telegram Username: [tioneb](https://t.me/tioneb)
Discord Username: tioneb#4951
Twitter Username: [tioneb_DotSama₱ha](https://twitter.com/tioneb442)
PHA Wallet Address: 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7

Departments : #CM & #MK
Department Score Weight : 50% & 50%

Hello !!

First of all, I think I should explain why my last activity report was dated October and why I didn't provide those for November and December.
I'm running out of time. At the beginning of each month, when the "Phala report" task is in competition with others, it loses the "urgent first" battle.

As always, I tryed to react as quickly as possible to the fr community, whether on the telegram or on the discord server. But I have to admit that the community isn't too active these months.
The old-timers know the project well and don't have any questions other than "wen usescases?" No new members wishing to introduce themselves and find out what Phala is all about... 
I'm still relaying important news and have tried to promote Phala-network as a major project in the DePIN narrative, reminding anyone who will listen that in "DePin" there's "De" for decentralize....  

Since November, I've been presenting myself as a Phala-Network ambassador at local events. 
- In November, I had lunch with a small group from a local telegram, made up of people who work full time in BC.

- In december, I went to this event: 
https://blockchainsociete.org/events/2023-12-13/
<img width="454" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/5ec1f6a6-6c06-4a3c-af9d-c349f4e109a5">

I estimate that about 20 people attended and that everyone heard about Phala-Network because I chatted with everyone.   

- In January: I went to the recording of a show offered by Clever Cloud
https://www.clever-cloud.com/fr/blog/entreprise/2023/12/05/maci-fete-lepisode-100/
![image](https://github.com/Phala-Network/growth-program/assets/16654460/aebaa161-746c-40e9-8000-542faad68bac)
<img width="948" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/435de5ac-2245-4a06-9288-1486e572edc5">

This was followed by an amazing party and I met a lot of people who work at Clever Cloud and in the cloud services world.
Really interesting night and my astonishment after understanding that all of these web2 professionals do not understand at all the web3 that is coming (Whether it is decentralized, trustless and respectful of privacy or not). Even if some people see what a blockchain is, they don't understand how their data center business model will be reduced to providing DePIN resources to a decentralized network without having to implement, administer and secure cloud services. But that's what they're selling today.

As I was the technical manager of a dataCenter in a previous life, that's a way i will try to work in the next months.

I know this report is not structured as in the past but it's better than nothing AMO.
Thanks for your understanding.

Tio !
![image](https://github.com/Phala-Network/growth-program/assets/16654460/7e4140da-1b2e-4ff9-ad52-856da4abfe8f)

EDIT !!! I Forgot the best.... 🤦😂

Thanks Gator we was invited for an interview at Blockchain addict YT channel it's a new french crypto. It was a great !

https://twitter.com/Blockchains_FR/status/1748756794510360651
https://www.youtube.com/watch?v=A72XJ5e8z4k
https://twitter.com/antoinemarchain/status/1749361022018695291

<img width="890" alt="image" src="https://github.com/Phala-Network/growth-program/assets/16654460/fa388a2a-ab12-4cd6-9dae-5100a8326c3b">

**Comment by tionebDotsamapha** [comment]
score i suggested to my report : 80

**Comment by willphala** [comment]
Excellent work. I'm sure you were a great representative of the Phamily 😎
