### ISSUE TITLE
January 2024 Contributions - {defiguy}

### ISSUE THREAD

**Issue by astardefi** [Phala-Network/growth-program#360]
Telegram Username: @defiguy2022

AMB Rank: Candidate Ambassador

Discord Username: defiguy

Twitter Username: @defiguy22

PHA Wallet Address: 44PTq2ZCxXxPM3FYubiPtMw53WCXNdXUfNDnCE6c7wFixMbB

Departments: #CC / #CM

# Contributions

I helped spread information about Phala Network on Twitter, reaching thousands of users. I also created content for a more specialized audience on LinkedIn using infographics. Additionally, I established an account for the Brazilian community on TikTok.

I provide weekly updates on my YouTube channel https://www.youtube.com/watch?v=z577xf6aT70 about the Polkadot ecosystem and have a segment dedicated to sharing updates on Phala Network. **Average views close to 445 
(updated)**
![Screen Shot 2024-02-07 at 19 40 27](https://github.com/Phala-Network/growth-program/assets/104277195/d4d9fdd0-3f51-41e6-9282-2c45cbed48af)

# CC

## **Twitter posts**

https://twitter.com/defiguy22/status/1754841512771305584

**587 views**

https://twitter.com/defiguy22/status/1752442793568489834
**1074 views**

https://twitter.com/defiguy22/status/1752001693951184971

**1021 views**

https://twitter.com/defiguy22/status/1751942624544432636

**892 views**

https://twitter.com/defiguy22/status/1751581590940000602
**1096 views**

https://twitter.com/defiguy22/status/1750135069925109948
520 views

https://twitter.com/defiguy22/status/1749443085396762943
907 views

https://twitter.com/defiguy22/status/1748425096430023126
1276 views

https://twitter.com/defiguy22/status/1747592987947700663
736 views

https://twitter.com/defiguy22/status/1745414296962502904
978 views

## PHALA SEGMENT (Youtube videos)
![Screen Shot 2024-02-07 at 20 06 41](https://github.com/Phala-Network/growth-program/assets/104277195/f9b0d969-154b-4b2d-9c90-474c0e4119b7)

![Screen Shot 2024-02-07 at 20 06 59](https://github.com/Phala-Network/growth-program/assets/104277195/9d9ea90c-2a3b-4fbf-b49b-17a7cc61fee7)
https://youtu.be/bgTA0sItKCk?t=2419 - Phala Coprocessor announcement

![Screen Shot 2024-02-07 at 20 09 00](https://github.com/Phala-Network/growth-program/assets/104277195/c72e2f3b-68dd-40be-b120-a167e1ade6af)
https://youtu.be/jdf02xRKrm8?t=2618 - Phala Lens Proposal 

![Screen Shot 2024-02-07 at 20 10 25](https://github.com/Phala-Network/growth-program/assets/104277195/06737895-9896-461f-8e85-07601f4cd4a7)
https://youtu.be/vEBgLGju9dY?t=2818 - PHALA inDEX tech overview

# HD 

![Screen Shot 2024-02-07 at 20 12 59](https://github.com/Phala-Network/growth-program/assets/104277195/cc4f9388-3706-4f9b-a4a6-4e56ebea7870)

Suggested Scores:

#CC: 30/40

#СМ: 20/40

#CC: 10

#ART: 10

#HD : 2

Overall: 72

**Comment by willphala** [comment]
Nice work. Please note that your departments and supplementary tasks can't overlap as then you would be rewarded for the same type of contributions twice. For example, CM and HD are both community related contributions and CC (department), CC (supplementary task) and ART are all CC (department) based. Please ping me if any of this is unclear :)
