### ISSUE TITLE
January 2024 Contributions - John Rhodel

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#361]
Telegram Username: https://t.me/parachainboy
Discord Username: johnrhodel
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

CC : 40/40

Filipino Translations:
https://polkaverse.com/11194/paano-maglabas-at-kumuha-ng-mga-kaganapan-sa-phat-contract-50383
https://polkaverse.com/11194/ang-landas-ni-phala-sa-2024-coprocessor-para-sa-mga-50381
https://polkaverse.com/11194/ang-graph-starter-kit-isang-web3-native-dataflow-para-sa-50390
https://polkaverse.com/11194/phala-2023-taon-sa-pagsusuri-50389

Portuguese Translation:

https://medium.com/@phalaptbr/como-emitir-e-capturar-eventos-no-phat-contract-cc6f51829400
https://medium.com/@phalaptbr/o-caminho-da-phala-para-2024-coprocessador-para-blockchains-ai-hooks-e-depin-50d7fe54017c
https://medium.com/@phalaptbr/phala-2023-revis%C3%A3o-do-ano-6cfbce4726ab

Arts:

![1](https://github.com/Phala-Network/growth-program/assets/77474076/392bb9f8-af53-4277-8b09-293226467f2a)
![2](https://github.com/Phala-Network/growth-program/assets/77474076/09a60334-0597-40b8-ae98-aad90af46e1e)
![3](https://github.com/Phala-Network/growth-program/assets/77474076/b0edfd48-4475-4d48-956b-24906cc5fb4c)
![4](https://github.com/Phala-Network/growth-program/assets/77474076/9aaf2d6b-5d5f-4b7d-a681-b8eb1108a401)

MK:(35/40)

![21223](https://github.com/Phala-Network/growth-program/assets/77474076/0bfa7a5c-80e4-49e9-88bc-531888ae5e36)
![image32](https://github.com/Phala-Network/growth-program/assets/77474076/5487ee98-9fd4-47f8-a099-87490fb19bae)
Twitter Spaces about Roadmap from Phala
https://twitter.com/phalaportugues/status/1752663624080904655

![Captura de tela 2024-02-06 211206](https://github.com/Phala-Network/growth-program/assets/77474076/bf7e8e2a-2b67-4cd9-ad61-8ab3b7ac73ed)

![image](https://github.com/Phala-Network/growth-program/assets/77474076/adeb3c94-ea40-4ebd-9ce1-b9b956beb95d)

Twitter Spaces about Insights Phala 2024
https://twitter.com/phalaportugues/status/1750566980552151330

Posted Liked and RT Parachainboy and Phala:

https://twitter.com/parachainboy/status/1752664144522686543
https://twitter.com/parachainboy/status/1752470976598528197
https://twitter.com/phalaportugues/status/1752388144232558989
https://twitter.com/phalaportugues/status/1752328113894080681
https://twitter.com/phalaportugues/status/1752327827695833159
https://twitter.com/phalaportugues/status/1752092702672343064
https://twitter.com/phalaportugues/status/1749763482830921969
https://twitter.com/phalaportugues/status/1749536747241800001
https://twitter.com/phalaportugues/status/1748395295749079393
https://twitter.com/phalaportugues/status/1748395298290909283
https://twitter.com/phalaportugues/status/1748395302342599113
https://twitter.com/phalaportugues/status/1748395307572814296
https://twitter.com/phalaportugues/status/1748395324077486510
https://twitter.com/phalaportugues/status/1748068212527247734
https://twitter.com/phalaportugues/status/1747298764790874231
https://twitter.com/phalaportugues/status/1745216007063388360
https://twitter.com/parachainboy/status/1743389181999562895
https://twitter.com/phalaportugues/status/1743284128659706144

HD:(10/10)

![photo_2024-01-26_11-59-06](https://github.com/Phala-Network/growth-program/assets/77474076/21d58eec-dd31-42b5-8cec-68418eb10858)
![photo_2024-01-27_20-47-48](https://github.com/Phala-Network/growth-program/assets/77474076/6a6591ee-bb1d-4371-b5a1-af5e1485a8c1)
![photo_2024-01-30_15-47-23](https://github.com/Phala-Network/growth-program/assets/77474076/c34f5d67-5c71-4eab-aa29-ffcfdb250de6)
![photo_2024-01-30_20-27-02](https://github.com/Phala-Network/growth-program/assets/77474076/cc59bfaa-f7ce-43bd-96b0-f7faf8d0dc32)
![photo_2024-01-31_09-49-13](https://github.com/Phala-Network/growth-program/assets/77474076/1ada84c2-db89-462c-af8e-5ab691d81c90)
![photo_2024-01-31_13-11-30](https://github.com/Phala-Network/growth-program/assets/77474076/be1bf5a4-c6c6-423b-a7ea-fe10a22d045f)
![photo_2023-12-30_15-29-48](https://github.com/Phala-Network/growth-program/assets/77474076/9340765d-0ae2-48ba-a7ec-861d9c426734)

EM:(10/10)
![09](https://github.com/Phala-Network/growth-program/assets/77474076/f1d2d4ff-0677-48f3-a140-d232e13143f0)
![photo_2024-01-31_16-57-07](https://github.com/Phala-Network/growth-program/assets/77474076/4000babc-1bbc-454e-83f6-2fe833d20975)

Event Spaces about Oracles in Polkadot i'm talked about Phala and how the projects its very important for Polkadot

https://twitter.com/verbodotsama/status/1752780885928140806

My rate (95/100)

This year will be a year of increasingly accelerated growth and our work as ambassadors will be fundamental to the growth of the Phala brand!

I'm well motivated

**Comment by willphala** [comment]
Excellent report.
