### ISSUE TITLE
February 2024 Contributions - infaceAi

### ISSUE THREAD

**Issue by infaceAi** [Phala-Network/growth-program#367]
February 2024 report {infaceAi#5149}

PERSONAL INFO
Amb Rank: Senior Ambassador
Discord: infaceAi
Telegram:[ @infaceAi](https://t.me/infaceAi)
Twitter: https://twitter.com/infaceAi
PHA Address: 45vo82ABupacJoafLRW8oVWiYyErk9UqZLpfBn8wtE1zcB4M

Departments : #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

**Contributions**:
MK & CC -  I promote PhalaNetwork & PhatContract on Twitter & Phala local X account. Using new topics according to the Phala 2024 roadmap.
Also I do activities at Phala general and local telegram chats and some for Discord.
 
**Х analytics** February 2024 stats:

<img width="778" alt="X" src="https://github.com/Phala-Network/growth-program/assets/112633185/f266e334-482b-49bc-9366-7458ee6c9f55">

<img width="1117" alt="X1" src="https://github.com/Phala-Network/growth-program/assets/112633185/5860d238-9c0f-4880-96f8-c13b30125768">

<img width="813" alt="X2" src="https://github.com/Phala-Network/growth-program/assets/112633185/2f381304-64b3-485d-b912-60ece5eb2427">

Twitter analytics and https://analytics.twitter.com/user/infaceAi/home

<img width="671" alt="X stats" src="https://github.com/Phala-Network/growth-program/assets/112633185/3c86a27d-aa5c-4f47-b853-e4ebe6594c5f">

**X local**

<img width="931" alt="X u1" src="https://github.com/Phala-Network/growth-program/assets/112633185/b0bf1c19-e23f-44e5-a441-e9a521438233">

<img width="1062" alt="X u" src="https://github.com/Phala-Network/growth-program/assets/112633185/901bcab9-c614-41d1-bd30-8fcc518e7d70">

<img width="726" alt="X _u" src="https://github.com/Phala-Network/growth-program/assets/112633185/d5094c34-49ac-4050-91e6-467e07e3ab62">

**Phala tg** (local) - https://combot.org/c/1649002165/a

<img width="634" alt="tg 02 24" src="https://github.com/Phala-Network/growth-program/assets/112633185/aa057723-0252-4f81-a6b0-6b01c12e9b32">

**SUPPLEMENTARY** TASKS
#HD I did good support, trying to be as helpful as possible when someone seeks help for delegation/deposit/withdrawal/general question about Phala.

#ART - Some of the best art:
https://twitter.com/infaceAi/status/1758034911171133744
https://twitter.com/infaceAi/status/1754402979514642934
https://twitter.com/infaceAi/status/1758392265913815268
https://twitter.com/infaceAi/status/1756583856449228952
https://twitter.com/infaceAi/status/1760202703978815792

SUGGESTED SCORES
#CC : 40/40
#MK: 40/40
#HD: 10

I am trying to be even more active than last month. My X score as well as Phala Ukrainian X increased very well, both in new followers and in total people engagement.
(+38 for me and about 30 for local X. For X local it's almost +50% compared to last month!).

I’d like to inform you that in March month we are planning 2 local calls:  Amb call and local month community call.

I would like to mention the very good contribution of:
Dmitry (ivakhnenko_dmitriy). He was super active in Phala's social media chats.
Tori (toriribolla), she made the coolest sticker pack! Which is very popular among the participants of the telegram chat.

p.s: Cappex was and is top Ambas!

**Phala LFG!**

**Comment by willphala** [comment]
Fantastic report. Thank you for the info on Dmitry, Tori and Capps ❤️
