### ISSUE TITLE
inFaceAi candidate Ambassador Sept 2022 report

### ISSUE THREAD

**Issue by infaceAi** [Phala-Network/growth-program#37]
Telegram : [infaceAi](https://t.me/infaceAi)
Discord :infaceAi#5149
PHA Address : 45vo82ABupacJoafLRW8oVWiYyErk9UqZLpfBn8wtE1zcB4M
Have I participated in Discord Channel Moderation (choose)? Yes
Have I participated in Telegram Channel Moderation (choose)? Yes
I started https://t.me/PhalaWorld_ru (for both PN&PW) https://combot.org/telegram/top/groups?lng=all&page=1&q=Phala
![изображение](https://user-images.githubusercontent.com/112633185/193463471-249d2606-3b74-45f2-b78d-8dfe97f14215.png)
Definitely tiny, but very active group! 

Twitter
![изображение](https://user-images.githubusercontent.com/112633185/193463599-36561d71-8ced-4b0a-80e5-07e71b73e722.png)
![изображение](https://user-images.githubusercontent.com/112633185/193463622-2f9bb9e6-7af4-48c1-a6ab-7bf0c222f7cf.png)
![изображение](https://user-images.githubusercontent.com/112633185/193463638-eb92e5b6-6de6-46ab-94c5-a867347a03ba.png)

Medium&Phala forum
6 Articles about mining translated in Russian https://forum.phala.network/t/topic/3660
6 Articles related to PN including weekly reports (these are + 6 new to mentioned above and without 2 articles about PW **that contains >4k words**)
Also I prepared "how to" - reclaim PHA https://forum.phala.network/t/topic/3642

**Comment by luciaaaa4455** [comment]
Nice start, keep building!
