### ISSUE TITLE
February 2024 Contribution {rafaccc#5473}

### ISSUE THREAD

**Issue by rafaccc** [Phala-Network/growth-program#372]
Telegram : [rafaccc](https://t.me/rafaccc)
Discord : rafaccc#5473
Dirección PHA: 42LYD29z2f6hYQeuamH5puXTGa1KHhWd6YxYSHXzRjih4xJd

----------------------------------------------------------------------------------------------------------------------

**CONTENT**
You can also find other images of content created for other topics in other sections.

https://twitter.com/RafaelCabilla/status/1763389890534809995
![p12](https://github.com/Phala-Network/growth-program/assets/97988345/f4b28ddc-cea9-4684-a895-d457deb07996)

https://twitter.com/RafaelCabilla/status/1756127880017252422
![p1](https://github.com/Phala-Network/growth-program/assets/97988345/3ad162b4-c015-4c22-b7d9-beaaac05abc1)

https://twitter.com/RafaelCabilla/status/1755727894343528821
![p2](https://github.com/Phala-Network/growth-program/assets/97988345/5ebc1ddb-d57e-4a3d-9856-cbfb071ac4f6)

https://twitter.com/RafaelCabilla/status/1756806039955988881
![p3](https://github.com/Phala-Network/growth-program/assets/97988345/4ae0c8ea-cace-4457-9adc-82a7271d70c3)

https://twitter.com/RafaelCabilla/status/1758151220483457531
![p4](https://github.com/Phala-Network/growth-program/assets/97988345/6d4c392e-d143-4a8c-bfa6-011f190ee95e)

https://twitter.com/RafaelCabilla/status/1758984368364614037
![p5](https://github.com/Phala-Network/growth-program/assets/97988345/c6c14bea-8e9c-415d-9850-4b5d5f6efc24)

https://twitter.com/RafaelCabilla/status/1759722902625124651
![p6](https://github.com/Phala-Network/growth-program/assets/97988345/25b7aec9-1352-41f6-9118-cf3b8d1eb9ea)

https://twitter.com/RafaelCabilla/status/1761172025681313942
![p7](https://github.com/Phala-Network/growth-program/assets/97988345/5d800836-b2a3-4501-82f0-98200f16e6ee)

**GIF/VIDEO CONTENT**

https://twitter.com/RafaelCabilla/status/1762496842242437294
![P8](https://github.com/Phala-Network/growth-program/assets/97988345/773a26ba-064a-4f18-ad34-b6f34310ad89)

**TRANSLATED THREADS (5)**

https://twitter.com/PhalaEspanol/status/1754463989700898905
https://twitter.com/PhalaEspanol/status/1754478373575733270
https://twitter.com/PhalaEspanol/status/1758106630741479727
https://twitter.com/PhalaEspanol/status/1758517410443800869
https://twitter.com/PhalaEspanol/status/1759733355283685622

**TRANSLATION OF ARTICLES (9)**

1) https://medium.com/@rafacabilla/phala-network-que-es-depin-5daabb9a3580
2) https://medium.com/@rafacabilla/c%C3%B3mo-crear-una-cuenta-de-phat-dashboard-y-obtener-tokens-de-prueba-6bd839c78182
3) https://medium.com/@rafacabilla/phala-network-en-ethdenver-2024-32563f5dab6f
4) https://medium.com/@rafacabilla/descubriendo-el-poder-de-los-oracles-blockchain-un-vistazo-a-los-oracles-de-phat-contract-en-phala-a50cc2fb968c
5) https://medium.com/@rafacabilla/qu%C3%A9-es-el-coprocessor-4b60efef3311
6) https://medium.com/@rafacabilla/coprocessor-marco-de-computaci%C3%B3n-sin-confianza-c98ded509535?postPublishedType=initial
7) https://medium.com/@rafacabilla/coprocesador-obtenci%C3%B3n-de-datos-con-oracles-de-funciones-web3-298b49db8e5d
8) https://medium.com/@rafacabilla/coprocessor-marco-de-verificaci%C3%B3n-de-seguridad-beed5e878cf8
9) https://medium.com/@rafacabilla/descubriendo-el-poder-de-los-oracles-blockchain-un-vistazo-a-los-oracles-de-phat-contract-en-phala-cb839a4b7592

**MY ARTICLE: FEBRUARY SUMMARY**

https://medium.com/@rafacabilla/resumen-mensual-en-espa%C3%B1ol-4094cf7290e6
https://twitter.com/PhalaEspanol/status/1763326026804052203
![P9](https://github.com/Phala-Network/growth-program/assets/97988345/9b023380-5b4f-4418-91ca-f01683ffcd36)

**AMA**
Monthly call to the community in Spanish. Monthly call with the community, this month we will continue with a very good participation who participated in the AMA. We talk about Phala, its updates and everything that happened in the month

https://meet.google.com/drd-zynb-erd
![AMA phala1](https://github.com/Phala-Network/growth-program/assets/97988345/bb5bdc6b-32ec-4ca8-96be-02aa70f6e8fb)

https://twitter.com/PhalaEspanol/status/1763318695026192692
![p10](https://github.com/Phala-Network/growth-program/assets/97988345/7a7df887-9190-4ccc-98e4-03639c142bdb)

**TELEGRAM**
![image](https://github.com/Phala-Network/growth-program/assets/97988345/01980b25-d9a1-402e-aa3c-3835db5b4fd3)

**TWITTER (X)**

https://analytics.twitter.com/user/RafaelCabilla/home
Half of the total posts on Twitter are from Phala.

![image](https://github.com/Phala-Network/growth-program/assets/97988345/2f24373e-d2f2-4286-acbf-af5c5277b918)

https://docs.google.com/spreadsheets/d/1p948CPSDOTq0EG1s6p4_9NjEf0uguJNvtwordYuBrx0/edit?usp=sharing
![p11](https://github.com/Phala-Network/growth-program/assets/97988345/0d3071e5-6be0-4446-9a21-71c32205fc83)

**RT**
https://x.com/PhalaNetwork/status/1762898936715411919?s=20
https://x.com/PhalaNetwork/status/1762899185139880336?s=20
https://x.com/marvin_tong/status/1762499820982349938?s=20
https://x.com/PhalaNetwork/status/1762106358290088391?s=20
https://x.com/PhalaNetwork/status/1761058950265421861?s=20
https://x.com/Polkadot/status/1761154127932035346?s=20
https://x.com/PhalaNetwork/status/1760614394738753614?s=20
https://x.com/PhalaNetwork/status/1760636199104831881?s=20
https://x.com/PhalaNetwork/status/1760667037289071087?s=20
https://x.com/PhalaNetwork/status/1760295920938156128?s=20
https://x.com/PhalaNetwork/status/1759977976299458741?s=20
https://x.com/PhalaNetwork/status/1759995762493272232?s=20
https://x.com/PhalaNetwork/status/1759569203806310694?s=20
https://x.com/hashwarlock/status/1758745499501256861?s=20
https://x.com/PhalaNetwork/status/1758490000805507483?s=20
https://x.com/PhalaNetwork/status/1758074669041701140?s=20
https://x.com/PhalaNetwork/status/1757026770887278847?s=20
https://x.com/marvin_tong/status/1756003625149886819?s=20
https://x.com/PhalaNetwork/status/1755912326190891093?s=20
https://x.com/marvin_tong/status/1755668332135805205?s=20
https://x.com/PhalaNetwork/status/1755554569235399144?s=20
https://x.com/PhalaNetwork/status/1755267790049812721?s=20
https://x.com/PhalaNetwork/status/1754864413004136650?s=20
https://x.com/PhalaNetwork/status/1755185267856560253?s=20
https://x.com/PhalaNetwork/status/1754562043091595537?s=20
https://x.com/PhalaNetwork/status/1753448075413094783?s=20
https://x.com/PhalaNetwork/status/1753084240097390991?s=20
---------------------------------------------------------------------------------------------

MK: 38/40
CC: 38/40
ART: 10/10
Others: 10/10

Again this month I have developed all aspects:

-Translation of threads into Spanish
-RT and translation into Spanish of Phala's publications
-Creation of content in images, and Marketing
-Creation of content in GIF videos
-Monthly AMA session for the Spanish community
-Creation of an original article about Phala
-Translation into Spanish of various official articles of Phala.

**Comment by willphala** [comment]
Great #CC work! Please note that as previously explained if you belong to a department, all related supplementary tasks will be allocated to the department. For example, if you are in the #CC department, doing the ART supplementary task will be added to the department not as a separate task as you can't be rewarded twice for the same contribution. Please send me a dm if this does not make sense.
