### ISSUE TITLE
February 2024 Contributions - {the_scarlet_thread}

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#375]
Amb Rank: Ambassador
Telegram Username: @TheScarletThr
Discord Username: @the_scarlet_thread
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

### MANDATORY 
**CONTENT CREATION**

_**Threads/Long-form posts**_

1. Wrote a thread about Phat Contracts feature of running arbitrarily complex logic. In addition to writing the content of the long post, I made a video ( not everyone likes to come on X to read a long post, so listening/watching to a video is easier). 
_To make this video, my workflow was as follows:_
•Write and edit script, adapted from written content.
•Create each slide of visuals, add text and add extras such as transitions and cute graphics.
•Generate the voice over, edit to voice over to fit the correct timing.
•Download in high quality so that even with the compression of videos on X, it comes through okay (unfortunately downloaded in 4k but it doesn't show as good on X).
https://twitter.com/TheScarletThr/status/1756374383336075742?t=Bc65D06f9Dqs5Pvg8CMOnQ&s=19

2. Wrote thread about Phat Contracts omni-chain compatibility. In addition to the written post, this also had a video to listen to with a unique imaginative style introduction. 
 _My workflow for the video is as follows:_
•Script video and thread to convey the intended ideas and points
•Create opening lines for the imaginative introduction (city and beach)
• Create appropriate visuals for opening
• Make voiceovers
•Add sound effects
• Make graphic for each point and find suitable videos to match each point, add extras
https://twitter.com/TheScarletThr/status/1759474583252488526?t=XGVWpk9noWkwTTjJ1Egqfw&s=19

3. Wrote thread about Phala's approach to security and highlighted Phala's presence
at Ethereum Denver.
https://twitter.com/TheScarletThr/status/1761017926830723576?t=cwJHJtTgDG0CZeQTv49ktQ&s=19

Made the following graphics for this thread:

https://github.com/Phala-Network/growth-program/assets/99918790/e76aeb92-eaf7-47b0-85d0-8055bc6cfaaf

https://github.com/Phala-Network/growth-program/assets/99918790/f2177a7c-b849-40ac-bcd9-8b8bc16d8d8c

![20240223_151739_0000](https://github.com/Phala-Network/growth-program/assets/99918790/f22c87db-f488-4d70-a52f-c0103f8a0920)
![20240223_151740_0005](https://github.com/Phala-Network/growth-program/assets/99918790/30d4e464-236f-4190-be4b-c2a2a7eeb85a)
![20240223_151740_0004](https://github.com/Phala-Network/growth-program/assets/99918790/0226ed18-82f4-4b41-8ad6-666b1f26f862)
![20240223_151740_0003](https://github.com/Phala-Network/growth-program/assets/99918790/a5170167-d112-4570-b241-c2c9c7b4d864)
![20240223_151740_0002](https://github.com/Phala-Network/growth-program/assets/99918790/3eee133a-d74e-420d-a008-53d990c528e3)
![20240223_151739_0001](https://github.com/Phala-Network/growth-program/assets/99918790/0b15c6a1-93fe-440a-9780-3946c9fdc96b)

4. Wrote thread about oracles in blockchain and Phala's role in them highlighting this edition of Phala 101. 
https://twitter.com/TheScarletThr/status/1762358033189884375?t=cx93Oeh-x4iwRyTA0KPYCw&s=19

Made the following graphics for this thread:
![Add a heading_20240226_162836_0000](https://github.com/Phala-Network/growth-program/assets/99918790/cf536411-1f60-4f3c-9e6a-a4a8b4aa3998)
![6_20240226_162952_0001](https://github.com/Phala-Network/growth-program/assets/99918790/de4d4599-3f38-4d83-bd71-50cb2f13ddff)
![5_20240226_162952_0000](https://github.com/Phala-Network/growth-program/assets/99918790/83972829-d11a-4147-a76e-d46c94443d83)
![20240226_163327_0000](https://github.com/Phala-Network/growth-program/assets/99918790/b1e7f146-2b8c-4c5e-989d-fed59995a852)
![20240226_164813_0000](https://github.com/Phala-Network/growth-program/assets/99918790/e5ab01e6-85dd-4044-a54e-6d4419c91432)
https://github.com/Phala-Network/growth-program/assets/99918790/ff883fa7-7cc4-4d69-b39f-7c56aa45b07d

5. Wrote this short article on Polkaverse, titled "Phala Network: off-chain, on-point" about the benefits that Phala has even for the non-technical community.
https://polkaverse.com/12916/78850
Made the following graphic for this post:
![20240228_133605_0000](https://github.com/Phala-Network/growth-program/assets/99918790/c028435e-bd05-43d2-b67a-93450449aaff)

6. Wrote this short article on Polkaverse titled "Leading the pack in DePin"...which was about Phala and DePin which highlighted the Phala 101 blog about "What is DePin?". 
https://polkaverse.com/12916/phala-network-and-de-pin-80275
Made the following graphic for this post:
![Add a heading_20240229_184830_0000](https://github.com/Phala-Network/growth-program/assets/99918790/7e0919d6-5a1f-476a-aa38-acd6e7c82f59)

_**Infographics**_

1. Account Abstraction
https://twitter.com/TheScarletThr/status/1754783518406685113?t=ZikTgdPRffyOdxpiblFcMA&s=19
![20240206_102049_0000](https://github.com/Phala-Network/growth-program/assets/99918790/82e4ad40-5149-4e30-bbc1-1bf658e75afa)

2.  Did you know ? Phala + Depin
https://twitter.com/TheScarletThr/status/1758081193965166774?t=ZtrULQKkdGLzEwAQSHXR_g&s=19
![Delegators_20240215_124552_0000](https://github.com/Phala-Network/growth-program/assets/99918790/dcac1cc6-5bf2-4c27-bcb5-70b7accb3a8e)

5. Some limitations that Phala addresses
https://twitter.com/TheScarletThr/status/1760212689505104261?t=AkzP8aUKbTelmSsHjiPXEg&s=19
![Delegators_20240219_011225_0000](https://github.com/Phala-Network/growth-program/assets/99918790/6b4ffb9e-7cf7-4177-98e9-6f0de95ebd6f)

6.  Highlighting questions discussed during  Phala Africa Community Call 
https://twitter.com/TheScarletThr/status/1761420079143547168?t=FJHAFlDsVDrBLm9T_7gl7w&s=19
![20240224_175427_0000](https://github.com/Phala-Network/growth-program/assets/99918790/d264cf66-5024-4a85-a305-14278583040f)

7. Phat Contract Features
https://twitter.com/TheScarletThr/status/1762201032824655988?t=mGoiCyozD64Tx_m0Dh_C0A&s=19
![Delegators_20240226_213333_0000](https://github.com/Phala-Network/growth-program/assets/99918790/f7a320ea-9097-434e-a308-f344b5bc29c0)

8.  Blockchain Oracles
https://twitter.com/TheScarletThr/status/1763095424754233580?t=C9bT_JrR8vuq8P_NCOyzRQ&s=19
![Delegators_20240229_084626_0000](https://github.com/Phala-Network/growth-program/assets/99918790/8f8ca22c-7f66-4997-8b37-f0563ecabec4)

_**Memes**_

1. Spongebob Not Scared of The Flying Dutchman 
https://discord.com/channels/697726436211163147/766661203111575553/1204309103921471538

2. Computer Guy
https://discord.com/channels/697726436211163147/766661203111575553/1204742745596629082

4. This could be us
https://discord.com/channels/697726436211163147/766661203111575553/1205202760518205500

5. What your heart is saying

https://discord.com/channels/697726436211163147/766661203111575553/1205202760518205500

6.  Phat Contracts have omnichain compatibility Endgame Portal

https://discord.com/channels/697726436211163147/766661203111575553/1206306635044360242

7. Robot presenting Phala 
https://discord.com/channels/697726436211163147/766661203111575553/1206987024800944169

9.  Shoto Todoroki 
https://discord.com/channels/697726436211163147/766661203111575553/1207439414381518920

10.  Buff Tom
https://discord.com/channels/697726436211163147/766661203111575553/1208712981534343219

11.  Phala Friday Nights 
https://discord.com/channels/697726436211163147/766661203111575553/1209774636620058654

12. Tell me the truth I'm ready to hear it
https://discord.com/channels/697726436211163147/766661203111575553/1210207299914702848

13. Reduced To Atoms
https://discord.com/channels/697726436211163147/766661203111575553/1211273318695436299

14. A Little Fox
https://discord.com/channels/697726436211163147/766661203111575553/1211652475480834068

15. What gives people the feeling of power
https://discord.com/channels/697726436211163147/766661203111575553/1212063875328118834

16.  Cast It Into the Fire
https://discord.com/channels/697726436211163147/766661203111575553/1212296688253800448

17. Goku power
https://discord.com/channels/697726436211163147/766661203111575553/1212754873242751017

_**Video series**_
Started a new video animated series as a fun experiment, called "Paraverse Journals" on YouTube. I'm going to work on improving my skills. There will be a Phala edition, and I've posted episode one called " What the Pha ? ". 
This look really long to do and my workflow for this video was as follows:
• Create premise for the whole series
• Research, create first draft and final draft of the script. Read script here:
https://docs.google.com/document/d/1c4pgNfziSG72jTpqeFXW_bBVwltz_1yPFSlKhotr1O4/edit?usp=drivesdk

• Create the voiceover for each character. I made the voiceover for the main character Mia and generated the voice for the robot. Had to do multiple takes of my voiceover to get the right tone.

• Made the background. Each element in the background is a separate file (couch, desk, computer, pot plant, lounge chair etc...) so that the characters can move between the objects to look more realistic and gives room depth. Made a larger background so I can make different "camera" shots later (wide shot etc)

• Animate each character separately according to the audio. Animate the mouth movements (need to improve on this...), animate hand, leg and face movments.

• Combine all elements together ( background, each characters animations, audio). Set the scene and match the timing of audio to the rest of the animation and added extra effects. Created close-up scenes and wide shots etc. 

• Made YouTube thumbnail:
![PJ YouTube Thumbnails_20240227_175121_0000](https://github.com/Phala-Network/growth-program/assets/99918790/3b4cbdfd-8d37-4fc5-80e5-348413f72b5a)

**Good Points**
I tried something completely new which was making an animation, and i focused on improving the quality of each piece of content by making more effective graphics, videos and trying unique openings. I was happy to collaborate with Gator, who translated the script to French so the video can have accurate subtitles in French.

**Bad Points**
Didn't make a Medium article this month and would like to interact with other accounts who make posts about topics relevant to Phala ( like leave comments, engage)

**How To Improve**
Be more vigilant on social media, mention Phala in relevant posts in a tasteful way.

**COMMUNITY MANAGEMENT**
• I participated in monitoring the PhalaWorld, Phala Telegram, Phala Africa Telegram, and Phala Discord to eliminate spam, malicious content, engage and answer questions of the community. Addressing negative feedback to the best of my ability. See examples below:
![Screenshot_20240306_184929_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/1606bdcf-67d3-480e-a3ef-cb34ab27a2a1)
![1000058547-01](https://github.com/Phala-Network/growth-program/assets/99918790/bd0d1a75-87fc-48c2-903f-735a9c80206c)
![1000058548-01](https://github.com/Phala-Network/growth-program/assets/99918790/f2927843-d40b-40a5-8763-d68cc8aa7692)
![1000058549-01](https://github.com/Phala-Network/growth-program/assets/99918790/c2a3eb91-fc8e-4b32-856e-b8e86509e92e)
![1000058551-01](https://github.com/Phala-Network/growth-program/assets/99918790/c011fc7e-c0bd-4443-8ee4-4916d230130d)
![1000058552-01](https://github.com/Phala-Network/growth-program/assets/99918790/b4aa4951-4781-47a7-9ad4-eb2ceb998269)
![1000058553-01](https://github.com/Phala-Network/growth-program/assets/99918790/5ad9111a-d930-4eb2-be91-3d35368ca914)
![1000058554-01](https://github.com/Phala-Network/growth-program/assets/99918790/f2c9ce81-2146-43d7-b54b-cb7e32cd169a)
![1000058555-01](https://github.com/Phala-Network/growth-program/assets/99918790/a9a6c545-decb-4400-a46e-0badf0243c21)
![1000058556-01](https://github.com/Phala-Network/growth-program/assets/99918790/0113eabc-af8f-4c80-b973-2bdc2d0ab64c)
![1000058557-01](https://github.com/Phala-Network/growth-program/assets/99918790/6922c2b4-9103-43fd-a39e-41dc77839c68)
![1000058569-01](https://github.com/Phala-Network/growth-program/assets/99918790/1b8b01de-0188-4096-ba8f-0736f71b761c)

I've contributed towards helping our advocate by providing constant coaching and assistance throughout the month. He has now progressed to candidate. 

Supporting Phala Africa ambassadors efforts by offering guidance, feedback, and aid, assigning tasks, and monitoring progress. Assessing strengths and areas requiring improvement.

Researching, planning, and developing strategies to increase community engagement and improve teamwork and productivity within the Phala Africa team.

I participated in the community ambassador channel, gave ideas, feedback and conveyed some community sentiments to team.

•Stats:
![1000058539-01](https://github.com/Phala-Network/growth-program/assets/99918790/23b7b709-a368-445e-9937-243107b3ec6a)
![1000058540-01](https://github.com/Phala-Network/growth-program/assets/99918790/acdc4c73-3355-4787-b757-3bb577f05cca)
![1000058543-01](https://github.com/Phala-Network/growth-program/assets/99918790/a3896070-73a2-41cc-85c6-cdda301ff31b)
![1000058545-01](https://github.com/Phala-Network/growth-program/assets/99918790/c50e530e-e7bc-440d-851a-0bde3b816934)

**Good Points**
There were a lot of questions by community for Phala, probably boosted by the recent market movement and I assisted by answering questions and removing spam/scams in local and global channels. Phala Africa had a good rehearsal.

**Bad Points**
Low engagement on our local community and overall our collaboration within Phala Africa has slowed down.

**How To Improve**
Try different strategies, network with those who have experience and learn more about ways to boost community involvement. Attract more technical community members. Brainstorming with Phala Africa team on how we can collaborate more effectively, respond faster and increase productivity (more than just our regular community calls).

### SUPPLEMENTARY 
**PM**
I've actively promoted Phala Network both locally and globally, contributing to enhancing its visibility across diverse platforms. Through posts on Polkaverse, X, Telegram, YouTube and Discord, I've discussed various aspects of Phala, including Phat Contracts and PhalaWorld, engaging with the community and fostering insightful discussions.

Beyond the screenshots provided, I've interacted by liking, commenting, and retweeting content from Phala Network ambassadors, partners, the Phala Network X account, and Phala Team members. I've also promoted Phala's events, updates, and various forms of content.
![1000058574-01](https://github.com/Phala-Network/growth-program/assets/99918790/39d289e8-2238-4711-9846-03f35bb13822)
![1000058575-01](https://github.com/Phala-Network/growth-program/assets/99918790/237be7fe-3439-48a6-b0df-5e9846379c25)
![1000058576-01](https://github.com/Phala-Network/growth-program/assets/99918790/f188fb7c-6205-4923-9d34-42ee8c434dd9)
![1000058577-01](https://github.com/Phala-Network/growth-program/assets/99918790/6e937a0f-973e-441d-8f98-7fc0c8a7a957)
![1000058585-01](https://github.com/Phala-Network/growth-program/assets/99918790/04b526e4-0b74-43ed-a195-8deb8182a8bb)
![1000058579-01](https://github.com/Phala-Network/growth-program/assets/99918790/74fe3603-5beb-4aa9-a613-d63ada428933)
![1000058580-01](https://github.com/Phala-Network/growth-program/assets/99918790/8cb09c9e-e3ff-4262-916e-044f725eba28)
![1000058647-01](https://github.com/Phala-Network/growth-program/assets/99918790/e7891f40-9f0e-4d41-9df1-2085dc480c32)

**EM**
Phala Africa Community Call

We had another panel discussion on the topic of  Phala being the coprocessor for blockchains. It was an interesting call and 37 tuned in according to stats on X. This is quite an achievement for Phala Africa from our calls last year. Here is a screenshot of one moment in the call:
![Screenshot_20240223_154233_X-01](https://github.com/Phala-Network/growth-program/assets/99918790/f41810da-590f-4d72-85a1-27073447d124)

The recording has been made available here on Phala Africa X page:
https://twitter.com/PhalaAfrica/status/1761020389919002766?t=uVE3vQVdQcOoJmJM475pzg&s=19

I played my role by:
• Guiding the organization of the call:
 Initiated polls and discussions about various aspects of organising and doing tasks; delegated roles; brainstorming ideas for the event; tracked progress and finalizing details.

• Created banner for the announcement of the event.
![February Banner](https://github.com/Phala-Network/growth-program/assets/99918790/2b2ba621-55fe-45be-8cf5-a68a8bdfa1e3)

• Created the agenda and added some of the questions to it:
https://docs.google.com/document/d/1A9kQbRcPZ37x2D_saBYdLPlANReviZOjwZFTAYprJuw/edit?usp=drivesdk

I was one of the panellists so I prepared answers  for each question ( each of us answering questions at random but we prepared for every question)
https://docs.google.com/document/d/1tW_1sIh_arneNtTzBNlukx-pqc_0et2XeSzzkDGUz6E/edit?usp=drivesdk

•Attended the rehearsal and contributed feedback to improving our calls.

• Started working with Bekka on planning an event geared toward technical community. 

### SCORES
**CC:** 37/40
**CM:** 37/40
**PM:** 10/10
**EM:** 8/10
**TOTAL:** 92

### CLOSING COMMENTS 
I'm continuing to look for various effective ways of making content, improving my skills and learning new ones. With regards to Phala Africa, I am working on getting technical community-focused content done. I plan to work closely with fellow Phala Africa ambassadors to enhance our productivity. I am eager to collaborate with ambassadors and support others as much as possible.
Thank you !☀️
Scarlet

**Comment by willphala** [comment]
Excellent report!
