### ISSUE TITLE
September Contribution - {Angie_ada#0973}

### ISSUE THREAD

**Issue by Angie-ada** [Phala-Network/growth-program#38]
Telegram Username: @angie_ada
Discord Username: Angie_ada#0973
PHA Wallet Address: 42qf1tXPH8HfxBqUpTv79VHiTghEatoBnM1QULFgRRXeiUiL
Contributions:
MANDATORY TASKS

CM - Yes I contributed to moderating the official Phala Network Discord and telegram channels. I successfully provided Non-technical support and welcome new members. Also encouraged participation in Community calls.

The challenge was I wasn't very familiar with some of the Technical details in mining and node setup.

I asked for help from the core team for difficult questions and learning from the patterns senior ambassadors like CappeX use in providing the technical support .
![Screenshot_20221003-101812](https://user-images.githubusercontent.com/87555884/193542884-92e311b3-9367-41a0-8930-0b8d6a71d78a.png)
![Screenshot_20221003-101744](https://user-images.githubusercontent.com/87555884/193542913-d20fd752-7329-40b2-8251-e84ea0dfa5a1.png)

VSM - Twitted 4 memes & 2 Tweets
[https://twitter.com/_encrypted_____]
[https://analytics.twitter.com/user/_encrypted_____/tweets]
![Screenshot_20221003-105757](https://user-images.githubusercontent.com/87555884/193550783-a862a23d-bd13-46d4-b022-0de532e882b9.png)

TT - Wrote a tutorial 
[https://medium.com/@Angie_ada/how-to-claim-spirit-nft-435c35dba37e]
![Screenshot_20221003-112103](https://user-images.githubusercontent.com/87555884/193555425-8ecab87a-c83d-4b8e-9af9-25b55a4712de.png)

CC - 2 Articles >800 words
[ https://link.medium.com/EAADw2mDMtb
 https://link.medium.com/At4mrwhBMtb]
![Screenshot_20221003-112852](https://user-images.githubusercontent.com/87555884/193556500-39f59188-df29-4f64-a513-83135af20fad.png)
![Screenshot_20221003-112751](https://user-images.githubusercontent.com/87555884/193556516-d1625746-15ac-4410-90b5-689d9a7bd7af.png)

CC - 1 Short Video
[https://twitter.com/_encrypted_____/status/1576842951619026945?t=YfNZR_fS-6UedRz9SQKzig&s=19]

ART - 2 Animated Logos
[https://twitter.com/_encrypted_____/status/1573806248671297543?t=NwkgAQS4hnl15N1cZogXAQ&s=19
![Screenshot_20221003-113916](https://user-images.githubusercontent.com/87555884/193558227-d54217ee-67c2-471f-85d2-862954e396ff.png)]
[https://twitter.com/_encrypted_____/status/1573809568110596098?t=aXfhT5ives-h5HZ1YP16sw&s=19
![Screenshot_20221003-114053](https://user-images.githubusercontent.com/87555884/193558467-dea79a4b-d4d5-4ca9-bffa-eae98a4485fd.png)]

**Comment by luciaaaa4455** [comment]
Nice start! A nice place to publish Phala content--Phala forum
