### ISSUE TITLE
April 2024 contributions report {toriribolla}

### ISSUE THREAD

**Issue by toriribolla** [Phala-Network/growth-program#399]
PERSONAL INFO
Amb Rank : Ambassador
Telegram: @toriribolla
Twitter: @toriribolla
PHA Address : 435b1mp9FuSY4X6NNMTN6mALfyeChiQU1htPViw7hnD26sEM

Departments: #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

CC Contributions:

X @toriribolla:
1. https://x.com/ToriRibolla/status/1781344134697001064
2. https://x.com/ToriRibolla/status/1783460592776257657
3. https://x.com/ToriRibolla/status/1783471279602884993
4. https://x.com/ToriRibolla/status/1783809751387652378
5. https://x.com/ToriRibolla/status/1783813271818043398

![image](https://github.com/Phala-Network/growth-program/assets/132458076/71b2bcb3-76f7-4e14-bdd0-864812621fc3)

X @PhalaRussia:
1. https://x.com/PhalaRussia/status/1781262119956021514
2. https://x.com/PhalaRussia/status/1781329168971481260
3. https://x.com/PhalaRussia/status/1781623856915943457
4. https://x.com/PhalaRussia/status/1781684247067316609
5. https://x.com/PhalaRussia/status/1781986236426588565
6. https://x.com/PhalaRussia/status/1782046638149681570
7. https://x.com/PhalaRussia/status/1782348622644072553
8. https://x.com/PhalaRussia/status/1782711019166638383
9. https://x.com/PhalaRussia/status/1783073407527182625
10. https://x.com/PhalaRussia/status/1783435789101363440
11. https://x.com/PhalaRussia/status/1783798183513973165
12. https://x.com/PhalaRussia/status/1783828673965232210
13. https://x.com/PhalaRussia/status/1784160566845862162
14. https://x.com/PhalaRussia/status/1784190761631687163
15. https://x.com/PhalaRussia/status/1784522954119754002
16. https://x.com/PhalaRussia/status/1784583349962416613
17. https://x.com/PhalaRussia/status/1784589059743945047
18. https://x.com/PhalaRussia/status/1784915543423930445
19. https://x.com/PhalaRussia/status/1784945739413455184
20. https://x.com/PhalaRussia/status/1785247729318298067
21. https://x.com/PhalaRussia/status/1785308121415524397

![image](https://github.com/Phala-Network/growth-program/assets/132458076/fbd16ef1-8266-48a1-88a5-0f14e9dc4244)

MK Contributions:

X analytics @toriribolla:
![image](https://github.com/Phala-Network/growth-program/assets/132458076/b50ecb95-17ed-407d-99da-e91987f883f9)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/0700eb25-6a91-479a-ac8e-64c24ed330f4)

X analytics @PhalaRussia:
![image](https://github.com/Phala-Network/growth-program/assets/132458076/ca8ebbb3-4df5-476c-b81a-0dd591f8b609)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/2bae0c1d-0336-4c1a-85d2-07225ba6407b)

CC:
Translation: https://medium.com/@ribollavvv/138648ae8b0b
Translation: https://medium.com/@ribollavvv/f5a714e10828
Translation: https://medium.com/@ribollavvv/863963b6457a
Translation: https://medium.com/@ribollavvv/95c9e2a9bae4

ART:
![image](https://github.com/Phala-Network/growth-program/assets/132458076/0cbdf838-c1ce-4506-bd3e-e8f840bce85b)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/52724947-b1e1-44da-bb5d-cef3d12a9145)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/e7ea3836-8815-4ace-93d1-9d3d5bf75e70)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/d9ab4b80-4b8f-487c-918f-9f3374e05879)

EM:
https://x.com/PhalaRussia/status/1784589059743945047
I co-hosted a twitter space with mantra for the local Russian community. We covered the latest news, including AI agent contract and Agent Wars. 

SUGGESTED SCORES
#CC : 40
#MK : 30
#ART : 10
#EM : 10
Overall : 90

**Comment by willphala** [comment]
Brilliant work. Congrats on earning 90 points! 😎
