### ISSUE TITLE
April 2024 Contributions - Gabekoin

### ISSUE THREAD

**Issue by gabekvds** [Phala-Network/growth-program#400]
Telegram : @gabekoin
Discord : gabekoin
PHA Address : 454fB2TPc4MtcE5LD44t3Q4oQNLA3mqPojzcBYJ1yEiDv5Kt
My Mandatory (Basic) Contributions of April:
Senior Ambassador

**CONTENT (CC): 40/40**

**Threads Created:**
Tuesday #War:
https://twitter.com/gabekoin/status/1782742257684086965

Tuesday #War PT:
https://x.com/phalaportugues/status/1783524811601318252

AI Agents:
https://x.com/gabekoin/status/1774815390335414553?s=20

AI Agents PT:
https://x.com/phalaportugues/status/1775150124949184903?s=20

Blockspace:
https://x.com/gabekoin/status/1775906318156517589?s=20

Blockspace PT:
https://x.com/phalaportugues/status/1777020584817242355

what to expect:
https://x.com/gabekoin/status/1776342119617020187

what to expect PT:
https://x.com/phalaportugues/status/1777020584817242355

new era:
https://x.com/gabekoin/status/1777470151446671675

new era pt:
https://x.com/gabekoin/status/1777470151446671675

meetup:
https://x.com/gabekoin/status/1776394552976216105

game changer:
https://x.com/gabekoin/status/1778452941734588705

game changer pt:
https://x.com/phalaportugues/status/1778455089578905809

contract offering:
https://x.com/gabekoin/status/1780225910639112633

contract offering pt:
https://x.com/gabekoin/status/1780225910639112633

integration web3:
https://x.com/gabekoin/status/1781308873694974009

**Articles Translated:**
Blockspace:
https://medium.com/@phalaptbr/blockspace-pronto-para-agente-ai-da-phala-network-c4dc9f1dc77a

AI Agent:
https://medium.com/@phalaptbr/apresentando-o-contrato-de-agente-ia-para-agentes-inteligentes-6e272834c424

Agent War:
https://medium.com/@gabekoin/apresentando-agent-wars-fed289961a1e

**Threads Translated:**
multiagentes:
https://x.com/phalaportugues/status/1780601029719196049

ai agent game:
https://twitter.com/phalaportugues/status/1782456739016655282

Shaping the future:
https://x.com/phalaportugues/status/1784937307331608768

Monthly:
https://x.com/phalaportugues/status/1779892390150676709

Ambassadors:
https://x.com/phalaportugues/status/1778059799709602274

Blockspace:
https://x.com/phalaportugues/status/1775213256275116518?s=20

AI Agent:
https://x.com/phalaportugues/status/1777326719524815232

Flock:
https://x.com/phalaportugues/status/1775933423309205891?s=20

eigen layer:
https://x.com/PhalaNetwork/status/1778775263339245598

revolução:
https://x.com/phalaportugues/status/1780599699357286759

Trilha sonora:
https://x.com/phalaportugues/status/1780903328529948904

kus mensagem:
https://x.com/phalaportugues/status/1784014502079455645

Agent AI hash:
https://x.com/phalaportugues/status/1784986557067206928

**LINKEDIN POSTS CREATED:**
Blockspace:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_ai-agent-ready-blockspace-by-phala-network-activity-7180979388891492352-U0uL?utm_source=share&utm_medium=member_desktop

Blockspace Thread:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_blockspace-phatcontracts-blockchains-activity-7181673704865636352-34Px?utm_source=share&utm_medium=member_desktop

Flock:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-trustedexecutionenvironments-activity-7183087597030629377--Y_T?utm_source=share&utm_medium=member_desktop

AI Agent Article:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_introducing-ai-agent-contract-for-smart-agents-activity-7183093362328035328-Rd4W?utm_source=share&utm_medium=member_desktop

phala.network/ai:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-network-is-at-the-forefront-of-innovation-activity-7185974611006611456-oa23?utm_source=share&utm_medium=member_desktop

New Era:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_web3-defi-developers-activity-7183237542115229696-ckn4?utm_source=share&utm_medium=member_desktop

Unleashing:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_blockchain-ai-bittensor-activity-7186369719459864577-oZ_j?utm_source=share&utm_medium=member_desktop

ai agent 3rd part:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_phala-community-tokenomics-activity-7187454913193398272-zil-?utm_source=share&utm_medium=member_desktop

Agent Wars:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_introducing-agent-wars-by-phala-network-activity-7189294914407452673-Se2m?utm_source=share&utm_medium=member_desktop

Big Infrastructure:
https://www.linkedin.com/posts/gabriel-bonugli-gabekoin-3965379b_dcap-trustedexecutionenvironment-dcap-activity-7191150109055733760-ScDR?utm_source=share&utm_medium=member_desktop

COMMUNITY (CM): 40/40

![image](https://github.com/Phala-Network/growth-program/assets/112413448/cdfbc3f1-18f9-4186-8202-9148fe6caaa8)

![image](https://github.com/Phala-Network/growth-program/assets/112413448/33878a95-336e-4aa0-897c-93d1df7e43fe)

![1](https://github.com/Phala-Network/growth-program/assets/112413448/d6bdffb7-ad85-43cd-a3e8-aac65db82482)
![2](https://github.com/Phala-Network/growth-program/assets/112413448/51366e21-ae50-4751-a56c-8dc3afbe45fa)
![3](https://github.com/Phala-Network/growth-program/assets/112413448/31bc08f0-b0ab-410b-ab3e-cf5104dfff97)
![4](https://github.com/Phala-Network/growth-program/assets/112413448/f1a24cc9-ed73-465c-ba0e-3e26c7c6e91b)
![5](https://github.com/Phala-Network/growth-program/assets/112413448/814b254a-7100-4331-8747-f0b6960f0459)
![6](https://github.com/Phala-Network/growth-program/assets/112413448/ea942ed4-76fd-41d9-9d35-ada6d3cb4e2d)
![7](https://github.com/Phala-Network/growth-program/assets/112413448/60c32e15-28d4-4814-b6da-40fb8b5f09d6)
![8](https://github.com/Phala-Network/growth-program/assets/112413448/8d886711-e418-4f33-9179-ee275827fe9a)
![9](https://github.com/Phala-Network/growth-program/assets/112413448/293ff384-0c50-49c0-acb6-cbd1d9a7f103)
![10](https://github.com/Phala-Network/growth-program/assets/112413448/cbaa6610-4a62-43d5-9eaa-7d890a22458a)
![11](https://github.com/Phala-Network/growth-program/assets/112413448/346fc9f5-16a6-4608-965e-5d9a2a025081)
![12](https://github.com/Phala-Network/growth-program/assets/112413448/1c05d40d-bd76-4617-a50e-a66d6084ddd3)
![13](https://github.com/Phala-Network/growth-program/assets/112413448/afd21424-1cd7-4591-9061-c80e40638b7b)
![15](https://github.com/Phala-Network/growth-program/assets/112413448/26fe2169-82c7-4e5b-8ac6-e75c8ca83807)
![16](https://github.com/Phala-Network/growth-program/assets/112413448/0fe49184-749d-4390-b9aa-1746f8039454)
![17](https://github.com/Phala-Network/growth-program/assets/112413448/1cb739cc-4946-4fea-bc1f-b54e68372053)
![18](https://github.com/Phala-Network/growth-program/assets/112413448/1c1f8493-60bd-4161-b182-f1fcac69eb66)
![19](https://github.com/Phala-Network/growth-program/assets/112413448/8e721508-8cfd-428d-bffe-fb11dcc9e859)
![20](https://github.com/Phala-Network/growth-program/assets/112413448/5a4f8de3-19f8-457a-97bd-213570c681e4)
![21](https://github.com/Phala-Network/growth-program/assets/112413448/b173efb6-c9da-411a-ae1d-7a200f00265b)
![21](https://github.com/Phala-Network/growth-program/assets/112413448/fc67ac48-c7e1-48f9-b2df-4627a43d8aaf)
![22](https://github.com/Phala-Network/growth-program/assets/112413448/a8f13e19-a705-4e46-b439-078569bedc87)
![22](https://github.com/Phala-Network/growth-program/assets/112413448/4a5d6cb5-1fb6-4ce8-885e-e5fdd7d55d4c)

Supplementary: EM & PM (20/20)

PM: 10/10
https://x.com/m0neymantra/status/1777264110884819174
https://x.com/official_bles1/status/1776260293737202157
https://x.com/CryptoCappex/status/1777345852484292961
https://x.com/CryptoCappex/status/1777353552777634014
https://x.com/PhalaNetwork/status/1777321803293094015
https://x.com/Polkadot/status/1777446074577203397
https://x.com/infaceAi/status/1777221838885765429
https://x.com/marvin_tong/status/1777470191271919734
https://x.com/LaVarHenry/status/1778459071785345100
https://x.com/TheScarletThr/status/1778753811479224728
https://x.com/code4rena/status/1778573752911245480
https://x.com/RafaelCabilla/status/1778980123011616794
https://x.com/marvin_tong/status/1779188015681941581
https://x.com/gabekoin/status/1779450732913078491
https://x.com/marvin_tong/status/1779147885990617470
https://x.com/marvin_tong/status/1780020361389867344
https://x.com/TakoProtocol/status/1780163019261305209
https://x.com/PhalaNetwork/status/1780564417056284914
https://x.com/PhalaNetwork/status/1780568768390828468
https://x.com/zoemcfox/status/1780409004092506395
https://x.com/TheScarletThr/status/1780837795042304443
https://x.com/official_bles1/status/1780646954013184226
https://x.com/PhalaNetwork/status/1780892338916622439
https://x.com/hashwarlock/status/1780658800552227041
https://x.com/marvin_tong/status/1780837042206757053
https://x.com/TheSpartanLabs/status/1781265233933406213
https://x.com/infaceAi/status/1781581571947954440
https://x.com/gabekoin/status/1782109343900377547
https://x.com/TheScarletThr/status/1782346440662004097
https://x.com/marvin_tong/status/1782275896654569515
https://x.com/TheScarletThr/status/1782808674592760061
https://x.com/dephynetwork/status/1783562570911150536
https://x.com/hashwarlock/status/1784960797552058798
https://x.com/AIMedaResearch/status/1784958964066828383
https://x.com/gabekoin/status/1785283075934487034
https://x.com/CryptoCappex/status/1782447605881942042
https://x.com/marvin_tong/status/1783535530421969294
https://x.com/PolkadotInsider/status/1783165403881165074
https://x.com/PhalaNetwork/status/1783469035960578064

https://www.linkedin.com/posts/encode-club_register-for-the-build-on-polkadot-w3transfer-activity-7181232739960922112-Oonv?utm_source=share&utm_medium=member_desktop
https://www.linkedin.com/posts/phala-network_ai-blockchain-aiagent-activity-7179099456410189824-Ethr?utm_source=share&utm_medium=member_desktop

EM: 

DEPIN POLKADOT BRASIL

https://x.com/polkadot_brasil/status/1775644503505784913
![image](https://github.com/Phala-Network/growth-program/assets/112413448/6a23b779-bc7a-4e9d-aec6-2453559a3c43)
![image](https://github.com/Phala-Network/growth-program/assets/112413448/d3bd1d8b-5e5b-40b6-a9aa-afa3132c234c)

Twitter Monthly SPACES:
![image](https://github.com/Phala-Network/growth-program/assets/112413448/1c7f94f1-9f13-4d74-921f-40da8412feb6)

So we are completly happy about all that, our community is growing (much more now) and thats what we love to see!

Suggested scores:

[CC] 40/40
This month incredible, we have many new people in the community and some great content reaching many views.

[CM] 36/40
This month we had many users interactin in all our channels, that means we are gettin known everywhere.

For next month: Keep growing our local community and keep supporting International Phala Channels

[PM] 7/10
Shared all oficial content in all main social medias.
Many impressions this months EN & PT

[EM] 10/10
We hosted two Spaces to share knowledge about Phala and Depin

Overall suggested score: 93/100.

Abolutly happy about this month and excited for the next one!

For the next month: Do better

**Comment by willphala** [comment]
Great stuff!
