### ISSUE TITLE
April 2024 Contribution - @m0neymantra

### ISSUE THREAD

**Issue by bananasatan** [Phala-Network/growth-program#403]
**Personal info:**
- Amb rank: Advocate
- Telegram Username: @m0neymantra
- Twitter URL: x.com/m0neymantra
- Wallet address: 44jy9b5Ax9nJi6bfNwtfFeqikdJ7pnfSjUazruPn3Y4Ttmv7
- Departments: [CC] / [MK]
Department Score Weight : 50%(40) & 50%(40)

**Contributions:** 
CC/MK -  I promoted Phala Network and its new products such as AI Agent Contract and Agent Wars on Twitter from my personal account, The Dots account  and  Phala Russia Twitter account.
I helped community members on Discord and Telegram(main and local chat). 

**Twitter analytics April 2024:**
![Screenshot 2024-05-05 014124](https://github.com/Phala-Network/growth-program/assets/111198068/2e63e1c8-cc5b-471a-9adf-c4642ed3211b)

**Tweets:**

m0neymantra and The Dots
![Screenshot 2024-05-05 014321](https://github.com/Phala-Network/growth-program/assets/111198068/acd09898-3247-4470-a84f-557c43b592c3)
![Screenshot 2024-05-05 014514](https://github.com/Phala-Network/growth-program/assets/111198068/0801e68a-0189-44f3-a311-8dbb57e0c2e1)

https://x.com/m0neymantra/status/1783096451142123564
https://x.com/TheDotsMagazine/status/1782475290758791342
https://x.com/TheDotsMagazine/status/1777341926691233848
https://x.com/m0neymantra/status/1782855935930651114
https://x.com/m0neymantra/status/1777264110884819174
https://x.com/m0neymantra/status/1776922581343387908

Phala Network Russia:
![Screenshot 2024-05-05 014537](https://github.com/Phala-Network/growth-program/assets/111198068/c774b9dd-7c14-41a4-b380-9a41fddc537c)

https://x.com/PhalaRussia/status/1780287534527860760
https://x.com/PhalaRussia/status/1764044701743624396
https://x.com/PhalaRussia/status/1782820262091661409
https://x.com/PhalaRussia/status/1783217564237103528

**Supplementary tasks:**
[HD] I helped community members on Discord and Telegram. 

![Screenshot 2024-05-05 014731](https://github.com/Phala-Network/growth-program/assets/111198068/c81183e1-b774-4e20-90db-79119dcb1e9e)

[CC]
https://x.com/m0neymantra/status/1783096451142123564 - My first video contribution to Phala

[EM]
https://x.com/PhalaRussia/status/1784589059743945047 On May 30, me and Tori hosted a Phala Network Russia community call on Twitter about the latest Phala updates such as Agent Wars and AI Agent Contract. InFace helped us at the end with answers to questions from the audience. 8 people attended the call.

![Screenshot 2024-05-05 014825](https://github.com/Phala-Network/growth-program/assets/111198068/e613bfec-16d2-4c94-8dba-183c336c1834)

[RC]
https://x.com/m0neymantra/status/1776617281197314518
[ART] + [PM]
https://x.com/TheDotsMagazine/status/1782475290758791342
https://x.com/TheDotsMagazine/status/1777341926691233848

[PM]
https://x.com/m0neymantra/status/1782855935930651114
https://x.com/m0neymantra/status/1784256944913408493
https://x.com/m0neymantra/status/1775235244007772546
https://x.com/m0neymantra/status/1777264110884819174
https://x.com/m0neymantra/status/1777743210715955505
https://x.com/m0neymantra/status/1776922581343387908
https://x.com/m0neymantra/status/1779940012349395393
https://x.com/m0neymantra/status/1780295504997306455
https://x.com/m0neymantra/status/1782386053212512557
https://x.com/m0neymantra/status/1783096451142123564
https://x.com/PhalaRussia/status/1778429239508836662
https://x.com/PhalaRussia/status/1780287534527860760
https://x.com/PhalaRussia/status/1764044701743624396
https://x.com/PhalaRussia/status/1782820262091661409
https://x.com/PhalaRussia/status/1783217564237103528

I will continue to push Phala across Twitter, make memes and videos about Phala. I will also continue to help community members on Discord and Telegram. As I think the community call was pretty successful, we will do it again this month.

**Comment by willphala** [comment]
Fantastic start. I strongly recommend switching to the community department based on your activity on that front! 👏
