### ISSUE TITLE
April Contributions 2024 - Gatorkorps

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#406]
Telegram Username: @gatorkorps
Discord Username: gatorkorps
Twitter Username: https://twitter.com/gk18_dog
PHA Wallet Address: 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV

![image](https://github.com/Phala-Network/growth-program/assets/82824139/e009f15d-63e7-419d-86e8-ccd4592e711b)
Low activity on my own twitter

![image](https://github.com/Phala-Network/growth-program/assets/82824139/87a13667-39c8-4dc7-83dd-b010cda5fb6c)

Community:

Phalafr twitter account management
phalaFR telegram management
ban several shitcoin chiller on the main Phalanetwork TG

- Videos

https://twitter.com/phala_fr/status/1775386299144265819 edit of a video in collab with scarlet aboput how to have PHA and to transfert it. English

https://twitter.com/phala_fr/status/1783836102207602979 edit and translation of scarlet AI agent video presentation

- Translation :

Thread and translation of the article about AI Agent
[**https://twitter.com/phala_fr/status/1782445344942334339](https://twitter.com/phala_fr/status/1782445344942334339)

articles :
 https://medium.com/phala-fran%C3%A7ais/la-guerre-des-agents-agent-wars-6842195efba8
https://medium.com/phala-fran%C3%A7ais/introduction-de-lai-agent-pour-les-agents-intelligents-3ccb94b7cc02

marketing:

https://twitter.com/phala_fr/status/1782452306211926363 Pink proposal
https://twitter.com/gk18_dog/status/1775939621471256790 

A lot of work on the video and on the translation to understand the AI Agent concept and explain the update about Phat Contract to the french community. It' s along fight because a lot of user are waiting real use case. 
I was also focuse about the organisation of our polakdot party with a big part for Phala (24 of may in Nantes)
It's a small one without any proposal, financed by the Phala Amb reserve and other project. But we will have a lot of quality participant, more next month :)

community: 10
Content 40/40
Marketing 30/40
extra for video : 10

90

**Comment by willphala** [comment]
🤘🐊
