### ISSUE TITLE
(Still Updating) April Contributions - {the_scarlet_thread} 

### ISSUE THREAD

**Issue by TheScarletThread** [Phala-Network/growth-program#408]
Amb Rank: Senior Ambassador
Telegram Username: @TheScarletThr
Discord Username: @the_scarlet_thread
Twitter Username: @TheScarletThr
PHA Wallet Address: 44Uewz5cCC1iWLb2zzXfUnbc6eiuFwHWt55z3D7afyGzyTKK

### MANDATORY 
**CONTENT CREATION**
**Thread/Long-Form Posts**
1. I created a thread discussing the update of the AI Agent Contract and echoing the differentiation between its predecessor, Phat Contracts. I also made a follow-along video to go with this post for those who don't want to read. 
To make the video, my workflow is follows:
• Edit script, adapted from the post
•Create each slide of the visual, add text, graphics, videos and special effects like transitions.
•Generate the voiceover and match the recording to the correct timing in the video
•Download in high quality, which takes time and power to download.
Find video in the link
https://twitter.com/TheScarletThr/status/1778323134782800062?t=5S-C5wn-5vb_dwFNaMVroA&s=19
Here are is the video I created and two graphics for the remainder of the post:
_[Video is too long too upload here so it can be viewed via the post link]_
![Add a heading_20240411_093457_0000](https://github.com/Phala-Network/growth-program/assets/99918790/5a26d469-3835-4e50-8f0a-42308122bc58)
![Add a heading_20240411_094601_0000](https://github.com/Phala-Network/growth-program/assets/99918790/95766159-c117-41c7-a2a1-bbeebf48b633)

2. Created a post on Grill Chat (formally known as SubSocial) explaining the details of AI Agent Contract. I got some engagement and questions.
https://grillapp.net/12916/a-new-era-of-innovation-at-phala-network-126710
 I made the following graphic for this post:
![Delegators_20240415_100857_0000](https://github.com/Phala-Network/growth-program/assets/99918790/3e1d9f42-063d-42b0-9129-6207c2d72e75)

3. Created a thread about how Phala is making it possible to seamlessly integrate AI and Blockchain, making Web3 +AI more accessible for everyone. 
https://twitter.com/TheScarletThr/status/1782082156157628700?t=SkCfAoWcvmaau2-fY9y6UA&s=19
Created these graphics for this thread:
![1_20240421_181915_0000](https://github.com/Phala-Network/growth-program/assets/99918790/2a624c89-662f-4c43-99af-6339faa8312b)
![2_20240421_181915_0001](https://github.com/Phala-Network/growth-program/assets/99918790/01a49ae0-b308-4178-98f0-0fb24c4b2b2e)
![3_20240421_181915_0002](https://github.com/Phala-Network/growth-program/assets/99918790/84741676-b178-45a9-86c7-885dd57590c4)
https://github.com/Phala-Network/growth-program/assets/99918790/2c9d5221-1224-4c32-b21c-89424e851fdc
https://github.com/Phala-Network/growth-program/assets/99918790/66a2df3c-2351-48a7-b343-0bba8b2a8c6d
![6_20240421_181915_0005](https://github.com/Phala-Network/growth-program/assets/99918790/b2e163ce-371e-4e56-a53b-11fda13542c0)

4. Wrote a post introducing the Agent Wars game and touching on the main points. 
https://grillapp.net/12916/what-is-agent-wars-by-phala-network-133999
I’ve created this graphic for the post
![9_20240421_204150_0008](https://github.com/Phala-Network/growth-program/assets/99918790/7d5ee405-8a71-48b1-bf00-e4cf1a193f9f)

5. On Twitter, I created a post about Agent Wars that was slightly different than my approach for Grill Chat. Also, I included a follow-along video for those who don't want to read but still wanted to catch up on what Agent Wars is. To make the video, my workflow is follows:
• Edit script, adapted from the post
•Create each slide of the visual, add text, graphics, videos and special effects like transitions.
•Generate the voiceover and match the recording to the correct timing in the video
•Download in high quality, which takes time and power to download.
Find video in the link:
https://twitter.com/TheScarletThr/status/1783799884803375213?t=pmlwrOZZpPQHz2-DJvnsbQ&s=19

6. Created a post about remembering the achievements of Phat Contract as a recap for the community on how much of an impact it made.
https://grillapp.net/12916/remembering-some-achievements-of-phat-contracts-140605
Created this graphic for my post:
![Infographics _20240428_220123_0000](https://github.com/Phala-Network/growth-program/assets/99918790/e5b4464b-7891-4a07-8fa8-ca52747e597b)

7. Created a post discussing Phala's blog and spoke about the role of AI Agents and tokenomics in making blockchain accessible. I added a follow-along video for those who don't want to read. To make the video, my workflow is follows:
• Edit script, adapted from the post
•Create each slide of the visual, add text, graphics, videos and special effects like transitions.
•Generate the voiceover and match the recording to the correct timing in the video
•Download in high quality, which takes time and power to download.
https://twitter.com/TheScarletThr/status/1785231917014560799?t=z5eKGP3M1mh2BOYlueTS9A&s=19

**Infographics**
1. Phala Network and Flock partnership
https://twitter.com/TheScarletThr/status/1775991488846962699?t=4roWv0Qf1zde-SfruYF7eg&s=19
![April Phala Infographics _20240404_225625_0000](https://github.com/Phala-Network/growth-program/assets/99918790/d4e6a713-1090-42e7-929d-b7bedab15e3f)

2. Shift to AI Agent Contract
https://twitter.com/TheScarletThr/status/1777337348939784623?t=4mwJmFaAiQ8RQ2UDdYPzIg&s=19
![Add a heading_20240408_155837_0000](https://github.com/Phala-Network/growth-program/assets/99918790/80a4fec2-4246-488d-bb57-2bddb6c4a500)

3. Defining features of AI Agent Contract
https://twitter.com/TheScarletThr/status/1779591027881283803?t=u19m9xri7YwuNpRjXANTQQ&s=19
![Delegators_20240414_211728_0000](https://github.com/Phala-Network/growth-program/assets/99918790/5806ee97-ccca-4a90-bd9f-0b99f403b011)

4. AI Agent Contract in 3 steps
https://twitter.com/TheScarletThr/status/1780949298600931341?t=MCwcT4G2BNCrgFMa-LVp1g&s=19
https://twitter.com/TheScarletThr/status/1780949298600931341?t=FudOEbIH9FkfgkKkI9IHLQ&s=19
![Delegators_20240418_051327_0000](https://github.com/Phala-Network/growth-program/assets/99918790/915c39ed-d9e3-44b8-93ae-0a224e8a2044)

5. Fundamental pillars of the AI-Agent Economy in Agent Wars
https://grillapp.net/12916/pillars-of-ai-agent-economy-in-agent-wars-139744
![Delegators_20240427_110329_0000](https://github.com/Phala-Network/growth-program/assets/99918790/83a49775-b78b-4965-94d6-7c61fbf2476b)

6. Objectives of AI Agent Contract
https://twitter.com/TheScarletThr/status/1784916381407879252?t=QJgZm0YgYx-0KRTtAZty5A&s=19
![Delegators_20240429_140014_0000](https://github.com/Phala-Network/growth-program/assets/99918790/8aa8a886-8902-47c7-be79-b4de0c2e44ba)

7. Phala DCAP verification
https://twitter.com/TheScarletThr/status/1785281471663440210?t=Jch4c1DBayB1xopEIy10JA&s=19
![PHAT CONTRACT 2 0 STARTER KIT_20240430_140958_0000](https://github.com/Phala-Network/growth-program/assets/99918790/b2d2b9a4-1881-402e-809a-80af91138b3f)

8. Main Parts Of Agent Wars Tokenomics
https://grillapp.net/12916/have-you-heard-143147
![PHAT CONTRACT 2 0 STARTER KIT_20240430_201105_0000](https://github.com/Phala-Network/growth-program/assets/99918790/4caceaec-4eb0-469b-b548-daf8772106b2)

**Youtube**
1. Made an animated Youtube Video in the form of a news bulletin discussing Phala’s big announcement of pivoting from Phat Contracts to AI Agent Contract.Here is my workflow for this video:
 •Create Script
•Make background (background gas many small elements put together in layers)
•Generate voiceover
• Animate the character (speech, hand movements, eye movements)
•Collect slides, set timing for each slide
•Make thumbnail and description
https://youtu.be/-csg8_Bdnm4?si=WI4Wm73WGR28w0RW

2. Made a Youtube Short (also posted on X) for the rap dance of Marvin's song.
X Post:
https://twitter.com/TheScarletThr/status/1782808674592760061?t=NJzq9OQxCfTNBaTXcLn2ZQ&s=19

Youtube( I changed the layout and shortened the video for Youtube):
https://youtube.com/shorts/7TQpyGdz8_I?si=T93Obn5tqDTi6ERc

3. Created a dance short for the Phala blog “Shaping The Future Of AI and Web3 With Tokenization”. 
https://youtube.com/shorts/qWlyOUb5WpM?si=c6vfbHvvnYK4HBzS

Youtube Stats April:
![Screenshot_20240508_002608_YT Studio](https://github.com/Phala-Network/growth-program/assets/99918790/6fc24bb4-a792-45f4-969d-60debc796577)
![Screenshot_20240508_002611_YT Studio](https://github.com/Phala-Network/growth-program/assets/99918790/8dd36508-375e-4895-8c10-7c8270267031)
![Screenshot_20240508_002614_YT Studio](https://github.com/Phala-Network/growth-program/assets/99918790/de4017a3-821a-44dc-8e0b-2b0ca1edf274)
![Screenshot_20240508_002616_YT Studio](https://github.com/Phala-Network/growth-program/assets/99918790/b4d14453-062f-47fc-a41f-f69bca9cb7b4)

**Photos/Artwork**
1. Phala community
https://twitter.com/TheScarletThr/status/1777962333966680337?t=ghWdc40RBaskHKquCndzyQ&s=19
![Grey Modern Feature Twitter Post_20240410_093004_0000](https://github.com/Phala-Network/growth-program/assets/99918790/b1a1c1fa-f6c4-4023-867a-f43bfcc3f16b)

2. Laptop March Newsletter
https://twitter.com/TheScarletThr/status/1778753811479224728?t=vxCUl7BLRI3azBn2hHQioQ&s=19
![1000063008-01](https://github.com/Phala-Network/growth-program/assets/99918790/8c9b7c00-b578-4d63-8e4f-fdaca356de48)

3.Phala armband image holding coffee
https://twitter.com/TheScarletThr/status/1780183850015986111?t=5FW0CjkZcAKnVtPPgngk-Q&s=19
![1000062931-01](https://github.com/Phala-Network/growth-program/assets/99918790/a22daaee-6887-4dfb-972c-cb934df898d5)

4. Laptop opened to Phala Technical Documentation
https://twitter.com/TheScarletThr/status/1780837795042304443?t=v8e336VmsfsfugaTszVXLA&s=19
![20240418_065549](https://github.com/Phala-Network/growth-program/assets/99918790/747521c4-e385-4b61-9b79-1b14f5c5c221)

5. Phala Technical Docs in dark background
https://twitter.com/TheScarletThr/status/1782346440662004097?t=X_GBZi2cVGlHKHRk78hJIw&s=19
![20240418_001328](https://github.com/Phala-Network/growth-program/assets/99918790/60ccc32b-9cec-492c-9f7c-fe1276ffbf82)

**Memes**
1. Wish I was like that guy
https://discord.com/channels/697726436211163147/766661203111575553/1224984605283586048
![Man I Wish I Was More Like That Guy ](https://github.com/Phala-Network/growth-program/assets/99918790/05bd6885-8039-4ed8-9d7a-8f86b6d00b46)

2.Phala's taking over
https://discord.com/channels/697726436211163147/766661203111575553/1225427003730034699
![taking over](https://github.com/Phala-Network/growth-program/assets/99918790/6e8e475c-b6e3-4e3c-ace1-2867a896452a)

3. AI After integrating Phala Network
https://discord.com/channels/697726436211163147/766661203111575553/1226360950077001831
![AI After integrating Phala Network](https://github.com/Phala-Network/growth-program/assets/99918790/d10f9c0e-3b76-4ada-9225-30d094b0d393)

4. Phala buffet the AI Agents
https://twitter.com/TheScarletThr/status/1777277270341591408?t=QzX2xZEDshQ2G4Wy_DE-8w&s=19
https://github.com/Phala-Network/growth-program/assets/99918790/6fb1d8d4-bb22-4fe4-977a-4cd4ce93e167

5. Passing the baton
https://discord.com/channels/697726436211163147/766661203111575553/1227150242630078525
![Passing the baton](https://github.com/Phala-Network/growth-program/assets/99918790/558df29d-31ec-4957-8241-809510d4c0d2)

6.Squid Game Honeycomb 
https://discord.com/channels/697726436211163147/766661203111575553/1227292087704092764
![Squid Game Honeycomb ](https://github.com/Phala-Network/growth-program/assets/99918790/4e396aee-0ab6-452e-8386-c446e1151292)

7.AI relaxing
![AI relaxing](https://github.com/Phala-Network/growth-program/assets/99918790/177552db-f9ca-481c-9e43-5a4fe7345a98)

https://discord.com/channels/697726436211163147/766661203111575553/1227824865319456778

https://grillapp.net/12916/the-idea-of-an-ai-agent-contract-is-really-fascinating-121375

8. AI Agent Contract keeping things transparent 
https://discord.com/channels/697726436211163147/766661203111575553/1228621662304604292
![AI Agent Contract keeping things transparent ](https://github.com/Phala-Network/growth-program/assets/99918790/c73fe01d-fec3-4bcb-a1a4-5201160db10e)

9. Wow The Fortune Cookies Here Really Are More Accurate 
https://discord.com/channels/697726436211163147/766661203111575553/1229093231120351263
![Wow The Fortune Cookies Here Really Are More Accurate ](https://github.com/Phala-Network/growth-program/assets/99918790/bf3e1505-8591-4c36-8443-7ba51ff59aca)

10. We have you four to one
https://discord.com/channels/697726436211163147/766661203111575553/1229831240992165969
![ Like Those Odds ](https://github.com/Phala-Network/growth-program/assets/99918790/ac150f0c-d8b6-46ce-8a93-717705ce9f74)

11. Keeping up with Phala Network
https://discord.com/channels/697726436211163147/766661203111575553/1230249016265015397
https://github.com/Phala-Network/growth-program/assets/99918790/cb209fc3-4dc6-4bed-8147-c1834c098afe

12. Me after creating my AI Agents
https://discord.com/channels/697726436211163147/766661203111575553/1232259783424348180
![Giants Looking at a Peasant (1)](https://github.com/Phala-Network/growth-program/assets/99918790/3e675968-9bfb-4f23-8ca4-804f6a823dfd)

13. How i feel creating my AI Agent
https://discord.com/channels/697726436211163147/766661203111575553/1233708926206349332
![Tehc ](https://github.com/Phala-Network/growth-program/assets/99918790/8df211fa-69b3-4c70-a56c-aee121849d84)

14. Reality Can Be Whatever I Want 
https://discord.com/channels/697726436211163147/766661203111575553/1234234842254934078
![Reality Can Be Whatever I Want  ](https://github.com/Phala-Network/growth-program/assets/99918790/37c121af-1c86-498a-90e1-8884334a31b8)

15.  Everywhere I Go I See His Face 
https://discord.com/channels/697726436211163147/766661203111575553/1234484770151337985
![Everywhere I Go I See His Face ](https://github.com/Phala-Network/growth-program/assets/99918790/05320fb7-1fa6-43c5-bc48-4ddff649acd5)

16. Dancing Robot
https://discord.com/channels/697726436211163147/766661203111575553/1234486110508286072
https://github.com/Phala-Network/growth-program/assets/99918790/00873ffe-4ed0-4395-b1d7-839714d39ba4

**GOOD POINTS**
Tried some new content such as the animated dance challenges and explaining the new updates to Phala Network. Also I put a lot of effort into each piece (for example evaluating how can I add value, add a slightly different perspective, improve visuals + content etc).

**BAD POINTS**
Lower impressions on YouTube videos. Lower engagement on X.

**How To Improve**
Improve quality of Youtube Videos, incorporate various marketing strategies like better SEO. Learn more about X algorithm and growth strategies that work currently.

**COMMUNITY MANAGEMENT**
1. I participated in monitoring the PhalaWorld, Phala Telegram, Phala Africa Telegram, and Phala Discord to eliminate spam, bots, malicious content, engage and answer questions of the community. There has been a high rise of bots lately. Also try to address negative feedback to the best of my ability. See examples below:
![Screenshot_20240508_020633_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/56f0d44b-382f-4c6c-8090-443adfb925ac)
![Screenshot_20240508_020643_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/53873577-e669-4059-a914-0c50226fb96d)
![Screenshot_20240508_020706_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/2ff63736-5d3b-4c0b-bde7-e41f2747e321)
![Screenshot_20240508_020721_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/21d74e0b-4b67-43a0-af06-efbdaecc1a68)
![Screenshot_20240508_020804_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/5eb83884-b430-4230-8ff6-5b5b149ce32a)
![Screenshot_20240508_020829_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/20ca2f42-1c05-4caf-addf-1989794bb4ef)
![Screenshot_20240508_020912_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/1ce600d1-7723-4ec0-b5e5-92e79489fa21)
![Screenshot_20240508_020916_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/471421f5-cab3-4593-807e-466675539f55)
![Screenshot_20240508_020923_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/a17e2095-1d73-4609-a490-0de3a66431a8)
![Screenshot_20240508_021443_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/60c9c47e-417a-4009-88a7-b51dc379be23)
![Screenshot_20240508_021503_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/e0a20c5d-fa75-4618-940e-6ea7136e03a7)
![Screenshot_20240508_021532_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/75da8183-6400-4214-a003-74764df4d930)
![Screenshot_20240508_021538_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/4022d9c9-f01e-40ec-88f7-9406b43208f8)
![Screenshot_20240508_021556_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/eec0acbe-0ae6-40b3-a20c-30f4fce6e844)
![Screenshot_20240508_021630_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/dbdafee5-3956-43d5-afd8-b3474c229324)
![Screenshot_20240508_021641_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/451cb563-29f3-4fe7-8148-8c302c2686a0)
![Screenshot_20240508_021645_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/b2092b8e-56ef-4931-ab4a-9090e96ae062)
![Screenshot_20240508_021653_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/a621d151-6111-4f77-8709-32807b525a61)
![Screenshot_20240508_021659_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/28f9ab80-18fb-4a90-932f-253032a0f0c8)
![Screenshot_20240508_021704_Telegram](https://github.com/Phala-Network/growth-program/assets/99918790/b7b753c2-e7b0-411f-bc30-2a86491df2e6)
![Screenshot_20240508_020928_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/c7459ddc-fcf4-4296-aa48-d02be744b8b4)
![Screenshot_20240508_020932_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/4bf56416-82c1-4df3-80c2-6a28e0ca2587)
![Screenshot_20240508_020936_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/bbdb0bb2-5c0d-45fc-b44b-c7362ce28806)

2. Supporting Phala Africa ambassadors efforts by offering guidance, feedback, and aid, assigning tasks, and monitoring progress. Assessing strengths and areas requiring improvement.

3. Researching and planning on ways to increase community engagement and improve teamwork and productivity within the Phala Africa team. I've also spent time evaluating what I have done so far.

4. Active participation in the community ambassador channel. I asked for feedback on CM related things and conveyed some community sentiments to the team. I regularly participate in CM discussions with other ambassadors and sometimes team members.

Stats:
![Screenshot_20240508_022524_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/c0e464d3-87b5-4e3a-8337-477a45de2068)
![Screenshot_20240508_022545_Discord](https://github.com/Phala-Network/growth-program/assets/99918790/3bd4f6bc-abdf-467f-b835-8f567d6de5b3)
![Screenshot_20240508_022614_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/b7972f00-cee4-451f-80f1-ea0044ed47ce)
![Screenshot_20240508_022644_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/a4bc3f87-c522-42ae-86de-bf1c50c6d990)

**Good Points**
There was a good opportunity to participate in CM this month due to the new updates in Phala Network, so I increased the quality of share in CM and also engaged in general chats with other community members.

**Bad Points**
Can find simpler but clear ways to explain technical updates to those unfamiliar.

**How To Improve**
Practice doing explanations of the main points/updates in a simple way that has clarity. Ask the community member of they found the answer helpful.

### SUPPLEMENTARY
**PM**
April was pretty exciting. So I aimed at maintaining my contribution in spreading awareness about Phala Networks solutions both locally + globally. I've made posts on Polkaverse, X, Telegram, YouTube and Discord. I’ve been part of discussions about various aspects of Phala, the latest updates/activities, AI Agent Contracts and engaging with the community to foster more meaningful discussions. 

Beyond the screenshots provided, I've interacted by liking, commenting, and retweeting content from Phala Network ambassadors, partners, the Phala Network X account, and Phala Team members. I've also promoted Phala's events and updates.

![Screenshot_20240508_025014_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/fc450ad1-5926-4cd3-8aca-13dce374504b)
![Screenshot_20240508_025132_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/aa99bc71-cc2c-4b6d-adf8-bf17fd4dec3f)
![Screenshot_20240508_025319_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/d98d0a10-bbb7-468f-9680-94acaa5773f8)
![Screenshot_20240508_024941_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/018a2eb2-233e-43ad-b3bf-6ea37ea2dd2f)
![Screenshot_20240508_025001_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/75de72dc-35b4-4c5b-8fc0-3f857ace4f39)
![Screenshot_20240508_025126_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/476b9483-2ef9-47d9-a438-f155558b9fb6)
![Screenshot_20240508_025240_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/1b509ab4-581a-484b-bfc7-54a0be6abe23)
![Screenshot_20240508_025326_Samsung Internet](https://github.com/Phala-Network/growth-program/assets/99918790/edb5cba3-6a8e-4393-a562-09e52ccdb650)
![Screenshot_20240508_025916_Nova](https://github.com/Phala-Network/growth-program/assets/99918790/cc0f557a-f81d-491e-8f1b-e5ddbdc44e17)
![Screenshot_20240508_025920_Nova](https://github.com/Phala-Network/growth-program/assets/99918790/6ba7fd4f-1881-44ac-9d52-8ae747adf998)
![Screenshot_20240508_025957_Nova](https://github.com/Phala-Network/growth-program/assets/99918790/d2b25b96-3439-4385-ab67-b4e9fa41cc2b)
![Screenshot_20240508_030045_Nova](https://github.com/Phala-Network/growth-program/assets/99918790/98ed4aa1-7eda-42ff-9351-dd52bc59b786)

**EM**
The Phala Africa team held a community call for April in the form of a panel discussion. The topic was about " the significance of decentralized governance". Recording:
https://twitter.com/PhalaAfrica/status/1783850385213415483?t=FINrK_giEhb0Hd-6AVo66A&s=19
See a screenshot with some attendees. We had a decent turnout with some popping in and out of the call.
![Screenshot_20240426_154132_X](https://github.com/Phala-Network/growth-program/assets/99918790/1673a4cf-117c-4702-b679-906012c1dab7)

I played my role in this call by:
• Guiding the organization of the call:
Initiated polls and discussions about various aspects of organising and doing tasks; delegated roles; brainstorming ideas for the event; tracked progress and finalizing details.

• Made the banner for the announcement of the event:
![PhalaAfricaApril](https://github.com/Phala-Network/growth-program/assets/99918790/772b0f93-2461-44d9-af33-a45c2d26c8fc)

• Created the agenda and added some questions to it:
https://docs.google.com/document/d/1YvebsjZFK3OP9Je4omC1gSARCLjnZyPc8YEiEkJFmPA/edit?usp=drivesdk

• I was one of the panellists so I prepared answers for the questions that were assigned to me:
https://docs.google.com/document/d/1QH4iXPMMvtPxMPC27XlVF7ReQUyxJN9z2aCg7pIJdzc/edit?usp=drivesdk

• Attended the rehearsal and contributed feedback to improving our calls.

**SCORES:**
**CC** 39/40
**CM** 38/40
**PM** 9/10
**EM** 6/10
**TOTAL** 92

**CLOSING COMMENTS**

**Comment by willphala** [comment]
Great work!
