### ISSUE TITLE
September 2022 Contributions - {johnrhodel#8162}

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#41]
**Telegram Username: https://t.me/johnrmb
Discord Username: johnrhodel#8162
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK**

**My Mandatory(Basic) Contributions of September:**
**1. CM(Community Management)**

1/09 - the phala medium in portuguese was created in addition to the creation of the channel in portuguese on discord https://medium.com/@phalaptbr
3/09 - created the portuguese twitter of phala: https://twitter.com/phalaportugues

Have I participated in Discord Channel Moderation Portuguese (choose)? Yes
Have I participated in Telegram Channel Moderation (choose)? Yes little, but I can improve

**What was good?**
possibility of bringing teaching and education about the PHALA project to the Portuguese speaking community
**What was bad?**
The idea was to create a telegram but here in Brazil it was forbidden to use it intensively until the elections are over!
**How can I improve this next month?**
With the first round of elections passing, being able to use and create a group in Portuguese from phala! to have a metric beyond Discord!

**2. VSM(Twitter Virals)**
Twitter as Official Ambassador : https://twitter.com/parachainboy
Twitter as Official Local Phala Account : https://twitter.com/phalaportugues
![Twitter PHALA ANAL](https://user-images.githubusercontent.com/77474076/193869514-f930efa1-284c-4d01-89e7-0c1de4acdffe.JPG)
![analy parachain boy](https://user-images.githubusercontent.com/77474076/193869687-d88f8e1c-bad0-4958-a7a4-0e7900e64a54.JPG)

**All tweets**
05/09 – https://twitter.com/phalaportugues/status/1566787304248729608
06/09 - https://twitter.com/phalaportugues/status/1567259379136700418
07/09 - https://twitter.com/phalaportugues/status/1567347639217262595
09/09 - https://twitter.com/phalaportugues/status/1568756294365978626
10/09 - https://twitter.com/phalaportugues/status/1568756294365978626
11/09 - https://twitter.com/phalaportugues/status/1569020088539308032
13/09 - https://twitter.com/phalaportugues/status/1569818703834877952
23/09 - https://twitter.com/phalaportugues/status/1573472042183163912
28/09 - https://twitter.com/phalaportugues/status/1575299505964072960
28/09 - https://twitter.com/phalaportugues/status/1575301258205863938
28/09 - https://twitter.com/phalaportugues/status/1575301565308719105
29/09 - https://twitter.com/phalaportugues/status/1575410029724930048
29/09 - https://twitter.com/phalaportugues/status/1575411818272522242

**how to improve? I will also post more on my main twitter for having more interactions so the posts are well seen!**

**Medium articles and translation 6 articles**

2/09 - https://medium.com/@phalaptbr/roadmap-da-phala-network-para-2022-cdd7985fe470
3/09 - https://medium.com/phala-network/phala-recap-of-2021-highlights-achievement-8a86df19f00f
5/09 - https://medium.com/@phalaptbr/introdu%C3%A7%C3%A3o-ao-fat-contract-504592d58b4e
6/09 - https://medium.com/@phalaptbr/introdu%C3%A7%C3%A3o-%C3%A0s-tarefas-de-computa%C3%A7%C3%A3o-dos-tee-workers-711348a93840
7/09 - https://medium.com/@phalaptbr/ann-subbridge-%C3%A9-lan%C3%A7ado-na-rede-phala-aproveitando-a-interoperabilidade-entre-o-ecossistema-20346e5499ef
10/09 - https://medium.com/@phalaptbr/phala-a-nuvem-de-computa%C3%A7%C3%A3o-global-transparente-e-privada-d80f319d9364

**I'm doing an interview with Lucia for the series I'm working on "Q&A series" with several DOTSAMA projects and there will be episodes about PHALA and KHALA!**

**Comment by luciaaaa4455** [comment]
Any data image of the group management?
