### ISSUE TITLE
May 2024 contributions report {toriribolla}

### ISSUE THREAD

**Issue by toriribolla** [Phala-Network/growth-program#415]
ERSONAL INFO
Amb Rank : Ambassador
Telegram: @toriribolla
Twitter: @toriribolla
PHA Address : 435b1mp9FuSY4X6NNMTN6mALfyeChiQU1htPViw7hnD26sEM

Departments: #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

CC Contributions:

X @toriribolla:
1. https://x.com/ToriRibolla/status/1792883860495356223
2. https://x.com/ToriRibolla/status/1794409265974907050
3. https://x.com/ToriRibolla/status/1794421678866583790
4. https://x.com/ToriRibolla/status/1796111076133834799

X @PhalaRussia created by me:
1. https://x.com/PhalaRussia/status/1794406046276239537
2. https://x.com/PhalaRussia/status/1794422573515813321
3. https://x.com/PhalaRussia/status/1794424181087707433
4. https://x.com/PhalaRussia/status/1794639611806773598
5. https://x.com/PhalaRussia/status/1794700016986271959
6. https://x.com/PhalaRussia/status/1794730211847864722
7. https://x.com/PhalaRussia/status/1795002000138183092
8. https://x.com/PhalaRussia/status/1795092604607938970
9. https://x.com/PhalaRussia/status/1796226800332456008
10. https://x.com/PhalaRussia/status/1796226964950585505
11. https://x.com/PhalaRussia/status/1796232634647064624
12. https://x.com/PhalaRussia/status/1796583685187309868
13. https://x.com/PhalaRussia/status/1796585085715743158
14. https://x.com/PhalaRussia/status/1796586017895612898

MK Contributions:

X analytics @toriribolla:
![image](https://github.com/Phala-Network/growth-program/assets/132458076/f508fc50-1766-4a59-960e-d76b896b5a6b)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/db6d22b3-212d-46a9-bb68-eb0d069748d2)

X analytics @PhalaRussia:
![image](https://github.com/Phala-Network/growth-program/assets/132458076/46bd51c6-120e-4bb8-9e50-ec3f5e41cfc0)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/58bfcd73-d0e3-4841-b56e-493ece5db42a)

CC:
Translation: https://medium.com/@ribollavvv/51453cd9af3a

ART:
![bvnbvnbvn](https://github.com/Phala-Network/growth-program/assets/132458076/192bfacd-6ecb-44c3-8fbe-f9b7fbee8650)
![hgjbhj](https://github.com/Phala-Network/growth-program/assets/132458076/6af5f0cc-77aa-4ee9-a645-201051c3d8cc)
![орииоиотьл](https://github.com/Phala-Network/growth-program/assets/132458076/88bb2738-6399-4b35-b3a2-99d4f08a22a8)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/2aca1ff2-059e-42d3-8868-edbef89d567b)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/6235e461-695e-4d54-8e03-806b30f4fddd)
![image](https://github.com/Phala-Network/growth-program/assets/132458076/4f542679-4ec3-4e5f-8dfe-b2d1517d1c81)

SUGGESTED SCORES
#CC : 30
#MK : 30
#ART : 10
Overall : 70

**Comment by MaggiePhala** [comment]
Hi Tori! Pleasure to meet you here! 

I see that you have created and posted numerous tweets on your personal X account and Phala Russian X account to promote Agent Wars. Job well done! I am just wondering if you have thought about a way to promote Phala Russian X account among the Russian crypto communities? Feel free to DM me your thoughts on this. :)

Absolutely LOVE the infographics that you have created. It would be even better if the art creations align with Phala branding. I will get back to you with some feedback from our design team. 

Thanks Tori for your contribution to Phala.
