### ISSUE TITLE
May 2024 Contribution - m0neymantra

### ISSUE THREAD

**Issue by bananasatan** [Phala-Network/growth-program#416]
Telegram Username: @m0neymantra
Discord Username: m0neymantra
Twitter Username: https://twitter.com/m0neymantra
PHA Wallet Address: 44jy9b5Ax9nJi6bfNwtfFeqikdJ7pnfSjUazruPn3Y4Ttmv7

Department Score Weight : 50%(40) & 50%(40)

Contributions:

MK & CC
I promoted Phala Network on my personal X account, The Dots X account, Phala Network RU X account and Telegram CIS group! 
I made a video about RedPill in English and Russian; held a community call with Inface on Telegram CIS group. 

Twitter analytics May 2024 stats:

@m0neymantra 28 days
![Screenshot 2024-06-04 175812](https://github.com/Phala-Network/growth-program/assets/111198068/905ee77d-d3aa-40b1-846b-9fb678209f5b)

@TheDotsMagazine 28 days
![Screenshot 2024-06-04 175929](https://github.com/Phala-Network/growth-program/assets/111198068/93261113-107a-4933-a115-1be6580b6221)

Tweets:
https://x.com/m0neymantra/status/1795806896726610296
https://x.com/m0neymantra/status/1796634015379951915
https://x.com/TheDotsMagazine/status/1790319589248598378
https://x.com/m0neymantra/status/1789251685090812113
https://x.com/TheDotsMagazine/status/1793991265899454887
https://x.com/m0neymantra/status/1791126228600045816
https://x.com/m0neymantra/status/1786758631247183940
https://x.com/m0neymantra/status/1792496812948947446
https://x.com/m0neymantra/status/1785748464799977953
https://x.com/m0neymantra/status/1791467857806520631
https://x.com/m0neymantra/status/1790413768100364601
https://x.com/m0neymantra/status/1786487831499600082

Phala Network Ru tweets:
https://x.com/PhalaRussia/status/1796111558906405247
https://x.com/PhalaRussia/status/1794377889078763744
https://x.com/PhalaRussia/status/1792497507970212037
https://x.com/PhalaRussia/status/1791486253885424011
https://x.com/PhalaRussia/status/1791165128047468968
https://x.com/PhalaRussia/status/1790424613790405051
https://x.com/PhalaRussia/status/1787823877051298194
https://x.com/PhalaRussia/status/1786865949691584973
https://x.com/PhalaRussia/status/1786462784483668371

CM

![Screenshot 2024-06-04 175216](https://github.com/Phala-Network/growth-program/assets/111198068/fa4c5a8d-e619-4ce2-99f3-ea9b37de33ea)
I helped newcomers on Discord and Telegram (global + RU), answered their questions and addressed issues. 
![Screenshot 2024-06-04 183424](https://github.com/Phala-Network/growth-program/assets/111198068/1126112e-5be5-4a08-97db-4b522f652f4e)
![Screenshot 2024-06-04 183404](https://github.com/Phala-Network/growth-program/assets/111198068/3a7e305d-7e72-433c-a11a-f1ea63124648)
![Screenshot 2024-06-04 183304](https://github.com/Phala-Network/growth-program/assets/111198068/551f88bb-4695-4533-8520-6fe6bdd8dbc6)
![Screenshot 2024-06-04 183255](https://github.com/Phala-Network/growth-program/assets/111198068/47da0105-3b2b-4e1d-8887-5330f8741f15)

My video about RedPill
Russian:
https://www.youtube.com/watch?v=eIId-MU7mfw 
https://x.com/PhalaRussia/status/1796111558906405247
![Screenshot 2024-06-04 183722](https://github.com/Phala-Network/growth-program/assets/111198068/3ae7158d-9ebe-4191-a687-05006c460f6d)
English:
![Screenshot 2024-06-04 183857](https://github.com/Phala-Network/growth-program/assets/111198068/89a3f94c-f40a-45ca-81df-fcb1de49a0e2)
https://x.com/m0neymantra/status/1795806896726610296

Community call on Phala Network CIS Telegram, where I was a speaker:
![Screenshot 2024-05-30 191259](https://github.com/Phala-Network/growth-program/assets/111198068/73523d12-35ef-4be6-bb94-36238be9cde8)

I will continue promote Phala Network on every social platform mentioned above, make videos about Phala Network In English and Russian and also take part in community calls as a speaker. Help community members on Discord and Telegram.

**Comment by MaggiePhala** [comment]
Hey 

The YouTube video about RedPill is good. Think of a way to push it out to your local crypto communities so the views will be even higher. 

Overall I think you did a great job with content creation, marketing and community management. 

Keep up the good work!
