### ISSUE TITLE
May 2024 report {infaceAi#5149}

### ISSUE THREAD

**Issue by infaceAi** [Phala-Network/growth-program#417]
PERSONAL INFO
Amb Rank: Senior Ambassador
Discord: infaceAi
Telegram: infaceAi
Twitter: https://twitter.com/infaceAi
PHA Address: 45CjMAG87oPT6pJEYq6aY3aAnrfzRsCQRJ7t6THrjpFYxeXv

Departments : #CC & #MK
Department Score Weight : 50%(40) & 50%(40)

Contributions:
MK & CC
This month I promoted AiAgentWars and RedPill a lot, using corresponding tags - #AiAgentWars, #RedPill, #PhalaNetwork. We made calls with local ambas, and the local tg community. 
 
Х May 2024 stats:
Twitter analytics and https://analytics.twitter.com/user/infaceAi/home 

---
<img width="888" alt="X May" src="https://github.com/Phala-Network/growth-program/assets/112633185/a09874af-495d-4e9d-89d0-5704c731d2e2">
---
<img width="879" alt="X May 1" src="https://github.com/Phala-Network/growth-program/assets/112633185/fca4a048-3149-4c63-bf26-1740dcdbc444">
---
<img width="882" alt="X May 2" src="https://github.com/Phala-Network/growth-program/assets/112633185/921adb18-caf8-448f-9cd1-8e6be4410b89">
---
<img width="562" alt="stats may24" src="https://github.com/Phala-Network/growth-program/assets/112633185/01c807f8-75a2-4b19-bad5-fa424f4d82c3">
---
<img width="1222" alt="X pic" src="https://github.com/Phala-Network/growth-program/assets/112633185/fdc43c77-8a57-4195-bbcb-3b8f4a3dc5e3">
---
<img width="1387" alt="X pic1" src="https://github.com/Phala-Network/growth-program/assets/112633185/494efe7f-2201-45d2-8a5d-c8ff62f2f6b5">
---
tg local

<img width="672" alt="local tg May 24" src="https://github.com/Phala-Network/growth-program/assets/112633185/cb974785-0674-4539-8c71-45f40285a9d1">
---

**X local**
---
<img width="921" alt="X local" src="https://github.com/Phala-Network/growth-program/assets/112633185/054937c1-7d04-47e9-8a96-58272c21ccd2">
---
<img width="1270" alt="X local pic1" src="https://github.com/Phala-Network/growth-program/assets/112633185/2f79250c-59cd-4690-8f6f-8bdeeea8ce65">

SUPPLEMENTARY TASKS

#HD This month I did many activities at Phala general and local telegram chats. I try to give the most accurate and quality answers to questions from the Phala community's telegrams. I try to engage people to join Ai Agent Wars and explain about it and RedPill.

---

#**ART** - Some of the best:

**vids**
https://x.com/infaceAi/status/1793187037610193354
https://x.com/infaceAi/status/1795716706217934906
https://x.com/infaceAi/status/1791361033669361680
https://x.com/infaceAi/status/1794626511628079380

**pics**
https://x.com/infaceAi/status/1793905773472596028
https://x.com/infaceAi/status/1792819868003168466
https://x.com/PhalaUkraine/status/1793908541700395212
https://x.com/PhalaUkraine/status/1792452453163577464
https://x.com/infaceAi/status/1792459497803276741

SUGGESTED SCORES
#CC : 40/40
#MK: 40/40
#HD: 10

May was a busy and productive month!
In addition to the info above.
I contributed some ideas to watercooler Discord chats.
Also I gave feedback/suggestions about AiAgentWars and some about RedPIl.
I pay even more attention to the quality and diversity of my content, so I started making videos and songs. Hope it brings more interest to the Phala ecosystem.

**Comment by MaggiePhala** [comment]
Hey hey hey.

Great work per usual. I don't really have anything else to add except that we are lucky to have you with us. Any you needed from my side please let me know. 

Cheers! 

Maggie
