### ISSUE TITLE
May Contributions 2024 - Ayomide Bajo

### ISSUE THREAD

**Issue by ayomidebajo** [Phala-Network/growth-program#419]
Telegram username @dev_bekka
twitter url: https://twitter.com/ayomide_bajo
wallet address: 435qKnxBXY23mDMVygUxYm3GkpGoQddCUigXpya78LfGfnV9
departments: MK/CC

Contributions
I hosted a Polkadot (X)Twitter space and invited my fellow Phala ambassadors to speak and market Phala network's AI agents.

I promoted and interacted with Phala Network's Official tweets by sharing and liking them, as well as doing the same for my fellow Ambassador's tweets, I also quoted some of them and made a few posts. I also participated in Phala Africa community call as a panel speaker, where I answered technical questions asked by the community on Redpill gpt, it was an interactive Q&A session.

Tweets, Retweets and Posts (links)

https://x.com/phalanetwork/status/1785677956657877433?s=46
https://x.com/phalanetwork/status/1786442814903001236?s=46
https://x.com/agashiharuna/status/1786775186466906560?s=46
https://x.com/phalanetwork/status/1785976296020857071?s=46
https://x.com/phalanetwork/status/1788137792242954467?s=46
https://x.com/phalanetwork/status/1788137792242954467?s=46
https://x.com/phalanetwork/status/1790410734775455810?s=46
https://x.com/phalanetwork/status/1793123103914201321?s=46
https://x.com/phalanetwork/status/1793730884496957895?s=46
https://x.com/marvin_tong/status/1793108884913283317?s=46
https://x.com/official_bles1/status/1795442706183078019?s=46
https://x.com/immei256/status/1795416308621988219?s=46
https://x.com/phalanetwork/status/1795484778449551365?s=46
https://x.com/phalanetwork/status/1795476270186156246?s=46
https://x.com/infaceai/status/1794626511628079380?s=46
https://x.com/gabekoin/status/1797311595279679848?s=46

I'm the official moderator for Polkadot Africa (X)Twitter. I utilise the opportunity to market Phala network as much as possible.

https://x.com/ayomide_bajo/status/1792858521697939746?s=46

Conclusion
Now, that Phala has finalised its updates, I can focus on creating content based on the available content on Phala website and docs.

Score
Mk: 40
CC: 15
HD: 5
Total = 60

**Comment by MaggiePhala** [comment]
Hey Bekka,

How are you?

I've heard amazing things about you and I've been looking to connect with you as well. I understand you're strong in tech and our current Ambs program might not necessarily have the right frame for you to fully utilize what you're good at doing. But the good news is I am about to revamp the program and add a 'Tech' sector to this program. Does it sound like something you would be interested in fully participating in? Let me know your thoughts on this. :)

Thanks Bekka.

**Comment by ayomidebajo** [comment]
Hey Maggie,

I'm good, thanks. i hope you are too!
Thank you for your kind words, i appreciate it. I'm interested in learning more details about the Tech sector of the program, it sounds interesting already.

I think I can send you a message on Twitter.

Thanks for reaching out Maggie.
