### ISSUE TITLE
September 2022 Contributions - {tioneb#4951}

### ISSUE THREAD

**Issue by TionebErtahcnom** [Phala-Network/growth-program#42]
Telegram : [tioneb](https://t.me/tioneb)
Discord : tioneb#4951
PHA Address : 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7
My Mandatory (Basic) Contributions of September:
Senior-ambassador

Phala frenchChannel link: [₱hala francophone](https://t.me/phala_french)
Have I participated in Discord Channel Moderation ? no

Combot Link : https://combot.org/c/-1001424849386/a
![image](https://user-images.githubusercontent.com/16654460/194246541-6a849eb0-d22c-4df9-a5e1-6b88dde9cc8a.png)

###Comments:
How many people increased or decreased? Why?
The number of users remained constant during the month
How can I improve this next month?
I would hope for a return of the activity with the end of the holidays. But it's still very quiet.... it's the whole crypto planet that is at a standstill. But as you will see below, our fr community is still fighting the bear.

###VSM(Twitter Virals)
Twitter  : https://twitter.com/tioneb442
Analytic : https://analytics.twitter.com/user/tioneb442/tweets
![image](https://user-images.githubusercontent.com/16654460/194249073-7715914a-7557-41dd-aa06-f6ab33302019.png)
https://twitter.com/search?q=PhalaNetwork%20(from%3Ationeb442)%20until%3A2022-09-30%20since%3A2022-09-01&src=typed_query&f=top

### Youtube Channel : 
![image](https://user-images.githubusercontent.com/16654460/194261641-58c00f3b-02a2-4943-825d-20f3a4c87776.png)

###My Supplementary(Advanced) Contributions of September:

I am currently helping 6 new miners to launch their miners. It's taking a lot of my time to help them.
About mining, I asked at the last amb monthly meeting if there were any problems with PruneNode. Apparently, no problems were reported.
But since then none of my guys have managed to launch with a pruneNode. Every time, once the node sync is finished, the pherry sync encounters problems.

https://youtu.be/bMGaZFQvf3U
Our last AMA in September was amazing. We invited a Youtuber (https://www.youtube.com/c/MansaCrypto) who didn't know PhalaNetwork. The game was: "this guy doesn't know PhalaNetwork. He won't leave the AMA without give a proof of knowledge !".
I received a lot of good feedback about this AMA. 

https://twitter.com/tioneb442/status/1573254897835077632?s=20&t=2JSGh0KM1rTDKivNYaCX1w
 [![image](https://user-images.githubusercontent.com/16654460/194264006-eafeb914-dcc5-4a2b-ab5e-126d28c70dab.png)](https://twitter.com/tioneb442/status/1573254897835077632?s=20&t=2JSGh0KM1rTDKivNYaCX1w)

**Comment by luciaaaa4455** [comment]
Good to see you are inviting some new guys into Phamily!
