### ISSUE TITLE
May 2024 Contributions {Favour}

### ISSUE THREAD

**Issue by BBoss01** [Phala-Network/growth-program#421]
Amb Rank : Ambassador
Discord username  : favour_cy#5138
Telegram username : @solomonfav 
Twitter Link : https://twitter.com/official_bles1?t=eR-KQW9NjmPi7pCNo7ziLg&s=09
PHA address : 41dNB3qCWz1m4b874815wYnthsbSUvmKUws6624wRrjX4tnL
Department : MK & CC
Score weight 50/50

CC

Departmental Channels - I actively participated in the Phala Africa ambassador channel, where I contributed ideas, planned events, and raised awareness for our community call. I also engaged in the content and marketing channel department.

CC - I created four articles about Phala Network

• Understanding Red pill relationship and impact on Phala Network 
https://medium.com/@boyesolomon8/understanding-redpills-relationship-and-impact-on-phala-network-de53f623eee8

• Tokenomics of Agent Wars powered by Phala Network 
https://medium.com/@boyesolomon8/tokenomics-of-agent-wars-powered-by-phala-network-be3fbde58ebb

• Integration of Decentralized AI systems and Blockchain technology 
https://medium.com/@boyesolomon8/the-integration-of-decentralized-ai-systems-and-blockchain-technology-359561bb1fe9

• Revolutionizing AI Agents in web3 
https://medium.com/@boyesolomon8/revolutionizing-ai-agents-in-web3-37a23f13a36f

X Library GIF 

- I created some GIFs and added them to the X GIF Library, which also reflects across various social platforms, to increase awareness of Agent Wars and Redpill among both familiar and unfamiliar audiences with Phala Network.
Keywords
- Redpill AI
-Agentwars

![Screenshot_20240605_095601.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/2838d7c0-c238-4225-98ff-aed7a2b61934)

![Screenshot_20240605_095621.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/bc5a372b-af4c-4be1-815c-7f4557516797)

Community Call - 

- We followed to our usual routine for the community call, during which I contributed as a speaker, sharing my insights in response to the prepared questions. I participated in the rehearsal for the community call and promoted the event by quoting and sharing the original post on Discord. ![Screenshot_20240605_110237.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/26c7186f-d51b-412b-a9d6-6f9df14fbab2)

Call Link - https://x.com/PhalaAfrica/status/1794050241362293216?t=91KW7Q6cmnIqldhrjEJ43A&s=19

Additionally, I joined the Polkadot Africa call and briefly discussed Phala Network, and shared relevant links during the session.
![Screenshot_20240605_105700.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/534f735f-b501-48c7-bd87-a072a78b7154)

TT - 
I made a guide on how to get PHA tokens on base chain for those who wants to participate in Agent Wars.
 
https://medium.com/@boyesolomon8/how-to-get-pha-tokens-on-the-base-chain-f42e5d217648

Video -
I created two YouTube videos on Phala Network.

Revolutionizing AI access with Redpill https://youtu.be/FS2BmWTCSgE?si=c8J_mqe2ip3HBC6S

Unlocking the power of web3 AI with Phala Network
https://youtu.be/Oc4ubZ0UnfI?si=7M8JWGfDYXYzM67b

ART 
I Created and shared some infographics and banners about Phala Network.
![Blue Gradient Company Business Profile Presentation_20240506_093048_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/1df9de9f-8fe0-4c58-93d0-cb4c68150198)

![20240506_093129_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/9aca92b0-6bb0-43d0-9fdb-f74cb6781288)

![Blue Gradient Company Business Profile Presentation_20240506_093205_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/3a44e33a-4f12-45e2-857e-ca4d160c86f5)

![Blue Gradient Company Business Profile Presentation_20240507_094313_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/d260ef69-d29f-4fc4-98f7-ca9ee73410e9)

![20240509_211349_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/8875bf41-7b49-482b-bd05-9424a044c568)

![20240509_211544_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/911dce79-8f95-4b53-bbcd-1802499b733b)

![20240509_211642_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/04cafbe7-6e01-44c1-bdc9-17528b683590)

![Blue Gradient Company Business Profile Presentation_20240510_085931_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/3aeff23c-53a9-4623-af5b-5fa2e9074868)

![Blue Gradient Company Business Profile Presentation_20240513_215316_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/31ba2e07-616b-4462-84a7-07a7ccb7d2d7)

![20240513_222025_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/410de4f7-837b-4d21-8452-727934e3c504)

![20240513_222540_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/dff8d897-ade4-4c47-851a-cec1b450576e)

![20240520_102730_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/ec8d254a-f056-4b6e-8ed1-3dd65e6e3a5e)

![Blue Gradient Company Business Profile Presentation_20240521_101851_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/daa9fb86-8463-4a96-8fda-fea7b6f51397)

![Blue Gradient Company Business Profile Presentation_20240521_101923_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/4621a4e4-bd54-48e0-983e-522e12749aa0)

![Blue Gradient Company Business Profile Presentation_20240521_110304_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/5f709ebb-2edc-451e-88dd-b0b2b4f260b4)

![Blue Gradient Company Business Profile Presentation_20240522_095007_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/c968708f-eed1-4013-b325-65d16520b8bf)

![20240523_085227_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/908e40de-fb7a-4f8f-8f99-0fb663509198)

![Blue Gradient Company Business Profile Presentation_20240523_091037_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/78305d35-fc8b-4bf7-ba28-011663c7a959)

![Blue Gradient Company Business Profile Presentation_20240527_231211_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/ffc648d9-6091-4a15-8ad6-0c065e9be965)

![Blue Gradient Company Business Profile Presentation_20240527_231247_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/7d18837f-43f3-450b-80d3-a52f48125f41)

![Blue Gradient Company Business Profile Presentation_20240527_231328_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/db97f901-35c4-4555-943b-e3dba82b8e20)

![Blue Gradient Company Business Profile Presentation_20240528_121947_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/df37e1af-8839-4d4d-a9d8-1985e4d4da83)

![Blue Gradient Company Business Profile Presentation_20240528_122037_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/1cba69da-396a-4713-b2c7-9ba3424fb6bd)

![Blue Gradient Company Business Profile Presentation_20240528_140723_0000.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/f7bbd360-9d82-46cb-88d3-0ca2b26357fe)

MK

I actively promoted Phala Network on multiple platforms, including X, LinkedIn, and Polkadot Community. By actively promoting Phala Network, the goal was to foster greater community involvement and facilitate its expansion. My engagement strategy involved not just posting original content but also supporting fellow ambassadors by interacting with their posts. I participated by liking, reposting, and quote posting both on global and local communities.

X Statistics :

https://x.com/search?q=from%3A%40official_bles1%20Phala%20Network&t=qIrwaBSYZJCG8I1hhwYMhg&s=09

https://x.com/search?q=from%3A%40official_bles1%20Agent%20Wars&t=TtTu2oOgg3o8nmSNP6bFDQ&s=09

https://x.com/search?q=from%3A%40official_bles1%20Redpill&t=W7Jf64vDBepHW0xUv1sMWg&s=09

![Screenshot_20240605_094914.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/dc0644a7-148c-4f5a-ba65-2a9694342849)

LinkedIn Posts: 

- https://www.linkedin.com/feed/update/urn:li:activity:7203696929858359296

- Agent Wars https://www.linkedin.com/posts/favour-solomon-99b430236_phalanetwork-polkadot-web3-activity-7202610736882192386-4FLS

- Phala Network Revolutionizing the landscape of web3 
https://www.linkedin.com/posts/favour-solomon-99b430236_phalanetwork-ai-web3-activity-7201718968103915520-A7Rw

- Consensus 2024
https://www.linkedin.com/posts/favour-solomon-99b430236_web3-ai-phalanetwork-activity-7201716380197400578-T_tk

- SubBridge https://www.linkedin.com/posts/favour-solomon-99b430236_ai-crosschain-bridge-activity-7200785012382715904-B08I

- Redpill 
https://www.linkedin.com/posts/favour-solomon-99b430236_ai-gpt-web3-activity-7198626019673591809-EPi4

- Redpill platform 
https://www.linkedin.com/posts/favour-solomon-99b430236_ai-web3-gpt-activity-7198625302946729984-dnBO

- https://www.linkedin.com/posts/favour-solomon-99b430236_ai-web3-blockchain-activity-7193943818050686977-FF3X

- I promoted Phala Network on Polkadot Discord channel. 
![Screenshot_20240605_095711.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/3076d5b3-0c11-400d-8be5-fb9922289007)

![Screenshot_20240605_095732.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/6719ad1f-b267-4b6d-bcc9-8d7b56833ec7)

![Screenshot_20240605_095745.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/ada50531-3fc0-48e6-b5c6-0b2700f31827)

- I promoted Phala Network on Kusama Discord channel.

![Screenshot_20240605_095833.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/b9bbceca-8e16-4db0-b9ec-dd271d2e5603)

![Screenshot_20240605_095850.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/46074cda-5b48-4bf9-8d90-5af2be62312f)

![Screenshot_20240605_095900.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/26ac7829-c2bb-44b7-8e29-3a92c68ffe6d)

SUPPLEMENTARY TASK

HD
I actively participated in the Phala Africa Telegram and Phala Network Discord community, providing valuable information, answering Questions, welcoming new members, and moderating spam and spammers. I had little engagement in PhalaWorld discord community.
![Screenshot_20240605_101329.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/486ec574-94d7-4d69-a9c4-319e6440a93e)

![Screenshot_20240605_095259.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/af0ff2c5-af0e-4a2d-9532-b7f9930fb75d)

![Screenshot_20240605_095107.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/5b6eb47a-e265-4596-b9f0-f6e516357006)

![Screenshot_20240605_095058.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/2467a35b-d7c5-4392-89dc-37171687861e)

![Screenshot_20240605_095050.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/7f01af98-fb61-4cc6-950d-86ab117dbbf9)

![Screenshot_20240605_095043.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/067519c8-21c2-48f7-ad93-844f79661548)

![Screenshot_20240605_095034.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/44882357-35c5-4d93-8389-ced40a0211a0)

![Screenshot_20240605_095521.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/86764790-9918-48a4-8e17-4df9253725c8)

![Screenshot_20240605_095439.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/4cf6e3ba-b539-416c-9ed7-4dedb9b574c3)

![Screenshot_20240605_095349.jpg](https://github.com/Phala-Network/growth-program/assets/116058765/46c4c5aa-f859-4d37-9dc4-21438cc4badb)

Good Points: - We had a great number of attendees at our community call, and it was an interactive session with Bekka answering some technical questions. I improved the quality of the content I produced alongside the posts I made. 

Bad Points: - Low engagement in our local Telegram and Discord communities. I had low impressions on LinkedIn as well. 

How to Improve: - I will continue to enhance the quality and quantity of content created and collaborate more effectively with fellow ambassadors to foster community growth.

Suggested Scores
CC - 40
MK - 40
HD - 10
Total - 90

Closing Comment 
My performance has generally improved, with enhanced community engagement on telegram and discord. The production of higher-quality art. I have also improved my article and social media post quality, and have successfully collaborated with ambassadors from different departments. I will continue to collaborate with all ambassadors to further increase productivity and content quality. Thank You.

**Comment by MaggiePhala** [comment]
Hey Favour! 

Great work! I wonder where all these images created by you were used? Also the LinkedIn posts didn't seem to have reached a lot of people. How do you think you can improve it? Feel free to DM me. 

It was great to see you were actively engaging with the community.

**Comment by BBoss01** [comment]
> Hey Favour! 
> 
> Great work! I wonder where all these images created by you were used? Also the LinkedIn posts didn't seem to have reached a lot of people. How do you think you can improve it? Feel free to DM me. 
> 
> It was great to see you were actively engaging with the community. 

Hi, thanks for the feedback on my report.

1. All images were used alongside the content created. Most were used on X, with threads and short posts, some with medium write-ups, and the rest on LinkedIn. You can see the images by clicking the X and Medium links above, as well as on LinkedIn.

 2. I am also ready to work on improving my LinkedIn reach. I'll send you a DM. Thank you!
