### ISSUE TITLE
April 2024 Contributions - Arηo#8446

### ISSUE THREAD

**Issue by arnobase** [Phala-Network/growth-program#425]
Telegram Username: @arnobaze
Discord Username: Arηo#8446
Twitter Username: https://twitter.com/test_ut
PHA Wallet Address: 44siNV2pbrTSwiL3KdT4VVC1yqcSvfGzxcd7rHMD1cgQnjcn

mandatory tasks : CM & CP
ratio : 50%CM (40/80) - 50%CP (40/80)

## CM
read all the messages on all the threads, to keep up to date with the latest news and requests from the community.
Antispam work, delete spam and ban spammers on TG and Discord
spotted Discord hacked account and urgently reported to Will and Marvin, resulting in kicking the hacker immediately 

## CP 
worked with Radiumblock to add Khala and Phala archive to their available blockchain snapshots 
https://khala-archive.radiumblock.com/providers-khala-archive.php?name=khala_rocksdb_archive
https://snapshots.radiumblock.com/providers-phala-archive.php?name=phala_rocksdb_archive
see full retrospective on discord https://discord.com/channels/697726436211163147/1092712333412937738/1238249488771186739
all the work done so far on the proposal hasn't been included in previous reports

provided help desk, reported to team when necessary

### maintain Doc PHA from CEX's (check networks, update fees)
- https://docs.google.com/document/d/1o4GEq7B2y7JoCvnBfN0q3yVnoObgShjEOLs8-JFWjGw
<img width="450" alt="pha cex fee" src="https://github.com/Phala-Network/growth-program/assets/8094810/b55916c4-6833-4bcd-8e89-72308ba0ba65">

## DEV
developpment of lotto dapp based on phat contract
see phala's tweet about it : https://x.com/PhalaNetwork/status/1790410734775455810
<img width="400" alt="lotto dapp phala" src="https://github.com/Phala-Network/growth-program/assets/8094810/e5cce9dd-03ca-4a51-b97f-d95d59c5c988">

SUGGESTED SCORES
#CM : 25/40 
#CP: 25/40
#EM : 10
#DEV : 10

Overall : 70

I returned to my ambassadorial activities on a regular basis this month. For the previous 4 months, I had only sporadic actions and basic interractions with the community. However, I've kept up to date with Phala and remain passionate about web3 and the possibilities offered by Phat Contract.
This month, my participation has been a bit more modest than what I've done as a Phala ambassador in the past, but I've been able to help community members by providing targeted answers, and I've taken part in the debates in the threads dedicated to ambassadors. I've also done some development based on PhatContract technology through a game called Lotto, which we plan to roll out in collaboration with Phala and other teams next month.

**Comment by MaggiePhala** [comment]
Hey Arno! How are you?

First of all Will has said so many nice things about how you're an anti-spam expert and are always quick to catch any spamming activities - super! I would only encourage you to be more active in the global channel. I know you're quite technical - feel free to use your expertise in helping out answering the techy questions from the community. I am sure you are going to be so good at doing it! 

Second of all - back to what I said about you being techy. I will revamped the Ambs program a bit and add a new sector that's called "Tech Ambs". You can really put your expertise in good use and start contributing to Phala from a more techy side. How do you feel about that? DM me and let me know! :)

Thanks Arno!
