### ISSUE TITLE
May 2024 Contributions - {rom1.dot}

### ISSUE THREAD

**Issue by xcRom1** [Phala-Network/growth-program#426]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/63704652/216827308-dd6a24be-5517-4e09-9c0e-c65a763aca3b.png">

Amb Rank : Ambassador
Telegram Username: https://t.me/rom1_dot
Discord Username: rom1.dot
Twitter Username: https://twitter.com/rom1_dot
PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q

Departments : #CM & #MK

**Contributions:**
Hello, last month was pretty quiet as far as the community is concerned. I did a few translations and we organised the Polka Party in Nantes with Gator & Tioneb where we represented Phala Network.

![image](https://user-images.githubusercontent.com/63704652/222117520-bf30a95b-18be-44e8-9e0f-aad3e09f879c.png)

Twitter analytics: [Here](https://analytics.twitter.com/user/RCajina/home)

<img width="1010" alt="image" src="https://github.com/Phala-Network/growth-program/assets/63704652/c46c9364-06df-44d9-94b8-7ca85dc9c151">

![image](https://user-images.githubusercontent.com/63704652/222134127-67fe6ec1-f49c-43d7-a391-f681d8d5a87e.png)

Here are the translations  : 2475 words 
- [Agent Wars: façonner l’avenir de l’IA et du Web3 grâce à la tokenisation](https://medium.com/phala-fran%C3%A7ais/agent-wars-fa%C3%A7onner-lavenir-de-l-ia-et-du-web3-gr%C3%A2ce-%C3%A0-la-tokenisation-965c787e4d17)
- [Les systèmes Multi-Agents, nouvelle frontière de l’innovation blockchain](https://medium.com/phala-fran%C3%A7ais/les-syst%C3%A8mes-multi-agents-nouvelle-fronti%C3%A8re-de-linnovation-blockchain-5b70e61df12b)

![image](https://user-images.githubusercontent.com/63704652/222134855-7eff0b13-3d74-4aad-a848-63d581a00c44.png)

We organised the meetup in Nantes (France) with Gator & Tioneb, we had an average of 40/50 people and Phala Network was there !!!! [Here](https://phala-network.4everland.store/videos/polkaParty_2024_promo_20m.mp4) is the video presentation of the event 

![image](https://github.com/Phala-Network/growth-program/assets/63704652/719f0931-e69b-4c23-9d0b-48d7cbd46f12)

## SUGGESTED SCORES
#CM: 30/40
#MK: 30/40

Other:
#CC: 10/10

Overall : 70

***Quote*** : "Start by doing what's necessary, then do what's possible and you'll achieve the impossible before you know it." - Saint François d'Assise

**Comment by MaggiePhala** [comment]
Hey there! 

First of all thanks for the contribution to Phala. 

About CM - I will need to see the screenshots of the things you've said in the community. Please understand these evidence are necessary and much needed in order for me to come up with an accurate assessment score. 

Same thing with MK - Super important for me to see what you have tweeted about and their impact (twitter impression). Include screenshots as well please. 

From the video I see this event is hosted by Polkadot? For future event organization, please share pre-event planning and post-event recap with me. It's important to know why we had this event and what the ROI roughly look like. 

Thanks.
