### ISSUE TITLE
May  2024 Contributions - Gatorkorps

### ISSUE THREAD

**Issue by gk1845** [Phala-Network/growth-program#428]
Hello,

Telegram Username: @gatorkorps
Discord Username: gatorkorps
Twitter Username: https://twitter.com/gk18_dog
PHA Wallet Address: 42yHNqpRKAawNSvmXJpnEh7jGArwz2pkGfH9KEHcE7WnEjBV

Community:

Phalafr twitter account management
phalaFR telegram management

![image](https://github.com/Phala-Network/growth-program/assets/82824139/9dcb8a56-df09-469c-b01b-0a0b437d5d17)
![image](https://github.com/Phala-Network/growth-program/assets/82824139/99f5908f-3bc6-41ed-8e5a-4330652386b6)

ban several shitcoin chiller on the main Phalanetwork TG

The month was monopolized by the organisation of our first Polkadot Party.

https://x.com/phala_fr/status/1787947756901839139

Phala was also very present and we had the occasion to meet our community to speak about the protocol AI  Agent and all the great new feature.
The event was clearly a succes with must than 50 participants and great discussion around Phala and others project.

![image](https://github.com/Phala-Network/growth-program/assets/82824139/729b28c2-6445-4c43-b886-0097ab0648e7)

It was a test event, in 6th biggest french city. Our goal is to export this event in ither city to present the protocol.
We used our Ambassador rewards to pay the pizza :) 

Personnal account : 
![image](https://github.com/Phala-Network/growth-program/assets/82824139/e24c0aaf-413d-4d82-95b1-d53cbffe08a8)

On the other end the account continue to amplify all the great product from other ambassadors and core team
. We work to bring french journalist in decoded to speak about Phala.... our main goal is to bring big french influencer to speak about phala:

https://x.com/gk18_dog/status/1797626320056369412

Mr Tk is in the top5 french crypto account.

Phala_FR X account:

![image](https://github.com/Phala-Network/growth-program/assets/82824139/b231ebc0-e511-4616-8b69-fea9429858ba)

<html>

EM | The Event Manager: Organize an online/physical meetup/AMA with your local community. Plan ahead and please reach out to us if you need financial support. It is best to record the meetup session. | 1 per month | Quality & Engagement | 10

PM | The promoter: promote Phala across relevant social media platforms. | 5 per month | Reach & engagement | 20

CC - 20
CM - 20

70 pts asked

**Comment by MaggiePhala** [comment]
Hey there,

It's amazing to see you guys have put together an offline event and represented Phala! However, I found a severe lack of information on this report such as the TG management and Twitter management - how have you managed these channels? What are the impacts? 

Can you please provide necessary info, following the format of the report (https://github.com/Phala-Network/growth-program) so I can better assess your contribution in May? Thanks.
