### ISSUE TITLE
May 2024 Contributions - John Rhodel Bartolome

### ISSUE THREAD

**Issue by johnrhodel** [Phala-Network/growth-program#429]
Telegram Username: https://t.me/johnrhodel
Discord Username: johnrhodel
PHA Wallet Address: 428C77AEFcs7ytBLEwSYhJWwpRAHk69MdqgWP7X6nR9RtVXK

CC: 40/40

Article translated Filipino:

https://grillapp.net/11194/agent-wars-paghubog-sa-kinabukasan-ng-ai-at-web3-gamit-ang-177427?ref=8730

Articles Created Portuguese:

https://medium.com/@phalaptbr/aumentando-a-seguran%C3%A7a-na-ci%C3%AAncia-da-computa%C3%A7%C3%A3o-com-tee-e-zk-rollups-c0a8eb49778b

Articles Created Filipino:
https://grillapp.net/11194/pagtaas-ng-seguridad-sa-computer-science-gamit-ang-tee-at-177425?ref=8730

Threads Created:

Portuguese:
https://x.com/phalaportugues/status/1794536034371248494
https://twitter.com/phalaportugues/status/1796351686262583689

English:
https://x.com/johnrhodelb/status/1794530482371043607

MK(34/40) (like/rtwt/quoted)

https://twitter.com/phalaportugues/status/1794536034371248494
https://twitter.com/phalaportugues/status/1796351686262583689
https://twitter.com/phalaportugues/status/1795856490286186676
https://twitter.com/phalaportugues/status/1796268019519492104
https://twitter.com/phalaportugues/status/1795473714584142275
https://twitter.com/phalaportugues/status/1795437621180821551
https://twitter.com/phalaportugues/status/1795437324152734203
https://twitter.com/phalaportugues/status/1795436163865743506
https://twitter.com/phalaportugues/status/1795070721405710602
https://x.com/CryptoCappex/status/1793709162435907692
https://x.com/PhalaNetwork/status/1793730884496957895
https://x.com/PhalaNetwork/status/1793224219494359400
https://x.com/PhalaNetwork/status/1793123103914201321
https://twitter.com/marvin_tong/status/1784019344802066903
https://x.com/marvin_tong/status/1786882773200011739
https://x.com/PhalaNetwork/status/1785976296020857071
https://x.com/zoemcfox/status/1787492241277059459
https://x.com/PhalaNetwork/status/1787492939817529798
https://x.com/PhalaNetwork/status/1787497784972841399
https://twitter.com/phalaportugues/status/1796639400467517747
https://twitter.com/phalaportugues/status/178401450207945564

Spaces:

Agent Wars:
https://x.com/phalaportugues/status/1794066547188621752

Monthly:
https://x.com/phalaportugues/status/1795070721405710602

AI Agent Contract Especial:
![image](https://github.com/Phala-Network/growth-program/assets/77474076/90a3bc3d-e260-460d-86c3-c206c3640382)

https://x.com/phalaportugues/status/1796268019519492104

Deep Dive:
![image](https://github.com/Phala-Network/growth-program/assets/77474076/c0ed7cd8-61c8-4149-9c4b-abec173d67c3)

https://x.com/phalaportugues/status/1796639400467517747

HD:(10/10):

![hd 2](https://github.com/Phala-Network/growth-program/assets/77474076/e92ac6d9-efb5-4303-913d-1b05891ad8aa)
![hd 3](https://github.com/Phala-Network/growth-program/assets/77474076/a6ca8d5b-5659-42c5-a687-ab2f569627f5)
![hd 4](https://github.com/Phala-Network/growth-program/assets/77474076/98262740-29c3-46b2-af45-7b8e51e38177)
![hd 5](https://github.com/Phala-Network/growth-program/assets/77474076/3a8eb28c-122c-49c7-b66f-e78ff3e938a7)
![hd 6](https://github.com/Phala-Network/growth-program/assets/77474076/6a35a357-f5d0-47f1-91cf-95ed8f131fba)
![hd 7](https://github.com/Phala-Network/growth-program/assets/77474076/1efc79ad-92a4-401f-85f0-70f6136881d1)
![hd 8](https://github.com/Phala-Network/growth-program/assets/77474076/a0056002-c113-46fc-a0dc-860869f64aa2)
![hd 9](https://github.com/Phala-Network/growth-program/assets/77474076/9cb9e6dd-3f23-4c37-825a-f20d239819be)
![hd](https://github.com/Phala-Network/growth-program/assets/77474076/57ec6040-8e2b-438f-8e93-81aa4ad02027)

EM (10/10)

Desmitificando Polkadot - Arca Hub

![image](https://github.com/Phala-Network/growth-program/assets/77474076/1a530d52-f484-4af3-853a-cd9ede2fa36b)
![image](https://github.com/Phala-Network/growth-program/assets/77474076/6c4ae582-0622-4e67-97ca-86d129e9df29)
https://youtu.be/f0j_Tpg2uow?si=a7ibQIcJodZnhcYy

Bankless spaces:
![image](https://github.com/Phala-Network/growth-program/assets/77474076/975f2ffe-7d0e-4542-bbdc-60eccff9cf2b)
https://x.com/BanklessBR/status/1790866897069572242
![image](https://github.com/Phala-Network/growth-program/assets/77474076/6b7774ad-0f1f-4ce6-9e04-b9842a7c34f3)

**Comment by MaggiePhala** [comment]
AMAZING work you've done there John! 

Just a question - all these blog articles are great. How did you find a way to increase their visibilities among your local crypto communities? Feel free to DM me. Also next time in the report please include the screenshots of the Twitter impressions & article views. That would be super. 

I love the online events you've done. Can you let me know some of the event stats? Such as how many people joined the twitter space, what questions asked by the community, what have you guys talked about in the twitter space, etc. If there is a script or a list of questions I would love to see them prior to the events. 

I would also love to see you being more active in the global community as well. :)

Thanks John! Cheers!
