### ISSUE TITLE
May 2024 Contributions - {ivakhnenko_dmitriy}

### ISSUE THREAD

**Issue by MrDobby007** [Phala-Network/growth-program#430]
**Personal Information:**
**AMB Rank:** Candidate Ambassador
**Discord:** ivakhnenko_dmitriy
**Telegram:** @Ivakhnenko_Dmitriy
**Twitter:** https://twitter.com/Dima35109517
**PHA Address:** 457dtbUfSkGAHGzD97qWicrCJWGpDjAHjcHYBuPBnkiuW1KT

**DepartmeDepartment Score Weight:nts:** #CC / #CM
**Department Score Weight:** 50% (40) / 50% (40)

**Contributions:**
Hello, Phala team. I finished the May campaign in the Phala Network ecosystem in a high position and am ready to showcase all my achievements for this month. I had a very productive and active month in all aspects, striving to make May as successful as all my previous working months. In May, I made significant contributions to the Phala project and the community every day. During my work, I demonstrated high productivity, efficiency, versatility in all areas of my tasks. I showed a high level of knowledge and skills, especially during work, and throughout the month, I showcased my achievements on both local and global levels, paying special attention to various channels, Discord groups, and Phala Telegram. Throughout the month, I consistently and actively communicated and published my creative work on Twitter, Discord, Telegram, and other social networks, aiming to promote the team's interests and the Phala brand every day. In May, I created a lot of content and educational materials for the Phala community. I made several informative infographics, banners, funny memes, and cool images related to Phala. I was consistently active on Twitter, Discord, and Telegram, posting and sharing various Phala-related content every day. I actively engaged with the community, maintaining a friendly atmosphere, and also tried to actively help other Ambassadors and the Phala team. I aimed to be online as much as possible throughout the day

In May, I also enthusiastically continued to promote local and regional Phala communities on various social media platforms. Together with InFace, we continued to develop the Ukrainian Phala community on Discord and Twitter. I created and published some interesting works for Phala Ukraine (thanks to InFace for his help and support). I actively contributed to the development of Phala Ukraine, constantly commenting, quoting tweets, and engaging with various posts on Twitter and Phala Discord. Summing up May, I can say that I am satisfied with my work and happy to be part of such a large ecosystem as Phala. In June, I want to further improve my statistics and overall performance, making my work even better. I have provided significant support to Phala and hope that my actions have helped both the project and the users

_**Below you will find more detailed statistics of my work in May. I would appreciate your Feedback and evaluation of my report. Thank you and have a great start to the new work week Phala team**_

### Analytics May 2024 stats:

In May, I actively continued to develop my main Twitter account and increase user engagement and demand for posts related to Phala. According to the overall statistics, I lagged slightly compared to previous months, but even so, the performance looks extremely productive. You can see a slight drop in the second half of this month. This situation was due to my major move and change of residence. I wasn't very active on Twitter with my other projects, but I still continued to publish content related to Phala. Despite all the challenges this month, I tried to stay positive and remain among the top performers, and I hope I succeeded. I constantly strive to improve the quality and quantity of my work, thereby enhancing statistics and metrics related to Phala. Special thanks to the Phala community and my fellow Ambassadors for their continued support of my work and publications

**Below, you can see detailed statistics of my Twitter activity for May**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/690d377b-fc0f-4ff9-9bd9-3c781f038e74)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/98fd1342-3971-44dc-b339-f70975e7981b)

**In May, I published a lot of cool and interesting works related to Phala. Below is a selection of all my works from this month. When creating these works, my goal was to make them as attractive, informative, and engaging as possible for the Phala community. Throughout the month, I consistently supported and commented on all possible tweets related to Phala. I also made numerous Quotes from other Ambassadors, Phala team members, and any other tweets related to Phala. In addition to this, you will find my own informative tweets with personally created images. This collection of work contains a variety of information accumulated during May. Despite my long move, I continued to publish a lot of content related to Phala**

![3_](https://github.com/Phala-Network/growth-program/assets/68858747/93ddb83f-ae9f-4628-9713-b4f67203a449)
![2_](https://github.com/Phala-Network/growth-program/assets/68858747/b049eae6-7ef5-45fe-8ac2-519a7e88b496)
![4_](https://github.com/Phala-Network/growth-program/assets/68858747/9e7cd1bd-8460-47ab-9276-519e843c6fd3)
![6_](https://github.com/Phala-Network/growth-program/assets/68858747/83097786-f49a-474e-ab59-2ef3a0aff122)
![1](https://github.com/Phala-Network/growth-program/assets/68858747/72124069-89bf-4a44-be21-014eac154e89)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/14907ac0-5930-4975-81d4-e05fce734b18)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/3e42b0e9-b1c8-4671-aef6-b70808cee978)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/965480b7-face-4a85-ba9b-77088d0ab893)
![9](https://github.com/Phala-Network/growth-program/assets/68858747/14cc34cc-b763-400a-987b-04f20661ee2a)
![1](https://github.com/Phala-Network/growth-program/assets/68858747/9cfd6897-f072-4eff-83af-4df78317a375)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/8e5accff-c540-4f7e-b465-002de68d7e79)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/5ee69362-653e-4be0-8899-42fbd6007b5e)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/432c0667-e901-41ee-bb39-770f5dd71d43)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/3ee21c61-353b-4023-8061-50b2fb025732)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/2b071e6d-e5fc-47af-a795-673df7d807b6)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/3db0438b-fe91-4704-86d1-b487bacc7537)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/55abb639-e107-42e2-b612-5c4dd8aeec64)
![9](https://github.com/Phala-Network/growth-program/assets/68858747/85de16cd-5e64-48c8-97b6-3cb8c7400d8a)
![10](https://github.com/Phala-Network/growth-program/assets/68858747/26c17490-0153-4b81-b121-3407d3f36d84)
![11](https://github.com/Phala-Network/growth-program/assets/68858747/9fe30284-ae9f-4b38-9a1a-c423b40f6a60)
![12](https://github.com/Phala-Network/growth-program/assets/68858747/2887ca63-84eb-4dce-9a08-6fd44d7b1f80)
![13](https://github.com/Phala-Network/growth-program/assets/68858747/fef0eea8-6d2d-402b-8e61-a5c85f905bff)
![14](https://github.com/Phala-Network/growth-program/assets/68858747/f28ac1d4-9407-4746-808f-5ae11a8862d1)
![15](https://github.com/Phala-Network/growth-program/assets/68858747/e571b1d7-8b31-415e-8f00-b7cb0afff4d8)
![16](https://github.com/Phala-Network/growth-program/assets/68858747/136fe774-4df6-4003-bc64-3424abe76df8)
![17](https://github.com/Phala-Network/growth-program/assets/68858747/fec6078e-c44a-4513-965c-06317a18a851)
![18](https://github.com/Phala-Network/growth-program/assets/68858747/450e8c00-8696-4684-8c4c-c43a52654c6d)
![19](https://github.com/Phala-Network/growth-program/assets/68858747/735bc14b-59cd-4c21-89a1-32fb95d76d3f)
![20](https://github.com/Phala-Network/growth-program/assets/68858747/b867894c-fc4a-4990-8a5a-02b745ab77f5)
![21](https://github.com/Phala-Network/growth-program/assets/68858747/234e1039-43f6-4d17-837a-71c609ee995d)
![22](https://github.com/Phala-Network/growth-program/assets/68858747/d2591131-d921-404a-ae11-9c2a3843c2d5)
![23](https://github.com/Phala-Network/growth-program/assets/68858747/6546de37-e318-4ea8-ae15-6297ddd94137)
![24](https://github.com/Phala-Network/growth-program/assets/68858747/0dd2a551-8388-4553-bc72-51dfc27d470a)
![25](https://github.com/Phala-Network/growth-program/assets/68858747/562f99de-3ad3-4636-9b18-4dd05119c699)
![26](https://github.com/Phala-Network/growth-program/assets/68858747/efb02e73-2ea1-48e4-b9eb-89ad9e98ea3f)
![27](https://github.com/Phala-Network/growth-program/assets/68858747/67b08c69-9735-4f4e-9481-5a04afd9894f)
![28](https://github.com/Phala-Network/growth-program/assets/68858747/1d9b69b0-5780-487c-8dda-207feada3de5)
![29](https://github.com/Phala-Network/growth-program/assets/68858747/202ab10a-5368-4445-8e95-306b481283f7)

**Below is a diagram illustrating the change in the level of my Discord account in the Phala network. In May, I paid special attention to working with the Phala community, constantly engaging and supporting it, as well as creating a friendly atmosphere in communication. Additionally, I responded promptly and clearly to various questions, stayed online consistently, and dedicated a lot of time to moderating various Phala communities**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/46a4ead7-8ed4-485a-920a-f9595789a3ac)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/5861233c-9c7d-46f5-ae4d-67b0f9d81bb0)

**Below is detailed statistics showing the overall user activity in the official Phala Telegram channel, and this report also shows my activity for May. I made a lot of effort to maintain a positive atmosphere in our chats, actively engaged with the Phala community, and shared interesting and relevant information related to the Phala Network project. May was very successful and productive in terms of activity in various communities, both on Telegram and Phala Discord. I actively collaborated with the Phala community, helping them navigate the ecosystem, sharing the latest news and updates, mentioning new technologies and developments, answering frequently asked questions, moderating, and simply maintaining a friendly atmosphere**

![3](https://github.com/Phala-Network/growth-program/assets/68858747/5a7ef291-684b-4735-81fc-a8bbce91605c)

**In May, as always, I demonstrated a high level of activity and work, constantly interacting with the Phala community on various social media platforms, including Discord and Telegram. I not only answered their questions but also published interesting information related to Phala, shared my content, and simply maintained a friendly atmosphere. Below, you will find screenshots of my conversations with users. Throughout the month, I aimed to stay connected and be active for as much of my working time as possible**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/14c3291f-d0a0-44e8-a7ac-311b0fff4ba9)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/7ff6ed1e-b7ab-401e-97d6-f73f5677e110)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/fe449e9a-0b47-46d0-84b3-551dc3e61223)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/c3e0096e-a541-457b-ab7c-0e2c72548caa)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/31297ccf-b146-4e6e-a136-564074e15c4e)
![1](https://github.com/Phala-Network/growth-program/assets/68858747/66582007-079e-4de9-94e9-94576d450b25)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/f0b77f23-55e6-4e4d-9c38-18e6c0b2267b)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/62a14a87-0acb-40fa-be2a-4b47f4864f0c)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/cff171d8-6ba2-466f-ae83-940010690b3c)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/dafea3be-9140-42e0-86ea-6f8acb3ff296)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/d94d81ce-14ad-40eb-b8dc-8437e986786b)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/59b7b401-34e4-4402-834e-4713e2d1c613)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/7bf24cd1-fc95-4019-afb0-7259ef2bde54)
![9](https://github.com/Phala-Network/growth-program/assets/68858747/669a5e60-f334-47b6-bfb6-dcc24862594e)
![10](https://github.com/Phala-Network/growth-program/assets/68858747/33396342-0d65-4c8c-8dff-bd29ed31c86a)
![11](https://github.com/Phala-Network/growth-program/assets/68858747/dc1edbda-99cc-47b3-87de-4ec53e394970)
![12](https://github.com/Phala-Network/growth-program/assets/68858747/27891d5c-b5b4-4029-8625-47f5acc9cea8)
![13](https://github.com/Phala-Network/growth-program/assets/68858747/6e7ba1ad-0c19-45ba-b0b7-d6dad7c61c3c)
![14](https://github.com/Phala-Network/growth-program/assets/68858747/00a37576-10fc-4839-8eb3-38e3afc22614)
![15](https://github.com/Phala-Network/growth-program/assets/68858747/68cb0435-236f-4bf3-bbdd-86b7b47b2e00)
![16](https://github.com/Phala-Network/growth-program/assets/68858747/fcfcf5b2-9f34-4a6e-8728-a9b75387c02f)
![17](https://github.com/Phala-Network/growth-program/assets/68858747/57196c9a-7168-40f0-b5c1-1e283e6d0fce)
![18](https://github.com/Phala-Network/growth-program/assets/68858747/8ed6fbd9-0141-46c8-b6ee-487eb38a53ca)
![19](https://github.com/Phala-Network/growth-program/assets/68858747/0de3cfd2-72bd-4c62-93ff-8909f460f6e5)
![20](https://github.com/Phala-Network/growth-program/assets/68858747/cd01215a-4de5-475d-953d-0e5b4e843017)
![21](https://github.com/Phala-Network/growth-program/assets/68858747/753b4bd7-3ea2-41c4-b22f-78faee77cba9)
![22](https://github.com/Phala-Network/growth-program/assets/68858747/c70c964d-6c85-47b1-b472-c0e3e2eb39cd)
![23](https://github.com/Phala-Network/growth-program/assets/68858747/991fe8d4-3c63-46c2-8491-90e4adbf24d6)
![24](https://github.com/Phala-Network/growth-program/assets/68858747/eae6d5cf-a85f-4672-ba07-56c168f3c991)
![25](https://github.com/Phala-Network/growth-program/assets/68858747/dc81a5be-e85a-401b-9117-99399655d2e1)
![26](https://github.com/Phala-Network/growth-program/assets/68858747/fb1a80c3-4f5a-4d1c-ab53-436492af6390)
![27](https://github.com/Phala-Network/growth-program/assets/68858747/91149d14-8073-401b-b49f-be58fb5b2cc1)
![28](https://github.com/Phala-Network/growth-program/assets/68858747/4fd65322-79a2-4bd6-a694-695c40202030)
![29](https://github.com/Phala-Network/growth-program/assets/68858747/bbcbd353-8fad-48a2-92e1-01d6db95242d)
![30](https://github.com/Phala-Network/growth-program/assets/68858747/ebebfa25-6320-488f-ad34-d51aa6326641)
![31](https://github.com/Phala-Network/growth-program/assets/68858747/35aafc37-8f75-4ef5-8c2a-5600b1376629)
![32](https://github.com/Phala-Network/growth-program/assets/68858747/a6aa8ff2-e437-488d-acb9-93b62324f310)
![33](https://github.com/Phala-Network/growth-program/assets/68858747/24c752fb-ea57-44b2-8144-a9cdc64180fd)
![34](https://github.com/Phala-Network/growth-program/assets/68858747/7dd24966-3401-444f-b0a2-f9576f83479c)
![35](https://github.com/Phala-Network/growth-program/assets/68858747/001e27a9-bafa-47bc-b52e-c7e98b725523)
![36](https://github.com/Phala-Network/growth-program/assets/68858747/71d92261-0ca0-4e61-bfa7-4854fd756db1)
![37](https://github.com/Phala-Network/growth-program/assets/68858747/648ecba3-f38d-4d29-87eb-eb418e6dcf9d)
![38](https://github.com/Phala-Network/growth-program/assets/68858747/f8aa7d29-ba68-4449-8751-dd57f17f2979)
![39](https://github.com/Phala-Network/growth-program/assets/68858747/208a8b80-b277-4794-9783-790ecb7fd0e3)
![40](https://github.com/Phala-Network/growth-program/assets/68858747/7759fade-820b-4ee2-b03e-ffcf0c3f0223)
![41](https://github.com/Phala-Network/growth-program/assets/68858747/a6a1cf6c-4b10-44d9-8a49-e76761a8a491)
![42](https://github.com/Phala-Network/growth-program/assets/68858747/3790fbc1-9119-49a2-9b47-ef510a29f35f)
![43](https://github.com/Phala-Network/growth-program/assets/68858747/f7aa3287-ce1a-4301-8ee4-1fbeed5af3c3)
![44](https://github.com/Phala-Network/growth-program/assets/68858747/51e93e6c-f22a-4a42-9673-dc844f65c63d)
![45](https://github.com/Phala-Network/growth-program/assets/68858747/b7ed8bf0-b38f-4993-9450-fbf09d1e039d)
![46](https://github.com/Phala-Network/growth-program/assets/68858747/3b100b8a-2f17-48f2-8ed8-4d069ee76993)

**During May, I created many interesting Images, Banners, and Memes, which I later shared in the special channels of the Phala Network Discord and Telegram. I am very pleased that the Phala community highly appreciated my work and achievements this month. Next month, I want to make my work even more diverse and multifaceted in all aspects**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/26132410-4b81-4b95-b39f-1e49504bbd08)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/16b0ec83-a0de-4529-b1fd-5468848f094b)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/69723eb5-6d84-4ea5-b7c8-04f78b854363)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/d2029ac2-1ee9-45ce-bce4-5bd0a32b652d)
![15](https://github.com/Phala-Network/growth-program/assets/68858747/cdc29ad5-90fa-475d-91e2-2d4094839a81)
![19](https://github.com/Phala-Network/growth-program/assets/68858747/6d10e376-fb66-4260-a771-51ede74e790b)
![21](https://github.com/Phala-Network/growth-program/assets/68858747/b188a122-7ca2-48ec-807d-321d1a3cf603)
![25](https://github.com/Phala-Network/growth-program/assets/68858747/7ec92156-a913-4d30-8e1e-5963fbe97745)
![27](https://github.com/Phala-Network/growth-program/assets/68858747/1d6a6870-f66f-4d4f-a27b-6277aa078dfc)
![30](https://github.com/Phala-Network/growth-program/assets/68858747/57ef8388-34d9-4960-95a2-5bf6efb362c2)
![34](https://github.com/Phala-Network/growth-program/assets/68858747/8d806cfc-4d79-411e-936a-0e1e84c2266c)
![39](https://github.com/Phala-Network/growth-program/assets/68858747/63be6908-4d79-40b6-be1a-017aa04fdb4e)

**In May, I dedicated a lot of time to moderating the Phala Discord and Telegram chats. I maintained a constant online presence, monitoring all incoming messages in various chats and promptly responding to any spam, malicious, or fraudulent content. Thanks also to my fellow Ambassadors for their Support in Moderation**

![image_2024-06-09_19-09-12](https://github.com/Phala-Network/growth-program/assets/68858747/be0c1378-1211-46da-8a1f-3dbc2d4cb9cf)

### Phala Ukraine

**In May, together with InFace, we continued to actively work on developing the Ukrainian Phala Community on Discord and Twitter. Throughout the month, I consistently engaged with and maintained a friendly atmosphere in the Phala Ukraine Community. We aimed to increase the engagement of Ukrainian users in Phala on Twitter and Discord. I created, wrote, and published a lot of high quality and interesting content related to Phala. I supported and quoted all tweets from the Phala team and the official Twitter account. I have already prepared a detailed development plan for the Ukrainian community, which I will implement in June, and I am optimistic about its success. Below is a more detailed overview of Phala Ukraine statistics for May and the content I published**

![image_2024-06-09_19-32-12](https://github.com/Phala-Network/growth-program/assets/68858747/62ff2c7b-1954-4956-be71-5d89b42a2e4f)
![image_2024-06-09_19-32-28](https://github.com/Phala-Network/growth-program/assets/68858747/e487cbb7-7c9b-44c2-8620-e41b0760be65)
![image_2024-06-09_19-43-31](https://github.com/Phala-Network/growth-program/assets/68858747/5682b5a0-507d-4489-a355-a65853637679)
![image_2024-06-09_19-44-11](https://github.com/Phala-Network/growth-program/assets/68858747/906461e8-a439-4739-9757-a24b2dc39284)

### Analytics May 2024 stats:

![1](https://github.com/Phala-Network/growth-program/assets/68858747/d24f611d-6d08-4c38-a45b-3841cc260087)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/b16c61b6-940c-432f-88d6-01df142a417b)

**Below you will find the tweets I published, as well as those I created, along with other content that InFace and I shared. Additionally, you will see various quotes from other tweets by the Phala team and other Ambassadors**

![1](https://github.com/Phala-Network/growth-program/assets/68858747/42c629a0-ef38-4dd0-a6c0-2eb7f06fd638)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/6993c342-c689-42d0-9b86-1e25f74398b5)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/81a359e1-92a2-4101-b095-74dbfabda675)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/9da4c6e1-8b43-4122-864f-4bbd5392100d)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/09ed81cd-ab89-4972-8d14-326ddd22eeeb)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/a9b027ef-924f-4ea6-8dc5-fef51cd3a4fa)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/984f5374-4c33-4653-9581-6d687a81630a)
![8](https://github.com/Phala-Network/growth-program/assets/68858747/36623089-972c-4e64-a3c8-8b21be4f26f4)
![9](https://github.com/Phala-Network/growth-program/assets/68858747/08c8dbf2-e5b5-4677-87fe-2c0f2dca376f)
![10](https://github.com/Phala-Network/growth-program/assets/68858747/642a75c6-160e-4959-8354-dd8aa14a6f2e)
![11](https://github.com/Phala-Network/growth-program/assets/68858747/eec839a0-4a41-49ae-b82f-1ebe311ef2e2)
![12](https://github.com/Phala-Network/growth-program/assets/68858747/487e53d2-15c5-48b9-9b9d-634cfac7bb58)
![13](https://github.com/Phala-Network/growth-program/assets/68858747/66a417ca-b7f5-46d2-87ca-9f861e86c5e0)

**In May, I published several cool and engaging Tweets and Quotes related to Phala. The previous section covered additional Collaborative works and Quotes. Below, you will find the joint works created together with InFace (thanks to him for his support this month)**

1) https://x.com/PhalaUkraine/status/1785411546249675228
2) https://x.com/PhalaUkraine/status/1785413243197940137
3) https://x.com/PhalaUkraine/status/1785732908386320675
4) https://x.com/PhalaUkraine/status/1785919681909473445
5) https://x.com/PhalaUkraine/status/1787006814875472071
6) https://x.com/PhalaUkraine/status/1787733351832690989
7) https://x.com/PhalaUkraine/status/1788226372470542346
8) https://x.com/PhalaUkraine/status/1789705474897580227
9) https://x.com/PhalaUkraine/status/1789922531232592109
10) https://x.com/PhalaUkraine/status/1790442022383362221
11) https://x.com/PhalaUkraine/status/1791360258725597534
12) https://x.com/PhalaUkraine/status/1792104152400851066
13) https://x.com/PhalaUkraine/status/1792452453163577464
14) https://x.com/PhalaUkraine/status/1793908541700395212
15) https://x.com/PhalaUkraine/status/1794633824820687109
16) https://x.com/PhalaUkraine/status/1795683470842454525

### Supplementary Tasks:

The first additional task I completed was #TT - The Tutor: writing a guide in my own words. I wrote the third part of my step by step guide on which DEX platforms you can Buy, Sell, and Trade $PHA Tokens. This time, I decided to review a new platform called "Parallel Finance," which offers a wide variety of uses for the Phala Token on its platform. I believe the article turned out to be informative with many interesting components. Like the previous two articles in this series, this article contains information about the latest important updates in the Phala Ecosystem, as well as some brief comments from me and lots of useful information about various DEX platforms. I aimed to make the article as easy to read as possible while remaining informative. I would appreciate any feedback, thank you. I have at least one more similar article planned

**#TT - The Tutor: Write a how to tutorial in your own words**

1) https://medium.com/@MrDobby/part-3-practical-guide-for-the-phala-network-community-313bc93b2e8c

**#PM - I promoter Phala across social media platforms**

In May, I continued to actively engage with Phala across various social media platforms. I paid close attention to disseminating information about Phala on Twitter, Telegram, and Discord, as well as in various groups and chats of different projects. I actively developed my main profile on Twitter, wrote numerous successful posts, and shared a large number of Phala related Quotes on Twitter. Additionally, I actively developed the Phala Ukraine Community, regularly shared information about Phala team achievements, and interacted with the community

In May, I created and published a lot of content on our beloved platform Phaver, related to Phala Network. This platform is actively evolving every month and reaching new levels. Developing the Phala brand under such conditions is extremely successful. In May, I continued to create interesting and engaging content, which was well received by many users. I put in a lot of effort, and I am confident that my work did not go unnoticed. In this regard, I maintained my work pace and plan to create even more content in the coming month. Below, you will see all the statistics showing my work on social media platforms

**Publishing articles on Medium**

1) https://medium.com/@MrDobby/part-3-practical-guide-for-the-phala-network-community-313bc93b2e8c

**Publication on the channel Phala Ukraine**

<img width="1270" alt="5" src="https://github.com/Phala-Network/growth-program/assets/68858747/29c58b0d-6735-4a31-a567-3a58c4646ca9">

### Publishing on the Phaver platform

![12___](https://github.com/Phala-Network/growth-program/assets/68858747/3e5d9c10-fcf1-41ea-9c7c-fe2d808fea8c)
![8_](https://github.com/Phala-Network/growth-program/assets/68858747/a8f11321-1ff0-4821-a9a4-faede8d08268)
![9_](https://github.com/Phala-Network/growth-program/assets/68858747/854dc547-1540-423e-baaf-15baa27128c8)
![10_](https://github.com/Phala-Network/growth-program/assets/68858747/6bea24a0-ff15-470d-bc44-067ddb66ce56)
![11_](https://github.com/Phala-Network/growth-program/assets/68858747/cde9217a-d342-4fb7-94c5-91dbafe3d043)
![13_](https://github.com/Phala-Network/growth-program/assets/68858747/163238ad-54a8-46d5-b159-f122e279e1f4)
![1](https://github.com/Phala-Network/growth-program/assets/68858747/b2c0be47-81b4-4cc3-a839-9f0e8ca2b9f9)
![2](https://github.com/Phala-Network/growth-program/assets/68858747/7fa67c26-abe9-41b7-bd4a-6a9e5421bf0f)
![3](https://github.com/Phala-Network/growth-program/assets/68858747/020c080b-2a34-4ec5-909a-7f7823a96d19)
![4](https://github.com/Phala-Network/growth-program/assets/68858747/b8fda902-c338-4901-a222-8ced9b6a0a48)
![5](https://github.com/Phala-Network/growth-program/assets/68858747/c0a3b612-bffd-416b-af23-cb1e52d77ae8)
![6](https://github.com/Phala-Network/growth-program/assets/68858747/056c0497-0e10-4e08-92f0-dbef1ad194ad)
![7](https://github.com/Phala-Network/growth-program/assets/68858747/0d7cb93f-88c5-4207-9d7c-5de2b37b4a60)
![14](https://github.com/Phala-Network/growth-program/assets/68858747/bba40190-17b2-4191-af69-a93cd76c1e2b)
![15](https://github.com/Phala-Network/growth-program/assets/68858747/ceb08c56-9627-4253-9144-237358c5ebca)
![16](https://github.com/Phala-Network/growth-program/assets/68858747/6b416f12-2862-4ede-8aa8-9419c880dfad)

**#ART - I have created numerous informational infographics about the Phala ecosystem, its developments, technical products and recent achievements**

**Summing up the content work in May, it was successful. I continued to maintain a high level of productivity and created many cool and interesting pieces that were well received by a large number of users in the Phala Community. I spent a lot of time developing necessary designs and am very satisfied with the work done. In the coming month, I will continue to share new cool content. I supported Phala team work on topics such as Agent Wars, Red Pill, AI Agent, and AI Agent Contract, among others. I am confident that the next month will be even more successful**

![image_2024-04-28_23-16-37  problembo com](https://github.com/Phala-Network/growth-program/assets/68858747/1f480d30-158c-44b9-af66-638ec4c54cab)
![image_2024-04-28_23-35-46  problembo com](https://github.com/Phala-Network/growth-program/assets/68858747/e243d5e5-77db-4c26-b620-d773ec724ab4)
![image_2024-05-04_22-23-35  problembo com](https://github.com/Phala-Network/growth-program/assets/68858747/6f4496bb-7ea0-432a-b560-5a08eb226ae5)
![image_2024-05-04_22-58-57  problembo com](https://github.com/Phala-Network/growth-program/assets/68858747/3ea5d480-071f-4234-b51a-92179d7d8ece)
![image_2024-05-02_11-31-11-transformed (4)](https://github.com/Phala-Network/growth-program/assets/68858747/768143c3-4df1-4c83-ab37-e4873c465d83)
![image_2024-05-02_16-44-46  problembo com](https://github.com/Phala-Network/growth-program/assets/68858747/5a08fa44-38fc-4839-a6f8-57c840cfed24)
![image_2024-05-02_22-44-12  probl_lembo com](https://github.com/Phala-Network/growth-program/assets/68858747/bdfd1e79-6c66-4da6-8428-e834a33cd58b)
![image_2024-05-09_01-23-29  problembo com](https://github.com/Phala-Network/growth-program/assets/68858747/263a4d15-fce0-4ba5-aca3-ec237a3f1013)
![InShot_20240505_122932427](https://github.com/Phala-Network/growth-program/assets/68858747/272717d6-2a1a-4511-ae59-4f7cf937b555)
![image_2024-04-25_23-42-40  problembo com](https://github.com/Phala-Network/growth-program/assets/68858747/127b8b86-aa7a-4cdd-818e-256098ea0720)
![image_2024-04-26_01-42-00  problembo com](https://github.com/Phala-Network/growth-program/assets/68858747/c251c13e-0c18-4754-b16a-51aac9fe7723)
![Robot_cat_from](https://github.com/Phala-Network/growth-program/assets/68858747/3960f5c7-0b79-47e5-a4e7-c27cd5308a03)

**#ART - I have created many pictures and images related to Phala Network
My Twitter posts for May**

Throughout May, I created a lot of diverse, engaging content, which I then published on Twitter, Discord and other Social Media Platforms. Below, you will find all the links to my work, tweets, quotes and posts in May that I created for Phala Network. This month was as productive and successful as all the previous ones and I am very pleased with the amount of work done. I dedicated a lot of time to ensuring the quality of each piece. I aimed to bring a lot of creativity and my own uniqueness to each work. In the upcoming month, I plan to increase my work pace and bring even more creativity to my projects

1) https://x.com/Dima35109517/status/1785619511195873415
2) https://x.com/Dima35109517/status/1785975859314139270
3) https://x.com/Dima35109517/status/1786122400905449975
4) https://x.com/Dima35109517/status/1786867133348987314
5) https://x.com/Dima35109517/status/1787950317042028711
6) https://x.com/Dima35109517/status/1788211496930943134
7) https://x.com/Dima35109517/status/1788522063587598595
8) https://x.com/Dima35109517/status/1790039288169525388
9) https://x.com/Dima35109517/status/1795934931337515060
10) https://x.com/Dima35109517/status/1786318698136932381
11) https://x.com/Dima35109517/status/1786344818232225803
12) https://x.com/Dima35109517/status/1787222915139735812
13) https://x.com/Dima35109517/status/1787224958420025476
14) https://x.com/Dima35109517/status/1787484801072529602
15) https://x.com/Dima35109517/status/1787488223192649842
16) https://x.com/Dima35109517/status/1787491431893852632
17) https://x.com/Dima35109517/status/1787586202645799278
18) https://x.com/Dima35109517/status/1787587850432598102
19) https://x.com/Dima35109517/status/1788345976479948999
20) https://x.com/Dima35109517/status/1788349848434925574
21) https://x.com/Dima35109517/status/1788552134914363903
22) https://x.com/Dima35109517/status/1788556292669288744
23) https://x.com/Dima35109517/status/1788560129505284330
24) https://x.com/Dima35109517/status/1788674494996853153
25) https://x.com/Dima35109517/status/1788691447182426215
26) https://x.com/Dima35109517/status/1788696806785777836
27) https://x.com/Dima35109517/status/1789072499650544089
28) https://x.com/Dima35109517/status/1789078115936829780
29) https://x.com/Dima35109517/status/1789762381322547558
30) https://x.com/Dima35109517/status/1785644861770592521
31) https://x.com/Dima35109517/status/1785647559450431900
32) https://x.com/Dima35109517/status/1785654117995610295
33) https://x.com/Dima35109517/status/1785786075190862329
34) https://x.com/Dima35109517/status/1786031402498097430
35) https://x.com/Dima35109517/status/1786044301757006089
36) https://x.com/Dima35109517/status/1786049560382439503
37) https://x.com/Dima35109517/status/1786149243285114936
38) https://x.com/Dima35109517/status/1786317182860763300

My aim in this month was to generate maximum engagement and reach a broad audience. I am confident that in the upcoming month, I will surpass the amount of work I demonstrated in May. Throughout this month, I have shown genuine support for the Phala project and its community on social media. I actively helped my fellow ambassadors with their work, content creation and community engagement

### May 2024 Result:

Summarizing my report and all the work done for the Phala Network ecosystem in May, I can say just one thing – success, as usual. I finished this month on a high note. I am satisfied with the amount of work I completed and the contribution I made to the Phala project this month. The desire to improve my results and increase my influence in Phala motivates me for future successful endeavors. I am grateful to the Phala community and my fellow Ambassadors for their help and support in all aspects of my work, it means a lot to me. I am happy to be an integral part of such an extensive ecosystem as Phala Network, and I am delighted to contribute and bring constant value to the project every month. The next month will once again be one of the most successful. Summer is a time for rest, but not for me, for me, it is a time to become an even better version of myself and reach a whole new level of development to be among the best, and I am confident I will succeed. Thank you for reading my monthly report. I wish you all the best

I want to express my sincere gratitude to my fellow Ambassadors for their constant assistance, support and collaborative efforts in achieving success. You're the best - InFace / Cappex / Scarlet / Gabriel / Favour / Kamala / John / MoneyMantra

**Thank you for reading my report
Best regards
Dmitriy**

**Suggested Scores:**
**#CC:** 38/40
**#СМ:** 38/40
**#TT:** 5
**#PM:** 9
**Overall:** 90

**Comment by MaggiePhala** [comment]
Hey Ivakhnenko! I mean WOW! 

I can see you've put a lot of effort into promoting Phala and making contribution to the Phala community. Kudos to you! 

Just one suggestion for you - try to find local marketing resources (online communities such as TG groups, forums, etc.) to push out your AMAZING content. You've done a really a good job with content creation however the reach is low. If you can find ways to do that I think it would be perfect. 

Also the art you've created is fire. 

Cheers!
