### ISSUE TITLE
September Contributions 2022- Kamala Immaculate

### ISSUE THREAD

**Issue by KAMALAIMMACULATE** [Phala-Network/growth-program#44]
Name: Kamala Immaculate
Email: kamalaimmaculate@gmail.com
Telegram: Kamala Immaculate
Discord: Kamala Immaculate#5476
Twitter: @Immei256
PHA Address: 46KQkYs3uxsS8zxVGKK9BpdcaVt2vUaspA2Rn45mkmCehEjr
Basic Contribution of September: Ambassador

1. I created the African telegram group and managed it. Here is the link 
https://t.me/+qtaMWJoXhKYyNjM0
I had some issues with the group Analytics recordings. hopefully next month the information will be provided.

2. I hosted my first local community meetup with some university students in my area, we had 30 people people who attended.
https://drive.google.com/drive/u/0/folders/1-P-WE_NRqKf7jmJYBbZgsdAOuUOuc7gO

3. Designed some educative inforgraphics about Phala network and made tweet posts of them
https://twitter.com/immei256/status/1566290411274002434?s=21&t=3DKiDoomZbG54MuHFnJnBg

https://twitter.com/immei256/status/1566807346789203972?s=21&t=3DKiDoomZbG54MuHFnJnBg

https://twitter.com/immei256/status/1566408503840972801?s=21&t=3DKiDoomZbG54MuHFnJnBg

https://twitter.com/immei256/status/1567501758607269899?s=21&t=3DKiDoomZbG54MuHFnJnBg

https://twitter.com/immei256/status/1568543952545906691?s=21&t=3DKiDoomZbG54MuHFnJnBg

https://twitter.com/immei256/status/1569758253739028480?s=21&t=3DKiDoomZbG54MuHFnJnBg

https://twitter.com/immei256/status/1574751272300838913?s=21&t=3DKiDoomZbG54MuHFnJnBg

https://twitter.com/immei256/status/1569991912458797056?s=21&t=3DKiDoomZbG54MuHFnJnBg

https://twitter.com/immei256/status/1571044593512357890?s=21&t=3DKiDoomZbG54MuHFnJnBg

4.Tweet Activities.
![IMG_2806](https://user-images.githubusercontent.com/61009431/194648871-0a1dca41-ed6d-4c95-9105-b4ad6e4f6f0b.PNG)

![IMG_2804](https://user-images.githubusercontent.com/61009431/194648934-46b5c191-ab7b-4638-9fd4-fdaf7d17eb84.PNG)

![IMG_2805](https://user-images.githubusercontent.com/61009431/194648976-fa81c0d9-eb0f-4d30-986c-d16188bcac99.PNG)

![IMG_2802](https://user-images.githubusercontent.com/61009431/194649017-72fed0fe-68d7-40a5-bdb5-e27e76e3bdd2.PNG)

![IMG_2803](https://user-images.githubusercontent.com/61009431/194649145-c948d7be-39cb-400d-aee1-2da270288163.PNG)

![IMG_2805 (1)](https://user-images.githubusercontent.com/61009431/194649213-415fb1f1-dc71-44f6-8d35-850add13b428.PNG)

![IMG_2800](https://user-images.githubusercontent.com/61009431/194649282-bcef4ba8-7942-4da7-b327-a8b306d70e4a.PNG)

![IMG_2801](https://user-images.githubusercontent.com/61009431/194649329-5e9c2978-337c-44ee-9ede-e5cc9623e63d.PNG)

![IMG_2799](https://user-images.githubusercontent.com/61009431/194649371-c2061679-81c7-4631-bfc1-6532c1b1e4ab.PNG)

![IMG_2797](https://user-images.githubusercontent.com/61009431/194649445-24ed258b-ae81-4930-82a2-af4466a0b42a.PNG)

![IMG_2795](https://user-images.githubusercontent.com/61009431/194649477-62a9b867-3288-4c80-ad35-9b5414f59893.PNG)

![IMG_2794](https://user-images.githubusercontent.com/61009431/194649539-0ca39257-d94d-4a61-a3f3-2a6ea0b94a46.PNG)

![IMG_2798](https://user-images.githubusercontent.com/61009431/194649591-9638fc9b-be6e-43cc-8aa3-dd1861371e84.PNG)

![IMG_2796](https://user-images.githubusercontent.com/61009431/194649630-ee6bcf49-5009-43c8-b960-20abc0a74f84.PNG)

Thank you.
Kamala Immaculate

**Comment by luciaaaa4455** [comment]
The event seems good, it's better if you can spread some pic of it and any recap in social media
