### ISSUE TITLE
July 2024 Contribution by Captain jack 

### ISSUE THREAD

**Issue by Captainjack122** [Phala-Network/growth-program#447]
Title: July 2024 contribution

1. PERSONAL INFORMATION 
 
Amb rank: Candidate Ambassador 

Discord user : captainjack #3452 

Twitter URL : https://x.com/captainjack125?t=3XFxb_uS1rlW0Sy5SHHGzA&s=09

Pha wallet Addres : 3ziwT5BL7iwUj6NonSX7jyJm2mAeXWnJPjqP3GmSagPqGSXc

Department: Content creation & community management.

2. DEPARTMENT
The month of July was an incredible month of progress for me, being my first month started working with phala Network, which has been an amazing month for the project with many huge milestones reached, strategic partnership and high development.

I spread information about phala networks and increased the project visibility and awareness through the amazing & quality contents and articles I created that reached thousands of people, I also partnered with some KOL in promoting phala's Network whereby they retweet every of my post related to phala's Network only and also I do comment, like and retweet phala's Network tweets, I make sure I reply any one asking any questions related to phala's Network under comment section of any post I found and all my post about phala's Network gained a good visibility, I was very active consistently on Twitter and discord and I also make sure I helped each Ambassadors by engaging some of their contents and share ideas together on how we can contribute more to the phala Network.

Threads/ contents created ✨️ 

1. https://x.com/captainjack125/status/1813273546514170178?t=tEZlKaRr74iMOckvjEvs1w&s=19
2. https://x.com/captainjack125/status/1813632438582817092?t=CciUA_usdnBXiTKcCHbryw&s=19
3. https://x.com/captainjack125/status/1814186148626936104?t=Z6PycsCoXjM4UfxIYt15-Q&s=19
4. https://x.com/captainjack125/status/1815099476945797558?t=2YdzNDdycGKapAmD0e9nCQ&s=19
5. https://x.com/captainjack125/status/1815272645476102170?t=Crv6w_vZcS4X_AjPOyEszA&s=19
6. https://x.com/captainjack125/status/1815803758271684633?t=ejq3jQfNpKRIw32eJsg-og&s=19
7. https://x.com/captainjack125/status/1816357001464541542?t=usioh_X3nUkir4jFsrqfUw&s=19
8. https://x.com/captainjack125/status/1817616298123182456?t=oPoy3gxRER86gweHBfzKOw&s=19
9. https://x.com/captainjack125/status/1818168459504517454?t=fjBMlc7pfjmz1M4TJB88XA&s=19
10. 
https://x.com/captainjack125/status/1819253289675833658?t=GCWqlab0vTd1RyxH8wAAMA&s=19

Twitter Analytics 
![Screenshot_20240804_065156_Mises](https://github.com/user-attachments/assets/2a845b9a-ddbb-4866-9ba0-7b21c0ee8cde)

![Screenshot_20240804_065319_Mises](https://github.com/user-attachments/assets/855c49e2-4495-4dd0-9114-be20acf316e1)

![Screenshot_20240804_070144_Mises](https://github.com/user-attachments/assets/696fb6f0-ff36-4cd6-bb96-08f31782388b)

Community 

I tried to engage in the community most especially phala's discord channel and phala's official X handle, I tried to interact and answer questions related to phala's Network, i answered questions related to Agent wars on X and also about the Ambassadorship program.

I reported scammer posted a phishing links in the general discord thrice whereby he posted the phising link to hack people wallet, I reported to the head of Ambassador (Scalet ) he deleted the message and banned the scammer, second time samething happened I reported again before he grant me access to be able to delete such message like that and to be able to ban the scammer.

![Screenshot_20240804_070734_Discord](https://github.com/user-attachments/assets/8e3ff5dd-023f-4cc1-b5e6-df9c083ae32e)

![Screenshot_20240804_070725_Discord](https://github.com/user-attachments/assets/e0a2b4f7-c163-4ebb-a76c-23eb3e23687a)

![Screenshot_20240804_070710_Discord](https://github.com/user-attachments/assets/846e6d13-7f63-4a18-9414-8f0dc8ebae64)

I attended about 4 different spaces in the month of july organised by phala's Network and gain more knowledge about #TEE & #ZKP and the likes 

![Screenshot_20240804_070744_Discord](https://github.com/user-attachments/assets/57028824-7e2c-4266-a752-86e2c17da342)

**Comment by MaggiePhala** [comment]
Hey Captain Jack,

Really impressed with your active twitter engagement with your followers. For Community Management, I encourage you to improve this by translating content into your native language (German). Let me know if you needed anything from me! My DMs are always open! 

Best,
Maggie
