### ISSUE TITLE
July 2024 Contributions - Favour 

### ISSUE THREAD

**Issue by BBoss01** [Phala-Network/growth-program#451]
Amb Rank : Ambassador
Discord username  : favour_cy#5138
Telegram username : @solomonfav 
Twitter Link : https://twitter.com/official_bles1?t=eR-KQW9NjmPi7pCNo7ziLg&s=09
PHA address : 41dNB3qCWz1m4b874815wYnthsbSUvmKUws6624wRrjX4tnL
Department : CC, MK, CM

**CONTENT CREATION**

Articles - 
I created four articles about Phala Network

• Integration of Decentralized AI systems with Blockchain technology 
https://medium.com/@boyesolomon8/integration-of-decentralized-ai-systems-with-blockchain-technology-58efa0f64dcd

• The basics of coprocessors in Blockchain 
https://medium.com/@boyesolomon8/the-basics-of-coprocessors-in-blockchain-1ca3bb0a0320

• Understanding multi agent systems 
https://medium.com/@boyesolomon8/understanding-multi-agent-systems-a598f09dbdec

• Powering DePIN revolution with Phala Network 
https://medium.com/@boyesolomon8/powering-depin-revolution-with-phala-network-b17509e7864e

![Screenshot_20240804_123753.jpg](https://github.com/user-attachments/assets/577e701f-6484-46fa-ad85-e69c9c6d0d2f)

![Screenshot_20240804_123740.jpg](https://github.com/user-attachments/assets/81df3ff5-622d-4a1f-b034-03ce07532a59)

![Screenshot_20240804_123720.jpg](https://github.com/user-attachments/assets/27108874-7e08-474d-b35b-32f7857859dc)

![Screenshot_20240804_123713.jpg](https://github.com/user-attachments/assets/c610b4e4-cf0a-45e3-b689-e8d68be8b103)

TT - 
I developed a "Getting Started with Redpill AI" guide, reviewed by Scarlet and published on the Phala African Medium page by Kamala.

https://medium.com/@phalaafricacommunity/getting-started-with-redpill-ai-036d198d1668

Video -
I created two YouTube videos about Phala Network.

Unlocking trust in AI with Blockchain and TEE https://youtu.be/h4ojQajU_PM?si=U0b3eI1YFHGi4ZNU

The future of decentralized intelligence with Phala Network 
https://youtu.be/rZ6ZBxSfw5w?si=rRaFO2tphn0lpJj-

![Screenshot_20240804_123836.jpg](https://github.com/user-attachments/assets/9cbc2bc3-f779-4b79-a096-8eeefb537703)

![Screenshot_20240804_123826.jpg](https://github.com/user-attachments/assets/31b12610-9416-4da6-8482-acb87a377fc1)

Social media Posts : I actively promoted Phala Network on X, LinkedIn, CMC, and within Polkadot $ Kusama community to increase community engagement and network growth. 

X - I created educational threads, short and long posts on X, engaging with both global and local Phala accounts through reposting, liking, and quote posting. I also amplified content from fellow ambassadors.

X posts Link -
https://x.com/search?q=from%3A%40official_bles1%20Phala%20Network&t=l66LR0TDyke3_8kUAVh1iw&s=09

https://x.com/search?q=from%3A%40official_bles1%20Agent%20Wars&t=5StH3oodDYDHOh0_dUkyHg&s=09

https://x.com/search?q=from%3A%40official_bles1%20RedPill%20AI&t=r8iPJth2w263tdJ0-xeqow&s=09
![Screenshot_20240804_125347.jpg](https://github.com/user-attachments/assets/ae7a5ff6-f80d-43f3-820d-11f0bd6e8aa5)

![Screenshot_20240804_125342.jpg](https://github.com/user-attachments/assets/1356a3e3-034f-46ea-bf6b-2badbbc4e2da)

LinkedIn - I continued publishing long-form posts about Phala Network on LinkedIn, tagging the official Phala account for increased visibility.

LinkedIn Posts -
https://www.linkedin.com/posts/favour-solomon-99b430236_ai-blockchain-base-activity-7225082316044328961-K32a

https://www.linkedin.com/posts/favour-solomon-99b430236_ai-web3-blockchain-activity-7224010271852232705-PIy0

https://www.linkedin.com/posts/favour-solomon-99b430236_ai-web3-blockchain-activity-7224008780697526272-PmjZ

https://www.linkedin.com/posts/favour-solomon-99b430236_web3-polkadot-hackathon-activity-7221823372148547585-zu7h

https://www.linkedin.com/posts/favour-solomon-99b430236_ai-tee-web3-activity-7221822026141827072-Dmwn

https://www.linkedin.com/posts/favour-solomon-99b430236_ai-web3-eth-activity-7219979119806074880-OOTm

https://www.linkedin.com/posts/favour-solomon-99b430236_web3-ai-aiagents-activity-7219395490411343874-zguG

https://www.linkedin.com/posts/favour-solomon-99b430236_aiagents-ai-web3-activity-7218969468553617409-1na7

https://www.linkedin.com/posts/favour-solomon-99b430236_web3-ai-aiagents-activity-7215704939124162560-AKQ8

https://www.linkedin.com/posts/favour-solomon-99b430236_blockchain-defi-web3-activity-7215697983873421312-IPxg

CMC- I shared informative short posts on CMC, incorporating links to the Phala Network website and X account to raise awareness. 

CMC Posts - 

https://coinmarketcap.com/community/share/post/337728157

https://coinmarketcap.com/community/share/post/337923929

https://coinmarketcap.com/community/share/post/338027303

https://coinmarketcap.com/community/share/post/338432627

https://coinmarketcap.com/community/share/post/338432615

https://coinmarketcap.com/community/share/post/338261338

https://coinmarketcap.com/community/share/post/338194314

https://coinmarketcap.com/community/share/post/338062558

https://coinmarketcap.com/community/share/post/338025882

https://coinmarketcap.com/community/share/post/337955235

https://coinmarketcap.com/community/share/post/337957101

https://coinmarketcap.com/community/share/post/337922678

https://coinmarketcap.com/community/share/post/337906251

https://coinmarketcap.com/community/share/post/337901970

https://coinmarketcap.com/community/share/post/337903058

https://coinmarketcap.com/community/share/post/337729151

Total impressions - 11,800

Polkadot and Kusama discord communities - I promoted Phala Network within the Polkadot and Kusama Discord communities by sharing relevant content from Phala Network's X account. 

![Screenshot_20240804_123310.jpg](https://github.com/user-attachments/assets/68e3d599-c748-47f0-ba02-25198093c381)

![Screenshot_20240804_123305.jpg](https://github.com/user-attachments/assets/7539568f-13fa-49fd-935b-f4781d9ffbd8)

![Screenshot_20240804_123258.jpg](https://github.com/user-attachments/assets/a2549391-8d31-47fc-9827-12764df08079)

![Screenshot_20240804_123216.jpg](https://github.com/user-attachments/assets/1117ff88-fcb2-49ea-9fd4-35b8e85a6aaf)

![Screenshot_20240804_123207.jpg](https://github.com/user-attachments/assets/717ce4d2-3eb7-449c-bd3a-08cf16e6753a)

![Screenshot_20240804_123200.jpg](https://github.com/user-attachments/assets/45a86944-3788-4670-a8ae-661f5797c3b5)

![Screenshot_20240804_123145.jpg](https://github.com/user-attachments/assets/c5a93369-63d7-4844-92d8-88b709ba2ce2)

Warpcast - Expanded Phala Network's presence on Warpcast by creating and sharing content, while actively exploring strategies for greater engagement on the platform.

Warpcast Posts -

https://warpcast.com/favour01/0x481201cd

https://warpcast.com/favour01/0x47ae6644

https://warpcast.com/favour01/0x70b98e19

https://warpcast.com/favour01/0xac8f1c82

https://warpcast.com/favour01/0xbb86c506

https://warpcast.com/favour01/0x4fd2c5c6

ART 
I Created and shared some infographics, banners and gifs about Phala Network
![Blue Gradient Company Business Profile Presentation_20240706_202205_0000.jpg](https://github.com/user-attachments/assets/3aabceba-d47b-4db1-ac2c-43bc1230363d)

![Blue Gradient Company Business Profile Presentation_20240707_134143_0000.jpg](https://github.com/user-attachments/assets/d77fc060-df44-43de-b934-6f16102a393b)

![Blue Gradient Company Business Profile Presentation_20240712_190812_0000.jpg](https://github.com/user-attachments/assets/b88ba94b-8fc0-43cd-8d03-c8000ab4323c)

![Blue Gradient Company Business Profile Presentation_20240712_191646_0000.jpg](https://github.com/user-attachments/assets/5f34e204-9207-4c48-add7-9ca0cc25f8b1)

![Blue Gradient Company Business Profile Presentation_20240712_193219_0000.jpg](https://github.com/user-attachments/assets/345f0a2b-b338-4cb6-8beb-7b5776c3d246)

![Blue Gradient Company Business Profile Presentation_20240712_194051_0000.jpg](https://github.com/user-attachments/assets/a925b127-a70a-43c4-91a1-a8e11aef277e)

![Blue Gradient Company Business Profile Presentation_20240712_194905_0000.jpg](https://github.com/user-attachments/assets/55164209-4a89-4853-8304-200585eeb416)

![Blue Gradient Company Business Profile Presentation_20240712_200712_0000.jpg](https://github.com/user-attachments/assets/b73b846c-736f-48de-a716-b117dec125f9)

![Blue Gradient Company Business Profile Presentation_20240715_144345_0000.jpg](https://github.com/user-attachments/assets/cc6116cf-e625-425d-9ef1-b29b8f0a3170)

![Blue Gradient Company Business Profile Presentation_20240716_131542_0000.jpg](https://github.com/user-attachments/assets/db94eac1-b40d-4147-a36d-8fc8ce56f59f)

![Blue Gradient Company Business Profile Presentation_20240717_183620_0000.jpg](https://github.com/user-attachments/assets/40a4afd3-c560-46ad-9837-a6bd2e27fa26)

![Blue Gradient Company Business Profile Presentation_20240722_101735_0000.jpg](https://github.com/user-attachments/assets/6f87efe6-ac02-4222-80d3-b8cd1f7899c2)

![Blue Gradient Company Business Profile Presentation_20240728_131053_0000.jpg](https://github.com/user-attachments/assets/0b8c2dfc-c5a7-435f-9b3d-138e9aca8b5d)

![Blue Gradient Company Business Profile Presentation_20240729_115311_0000.jpg](https://github.com/user-attachments/assets/8aed01fc-69cf-4433-9e43-20c44cff87b1)

![Blue Gradient Company Business Profile Presentation_20240801_175226_0000.jpg](https://github.com/user-attachments/assets/58e588fd-0d1b-4611-9662-06a7095dbf43)

![Blue Gradient Company Business Profile Presentation_20240801_175709_0000.jpg](https://github.com/user-attachments/assets/52adcdea-81dd-4278-8394-c107e8210a04)
![pha copro 02](https://github.com/user-attachments/assets/cbd2a8de-8f8b-43a8-bcb1-25f62e51dd00)
![pha copro 01](https://github.com/user-attachments/assets/dccd625a-8074-49a5-9e74-6e78712f6875)
![pha int](https://github.com/user-attachments/assets/e00d49f3-799c-4867-a7f3-b36bf21e792d)
![ma 02](https://github.com/user-attachments/assets/91e910cb-1822-4ebc-a4b3-7e7cab13de03)
![ma 01](https://github.com/user-attachments/assets/e9f46d01-44f2-47e9-9316-7b40e7054711)
![depin p 02](https://github.com/user-attachments/assets/3a1daa1f-c167-4d9b-8295-4744b22075c4)
![depin p 01](https://github.com/user-attachments/assets/b7eaa555-55a8-4a54-bbd4-1789f5c8283e)

Good Points:

- I significantly improved the quality and quantity of content across social media platforms.
- I'm exploring Warpcast to further enhance my reach. 

How to improve 
-  I will continue to enhance the quality and quantity of content created and collaborate more effectively with fellow ambassadors to foster community growth.

**MARKETING**

Phala African community call -
I participated as a panelist in the recent African community call, following an agenda set by Bekka. I answered pre-submitted questions and shared resources about Agent Wars. The call was a success, attracting new attendees and reaching 134 people.
![Screenshot_20240804_121024.jpg](https://github.com/user-attachments/assets/b0ade747-d67f-462a-8103-0c3829635a14)

Phala Network Ambassador X Metapool Ambassador -  
I collaborated with a Metapool ambassador to host a Twitter Space, introducing Phala Network and its ambassador program to their audience. Our Lead ambassador Scarlet, reviewed the pre-call request and post-call report, and provided valuable feedback for improvement. 

Event report - https://docs.google.com/document/d/1FT-qgIvmwySsGt1vacjrPMVAjg_iJjss0KStI38_3JM/edit?usp=drivesdk

![Screenshot_20240804_123614.jpg](https://github.com/user-attachments/assets/435dbac4-749b-4f62-b08d-0ab5f6d7d7f3)

![Screenshot_20240804_123621.jpg](https://github.com/user-attachments/assets/b33d8e48-33d4-4dd6-a16f-08027d03f659)

Potential Partnerships: 
Following the Twitter Space, Metapool ambassador expressed interest in a partnership. I provided them with introductory documentation about Phala Network to facilitate their research. 

Doc Link: https://docs.google.com/document/d/1_5XhHwuanNapPGs7tudpBTVQ1bFIZUJPwV6D2D0a-hI/edit?usp=drivesdk

Tectum:
I received a partnership request from Tectum ambassador and informed Our lead ambassador Scarlet. We are collaboratively developing a proposal, following her guidance.

Doc Link: https://docs.google.com/document/d/1Sb6n6R9biJBMCggKwtu30oxvHHaKkmOWlVtW4pPgCfA/edit?usp=drivesdk
( Currently working on the corrections pointed out by Scarlet)

"Web3 Hub and Network" Discord Channel:
To foster collaboration and event planning amongst Web3 ambassadors, I created a dedicated Discord channel. This will facilitate promoting Phala Network and organizing both online and offline events. Currently, the channel has 8 members and is open for further participation.

![Screenshot_20240804_125901.jpg](https://github.com/user-attachments/assets/334f7040-1f46-404f-a357-9024f21019e4)

Good Points:

- Our community call saw a great turnout with many new faces.
- The X space with the Metapool ambassador generated positive interest in Phala Network, particularly around Agent Wars and the ambassador program.
- Lead ambassador, Scarlet, provided valuable tips for improvement which I am implementing.

Bad Point:

Technical difficulties during the Metapool ambassador call prevented direct link sharing in the comments. While I shared links under my repost and directly with the ambassador, I was unable to track community member influx from the call.

How to improve:

- Following the guide created by our lead ambassador, before, during and after events.

**COMMUNITY MANAGEMENT**

I actively participated in the Phala Africa Telegram and global Discord communities and on Phala World, providing valuable information, answering Questions, welcoming new members, and moderating spam and spammers.

![Screenshot_20240804_125231.jpg](https://github.com/user-attachments/assets/5bd4d8fe-f2b9-4736-89a1-21a078299f09)

![Screenshot_20240804_123020.jpg](https://github.com/user-attachments/assets/868cf475-1814-4615-8d45-8cb508791fb1)

![Screenshot_20240804_122953.jpg](https://github.com/user-attachments/assets/5e89d03e-1a60-4a79-a870-b7c521ab0cfd)

![Screenshot_20240804_122924.jpg](https://github.com/user-attachments/assets/3a46d2a6-deb0-45ea-91d8-6c4d114318a5)

![Screenshot_20240804_122918.jpg](https://github.com/user-attachments/assets/b648f30e-3f28-498c-bf9e-9b5845e4704d)

![Screenshot_20240804_122912.jpg](https://github.com/user-attachments/assets/b2b186f0-1fb0-43eb-8e0a-21dc377dce6f)

![Screenshot_20240804_122827.jpg](https://github.com/user-attachments/assets/03b09f46-649a-48dd-b71c-dad9b3396f7a)

![Screenshot_20240804_122755.jpg](https://github.com/user-attachments/assets/1140b4f2-4aad-4569-af23-33cee652cee0)

![Screenshot_20240804_122724.jpg](https://github.com/user-attachments/assets/736dba2a-338d-4cad-b09d-d18af5fefcee)

![Screenshot_20240804_122717.jpg](https://github.com/user-attachments/assets/e1fd3a00-6555-4dfd-adea-64308f17273c)

![Screenshot_20240804_122710.jpg](https://github.com/user-attachments/assets/09db98b3-d502-4c5d-8cbc-2ebe71f9975e)

![Screenshot_20240804_122702.jpg](https://github.com/user-attachments/assets/799379e6-856a-49b6-a739-582bf61c4362)

![Screenshot_20240804_122657.jpg](https://github.com/user-attachments/assets/1da6ffab-f0fb-4060-b07b-c440b1c9440c)

![Screenshot_20240804_122649.jpg](https://github.com/user-attachments/assets/6ef1e295-c5e9-45a2-a138-63de814a9102)

![Screenshot_20240804_122636.jpg](https://github.com/user-attachments/assets/48269378-558b-40fc-9c16-9084340a57e2)

![Screenshot_20240804_122643.jpg](https://github.com/user-attachments/assets/3a99bca7-d4b0-4d3d-86a0-2a51a22b5a51)

Good Points: 

- The Phala African community experienced increased positive engagement. I have also improved my engagement in the local and global communities.

How to Improve: 

- I will continue to improve my engagement within the community and extend my engagement to Redpill discord channel.

Suggested Scores 

CC - 40/40
MK - 30/40
CM - 30/40
Total - 100

**CLOSING COMMENT**

My performance significantly improved in July. I increased engagement in Phala communities, produced higher quality content in greater volume, and explored new communities. I began learning about business development with guidance from our lead ambassador, Scarlet. My collaboration with fellow ambassadors also improved through quote Posts and cross-platform promotion of their events. I actively participated in departmental channels and am currently on track with tasks assigned by our lead. Going forward, I aim to further improve collaboration, participate in more events, and continue my growth trajectory. 

THANK YOU.

**Comment by MaggiePhala** [comment]
Hey Favour! 

You have a constant presence and performance of basic community moderation, however there might be an excessive "spam" of emoji in the welcome channel (discord). In order to score higher in CM please be more present on Phala's official telegram channel, not only on the African channel.

Feel free to DM me if you needed anything! Cheers. 

Maggie

**Comment by BBoss01** [comment]
Hello Maggie, I appreciate the feedback and will incorporate it.
