### ISSUE TITLE
September 2022 Contributions - {102j#2259}

### ISSUE THREAD

**Issue by ZunkCii** [Phala-Network/growth-program#46]
Telegram : [[치포](https://t.me/J102J)](https://t.me/J102J)
Discord : 102j#2259
PHA Address : 3zkfLRrjyCy33f9xTNHDwAEjdjJknx4W6ZQ6GVTk5ffJcpck

My Mandatory (Basic) Contributions of September:
ambassador

CM(Community Management)
Phala Korean Channel link: https://t.me/phalakorean
Have I participated in Telegram Channel Moderation (choose)? Yes

Combot Link : https://combot.org/c/1340032853/a?start=2022-09-01&end=2022-09-30
![스크린샷 2022-10-09 오후 8 42 29](https://user-images.githubusercontent.com/96286632/194754991-3502d731-35ea-4bae-ae52-a02a86e7ccb5.png)
![스크린샷 2022-10-09 오후 8 43 00](https://user-images.githubusercontent.com/96286632/194755004-d903c51b-cbda-4d29-837f-c07fd9cefe22.png)
![스크린샷 2022-10-09 오후 8 44 18](https://user-images.githubusercontent.com/96286632/194755054-6c8ff7b0-677b-4084-aaf8-eb25365c2857.png)

**Comments : 

- How many people increased or decreased? Why?
The number of users remained constant during the month
- What was good?
The miner is running without any problems.
- How can I improve this next month?
Like in August, I tweet and help with errors, and it doesn't seem to be any different.

**2. VSM(Twitter Virals)**Twitter as Official Ambassador : https://twitter.com/ZunkCii
Analytic : https://analytics.twitter.com/user/ZunkCii/tweets

**Comments :**
September seems to be an ice age for both the crypto market and the phala. Therefore, it is difficult for new people to come in, and it seems that existing people only appear when there is a problem while mining.

**1. CC(Contents Creation)**
https://blog.naver.com/102j102j/222869179771

**Comment by luciaaaa4455** [comment]
Please paste the VSM data image from the next time, thanks!
