### ISSUE TITLE
Title: August 2024 Contribution - {Captain jack#3452}  

### ISSUE THREAD

**Issue by Captainjack122** [Phala-Network/growth-program#466]
1. Personal info:

- Amb rank: Candidate Ambassador 
- Discord Username: captainjack #3452 
- Twitter URL: https://x.com/captainjack125?t=BepkLV4AEnkZvQyhuApjrw&s=09
- PHA Wallet Address: 3zqxbHy8FYEgPJzerRGGo1DSMtkQkWMT1xmi6zjkVq7CVBJB
- 
- Departments: CC/CM

DEPARTMENT CM [COMMUNITY MANAGEMENT]

The month of August was a remarkable month for me where be I take into consideration during the last month [July] on how I can make the month of August more better which I did.

I was able to improve myself in this department whereby I was very active on phala media most especially the Phala's TG account, I'm active days and nights which I detect alots of scammers posting phishing links that can drain people wallets, most especially newbies, they can easily click on those links and there wallet can get drained easily.

There is a particularly strategy I do use, anytime I see a user that did personal promotion or posted a scam link, I warn the person and delete the message, but if the same person repeated such act again, I consider banning the user, I can confidently say I have warned over 30 users during the month of August and banned around 6-8 users that consistently posting a phising links, there are some I do and feel like taking the screenshot of everything doesn't necessarily needed, and I do take some screenshots too.

I answered some questions asked by members  related to phala's Network.

Below are some of the screenshot for CM 👇👇👇👇👇👇

![Screenshot_20240831_220144_Telegram](https://github.com/user-attachments/assets/867066ea-ff56-4e5b-933e-3d9e93a382ca)

![Screenshot_20240831_135655_Telegram](https://github.com/user-attachments/assets/dfc2c842-8315-4138-aeb1-ac5a46838fc2)

![Screenshot_20240831_122835_Telegram](https://github.com/user-attachments/assets/da210da2-035d-4408-b20e-0a57b0dfc28d)

![Screenshot_20240829_012954_Telegram](https://github.com/user-attachments/assets/a94a8e26-e40b-49db-a132-1329bcdc3dd6)

![Screenshot_20240828_045508_Telegram](https://github.com/user-attachments/assets/4827025a-9f78-4877-b95f-4ccf3dbfadce)

![Screenshot_20240827_211956_Telegram](https://github.com/user-attachments/assets/0f306e01-958f-4e39-a9f2-61e12daf15ea)

![Screenshot_20240827_040646_Telegram](https://github.com/user-attachments/assets/d27a9102-a6c0-42a1-9969-0928be80f5f2)

![Screenshot_20240826_214506_Telegram](https://github.com/user-attachments/assets/0a5a12fa-13e7-4c99-bd39-9ab470ead264)

![Screenshot_20240824_221346_Telegram](https://github.com/user-attachments/assets/c66ff530-a227-43ab-af10-db19d627bbad)

![Screenshot_20240824_221356_Telegram](https://github.com/user-attachments/assets/2a2dd7d2-0d51-4bcb-a1f4-2fbc73afd2e2)

![Screenshot_20240824_195619_Telegram](https://github.com/user-attachments/assets/f894e922-9be7-400d-82ff-bbcb19b835a1)
![Screenshot_20240824_195608_Telegram](https://github.com/user-attachments/assets/6099bb2e-4a47-4c35-b96f-d5797d65e4bf)
![Screenshot_20240824_195541_Telegram](https://github.com/user-attachments/assets/0cf4139e-a9b6-4a7f-b7b9-03fab6feffc7)
![Screenshot_20240824_195042_Telegram](https://github.com/user-attachments/assets/9f77b4bd-cbe5-4b9d-9bec-f0db466342f7)

DEPARTMENT: CC - CONTENT CREATION. 

Also I tried my possible best to improve myself in this department, I partnered with some random KOLs whereas they retweet my post related to phala's Network mostly, creating more awareness and visibility for phala's Network. 

I tried my best in seeking opinion from some of the Phala's senior Ambassadors, my regional lead and some random community member about how they see my contents so far, if there's anything I need to work on to improve my creativity, whereby I merged their ideals together to improve my creativity.

Below are the contents I made this month .

1. https://x.com/captainjack125/status/1820706732122747198?t=Ks_72GSgJ0A_TEnG5Fu0pw&s=19

2. https://x.com/captainjack125/status/1821424389641863251?t=A3yzx6auZO_m6HQXeXUp3w&s=19

3. https://x.com/captainjack125/status/1822157763226591649?t=Z52YOu1SmV6V71lJmOczQg&s=19

4. https://x.com/captainjack125/status/1823064372303770004?t=Ag1CK97BustyRtkSlIOEDA&s=19

5. https://x.com/captainjack125/status/1823244619863175554?t=RZ05LKj1j_7iEWALZs6H9Q&s=19

6. https://x.com/captainjack125/status/1824327405537759369?t=fDeQ4A4KrZe0vRL0fHGbsg&s=19

7. https://x.com/captainjack125/status/1825961427468792308?t=iLk8Col857L0sDh--mmKdw&s=19

8. https://x.com/captainjack125/status/1826326477996003635?t=D-KmBQddKwHEPvNfZcYTtA&s=19

9. https://x.com/captainjack125/status/1827403738178314422?t=H4gUwwxUmdj88s0YTzFY1g&s=19

10. https://x.com/captainjack125/status/1827404060066230531?t=vSZI-oV1aTfsBKZZG2iOnQ&s=19

Suggested score 

#CM (Community Management ) - 40/40
#CC (Content Creation ) - 40/40

**Comment by MaggiePhala** [comment]
Hey Jack. 

Thanks for your contribution in August. 

Just a heads up - CM score will be significantly improved if you can translate important Phala news & updates into German. Please note CM tasks include community moderation & translation. 

Can't wait to see you create content on Phala's GPU TEE. Let me know if you have any questions about TEE. 

Maggie
