### ISSUE TITLE
August 2024 Contributions - xcRom1

### ISSUE THREAD

**Issue by xcRom1** [Phala-Network/growth-program#479]
1. Personal info:

- Amb rank: Ambassador
- Discord Username: rom1.dot
- Telegram: https://t.me/rom1_dot
- Twitter URL: https://x.com/rom1_dot
- PHA Wallet Address: 45y4GFYueXCswuXnrMo6mmUNYNF4853EuxV9UkNTEseK6p3q
- Departments: [1]/[2]/[3]
 
2. Departments:
 
· CM:
- List all completed tasks: Management of the tweeter account for the French-speaking community
 - 29x tweets
 - 4x Translation
- You can find the tweet and translations report in the August 2024 tab. [Here](https://docs.google.com/spreadsheets/d/1BilxiwQeKo0d-h_l0FmvP1t6QUYwwpE0BiKNMgY2ir8/edit?usp=sharing)

![image](https://github.com/user-attachments/assets/8eccb106-0410-4dc0-90ad-098bc84a6ecc)

I translated 4 articles totalling 4009 words : 
- [Annonce de Partenariat : Phala Apporte le Calcul TEE Vérifiable à Morpheus et Lumerin](https://medium.com/phala-fran%C3%A7ais/annonce-de-partenariat-phala-apporte-le-calcul-tee-v%C3%A9rifiable-%C3%A0-morpheus-et-lumerin-fe8f35613326)
- [Hyperbolic et Phala annoncent un partenariat stratégique pour faire progresser l’informatique IA sécurisée et vérifiable.](https://medium.com/phala-fran%C3%A7ais/hyperbolic-et-phala-annoncent-un-partenariat-strat%C3%A9gique-pour-faire-progresser-linformatique-ia-9e362159c816)
- [Annonce du partenariat stratégique entre Phala Network et Aligned Layer.](https://medium.com/phala-fran%C3%A7ais/annonce-du-partenariat-strat%C3%A9gique-entre-phala-network-et-aligned-layer-fdc690dbdf50)
- [Vérification des TEE Onchain avec RiscZero zkVM](https://medium.com/phala-fran%C3%A7ais/v%C3%A9rification-des-tee-onchain-avec-risczero-zkvm-552007e8fa8c)

Good points :  We are witnessing a renewed interest from our community in our commitments!
Bad points : A little more concern from our users about the health of the global market. 
 
· MK:
- List all completed tasks : Help with researching possible events to do
- You will find [Here](https://docs.google.com/spreadsheets/d/1L38-pKIwtAplsTpoLVd-XjA-dwr-gOwyue8cP4R04qQ/edit?usp=sharing)

I've taken on board the comments about 'non-priority' events. I have identified new events, but have not yet added them as the list is still evolving and there are discussions around organization, as well as the search for physical representatives, as I understand it.

Even if some events are not considered a priority, I'm still convinced that we need to participate in AI-oriented Web2 meetings to attract new Builders, Customers and potential Users.
 
 
4. Suggested scores: 
 
- [Department 1] 10/10
- [Department 2] 40/40
- [Department 3] 30/40

- Overall suggested score: 80/100.

The community expresses its disappointment at the drop in promotion of AI War, similar to what happened with Phalaworld. Despite this, it hopes to see new customers and new use cases join Phalaworld. In Septembre, despite a difficult market, we will continue to strengthen our community commitments.

**Comment by MaggiePhala** [comment]
Hey hey,

The scoring for CM was made having taken the translation of the content in the native language into consideration, the score will increase with a greater presence in chat.

Thanks.

Maggie
