### ISSUE TITLE
Title: June 2022 Contribution - {BlackStoneSheperd | Phala Amb#0238}

### ISSUE THREAD

**Issue by BlackStoneSheperd** [Phala-Network/growth-program#8]
Telegram Username: @BlackStoneSheperd
Discord Username: @BlackStoneSheperd | Phala Amb#0238
PHA Wallet Address: 42fBg7rmA9fp1dyA9LhVVKm5rAzNLLSxdiqkq46sBJGjEEHU
1 CM - Manage and support both Local and Main community chat.
- Phala French Channel link : https://t.me/phala_french
- Have I participated in Discord Channel Moderation ? Yes
- Combot Link : https://combot.org/c/-1001424849386/a?start=2022-06-01&end=2022-06-30
![image](https://user-images.githubusercontent.com/107954611/179395395-1ba8fc96-a39c-458a-8f0e-66c06b97bcab.png)

Translations on Medium : 
https://medium.com/phala-fran%C3%A7ais
Translations of Phala Network & Phala World. I've made some arrangement to the Medium Page organising articles for user ease.

2. VSM(Twitter Virals)
Twitter as Official Ambassador : https://twitter.com/BsSheperd
Twitter as Official Local Phala Account : https://twitter.com/phala_fr
Analytic : https://analytics.twitter.com/user/BsSheperd/tweets
Analytic : https://analytics.twitter.com/user/phala_fr/tweets

Comments :
How many people increased or decreased? Why? 10 new users, but we also had people unfoolowing. We get to 400 follower for the first time !
What was good ? Our AMA and the launch of Spirit NFT claim
What was bad ? The bear market still impacts the follower number. We have a delay related to the roadmap, people are wondering.
How can I improve this next month ? I have organised an AMA with Binance French. We'll offer a Shell NFT to the community. We'll share the audience with binance which I'm sure will bring some people to PhalaNetwork & PhalaWorld ! Introducing TEE Mining, FatContract, Phala World & a bit of Polkadot as Binancians don't know much about.
I launched a poll on twitter to involve the community by making them choose the spicies they want us to mint and offer during the AMA, I'll launch another poll to make them choose the careere !

My Supplementary(Advanced) Contributions of June:
1. CC(Contents Creation)
Introducing Phala Mining with Tioneb & Gator during an AMA with french community on our Twitch & Youtube channel.
When : June 22th, (21:00 GMT + 2)
Topics : Phala Mining ; Technical & Hardware requirement
Video Link: https://www.youtube.com/watch?v=s4jqo2OR-hQ
https://www.twitch.tv/videos/1510190340

OTHER :
I'd like to see gator get his well deserved Senior Ambassador title. Gator has been introduced by Tioneb by the month of march and he's been really involved so far, we'd be proud to promote him !

**Comment by RHEEUNION** [comment]
Also, please follow my example template for issue your contribution report, your report is not following the template so, kind of vague to give an accurate points.

**Comment by BlackStoneSheperd** [comment]
> @BlackStoneSheperd Your final message is well-received, but Gator needs to be more active in Discord and Telegram main channel like you and Tioneb in order to be qualified to become a Senior, and the requirements are clearly stated in the github page(go back to the main Growth Program Intro page). I also left my message on Gator's issue page.

Hi, @RHEEUNION. I understand, we'll tell him so.

**Comment by RHEEUNION** [comment]
> > @BlackStoneSheperd Your final message is well-received, but Gator needs to be more active in Discord and Telegram main channel like you and Tioneb in order to be qualified to become a Senior, and the requirements are clearly stated in the github page(go back to the main Growth Program Intro page). I also left my message on Gator's issue page.
> 
> Hi, @RHEEUNION. I understand, we'll tell him so but he was more active than me on telegram for june I don't know if i missed something.

Thanks for your info.
I just raised another 15 points for Gator, thank you guys =]

**Comment by BlackStoneSheperd** [comment]
> > > @BlackStoneSheperd Your final message is well-received, but Gator needs to be more active in Discord and Telegram main channel like you and Tioneb in order to be qualified to become a Senior, and the requirements are clearly stated in the github page(go back to the main Growth Program Intro page). I also left my message on Gator's issue page.
> > 
> > 
> > Hi, @RHEEUNION. I understand, we'll tell him so but he was more active than me on telegram for june I don't know if i missed something.
> 
> Thanks for your info. I just raised another 15 points for Gator, thank you guys =]

> Also, please follow my example template for issue your contribution report, your report is not following the template so, kind of vague to give an accurate points.

Hi @RHEEUNION, I took the time to fill the report. Indeed, informations wasn't well reported. Let me know !
