### ISSUE TITLE
December 2022 Contributions - {Cappex#7765}

### ISSUE THREAD

**Issue by cappehub** [Phala-Network/growth-program#82]
Telegram Username: @cryptocappex
Discord Username: @Cappex#7765
Twitter Username: https://twitter.com/CryptoCappex
PHA Wallet Address: 46FGLnh69wQ2EQU6gotqhmZjq9foVCF4vYSYaaLmxKViPGTr

Contributions:
MK & PM - I promoted Phala on Twitter and on Polkadot and Kusama's official discord servers!
All the December details of my social (twitter) activity have been shared here: https://docs.google.com/spreadsheets/d/1jw-Rr95gozF6K0ibWub5JlJvKNgmTYsEIV-lyyy9i6M/edit#gid=0
https://twitter.com/search?q=%40phalanetwork%20(from%3Acryptocappex)%20until%3A2022-12-31%20since%3A2022-12-01&src=typed_query&f=top
https://twitter.com/search?q=%23phalanetwork%20(from%3Acryptocappex)%20until%3A2022-12-31%20since%3A2022-12-01&src=typed_query&f=top
https://twitter.com/search?q=%24PHA%20(from%3Acryptocappex)%20until%3A2022-12-31%20since%3A2022-12-01&src=typed_query&f=top
![cappex DIC](https://user-images.githubusercontent.com/57374748/210275760-3140ffa2-0473-41f7-8f5a-36956595b535.jpg)

CM - The interest of the Italian community is mainly in PhalaWorld, shell feeding and customization have been frequently discussed topics!
![PHA community DIC1](https://user-images.githubusercontent.com/57374748/210274299-e51d1e41-0d67-4ad9-813f-d44cee294a94.jpg)
![PHA community DIC2](https://user-images.githubusercontent.com/57374748/210274310-2fbcf496-12ef-4625-a5a0-4e31264d5654.jpg)
![PHA community DIC3](https://user-images.githubusercontent.com/57374748/210275326-0d649faa-b971-4677-abcd-5df944cabda7.jpg)
All December details of social activity related to Phala Italy's twitter account were shared here: https://docs.google.com/spreadsheets/d/1jw-Rr95gozF6K0ibWub5JlJvKNgmTYsEIV-lyyy9i6M/edit#gid=0
![PHA twitter DIC](https://user-images.githubusercontent.com/57374748/210276614-b59829b3-96b1-4d4e-a845-0f21a48c60b7.jpg)

CC Content - Provided twitter accounts and links for the marketing department.
https://docs.google.com/spreadsheets/d/1XCV8b5thOpcZskrz6HcavAb9yfQKEBSdjp8qlt3fLGU/edit#gid=1726082972

HD - Constant presence in chat (discord and telegram), moderation, answering users' questions, removing spam and banning users who don't follow the rules!
![card](https://user-images.githubusercontent.com/57374748/210276153-d01792a2-9c37-451f-b554-79be13784bfa.png)
![cappex DIC1](https://user-images.githubusercontent.com/57374748/210276306-fb7545c2-e2ed-41ee-819d-b5192f68b2fe.jpg)

RC - I have been promoting the ambassador program within the community, but I wouldn't know how to prove it and if any of the new applicants have mentioned my name!

CC Content Creator - Translation of articles on Medium from Phala World and Weekly Reports from Phala Network.
https://medium.com/phala-italia/latest

I expect a result in line with other months 90%:
MK: 30/40
CM: 40/40
CC: 10/40 
PM: 10 
HD: 10
RC: ??
CC: 10

**Comment by willphala** [comment]
@cappehub 

Departments:

1.	MK 40/40
•	Excellent Twitter statistics. E.g. total insights is the highest in MK.
•	Participated in outbound marketing.
•	Asked questions and actively initiated and participated in MK discussions.
•	I was happy to see you leading by asking ambs to RT tweets and sharing noteworthy tweets that our MK department should engage with e.g. third parties asking what they’re favourite crypto projects are. 
•	Contributed to MK department tasks. 

2.	CM: 40/40
•	Consistently supports community members with their tasks.
•	High quality responses to community members.
•	Good comm stats. 
•	Contributed to CM discussions.

Supplementary tasks:

•	PM/RC have been added to your MK department score.
•	HD has been added to your CM department score.

1.	CC: 10/10

Summary:
Overall great work as per usual. Moving forward please record community feedback and questions in our community digest doc.
