### ISSUE TITLE
December 2022 contributions DKSM#0396

### ISSUE THREAD

**Issue by darknight7** [Phala-Network/growth-program#85]
Telegram: randomusernameidontneed
Discord: DKSM#0396
PHA Address: 427s7coF6yveYnXPNvCc1BtKgkHABxwgZpcwbFXbpJE9X1iP

CM
Have I participated in Discord Channel Moderation (choose)? Yes, telegram too, my main focus is supporting miners.

Phala Italian Channel link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a
Comments: this month has seen much change in Phala, I think for the better. The renewed focus on making the miners more stable and allow them to sync faster is a step in the right direction.

How many people increased or decreased? Why?
The Italian Phala chats are traditionally very low traffic, following the PhalaWorld mint things are back to normal.
What was good?
Nothing worth mentioning, but the Italian ambassadors are bonding more than before, I think internal discussion brought by Will helped a lot.
What was bad?
Activity is minimal a usual, not a bad thing per se, especially in these market conditions.
How can I improve this next month?
I joined the community and content efforts, I wrote almost single handedly a document to onboard new users. I plan to finish the doc ASAP in January as soon as I recover from family/day job woes that affected me during the holidays. In december my effort was almost 100% on community but I did write a short recommendation on how to handle abusive users on discord when it was requested. Assuming new content will be generated in January I'll be happy to help translate it to engage a wider audience from the get go.

Phala Mining Channel link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a
Comments: I keep contributing as time allows as I always did.
I left the obsolete ambassador telegram chat.

VSM
Twitter as Official Ambassador : https://twitter.com/twdksm
My presence on twitter is minimal but I do follow my senior ambassador's guide and like/retweet to increase visibility.
![immagine](https://user-images.githubusercontent.com/4477195/210348248-098100be-2931-4caf-bd62-197ba7c59bf6.png)

**Comment by willphala** [comment]
@darknight7 

Departments:

1.	CC 35/40
•	Excellent participation in CC discussions. 
•	Consistent suggestions in CC channel. 
•	High quality contributions to CC department tasks.

2.	CM: 28/40
•	Contributed to CM discussions.
•	Unfortunately did not add any questions to our community digest report.
•	Provided support in mining chats, great to see this. 

Supplementary tasks:

1.	PM 2/10

Summary:

December has been your best month so far, congrats! Please in future include much more info in your reports. Please also document community insights, feedback, and questions in our community digest doc. It is also great to hear about the Italian ambs bonding, I really appreciate you sharing this feedback.
