### ISSUE TITLE
December 2022 Contributions - {rafaccc#5473}

### ISSUE THREAD

**Issue by rafaccc** [Phala-Network/growth-program#89]
Telegram : [rafaccc](https://t.me/rafaccc)
Discord : rafaccc#5473
Dirección PHA: 42LYD29z2f6hYQeuamH5puXTGa1KHhWd6YxYSHXzRjih4xJd

Telegram Phala Spanish Channel
Link: [https://t.me/phalaspanish](https://github.com/Phala-Network/growth-program/issues/url)
Combot Link : 
![image](https://user-images.githubusercontent.com/97988345/210410252-9b6ab2be-c5c2-478b-8aa2-3b8e27151038.png)

Comments:
I have actively participated every day in the moderation of Telegram and Discord channels in English and Spanish
How many people increased or decreased, why? 7 people increased
What was good? Interested in the App Phala
What was bad? the cryptocurrency market is down and that affects the $Pha token.
How can I improve this next month? help users solve their questions and stay calm and happy

Twitter
I have retweeted in English and Spanish the tweets sent by the official Twitter accounts of Phala Network and Phala World. In addition to that, I have also made my own publications to disseminate

Analytics.twitter: [https://analytics.twitter.com/user/RafaelCabilla/tweets](url)
![image](https://user-images.githubusercontent.com/97988345/210487087-5a291d7e-61f7-4af4-b807-3de621033291.png)
![image](https://user-images.githubusercontent.com/97988345/210413071-b147e1cb-96d2-4a6d-9281-e54ad3da7e19.png)

My supplementary(advanced) contributions :

CC(Content Creation): Article translation: I have translated all the Medium articles (6)
1-https://medium.com/@rafacabilla/la-prueba-beta-de-phala-app-v2-0-60b89c90e547
2-https://medium.com/@rafacabilla/se-est%C3%A1n-actualizando-las-funciones-en-la-cadena-de-stakepool-v2-phalaworld-dress-up-ya-est%C3%A1-e9a23b626472
3-https://medium.com/@rafacabilla/phala-app-2-0-b80c4daff143
4-https://medium.com/@rafacabilla/an%C3%A1lisis-t%C3%A9cnico-de-por-qu%C3%A9-phala-no-se-ve-afectado-por-vulnerabilidades-de-sgx-de-chips-intel-59f68be70dea
5-https://medium.com/@rafacabilla/descubra-las-emocionantes-nuevas-funciones-de-la-app-de-phala-que-hacen-a-su-delegaci%C3%B3n-m%C3%A1s-7834ecc03919
6-https://medium.com/phala-espa%C3%B1ol/resumen-de-phala-a%C3%B1o-2022-f234183c6b48

**ART**

1-Gif movie "New Year"
[https://twitter.com/RafaelCabilla/status/1609033036821045248?s=20&t=qDmZbysLitVHGYxVUy5MBQ](url)

2-Gif Movie "Christmas"
[https://twitter.com/RafaelCabilla/status/1607109577820016640?t=JHYdy2MXHZXO7gnYv6r5Ug&s=19](url)

**Hi Will, Expected scores,** 
CM 30-35/40
MK 30-35/40
Supplementary tasks 20/20 (CC 10;Art 10)

**Comment by willphala** [comment]
@rafaccc 

Departments:

1.	CM: 28/40
•	Active in TG and Discord. 
•	Contributed to both English and Spanish channels/groups.
•	Did not participate in any CM channel discussions.
•	Did not record any community insights, questions, or problems in our CM community digest report. 

2.	MK: 30/40

•	I can’t give you an accurate score for you Twitter analytics as you have not recorded your analytics in our MK Twitter analytics doc. Therefore I don’t have all of the required information and I can’t compare it with our other ambs performance metrics. 
•	Participated in some MK channel discussions.
•	Did not contribute to any MK department tasks. 

Supplementary tasks:

1.	CC 10/10. 
2.	Art 5/10

Summary:
Good work. To achieve a higher score you need to significantly increase your activity and contributions to your selected departments. To achieve a higher here you need to e.g. suggests/implement improvements and show leadership skills such as taking ownership of specific tasks etc. It would also be great to see more details in your next report too (please see e.g. Tioneb’s report for reference).
