### ISSUE TITLE
December 2022 contributions | pigro85#6032

### ISSUE THREAD

**Issue by pigro85** [Phala-Network/growth-program#90]
Telegram: @Pigro85
Discord: pigro85#6032
Address: 44Rc9bxvmfyVJx1qmKThhUXUCuyhU6tqULvM5QKxtxks19uH
Twitter: @Pigro85

**MK - Marketing**
Supporting the team with sharing and reteewt
<img width="795" alt="Screenshot 2023-01-04 alle 19 55 51" src="https://user-images.githubusercontent.com/92217448/210629124-22a947c0-f4bd-4426-a29c-7a81666fdf60.png">
<img width="795" alt="Screenshot 2023-01-04 alle 19 56 04" src="https://user-images.githubusercontent.com/92217448/210629135-90618de0-fbf5-4de9-807a-f1ba1d642622.png">
<img width="1038" alt="Screenshot 2023-01-04 alle 19 56 46" src="https://user-images.githubusercontent.com/92217448/210629144-4298b9ee-84aa-44a9-a94b-2f1e8830cfa9.png">

**CM - HD - Community**
Have I participated in Discord and Telegram Channel Moderation? Yes, both.

Phala Italia Channel link: https://t.me/phalaitalia
Combot Link: https://combot.org/c/-1001169537547/a

Phala Mining Channel link: https://t.me/phalaminer
Combot Link: https://combot.org/c/1161228313/a

**CC - TT - Content and Tech creation**
Working on:
- PRB installation guide (Italian and English version) in collaboration with others Italian Ambassador: https://docs.google.com/document/d/1AseG_U94uMEw1OjuCoTcXCO8Gu582rkH1QKDsq0I0Vw/edit. Synching time don't help to speed up the process.
- Bad block check guide (Italian and English version): https://docs.google.com/document/d/1daquDbNDFM1YYY0wcNaRWof6fb_TJKEWpX_BX0BEo7M/edit. On discord was present only a text file with few information not updated.
- Translation support

I expect a result that can match 60% of the requirement:
MK: 0/40
CM: 30/40
CC: 30/40

**Comment by willphala** [comment]
@pigro85 

Departments:

1.	CM: 20/40
•	Fairly active in the CM channel, however there is room for improvement.
•	Did not record any community insights, problems, product feedback etc in the CM Community Digest doc. This is really important so please work on this moving forwards. 
•	Supporting workers is important, so good work here.
•	It would be great to see you get more involved in the English channels etc.

2.	CC: 30/40
•	Decent Combot stats. 
•	Quite active in CC channel which is brilliant. 
•	Did not contribute to CC department tasks. 
•	Guides are really valuable resource so good job.

Supplementary tasks:

1.	PM: 10/10. 

Summary:

Big improvement, so great work. To achieve a higher score you need to increase your activity and contributions to your selected departments. To achieve a higher here you need to e.g. suggests/implement improvements and show leadership skills such as taking ownership of specific tasks etc.
