### ISSUE TITLE
Decembre 2022 Contributions - {tioneb#4951}

### ISSUE THREAD

**Issue by tionebDotsamapha** [Phala-Network/growth-program#94]
Telegram : [tioneb](https://t.me/tioneb)
Discord : tioneb#4951
PHA Address : 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7
My Mandatory (Basic) Contributions of October:
 Senior-ambassador

Phala frenchChannel link: [₱hala francophone](https://t.me/phala_french)
Have I participated in Discord Channel Moderation EN ? no

Title: Decembre 2022 Contribution - {tioneb#4951}
Telegram Username: [tioneb](https://t.me/tioneb)
Discord Username:  tioneb#4951
Twitter Username: [tioneb_DotSama₱ha](https://twitter.com/tioneb442)
PHA Wallet Address: 456nDKsqGX4zLCmxdz56cvQNij1cWhqRp5ipfYCCEYq1gDB7

Contributions :
# Community Management
- ## Telegram : 

I expected to see a decrease in activity on the Telegram due to the creation of the FR discord but I'm glad to see that this is not the case.
I'm glad to see that our spammers/scammers barrier that we put in place in November is working very well. 

Combot Link : https://combot.org/c/-1001424849386/a?start=2022-12-01&end=2022-11-31
<img width="510" alt="image" src="https://user-images.githubusercontent.com/16654460/211014152-5842a260-09d0-40d5-a8bd-f5dac17d9268.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/16654460/211016477-9576e26d-076b-45ac-b439-1d17b5b5dbd9.png">

- ## Discord :
The reasons that motivated the creation of the discord are fully justified today. The separation of the discussions, allows much better interactions with our community than in a simple group. The graph below shows it well by the number of messages but what it does not show are the exchanges in the vocal chans which are something new for us and which in my opinion will be very interesting to cultivate in the future. 

<img width="758" alt="image" src="https://user-images.githubusercontent.com/16654460/211014619-bb361366-024a-4fd8-b9a0-344790888ca7.png">

- ## Youtube : 
The traffic of our youtube channel is very good this month! 
I made some changes in the administration of the Youtube account. Indeed, the superAdmin rights of the channel were held by @lucia. So I was not receiving the email notifications of the users' comments. 
So I got myself the superadmin rights which allows me to receive notifications and by the game of filter, redistribute them to my friends ambassadors of the TeamPhalaFR.
We will now be able to be more responsive to the comments of followers on YT.
I kept informed @luciaaaa4455, of course.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/16654460/211015754-a6037dfe-8456-4de0-b733-1ef09da18951.png">

# Marketing

- ## Monthly AMA December :
 late November/early December was a crazy time in our community. Thanks to the foodDistribution system that I started for our French community, we had a crazy week that will be remembered by all participants.
Our AMA of the month was about this week of food distribution during which we explained to our community how from a spreadsheet we distributed the food, then how thanks to @Janema and @Arno, we came to the creation of an extrinsec generator allowing to distribute all the food of a shellNFT and according to our distribution in a single transaction.
We presented the customization of the shellsNFT and the StackingV2, then we proceeded to the vote of the giveaway that I will present below. 

https://youtu.be/OfnXzJUze90
<img width="863" alt="image" src="https://user-images.githubusercontent.com/16654460/211027132-280dd0fe-8dc1-4abb-b940-ca1ce0bd2cf1.png">

- ## Giveaway
As I said earlier, DistributionFood was a magical time.
This generated a lot of discussions in the discord, in a funny spirit and with a lot of jokes. Including that of the lady of "the canteen". The lady who fed us all this week.
So we launched a giveaway with a mouse pad to win for the one who would draw a representation of our "lady of the canteen".
The winner was chosen by a community vote in a dedicated channel.

https://twitter.com/tioneb442/status/1601250794208395264?s=20&t=jp7XKeQV27wxCTde95fEZw
<img width="440" alt="image" src="https://user-images.githubusercontent.com/16654460/211027672-d386a87e-5732-48cf-9fa6-a9c3ed31d3e8.png">

# Content Creation

- ## A new NFT.
This lady from the canteen is now part of the history of our community and all history must be written to survive time.
So i created and distributed an NFT for 31 owners of 52 shellNFTs of the canteen lady's representation that won the giveaway.
We're not finished with the canteen lady! The rest is to come and will be huge. 

https://singular.app/collectibles/kusama/ae83a63261153d6642-R7J3C
<img width="503" alt="image" src="https://user-images.githubusercontent.com/16654460/211033881-688aa3f4-32a5-46f7-9465-5f8c8ed29612.png">

# Marketing & PM
- # twitter

My twitter account is always used  more for the promotion of Phala.
This December, I tried to post less but get more impressions through more elaborate tweets.
I think it works but I don't know if there is not a PW and foodDristri effect behind it. To be worked on.

https://twitter.com/search?q=%40phalaWorld%20(from%3Ationeb442)%20until%3A2022-12-31%20since%3A2022-12-01&src=typed_query&f=top
https://twitter.com/search?q=%40phalanetwork%20(from%3Ationeb442)%20until%3A2022-12-31%20since%3A2022-12-01&src=typed_query&f=top
<img width="649" alt="image" src="https://user-images.githubusercontent.com/16654460/211036719-2d403585-db83-4769-8254-e4600043a0c5.png">

# Help Desk : 
That's my dayly task for me accross the telegram, discord and for some guy's i help for their cloud computing infrastructures in MP messages, calls, Remotes Desktop, etc....

# BH
After the stackingV2 update, like many miners I encountered problems. But I still managed to keep 50% of my infrastructure online by restarting my containers every 3 hours days and nights. I finally managed to keep my system stable without rebooting. I contacted @gast to report my progress but at the same time, the update that solved the problem fell. 😄
 
 # DEV
 On behalf of the community, I have applied for the Closed Beta PhatContract. The goal will be to work on a simple PhatContract project, not too complicate, so we can use it as a support to present to newcomers.
  
I expect a result in line with other months 90%:
here is the score i expect : 
CM : 40
MK: 30 
PM : 7
HD : 10
BH : 1
DEV : 1

**Comment by willphala** [comment]
- Please keep me updated on all progress on YouTube channel, rather than Lucia.
- Its good to hear that the Discord server is creating better organisation. 
- Food distribution/AMA was an excellent idea!
- Fantastic job creating a fun and active environment via the above. 
- Giveaway was another brilliant idea. Thanks for being generous with the community! 
- I LOVE the Lady of the Canteen lore, so immortalising her with an NFT is amazing. I really like the design and also look forward to hearing the rest of her story in the future. 
- Suggested score is fair given your great work overall. Congrats!
