### ISSUE TITLE
January 2022 Contributions - {BlackStone | Phala Amb#0238} 

### ISSUE THREAD

**Issue by BlackStoneSheperd** [Phala-Network/growth-program#98]
**PERSONAL INFO**
Amb Rank : Senior Ambassador
Telegram : [BlackStone](https://t.me/BlackStoneSD)
https://twitter.com/BsSheperd
PHA Address : 42fBg7rmA9fp1dyA9LhVVKm5rAzNLLSxdiqkq46sBJGjEEHU

Departments : #CC & #MK
Department Score Weight : 25% & 75%

**DEPARTMENTS**
#CC
I've translated weekly, articles etc, published it on our french Medium and our Discord/Telegram.
https://medium.com/@blackstonesheperd
https://medium.com/phala-fran%C3%A7ais
Arno gave me help and reviewed the translations.
I've started to make a weekly support for gator's weekly videos, the idea is that we can add informations, highlight what's not new, correct the translations. Here is an example : https://docs.google.com/document/d/1qASOVF58lniPiVnpnfVX7YSmHdxbeEc4uQXIY2SVqLg/edit
I've created a spreadsheet that is meant to be our support about figures with all the links necessary : Number/quality of partenerships, HRMP/XCM Channels oppened on subbridge. I'll add other stuff later. This document is being reviewed by Zoé. Once it will be done, I'll share it with other communities so that they can add their own links and use it.
https://docs.google.com/spreadsheets/d/1fIEucf5ob_JmsHsuc-UupIz-2P2fAmztWMSU2kbDZ58/edit#gid=0

I've made some content for the PhalaWorld lore (french lore)  and post the little serie on twitter.
![FnkIrilXwAEeH9x](https://user-images.githubusercontent.com/107954611/216030252-d8b4883d-c77f-489f-820e-eaf4a6ed9b4d.jpg)
![FnFrFetWIAIsNmy](https://user-images.githubusercontent.com/107954611/216030042-ba935ad9-add7-4074-9eea-6c4dd3a2c23a.jpg)
![FnFljcqXgAAR6h9](https://user-images.githubusercontent.com/107954611/216030066-299a8ab0-a5d4-42a0-a13f-b3face75c5ad.jpg)
![FnFeT8EX0AIMLYH](https://user-images.githubusercontent.com/107954611/216030085-b5cef589-01a7-4d4f-921c-fc0ebf125cf8.jpg)
![FnFUKJgXoAI8FEb](https://user-images.githubusercontent.com/107954611/216030118-2cb7083c-335a-4a78-8ad1-2a813fbcd6b1.jpg)

Gator launched a lore contest for the french community. I've started the lore of my character : BlackStone, Shell 421. posted on Twitter here : https://twitter.com/BsSheperd/status/1619652826640302080?s=20&t=03P6HEx8CC4nPBe-m1Y57Q

----- AMA for 2022 Review -----

#MK (Twitter)
official local : https://twitter.com/phala_fr
ambassador : https://twitter.com/BsSheperd

![image](https://user-images.githubusercontent.com/107954611/216031524-2f244a30-ccd8-4ebb-9483-81a4cb57117a.png)
![image](https://user-images.githubusercontent.com/107954611/216031614-cd9a905a-abd1-44cd-b815-179d1ef2210a.png)
![image](https://user-images.githubusercontent.com/107954611/216031776-355f2529-b2a6-422d-96cb-fbc33d0cf621.png)
![image](https://user-images.githubusercontent.com/107954611/216031864-93b79f49-c2d3-4b2f-9d98-3878356a66f7.png)

I wonder if the statistics have changed because i've more tweets but figures are not consistent : I have 34 tweets for january but it also shows 23 for the last 28 days.. strange.

I've been active on the MK channel : RT, post interresting things etc.. 

**SUPPLEMENTARY TASKS**
#CM
I've been more active this month, I think !
I've made the suggestion about doing our report on github over the month, not at the end : I think we need time to really do it.

**SUGGESTED SCORES**
#CC : 40/40
#MK : 40/40

#CM : 10

Overall : 90

**Comment by willphala** [comment]
Great work. It was great to see you contributing more in our department channels!
