### ISSUE TITLE
January 2023 Contributions - {Jeretucu | Tucuman.Phala#4603}

### ISSUE THREAD

**Issue by Jeretucu** [Phala-Network/growth-program#99]
Telegram : [jeretucu](https://t.me/jeretucu)
Discord : Jeretucu | Tucuman.Phala#4603
PHA Address : 41D9LFABTeEMZMgaskRaob15k6c7RAsriJeLNSnvWVApZnv3

Contributions of December : CC50% & CM50%

CC (Content)
Make all the translations of the weeklies in the official channel of Phala in Spanish
https://medium.com/phala-espa%C3%B1ol/phala-lanz%C3%B3-el-resumen-anual-de-2022-la-incubaci%C3%B3n-del-shell-de-phalaworld-sera-la-pr%C3%B3xima-semana-83b8640757b2
https://medium.com/phala-espa%C3%B1ol/phala-abre-las-solicitudes-para-el-programa-de-embajadores-f8ebb4b2506c
https://medium.com/phala-espa%C3%B1ol/phala-se-asoci%C3%B3-con-saaslab-phalaworld-lanz%C3%B3-una-hoja-de-ruta-a-corto-plazo-5b196e8aad66
https://medium.com/phala-espa%C3%B1ol/phala-estar%C3%A1-en-polkadot-meet-up-en-nueva-york-nuevo-caso-de-uso-de-phat-gan%C3%B3-hackathon-semanario-928bc74b5642
https://medium.com/phala-espa%C3%B1ol/muestre-su-pw-shell-privadex-ingresa-a-open-beta-semanario-de-phala-vol-118-cd75b795c810

One of the most common questions is: How much can I earn with Phala Network mining?
I wrote an article for the Spanish community about the calculator created by 100k.dev
https://medium.com/@jeretucu/c%C3%A1lculos-de-la-minera-en-phala-network-60c6f3282144

![image](https://user-images.githubusercontent.com/107716407/216374377-d6f5a7f4-08a9-49e2-b1e4-d3f1589e40a9.png)

Create the Linktree for the Spanish community: https://linktr.ee/phalaespanol
![image](https://user-images.githubusercontent.com/107716407/216380722-d3b2dc63-aa73-48bc-b2bf-600b2fc429b1.png)

Participate in the discord channel in Spanish / Stakepool / Miner

I shared the Guide as the tutorial I share them in discord with the other ambassadors for their translation in different languages

CM (comunidad)
Incentive with my tutorials on Telegram to attract new miners
![image](https://user-images.githubusercontent.com/107716407/216377845-4683ed2d-f200-426a-9e81-97820d85fd99.png)

Report in TG as in the ambassadors discord, about the rewards for error in Phala Staking
![image](https://user-images.githubusercontent.com/107716407/216379035-42a9b3b8-189c-45b1-b872-af175b32b404.png)
![image](https://user-images.githubusercontent.com/107716407/216379159-d1b9bc25-84d3-4785-b835-614b3ce32717.png)

Generate a guide with all the tutorials written in Spanish about the frequently asked questions
https://docs.google.com/spreadsheets/d/17YXg6B-gHHVi26u0XGAfVF01Vhaw8MQ41NcPoyxFBpc/edit?usp=sharing

![image](https://user-images.githubusercontent.com/107716407/216376818-22e8da50-43aa-4945-b000-3a99ce001ac3.png)

TG: I was active in the Spanish chat answering questions (please check Spanish telegram chat)
![image](https://user-images.githubusercontent.com/107716407/216381188-3fadf42d-2a25-4782-af0c-426072112fe1.png)
![image](https://user-images.githubusercontent.com/107716407/216381345-7105befe-d766-45f5-8b50-5a36bbd1e139.png)

PM:
Twitter as Official Ambassador : https://twitter.com/jeretucu
Analytic : https://analytics.twitter.com/user/jeretucu/tweets

![image](https://user-images.githubusercontent.com/107716407/216381688-de3d0519-837f-4e11-ade0-268968dbae95.png)
![image](https://user-images.githubusercontent.com/107716407/216383443-3b26ac48-1464-472b-8f89-f91e216e27e6.png)

RC:
I proposed Will, and I encouraged adding a mining expert as an ambassador
Indicate that you fill out the form for the request of ambassadors
his discord is: ale_o10 | tucuMAN.phala#9071

BH:
I keep reporting BUG

![image](https://user-images.githubusercontent.com/107716407/216383235-c7550653-8e1e-474e-868b-bd0a6334e8d7.png)
![image](https://user-images.githubusercontent.com/107716407/216383690-0efdf725-5592-4209-ab59-adfb08f4fc22.png)

Hi Will, I hope I can reach 90%
Increase my participation a lot this month.
Community 35/40
Contect 35/40
Supplementary tasks, 20/20 (PM, RC, BH)

**Comment by willphala** [comment]
Good work. Unfortunately to get 90+ I need you to participate and engage more within our departments. Please review our point system doc mate.
